"""DCT32 fused8 DAG -> ACLE emitter (8-lane loop-re-rolled codegen).

Consumes the width-independent DAGs from dct32_fused8_op_ir
(lower_pass1_fused8 + lower_pass2_fused8) and emits C++ with the same
loop shape as tools/emit_dct32_vl128.py --pass1 fused --pass2 fused:
  i loop over 4-row groups, k loops over odd/k2/k4 families, even k
  unrolled. `neon_dot=True` lowers the dots to pure NEON vmull/vmlal.
"""

from __future__ import annotations

import os
import re
import sys
from typing import Dict, List

from op_ir import Op

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from dct32_constants import GT32  # noqa: E402


def _v(name: str) -> str:
    return name.replace(".", "_")


def _tbl16(name: str, rows: List[List[int]]) -> str:
    body = "\n".join("    { %s }," % ", ".join(str(x) for x in r)
                     for r in rows)
    return "static const int16_t %s[%d][8] = {\n%s\n};" \
        % (name, len(rows), body)


def _tbl32(name: str, rows: List[List[int]]) -> str:
    body = "\n".join("    { %s }," % ", ".join(str(x) for x in r)
                     for r in rows)
    return "static const int32_t %s[%d][4] = {\n%s\n};" \
        % (name, len(rows), body)


def _const_decls() -> str:
    gt32a = [GT32[k][:8] for k in range(32)]
    gt32b = [GT32[k][8:16] for k in range(32)]
    k2 = tuple(range(2, 32, 4))
    k4 = tuple(range(4, 32, 8))
    s32a_k2 = [GT32[k][:4] for k in k2]
    s32b_k2 = [GT32[k][4:8] for k in k2]
    s32a_k4 = [GT32[k][:4] for k in k4]
    t8odd = [
        [89, 75, 50, 18, 89, 75, 50, 18],
        [75, -18, -89, -50, 75, -18, -89, -50],
        [50, -89, 18, 75, 50, -89, 18, 75],
        [18, -50, 75, -89, 18, -50, 75, -89],
    ]
    t8e = [
        [64, 64, 64, 64],
        [83, 36, 83, 36],
        [64, -64, 64, -64],
        [36, -83, 36, -83],
    ]
    return "\n\n".join([
        _tbl16("GT32A", gt32a), _tbl16("GT32B", gt32b),
        _tbl16("T8ODD16", t8odd),
        _tbl32("GT32S32A", s32a_k2), _tbl32("GT32S32B", s32b_k2),
        _tbl32("GT32S32A4", s32a_k4), _tbl32("T8E", t8e),
    ])


NEON_HELPERS = """\
static inline int16x8_t rev16(const int16x8_t a)
{
    return vreinterpretq_s16_s8(vqtbx1q_s8(
        vreinterpretq_s8_s16(a), vreinterpretq_s8_s16(a),
        vld1q_u8(rev16_tbl)));
}

static inline int32x4_t rev32(const int32x4_t a)
{
    return vreinterpretq_s32_s8(vqtbx1q_s8(
        vreinterpretq_s8_s32(a), vreinterpretq_s8_s32(a),
        vld1q_u8(rev32_tbl)));
}
"""

SVE_HELPERS = NEON_HELPERS + """\

static inline int64x2_t sdotq_s16(int64x2_t acc, int16x8_t x, int16x8_t y)
{
    return svget_neonq_s64(svdot_s64(svset_neonq_s64(svundef_s64(), acc),
                                     svset_neonq_s16(svundef_s16(), x),
                                     svset_neonq_s16(svundef_s16(), y)));
}

static inline int32x4_t vld1sh_s32(const int16_t* p)
{
    return svget_neonq_s32(svld1sh_s32(svptrue_pat_b32(SV_VL4), p));
}
"""

REV16_TBL = ("static const uint8_t rev16_tbl[16] =\n"
             "    { 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1 };")
REV32_TBL = ("static const uint8_t rev32_tbl[16] =\n"
             "    { 12, 13, 14, 15, 8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3 };")


def emit_neon8_ops(ops, func_name: str = "dynopt_dct32_sve2_shared",
                   neon_dot: bool = False) -> str:
    b1 = _looped_pass([o for o in ops if o.tile_id.startswith("p1.")],
                      1, shift=4, neon_dot=neon_dot)
    b2 = _looped_pass([o for o in ops if o.tile_id.startswith("p2.")],
                      2, shift=11, neon_dot=neon_dot)
    pass1 = "static inline void op_pass_4(" \
            "const int16_t* src, int16_t* dst, intptr_t stride)\n{\n" \
            "%s\n}" % "\n".join(b1)
    pass2_fn = "static inline void op_pass_11(" \
               "const int16_t* src, int16_t* dst)\n{\n%s\n}" \
               % "\n".join(b2)
    if neon_dot:
        includes = "#include <arm_neon.h>\n#include <cstdint>\n"
        helpers = NEON_HELPERS
    else:
        includes = ("#include <arm_neon.h>\n#include <arm_sve.h>\n"
                    "#include <arm_neon_sve_bridge.h>\n#include <cstdint>\n")
        helpers = SVE_HELPERS
    return """\
// Generated by optimizer/ir/dct32_fused8_emit.py -- do not edit.
// 8-lane fused quarter (VL=128 baseline).
%s

%s
%s

%s

%s

%s

%s

extern "C" void %s(const int16_t* src, int16_t* dst, intptr_t srcStride)
{
    int16_t coef[1024];
    op_pass_4(src, coef, srcStride);
    op_pass_11(coef, dst);
}
""" % (includes, REV16_TBL, REV32_TBL, helpers, _const_decls(),
       pass1, pass2_fn, func_name)


def _looped_pass(ops: List[Op], pass_id: int, shift: int,
                 neon_dot: bool) -> List[str]:
    leaf_start = "p%d.leaf.rowpair%d" % (pass_id, 2)
    try:
        idx0 = next(i for i, o in enumerate(ops) if o.tile_id == leaf_start)
    except StopIteration:
        raise ValueError("fused8 DAG missing group-1 leaf")
    g0 = [o for o in ops[:idx0]
          if o.tile_id.startswith("p%d.leaf." % pass_id)
          and (o.attrs.get("row") in (0, 1, 2, 3)
               or any(o.tile_id.endswith(x) for x in (
                   "row0", "row1", "row2", "row3",
                   "rowpair0", "rowpair1")))]
    odd_tpl = [o for o in ops if o.tile_id == "p%d.odd.k1.g0" % pass_id]
    k2_tpl = [o for o in ops if o.tile_id == "p%d.f2.k2.g0" % pass_id]
    k4_tpl = [o for o in ops if o.tile_id == "p%d.f4.k4.g0" % pass_id]
    even_tpl = [o for o in ops if o.tile_id in (
        "p%d.k0.k0.g0" % pass_id, "p%d.k8.k1.g0" % pass_id,
        "p%d.k16.k2.g0" % pass_id, "p%d.k24.k3.g0" % pass_id)]
    if not (odd_tpl and k2_tpl and k4_tpl
            and len({o.tile_id for o in even_tpl}) == 4):
        raise ValueError("fused8 DAG missing group-0 template family")
    body = ["    const int line = 32;",
            "    const int shift = %d;" % shift,
            "    for (int i = 0; i < line; i += 4)", "    {"]
    body += ["    " + l for l in _group(g0, {"neon_dot": neon_dot})]
    body += ["        for (int k = 1; k < 32; k += 2)", "        {"]
    body += ["        " + l for l in _group(
        odd_tpl, {"const_map": {"GT32A[1]": "GT32A[k]",
                                "GT32B[1]": "GT32B[k]"},
                  "k_loop": True, "neon_dot": neon_dot})]
    body += ["        }", "        for (int k = 2; k < 32; k += 4)",
             "        {"]
    body += ["        " + l for l in _group(
        k2_tpl, {"const_map": {"T8ODD16[0]": "T8ODD16[(k-2)/4]",
                               "GT32A[2]": "GT32A[k]",
                               "GT32S32A[0]": "GT32S32A[(k-2)/4]",
                               "GT32S32B[0]": "GT32S32B[(k-2)/4]"},
                  "k_loop": True, "neon_dot": neon_dot})]
    body += ["        }", "        for (int k = 4; k < 32; k += 8)",
             "        {"]
    body += ["        " + l for l in _group(
        k4_tpl, {"const_map": {"GT32S32A4[0]": "GT32S32A4[(k-4)/8]"},
                  "k_loop": True, "neon_dot": neon_dot})]
    body += ["        }"]
    body += ["    " + l for l in _group(
        even_tpl, {"k_loop": False, "neon_dot": neon_dot})]
    body += ["    }"]
    return body


def _group(ops: List[Op], ctx: Dict) -> List[str]:
    lines: List[str] = []
    const_cache: Dict[str, str] = {}
    const_map = ctx.get("const_map", {})
    neon_dot = ctx.get("neon_dot", False)

    def const_load(expr: str) -> str:
        nm = const_cache.get(expr)
        if nm is None:
            nm = "c_" + _v(re.sub(r"[^A-Za-z0-9]", "_", expr))
            expr2 = const_map.get(expr, expr)
            elem = "s32" if expr.startswith(("GT32S32", "T8E")) else "s16"
            if elem == "s32":
                lines.append("            const int32x4_t %s = "
                             "vld1q_s32(%s);" % (nm, expr2))
            else:
                lines.append("            const int16x8_t %s = "
                             "vld1q_s16(%s);" % (nm, expr2))
            const_cache[expr] = nm
        return nm

    def emit(op: Op) -> None:
        kind = op.kind
        attrs = op.attrs
        out = _v(op.out)
        ins = [_v(x) for x in op.inputs]
        if kind == "load":
            if attrs["arch"] == "neon-const":
                expr = const_map.get(attrs["const"], attrs["const"])
                nm = const_cache.get(attrs["const"])
                if nm is None:
                    nm = "c_" + out
                    if attrs["elem"] == "s32":
                        lines.append("            const int32x4_t %s = "
                                     "vld1q_s32(%s);" % (nm, expr))
                    else:
                        lines.append("            const int16x8_t %s = "
                                     "vld1q_s16(%s);" % (nm, expr))
                    const_cache[attrs["const"]] = nm
                return
            row = attrs["row"]
            idx = attrs.get("index", "")
            idx = re.sub(r"\br\b", "(i + %d)" % row, idx)
            lines.append("            const int16x8_t %s = "
                         "vld1q_s16(src + %s);" % (out, idx))
        elif kind == "permute":
            pk = attrs["kind"]
            if pk == "rev16":
                lines.append("            int16x8_t %s = rev16(%s);"
                             % (out, ins[0]))
            elif pk == "rev32":
                lines.append("            int32x4_t %s = rev32(%s);"
                             % (out, ins[0]))
            elif pk in ("zip1q", "zip2q"):
                fn = "vzip1q_s64" if pk == "zip1q" else "vzip2q_s64"
                lines.append("            int32x4_t %s = "
                             "vreinterpretq_s32_s64(%s("
                             "vreinterpretq_s64_s32(%s), "
                             "vreinterpretq_s64_s32(%s)));"
                             % (out, fn, ins[0], ins[1]))
            elif pk == "rev64q":
                lines.append("            int32x4_t %s = vrev64q_s32(%s);"
                             % (out, ins[0]))
            else:
                raise ValueError("dct32 neon8 permute %s" % pk)
        elif kind == "vget":
            fn = "vget_low_s16" if attrs["which"] == "lo" \
                else "vget_high_s16"
            lines.append("            int16x4_t %s = %s(%s);"
                         % (out, fn, ins[0]))
        elif kind == "widen_add":
            lines.append("            int32x4_t %s = vaddl_s16(%s, %s);"
                         % (out, ins[0], ins[1]))
        elif kind in ("add", "sub"):
            fn = ("vaddq_s16" if kind == "add" else "vsubq_s16") \
                if attrs["elem"] == "s16" else \
                ("vaddq_s32" if kind == "add" else "vsubq_s32")
            ct = "int16x8_t" if attrs["elem"] == "s16" else "int32x4_t"
            lines.append("            %s %s = %s(%s, %s);"
                         % (ct, out, fn, ins[0], ins[1]))
        elif kind == "dot_segment":
            ck = const_load(attrs["const_src"])
            if neon_dot:
                lines.append("            int32x4_t %s = vmull_s16("
                             "vget_low_s16(%s), vget_low_s16(%s));"
                             % (out, ck, ins[0]))
                lines.append("            %s = vmlal_s16(%s, "
                             "vget_high_s16(%s), vget_high_s16(%s));"
                             % (out, out, ck, ins[0]))
            else:
                lines.append("            int64x2_t %s = sdotq_s16("
                             "vdupq_n_s64(0), %s, %s);"
                             % (out, ck, ins[0]))
        elif kind == "dot_accum":
            ck = const_load(attrs["const_src"])
            if neon_dot:
                lines.append("            int32x4_t %s_b = vmull_s16("
                             "vget_low_s16(%s), vget_low_s16(%s));"
                             % (out, ck, ins[1]))
                lines.append("            %s_b = vmlal_s16(%s_b, "
                             "vget_high_s16(%s), vget_high_s16(%s));"
                             % (out, out, ck, ins[1]))
                lines.append("            %s = vpaddq_s32(%s, %s_b);"
                             % (out, ins[0], out))
            else:
                lines.append("            %s = sdotq_s16("
                             "%s, %s, %s);" % (out, ins[0], ck, ins[1]))
        elif kind == "neon_reduce_narrow":
            nm = "_%s" % out
            if neon_dot:
                lines.append("            const int32x4_t s01%s = "
                             "vpaddq_s32(%s, %s);" % (nm, ins[0], ins[1]))
                lines.append("            const int32x4_t s23%s = "
                             "vpaddq_s32(%s, %s);" % (nm, ins[2], ins[3]))
                lines.append("            const int32x4_t w%s = "
                             "vpaddq_s32(s01%s, s23%s);" % (nm, nm, nm))
                lines.append("            int16x4_t %s = "
                             "vrshrn_n_s32(w%s, shift);" % (out, nm))
            else:
                lines.append("            const int32x4_t t01%s = "
                             "vcombine_s32(vmovn_s64(%s), vmovn_s64(%s));"
                             % (nm, ins[0], ins[1]))
                lines.append("            const int32x4_t t23%s = "
                             "vcombine_s32(vmovn_s64(%s), vmovn_s64(%s));"
                             % (nm, ins[2], ins[3]))
                lines.append("            const int32x4_t w%s = "
                             "vpaddq_s32(t01%s, t23%s);" % (nm, nm, nm))
                lines.append("            int16x4_t %s = "
                             "vrshrn_n_s32(w%s, shift);" % (out, nm))
        elif kind == "neon_narrow4":
            lines.append("            int16x4_t %s = vmovn_s32(%s);"
                         % (out, ins[0]))
        elif kind == "neon_combine":
            lines.append("            int16x8_t %s = vcombine_s16(%s, %s);"
                         % (out, ins[0], ins[1]))
        elif kind == "neon_mul":
            ck = const_load(attrs["const_src"])
            lines.append("            int32x4_t %s = vmulq_s32(%s, %s);"
                         % (out, ck, ins[0]))
        elif kind == "neon_mla":
            ck = const_load(attrs["const_src"])
            lines.append("            %s = vmlaq_s32(%s, %s, %s);"
                         % (out, ins[0], ck, ins[1]))
        elif kind == "neon_padd":
            lines.append("            int32x4_t %s = vpaddq_s32(%s, %s);"
                         % (out, ins[0], ins[1]))
        elif kind == "neon_narrow":
            lines.append("            int16x4_t %s = "
                         "vrshrn_n_s32(%s, shift);" % (out, ins[0]))
        elif kind == "store":
            idx = attrs["index"].replace("4*g", "i")
            if not ctx.get("k_loop"):
                idx = idx.replace("32*k", "32*%d" % attrs["lanes"][0][1])
            lines.append("            vst1_s16(dst + %s, %s);"
                         % (idx, ins[0]))
        else:
            raise ValueError("dct32 neon8: unsupported op %s (%s)"
                             % (kind, out))

    for op in ops:
        emit(op)
    return lines
