"""dct32 pure-SVE emitter (source-translation of the neon8 fused8 code).

Same approach as dct16_pure_sve_emit: translate the DAG-generated
neon8 source to SVE-only ACLE using psv_* primitives. VL=128-fixed.
"""

from __future__ import annotations

from dct32_fused8_op_ir import lower_pass1_fused8, lower_pass2_fused8
from dct32_fused8_emit import emit_neon8_ops
from pure_sve_helpers import PURE_SVE_HELPERS
from dct16_pure_sve_emit import (_body_subs, _drop_neon_helpers,
                                 _replace_call, _split_args)


def emit_pure_sve(func_name: str = "dynopt_dct32_pure_sve") -> str:
    ops = lower_pass1_fused8() + lower_pass2_fused8()
    src = emit_neon8_ops(ops, func_name=func_name)
    cut = src.index("static const int16_t GT32A[32][8] = {")
    head = ("// Generated by optimizer/ir/dct32_pure_sve_emit.py "
            "-- pure SVE (VL=128-fixed).\n"
            "#include <arm_sve.h>\n#include <cstdint>\n\n"
            + PURE_SVE_HELPERS + "\n"
            + "static inline svint16_t rev16(const svint16_t a)"
            "{ return psv_rev16(a); }\n"
            + "static inline svint32_t rev32(const svint32_t a)"
            "{ return psv_rev32_s32(a); }\n"
            + "static inline svint64_t sdotq_s16(svint64_t acc, "
            "svint16_t x, svint16_t y){ return psv_sdot(acc, x, y); }\n"
            + "static inline svint32_t vld1sh_s32(const int16_t* p)"
            "{ return psv_ld1sh_s32(p); }\n\n")
    body = _body_subs(src[cut:])
    sig = ("extern \"C\" void %s(const int16_t* src, int16_t* dst, "
           "intptr_t srcStride)\n{" % func_name)
    guard = ("extern \"C\" void %s(const int16_t* src, int16_t* dst, "
             "intptr_t srcStride)\n{\n    if (svcntb() != 16) return;"
             % func_name)
    body = body.replace(sig, guard, 1)
    return head + body
