"""interp8 hpp (W,H) DAG -> pure-NEON ACLE emitter (per-coeff if/else)."""

from __future__ import annotations

from typing import List

from op_ir import Op


def emit_interp8_hpp(
        ops, func_name: str = "dynopt_interp8_16x16_sve2") -> str:
    loads: List[str] = []
    phases: List[List[str]] = [[], [], []]
    for op in ops:
        kind = op.kind
        attrs = op.attrs
        out = op.out
        ins = list(op.inputs)
        parts = op.tile_id.split(".")
        ph = 0
        for p in parts:
            if p.startswith("ph"):
                ph = int(p[2:])
                break
        if kind == "load_u8x16":
            loads.append("    uint8x16_t %s = vld1q_u8(src + %d * srcStride "
                         "+ %d + %d);"
                         % (out, attrs["row"], attrs["col"], attrs["off"]))
        elif kind == "dup_u8":
            phases[ph - 1].append(
                "        uint8x8_t %s = vdup_n_u8(%d);"
                % (out, attrs["value"]))
        elif kind == "dup16":
            phases[ph - 1].append(
                "        uint16x8_t %s = vdupq_n_u16(%d);"
                % (out, attrs["value"]))
        elif kind == "vget":
            fn = "vget_low_u8" if attrs["which"] == "lo" else "vget_high_u8"
            phases[ph - 1].append("        uint8x8_t %s = %s(%s);"
                                  % (out, fn, ins[0]))
        elif kind == "vsubl_u8":
            phases[ph - 1].append(
                "        uint16x8_t %s = vsubl_u8(%s, %s);"
                % (out, ins[0], ins[1]))
        elif kind == "vadd_u16":
            phases[ph - 1].append(
                "        uint16x8_t %s = vaddq_u16(%s, %s);"
                % (out, ins[0], ins[1]))
        elif kind == "vmlal_u8":
            phases[ph - 1].append(
                "        uint16x8_t %s = vmlal_u8(%s, %s, %s);"
                % (out, ins[0], ins[1], ins[2]))
        elif kind == "vmlsl_u8":
            phases[ph - 1].append(
                "        uint16x8_t %s = vmlsl_u8(%s, %s, %s);"
                % (out, ins[0], ins[1], ins[2]))
        elif kind == "vaddl_u8":
            phases[ph - 1].append(
                "        int16x8_t %s = vreinterpretq_s16_u16("
                "vaddl_u8(%s, %s));" % (out, ins[0], ins[1]))
        elif kind == "reinterpret_s16":
            phases[ph - 1].append(
                "        int16x8_t %s = vreinterpretq_s16_u16(%s);"
                % (out, ins[0]))
        elif kind == "vmlaq_n_s16":
            phases[ph - 1].append(
                "        int16x8_t %s = vmlaq_n_s16(%s, %s, %d);"
                % (out, ins[0], ins[1], attrs["const"]))
        elif kind == "vqrshrun":
            phases[ph - 1].append(
                "        uint8x8_t %s = vqrshrun_n_s16(%s, %d);"
                % (out, ins[0], attrs["shift"]))
        elif kind == "combine_u8":
            phases[ph - 1].append(
                "        uint8x16_t %s = vcombine_u8(%s, %s);"
                % (out, ins[0], ins[1]))
        elif kind == "store_u8x16":
            phases[ph - 1].append(
                "        vst1q_u8(dst + %d * dstStride + %d, %s);"
                % (attrs["row"], attrs["col"], ins[0]))
        else:
            raise ValueError("interp8 emit: %s" % kind)
    return """\
// Generated by optimizer/ir/interp8_emit.py -- do not edit by hand.
// interp8 hpp (W,H) pure NEON from width-independent DAG.
#include <arm_neon.h>
#include <stdint.h>

extern "C" void %s(const uint8_t* src, intptr_t srcStride,
                   uint8_t* dst, intptr_t dstStride, int coeffIdx)
{
%s
    if (coeffIdx == 1)
    {
%s
    }
    else if (coeffIdx == 2)
    {
%s
    }
    else
    {
%s
    }
}
""" % (func_name, "\n".join(loads), "\n".join(phases[0]),
       "\n".join(phases[1]), "\n".join(phases[2]))
