"""pixel_var 16x16 DAG -> pure-NEON ACLE emitter."""

from __future__ import annotations

from typing import List

from op_ir import Op


def emit_pixel_var(ops,
                   func_name: str = "dynopt_pixel_var_16x16_sve2") -> str:
    body: List[str] = []
    for op in ops:
        kind = op.kind
        attrs = op.attrs
        out = op.out
        ins = list(op.inputs)
        if kind == "dup16":
            body.append("    uint16x8_t %s = vdupq_n_u16(%d);"
                        % (out, attrs["value"]))
        elif kind == "dup32":
            body.append("    uint32x4_t %s = vdupq_n_u32(%d);"
                        % (out, attrs["value"]))
        elif kind == "load_u8x16":
            body.append("    uint8x16_t %s = vld1q_u8(pix + %d * stride);"
                        % (out, attrs["row"]))
        elif kind == "vget":
            fn = "vget_low_u8" if attrs["which"] == "lo" else "vget_high_u8"
            body.append("    uint8x8_t %s = %s(%s);" % (out, fn, ins[0]))
        elif kind == "vpadal_u8":
            body.append("    uint16x8_t %s = vpadalq_u8(%s, %s);"
                        % (out, ins[0], ins[1]))
        elif kind == "vmull_u8":
            body.append("    uint16x8_t %s = vmull_u8(%s, %s);"
                        % (out, ins[0], ins[1]))
        elif kind == "vpadal_u16":
            body.append("    uint32x4_t %s = vpadalq_u16(%s, %s);"
                        % (out, ins[0], ins[1]))
        elif kind == "vpaddl_u16":
            body.append("    uint32x4_t %s = vpaddlq_u16(%s);"
                        % (out, ins[0]))
        elif kind == "vadd_u32":
            body.append("    uint32x4_t %s = vaddq_u32(%s, %s);"
                        % (out, ins[0], ins[1]))
        elif kind == "vaddv_u32":
            body.append("    int %s = (int)vaddvq_u32(%s);"
                        % (out, ins[0]))
        elif kind == "vaddlv_u32":
            body.append("    uint64_t %s = vaddlvq_u32(%s);"
                        % (out, ins[0]))
        elif kind == "pack_var":
            body.append("    uint64_t var = (uint64_t)(uint32_t)%s | "
                        "(%s << 32);" % (ins[0], ins[1]))
        else:
            raise ValueError("pixel_var emit: %s" % kind)
    return """\
// Generated by optimizer/ir/pixel_var_emit.py -- do not edit by hand.
// pixel_var 16x16 pure NEON from width-independent DAG.
#include <arm_neon.h>
#include <stdint.h>

extern "C" uint64_t %s(const uint8_t* pix, intptr_t stride)
{
%s
    return var;
}
""" % (func_name, "\n".join(body))
