"""SATD 8x8 DAG -> pure-NEON ACLE emitter (PoC for non-DCT kernels)."""

from __future__ import annotations

from typing import List

from op_ir import Op


def emit_satd8(ops, func_name: str = "dynopt_satd_8x8_sve2") -> str:
    body: List[str] = []
    for op in ops:
        kind = op.kind
        attrs = op.attrs
        out = op.out
        ins = list(op.inputs)
        if kind == "load_diff":
            y = attrs["row"]
            if attrs.get("half"):
                vg = "low" if attrs["half"] == "lo" else "high"
                body.append("    int16x8_t %s = vreinterpretq_s16_u16("
                            "vsubl_u8(vget_%s_u8(vld1q_u8(pix1 + %d * sp1)), "
                            "vget_%s_u8(vld1q_u8(pix2 + %d * sp2))));"
                            % (out, vg, y, vg, y))
            else:
                body.append("    int16x8_t %s = vreinterpretq_s16_u16("
                            "vsubl_u8(vld1_u8(pix1 + %d * sp1), "
                            "vld1_u8(pix2 + %d * sp2)));" % (out, y, y))
        elif kind in ("add", "sub"):
            if attrs["elem"] == "u16":
                fn = "vaddq_u16" if kind == "add" else "vsubq_u16"
                ct = "uint16x8_t"
            else:
                fn = "vaddq_s16" if kind == "add" else "vsubq_s16"
                ct = "int16x8_t"
            body.append("    %s %s = %s(%s, %s);"
                        % (ct, out, fn, ins[0], ins[1]))
        elif kind == "permute":
            pk = attrs["kind"]
            if pk == "trn1q_s16":
                body.append("    int16x8_t %s = vtrn1q_s16(%s, %s);"
                            % (out, ins[0], ins[1]))
            elif pk == "trn2q_s16":
                body.append("    int16x8_t %s = vtrn2q_s16(%s, %s);"
                            % (out, ins[0], ins[1]))
            elif pk == "trn1q_s32":
                body.append("    int16x8_t %s = vreinterpretq_s16_s32("
                            "vtrn1q_s32(vreinterpretq_s32_s16(%s), "
                            "vreinterpretq_s32_s16(%s)));"
                            % (out, ins[0], ins[1]))
            elif pk == "trn2q_s32":
                body.append("    int16x8_t %s = vreinterpretq_s16_s32("
                            "vtrn2q_s32(vreinterpretq_s32_s16(%s), "
                            "vreinterpretq_s32_s16(%s)));"
                            % (out, ins[0], ins[1]))
            else:
                raise ValueError("satd permute %s" % pk)
        elif kind == "abs":
            body.append("    int16x8_t %s = vabsq_s16(%s);"
                        % (out, ins[0]))
        elif kind == "abd":
            body.append("    int16x8_t %s = vabdq_s16(%s, %s);"
                        % (out, ins[0], ins[1]))
        elif kind == "max":
            body.append("    uint16x8_t %s = vmaxq_u16("
                        "vreinterpretq_u16_s16(%s), "
                        "vreinterpretq_u16_s16(%s));"
                        % (out, ins[0], ins[1]))
        elif kind == "vpaddl":
            body.append("    uint32x4_t %s = vpaddlq_u16(%s);"
                        % (out, ins[0]))
        elif kind == "vpadal":
            body.append("    uint32x4_t %s = vpadalq_u16(%s, %s);"
                        % (out, ins[0], ins[1]))
        elif kind == "vaddv":
            body.append("    int satd = (int)vaddvq_u32(%s);" % ins[0])
        else:
            raise ValueError("satd emit: %s" % kind)
    return """\
// Generated by optimizer/ir/satd8_emit.py -- do not edit by hand.
// SATD 8x8 pure NEON from width-independent DAG.
#include <arm_neon.h>
#include <stdint.h>

extern "C" int %s(const uint8_t* pix1, intptr_t sp1,
                  const uint8_t* pix2, intptr_t sp2)
{
%s
    return satd;
}
""" % (func_name, "\n".join(body))
