"""SSD sse_pp 16x16 DAG -> pure-NEON ACLE emitter."""

from __future__ import annotations

from typing import List

from op_ir import Op


def emit_sse_pp(ops, func_name: str = "dynopt_sse_pp_16x16_sve2") -> str:
    body: List[str] = []
    ret = "ssd"
    for op in ops:
        kind = op.kind
        attrs = op.attrs
        out = op.out
        ins = list(op.inputs)
        if kind == "dup32":
            body.append("    uint32x4_t %s = vdupq_n_u32(%d);"
                        % (out, attrs["value"]))
        elif kind == "load_u8x16":
            sv = "stride1" if attrs["base"] == "pix1" else "stride2"
            body.append("    uint8x16_t %s = vld1q_u8(%s + %d * %s);"
                        % (out, attrs["base"], attrs["row"], sv))
        elif kind == "vget":
            if attrs["elem"] == "u16":
                fn = "vget_low_u16" if attrs["which"] == "lo" \
                    else "vget_high_u16"
                body.append("    uint16x4_t %s = %s(%s);"
                            % (out, fn, ins[0]))
            else:
                fn = "vget_low_u8" if attrs["which"] == "lo" \
                    else "vget_high_u8"
                body.append("    uint8x8_t %s = %s(%s);"
                            % (out, fn, ins[0]))
        elif kind == "vabdl_u8":
            body.append("    uint16x8_t %s = vabdl_u8(%s, %s);"
                        % (out, ins[0], ins[1]))
        elif kind == "vmull_u16":
            body.append("    uint32x4_t %s = vmull_u16(%s, %s);"
                        % (out, ins[0], ins[1]))
        elif kind == "vadd_u32":
            body.append("    uint32x4_t %s = vaddq_u32(%s, %s);"
                        % (out, ins[0], ins[1]))
        elif kind == "vaddv_u32":
            body.append("    int %s = (int)vaddvq_u32(%s);"
                        % (out, ins[0]))
        elif kind == "scalar_add2":
            body.append("    int %s = %s + %s;" % (ret, ins[0], ins[1]))
        else:
            raise ValueError("ssd emit: %s" % kind)
    return """\
// Generated by optimizer/ir/ssd_emit.py -- do not edit by hand.
// SSD sse_pp 16x16 pure NEON from width-independent DAG.
#include <arm_neon.h>
#include <stdint.h>

extern "C" int %s(const uint8_t* pix1, intptr_t stride1,
                  const uint8_t* pix2, intptr_t stride2)
{
%s
    return %s;
}
""" % (func_name, "\n".join(body), ret)
