// Generated by tools/emit_interp8_sve2_shared.py -- do not
// edit by hand. Vertical 8-tap luma 16x16 (SVE2, VL=256).
#include <arm_sve.h>

static inline svint16_t vrow(const uint8_t* p, intptr_t st, int k, int u, svbool_t p16)
{
    svuint16_t w = svld1ub_u16(p16, p + k * st + u * 16);
    // (b - 128) keeps 4-product s16 sums in range.
    return svreinterpret_s16_u16(svsub_n_u16_x(p16, w, 128));
}

extern "C" void dynopt_interp8_16x16_sve2_vpp(const uint8_t* src, intptr_t srcStride,
                   uint8_t* dst, intptr_t dstStride, int coeffIdx)
{
    const svbool_t p16 = svptrue_b16();
    const svbool_t p8b = svwhilelt_b8((uint32_t)0, (uint32_t)16);
    const int ph = (coeffIdx >= 1 && coeffIdx <= 3) ? coeffIdx : 2;
    const svint16_t c0 = svdup_n_s16(ph == 1 ? -1 : (ph == 3 ? 0 : -1));
    const svint16_t c1 = svdup_n_s16(ph == 1 ? 4 : (ph == 3 ? 1 : 4));
    const svint16_t c2 = svdup_n_s16(ph == 1 ? -10 : (ph == 3 ? -5 : -11));
    const svint16_t c3 = svdup_n_s16(ph == 1 ? 58 : (ph == 3 ? 17 : 40));
    const svint16_t c4 = svdup_n_s16(ph == 1 ? 17 : (ph == 3 ? 58 : 40));
    const svint16_t c5 = svdup_n_s16(ph == 1 ? -5 : (ph == 3 ? -10 : -11));
    const svint16_t c6 = svdup_n_s16(ph == 1 ? 1 : (ph == 3 ? 4 : 4));
    const svint16_t c7 = svdup_n_s16(ph == 1 ? 0 : (ph == 3 ? -1 : -1));
    // DC offset 8192 split across the accumulators
    // (2 accs -> 4096 each).
    const svint16_t off = svdup_n_s16(4096);
    const uint8_t* rb = src - 3 * srcStride;
    svint16_t v0_0 = vrow(rb, srcStride, 0, 0, p16);
    svint16_t v1_0 = vrow(rb, srcStride, 1, 0, p16);
    svint16_t v2_0 = vrow(rb, srcStride, 2, 0, p16);
    svint16_t v3_0 = vrow(rb, srcStride, 3, 0, p16);
    svint16_t v4_0 = vrow(rb, srcStride, 4, 0, p16);
    svint16_t v5_0 = vrow(rb, srcStride, 5, 0, p16);
    svint16_t v6_0 = vrow(rb, srcStride, 6, 0, p16);
    svint16_t v7_0 = vrow(rb, srcStride, 7, 0, p16);

    svint16_t v8_0 = vrow(rb, srcStride, 8, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v0_0, c0);
        a0 = svmla_s16_x(p16, a0, v2_0, c2);
        a0 = svmla_s16_x(p16, a0, v4_0, c4);
        a0 = svmla_s16_x(p16, a0, v6_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v1_0, c1);
        a1 = svmla_s16_x(p16, a1, v3_0, c3);
        a1 = svmla_s16_x(p16, a1, v5_0, c5);
        a1 = svmla_s16_x(p16, a1, v7_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 0 * dstStride + 0, uz);
    }
    svint16_t v9_0 = vrow(rb, srcStride, 9, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v1_0, c0);
        a0 = svmla_s16_x(p16, a0, v3_0, c2);
        a0 = svmla_s16_x(p16, a0, v5_0, c4);
        a0 = svmla_s16_x(p16, a0, v7_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v2_0, c1);
        a1 = svmla_s16_x(p16, a1, v4_0, c3);
        a1 = svmla_s16_x(p16, a1, v6_0, c5);
        a1 = svmla_s16_x(p16, a1, v8_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 1 * dstStride + 0, uz);
    }
    svint16_t v10_0 = vrow(rb, srcStride, 10, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v2_0, c0);
        a0 = svmla_s16_x(p16, a0, v4_0, c2);
        a0 = svmla_s16_x(p16, a0, v6_0, c4);
        a0 = svmla_s16_x(p16, a0, v8_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v3_0, c1);
        a1 = svmla_s16_x(p16, a1, v5_0, c3);
        a1 = svmla_s16_x(p16, a1, v7_0, c5);
        a1 = svmla_s16_x(p16, a1, v9_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 2 * dstStride + 0, uz);
    }
    svint16_t v11_0 = vrow(rb, srcStride, 11, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v3_0, c0);
        a0 = svmla_s16_x(p16, a0, v5_0, c2);
        a0 = svmla_s16_x(p16, a0, v7_0, c4);
        a0 = svmla_s16_x(p16, a0, v9_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v4_0, c1);
        a1 = svmla_s16_x(p16, a1, v6_0, c3);
        a1 = svmla_s16_x(p16, a1, v8_0, c5);
        a1 = svmla_s16_x(p16, a1, v10_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 3 * dstStride + 0, uz);
    }
    svint16_t v12_0 = vrow(rb, srcStride, 12, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v4_0, c0);
        a0 = svmla_s16_x(p16, a0, v6_0, c2);
        a0 = svmla_s16_x(p16, a0, v8_0, c4);
        a0 = svmla_s16_x(p16, a0, v10_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v5_0, c1);
        a1 = svmla_s16_x(p16, a1, v7_0, c3);
        a1 = svmla_s16_x(p16, a1, v9_0, c5);
        a1 = svmla_s16_x(p16, a1, v11_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 4 * dstStride + 0, uz);
    }
    svint16_t v13_0 = vrow(rb, srcStride, 13, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v5_0, c0);
        a0 = svmla_s16_x(p16, a0, v7_0, c2);
        a0 = svmla_s16_x(p16, a0, v9_0, c4);
        a0 = svmla_s16_x(p16, a0, v11_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v6_0, c1);
        a1 = svmla_s16_x(p16, a1, v8_0, c3);
        a1 = svmla_s16_x(p16, a1, v10_0, c5);
        a1 = svmla_s16_x(p16, a1, v12_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 5 * dstStride + 0, uz);
    }
    svint16_t v14_0 = vrow(rb, srcStride, 14, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v6_0, c0);
        a0 = svmla_s16_x(p16, a0, v8_0, c2);
        a0 = svmla_s16_x(p16, a0, v10_0, c4);
        a0 = svmla_s16_x(p16, a0, v12_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v7_0, c1);
        a1 = svmla_s16_x(p16, a1, v9_0, c3);
        a1 = svmla_s16_x(p16, a1, v11_0, c5);
        a1 = svmla_s16_x(p16, a1, v13_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 6 * dstStride + 0, uz);
    }
    svint16_t v15_0 = vrow(rb, srcStride, 15, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v7_0, c0);
        a0 = svmla_s16_x(p16, a0, v9_0, c2);
        a0 = svmla_s16_x(p16, a0, v11_0, c4);
        a0 = svmla_s16_x(p16, a0, v13_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v8_0, c1);
        a1 = svmla_s16_x(p16, a1, v10_0, c3);
        a1 = svmla_s16_x(p16, a1, v12_0, c5);
        a1 = svmla_s16_x(p16, a1, v14_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 7 * dstStride + 0, uz);
    }
    svint16_t v16_0 = vrow(rb, srcStride, 16, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v8_0, c0);
        a0 = svmla_s16_x(p16, a0, v10_0, c2);
        a0 = svmla_s16_x(p16, a0, v12_0, c4);
        a0 = svmla_s16_x(p16, a0, v14_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v9_0, c1);
        a1 = svmla_s16_x(p16, a1, v11_0, c3);
        a1 = svmla_s16_x(p16, a1, v13_0, c5);
        a1 = svmla_s16_x(p16, a1, v15_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 8 * dstStride + 0, uz);
    }
    svint16_t v17_0 = vrow(rb, srcStride, 17, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v9_0, c0);
        a0 = svmla_s16_x(p16, a0, v11_0, c2);
        a0 = svmla_s16_x(p16, a0, v13_0, c4);
        a0 = svmla_s16_x(p16, a0, v15_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v10_0, c1);
        a1 = svmla_s16_x(p16, a1, v12_0, c3);
        a1 = svmla_s16_x(p16, a1, v14_0, c5);
        a1 = svmla_s16_x(p16, a1, v16_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 9 * dstStride + 0, uz);
    }
    svint16_t v18_0 = vrow(rb, srcStride, 18, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v10_0, c0);
        a0 = svmla_s16_x(p16, a0, v12_0, c2);
        a0 = svmla_s16_x(p16, a0, v14_0, c4);
        a0 = svmla_s16_x(p16, a0, v16_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v11_0, c1);
        a1 = svmla_s16_x(p16, a1, v13_0, c3);
        a1 = svmla_s16_x(p16, a1, v15_0, c5);
        a1 = svmla_s16_x(p16, a1, v17_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 10 * dstStride + 0, uz);
    }
    svint16_t v19_0 = vrow(rb, srcStride, 19, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v11_0, c0);
        a0 = svmla_s16_x(p16, a0, v13_0, c2);
        a0 = svmla_s16_x(p16, a0, v15_0, c4);
        a0 = svmla_s16_x(p16, a0, v17_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v12_0, c1);
        a1 = svmla_s16_x(p16, a1, v14_0, c3);
        a1 = svmla_s16_x(p16, a1, v16_0, c5);
        a1 = svmla_s16_x(p16, a1, v18_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 11 * dstStride + 0, uz);
    }
    svint16_t v20_0 = vrow(rb, srcStride, 20, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v12_0, c0);
        a0 = svmla_s16_x(p16, a0, v14_0, c2);
        a0 = svmla_s16_x(p16, a0, v16_0, c4);
        a0 = svmla_s16_x(p16, a0, v18_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v13_0, c1);
        a1 = svmla_s16_x(p16, a1, v15_0, c3);
        a1 = svmla_s16_x(p16, a1, v17_0, c5);
        a1 = svmla_s16_x(p16, a1, v19_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 12 * dstStride + 0, uz);
    }
    svint16_t v21_0 = vrow(rb, srcStride, 21, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v13_0, c0);
        a0 = svmla_s16_x(p16, a0, v15_0, c2);
        a0 = svmla_s16_x(p16, a0, v17_0, c4);
        a0 = svmla_s16_x(p16, a0, v19_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v14_0, c1);
        a1 = svmla_s16_x(p16, a1, v16_0, c3);
        a1 = svmla_s16_x(p16, a1, v18_0, c5);
        a1 = svmla_s16_x(p16, a1, v20_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 13 * dstStride + 0, uz);
    }
    svint16_t v22_0 = vrow(rb, srcStride, 22, 0, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v14_0, c0);
        a0 = svmla_s16_x(p16, a0, v16_0, c2);
        a0 = svmla_s16_x(p16, a0, v18_0, c4);
        a0 = svmla_s16_x(p16, a0, v20_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v15_0, c1);
        a1 = svmla_s16_x(p16, a1, v17_0, c3);
        a1 = svmla_s16_x(p16, a1, v19_0, c5);
        a1 = svmla_s16_x(p16, a1, v21_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 14 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v15_0, c0);
        a0 = svmla_s16_x(p16, a0, v17_0, c2);
        a0 = svmla_s16_x(p16, a0, v19_0, c4);
        a0 = svmla_s16_x(p16, a0, v21_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v16_0, c1);
        a1 = svmla_s16_x(p16, a1, v18_0, c3);
        a1 = svmla_s16_x(p16, a1, v20_0, c5);
        a1 = svmla_s16_x(p16, a1, v22_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 15 * dstStride + 0, uz);
    }
}