// Generated by tools/gen_sve2_emit.py (generic vertical-ss recipe)
#include <arm_sve.h>
#include <stdint.h>

extern "C" void dynopt_interp8_vss_16x4_sve2(const int16_t* src, intptr_t srcStride, int16_t* dst, intptr_t dstStride, int coeffIdx)
{
    const svbool_t p32 = svptrue_b32();
    const svbool_t pg8h = svwhilelt_b16(0, 8);
    const svbool_t p16 = svptrue_b16();
    const int ph = (coeffIdx >= 1 && coeffIdx <= 3) ? coeffIdx : 2;
    const svint32_t c0 = svdup_n_s32(ph == 1 ? -1 : (ph == 3 ? 0 : -1));
    const svint32_t c1 = svdup_n_s32(ph == 1 ? 4 : (ph == 3 ? 1 : 4));
    const svint32_t c2 = svdup_n_s32(ph == 1 ? -10 : (ph == 3 ? -5 : -11));
    const svint32_t c3 = svdup_n_s32(ph == 1 ? 58 : (ph == 3 ? 17 : 40));
    const svint32_t c4 = svdup_n_s32(ph == 1 ? 17 : (ph == 3 ? 58 : 40));
    const svint32_t c5 = svdup_n_s32(ph == 1 ? -5 : (ph == 3 ? -10 : -11));
    const svint32_t c6 = svdup_n_s32(ph == 1 ? 1 : (ph == 3 ? 4 : 4));
    const svint32_t c7 = svdup_n_s32(ph == 1 ? 0 : (ph == 3 ? -1 : -1));
    svint16_t r0_0 = svld1_s16(p16, src + -3 * srcStride + 0);
    svint16_t r1_0 = svld1_s16(p16, src + -2 * srcStride + 0);
    svint16_t r2_0 = svld1_s16(p16, src + -1 * srcStride + 0);
    svint16_t r3_0 = svld1_s16(p16, src + 0 * srcStride + 0);
    svint16_t r4_0 = svld1_s16(p16, src + 1 * srcStride + 0);
    svint16_t r5_0 = svld1_s16(p16, src + 2 * srcStride + 0);
    svint16_t r6_0 = svld1_s16(p16, src + 3 * srcStride + 0);
    svint16_t r7_0 = svld1_s16(p16, src + 4 * srcStride + 0);
    svint16_t r8_0 = svld1_s16(p16, src + 5 * srcStride + 0);
    svint16_t r9_0 = svld1_s16(p16, src + 6 * srcStride + 0);
    svint16_t r10_0 = svld1_s16(p16, src + 7 * srcStride + 0);
    {
        svint32_t acc = svdup_n_s32(0);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r0_0), c0);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r1_0), c1);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r2_0), c2);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r3_0), c3);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r4_0), c4);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r5_0), c5);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r6_0), c6);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r7_0), c7);
        svint16_t n = svshrnb_n_s32(acc, 6);
        svint16_t z = svuzp1_s16(n, n);
        svst1_s16(pg8h, dst + 0 * dstStride + 0, z);
    }
    {
        svint32_t acc = svdup_n_s32(0);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r0_0), c0);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r1_0), c1);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r2_0), c2);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r3_0), c3);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r4_0), c4);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r5_0), c5);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r6_0), c6);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r7_0), c7);
        svint16_t n = svshrnb_n_s32(acc, 6);
        svint16_t z = svuzp1_s16(n, n);
        svst1_s16(pg8h, dst + 0 * dstStride + 8, z);
    }
    {
        svint32_t acc = svdup_n_s32(0);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r1_0), c0);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r2_0), c1);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r3_0), c2);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r4_0), c3);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r5_0), c4);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r6_0), c5);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r7_0), c6);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r8_0), c7);
        svint16_t n = svshrnb_n_s32(acc, 6);
        svint16_t z = svuzp1_s16(n, n);
        svst1_s16(pg8h, dst + 1 * dstStride + 0, z);
    }
    {
        svint32_t acc = svdup_n_s32(0);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r1_0), c0);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r2_0), c1);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r3_0), c2);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r4_0), c3);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r5_0), c4);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r6_0), c5);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r7_0), c6);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r8_0), c7);
        svint16_t n = svshrnb_n_s32(acc, 6);
        svint16_t z = svuzp1_s16(n, n);
        svst1_s16(pg8h, dst + 1 * dstStride + 8, z);
    }
    {
        svint32_t acc = svdup_n_s32(0);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r2_0), c0);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r3_0), c1);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r4_0), c2);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r5_0), c3);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r6_0), c4);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r7_0), c5);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r8_0), c6);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r9_0), c7);
        svint16_t n = svshrnb_n_s32(acc, 6);
        svint16_t z = svuzp1_s16(n, n);
        svst1_s16(pg8h, dst + 2 * dstStride + 0, z);
    }
    {
        svint32_t acc = svdup_n_s32(0);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r2_0), c0);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r3_0), c1);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r4_0), c2);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r5_0), c3);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r6_0), c4);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r7_0), c5);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r8_0), c6);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r9_0), c7);
        svint16_t n = svshrnb_n_s32(acc, 6);
        svint16_t z = svuzp1_s16(n, n);
        svst1_s16(pg8h, dst + 2 * dstStride + 8, z);
    }
    {
        svint32_t acc = svdup_n_s32(0);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r3_0), c0);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r4_0), c1);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r5_0), c2);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r6_0), c3);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r7_0), c4);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r8_0), c5);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r9_0), c6);
        acc = svmla_s32_x(p32, acc, svunpklo_s32(r10_0), c7);
        svint16_t n = svshrnb_n_s32(acc, 6);
        svint16_t z = svuzp1_s16(n, n);
        svst1_s16(pg8h, dst + 3 * dstStride + 0, z);
    }
    {
        svint32_t acc = svdup_n_s32(0);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r3_0), c0);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r4_0), c1);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r5_0), c2);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r6_0), c3);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r7_0), c4);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r8_0), c5);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r9_0), c6);
        acc = svmla_s32_x(p32, acc, svunpkhi_s32(r10_0), c7);
        svint16_t n = svshrnb_n_s32(acc, 6);
        svint16_t z = svuzp1_s16(n, n);
        svst1_s16(pg8h, dst + 3 * dstStride + 8, z);
    }
}
