// Generated by tools/emit_interp8_sve2_shared.py -- do not edit by hand.
// 8-bit horizontal 8-tap luma filter 8x8 (SVE2, VL=256), upstream-exact.
#include <arm_sve.h>
#include <arm_neon.h>
#include <arm_neon_sve_bridge.h>

static const int16_t CTBL[4][2][16] = {
    {
        { -1, 4, -10, 58, -1, 4, -10, 58, -1, 4, -10, 58, -1, 4, -10, 58 },  // m=0
        { 17, -5, 1, 0, 17, -5, 1, 0, 17, -5, 1, 0, 17, -5, 1, 0 },  // m=1
    },  // phase 1
    {
        { -1, 4, -11, 40, -1, 4, -11, 40, -1, 4, -11, 40, -1, 4, -11, 40 },  // m=0
        { 40, -11, 4, -1, 40, -11, 4, -1, 40, -11, 4, -1, 40, -11, 4, -1 },  // m=1
    },  // phase 2
    {
        { 0, 1, -5, 17, 0, 1, -5, 17, 0, 1, -5, 17, 0, 1, -5, 17 },  // m=0
        { 58, -10, 4, -1, 58, -10, 4, -1, 58, -10, 4, -1, 58, -10, 4, -1 },  // m=1
    },  // phase 3
};
static const uint16_t IDX_X0[16] =
    { 0, 1, 2, 3, 1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6 };
static const uint16_t IDX_X1[16] =
    { 4, 5, 6, 7, 5, 6, 7, 8, 6, 7, 8, 9, 7, 8, 9, 10 };
static const uint16_t IDX_X2[16] =
    { 8, 9, 10, 11, 9, 10, 11, 12, 10, 11, 12, 13, 11, 12, 13, 14 };


extern "C" void dynopt_interp8_8x8_sve2(const uint8_t* src, intptr_t srcStride,
                   uint8_t* dst, intptr_t dstStride, int coeffIdx)
{
    const svbool_t p16 = svptrue_b16();
    const svbool_t pg4b = svwhilelt_b8(0, 4);
    const svint64_t zero64 = svdup_n_s64(0);
    const int ph = (coeffIdx >= 1 && coeffIdx <= 3) ? coeffIdx : 2;
    const svint16_t c0 = svld1_s16(p16, CTBL[ph - 1][0]);
    const svint16_t c1 = svld1_s16(p16, CTBL[ph - 1][1]);
    const svuint16_t ix0 = svld1_u16(p16, IDX_X0);
    const svuint16_t ix1 = svld1_u16(p16, IDX_X1);
    const svuint16_t ix2 = svld1_u16(p16, IDX_X2);

    for (int r = 0; r < 8; r++)
    {
        const uint8_t* row = src + r * srcStride - 3;
        svuint16_t W = svld1ub_u16(p16, row);
        svint16_t X0 = svreinterpret_s16_u16(svtbl_u16(W, ix0));
        svint16_t X1 = svreinterpret_s16_u16(svtbl_u16(W, ix1));
        svint16_t X2 = svreinterpret_s16_u16(svtbl_u16(W, ix2));

        svint64_t t0 = svdot_s64(zero64, X0, c0);
        t0 = svdot_s64(t0, X1, c1);
        svint32_t lo0 = svuzp1_s32(svreinterpret_s32_s64(t0),
                                   svreinterpret_s32_s64(t0));
        svint16_t r0 = svrshrnb_n_s32(lo0, 6);
        svint16_t rz0 = svuzp1_s16(r0, r0);
        uint8x8_t u0 = vqmovun_s16(svget_neonq_s16(rz0));
        svst1_u8(pg4b, dst + r * dstStride,
                 svset_neonq_u8(svundef_u8(), vcombine_u8(u0, vdup_n_u8(0))));

        svint64_t t1 = svdot_s64(zero64, X1, c0);
        t1 = svdot_s64(t1, X2, c1);
        svint32_t lo1 = svuzp1_s32(svreinterpret_s32_s64(t1),
                                   svreinterpret_s32_s64(t1));
        svint16_t r1 = svrshrnb_n_s32(lo1, 6);
        svint16_t rz1 = svuzp1_s16(r1, r1);
        uint8x8_t u1 = vqmovun_s16(svget_neonq_s16(rz1));
        svst1_u8(pg4b, dst + r * dstStride + 4,
                 svset_neonq_u8(svundef_u8(), vcombine_u8(u1, vdup_n_u8(0))));
    }
}
