// Generated by optimizer/ir/dct32_fused8_emit.py -- do not edit.
// 8-lane fused quarter (VL=128 baseline).
#include <arm_neon.h>
#include <arm_sve.h>
#include <arm_neon_sve_bridge.h>
#include <cstdint>


static const uint8_t rev16_tbl[16] =
    { 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1 };
static const uint8_t rev32_tbl[16] =
    { 12, 13, 14, 15, 8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3 };

static inline int16x8_t rev16(const int16x8_t a)
{
    return vreinterpretq_s16_s8(vqtbx1q_s8(
        vreinterpretq_s8_s16(a), vreinterpretq_s8_s16(a),
        vld1q_u8(rev16_tbl)));
}

static inline int32x4_t rev32(const int32x4_t a)
{
    return vreinterpretq_s32_s8(vqtbx1q_s8(
        vreinterpretq_s8_s32(a), vreinterpretq_s8_s32(a),
        vld1q_u8(rev32_tbl)));
}

static inline int64x2_t sdotq_s16(int64x2_t acc, int16x8_t x, int16x8_t y)
{
    return svget_neonq_s64(svdot_s64(svset_neonq_s64(svundef_s64(), acc),
                                     svset_neonq_s16(svundef_s16(), x),
                                     svset_neonq_s16(svundef_s16(), y)));
}

static inline int32x4_t vld1sh_s32(const int16_t* p)
{
    return svget_neonq_s32(svld1sh_s32(svptrue_pat_b32(SV_VL4), p));
}


static const int16_t GT32A[32][8] = {
    { 64, 64, 64, 64, 64, 64, 64, 64 },
    { 90, 90, 88, 85, 82, 78, 73, 67 },
    { 90, 87, 80, 70, 57, 43, 25, 9 },
    { 90, 82, 67, 46, 22, -4, -31, -54 },
    { 89, 75, 50, 18, -18, -50, -75, -89 },
    { 88, 67, 31, -13, -54, -82, -90, -78 },
    { 87, 57, 9, -43, -80, -90, -70, -25 },
    { 85, 46, -13, -67, -90, -73, -22, 38 },
    { 83, 36, -36, -83, -83, -36, 36, 83 },
    { 82, 22, -54, -90, -61, 13, 78, 85 },
    { 80, 9, -70, -87, -25, 57, 90, 43 },
    { 78, -4, -82, -73, 13, 85, 67, -22 },
    { 75, -18, -89, -50, 50, 89, 18, -75 },
    { 73, -31, -90, -22, 78, 67, -38, -90 },
    { 70, -43, -87, 9, 90, 25, -80, -57 },
    { 67, -54, -78, 38, 85, -22, -90, 4 },
    { 64, -64, -64, 64, 64, -64, -64, 64 },
    { 61, -73, -46, 82, 31, -88, -13, 90 },
    { 57, -80, -25, 90, -9, -87, 43, 70 },
    { 54, -85, -4, 88, -46, -61, 82, 13 },
    { 50, -89, 18, 75, -75, -18, 89, -50 },
    { 46, -90, 38, 54, -90, 31, 61, -88 },
    { 43, -90, 57, 25, -87, 70, 9, -80 },
    { 38, -88, 73, -4, -67, 90, -46, -31 },
    { 36, -83, 83, -36, -36, 83, -83, 36 },
    { 31, -78, 90, -61, 4, 54, -88, 82 },
    { 25, -70, 90, -80, 43, 9, -57, 87 },
    { 22, -61, 85, -90, 73, -38, -4, 46 },
    { 18, -50, 75, -89, 89, -75, 50, -18 },
    { 13, -38, 61, -78, 88, -90, 85, -73 },
    { 9, -25, 43, -57, 70, -80, 87, -90 },
    { 4, -13, 22, -31, 38, -46, 54, -61 },
};

static const int16_t GT32B[32][8] = {
    { 64, 64, 64, 64, 64, 64, 64, 64 },
    { 61, 54, 46, 38, 31, 22, 13, 4 },
    { -9, -25, -43, -57, -70, -80, -87, -90 },
    { -73, -85, -90, -88, -78, -61, -38, -13 },
    { -89, -75, -50, -18, 18, 50, 75, 89 },
    { -46, -4, 38, 73, 90, 85, 61, 22 },
    { 25, 70, 90, 80, 43, -9, -57, -87 },
    { 82, 88, 54, -4, -61, -90, -78, -31 },
    { 83, 36, -36, -83, -83, -36, 36, 83 },
    { 31, -46, -90, -67, 4, 73, 88, 38 },
    { -43, -90, -57, 25, 87, 70, -9, -80 },
    { -88, -61, 31, 90, 54, -38, -90, -46 },
    { -75, 18, 89, 50, -50, -89, -18, 75 },
    { -13, 82, 61, -46, -88, -4, 85, 54 },
    { 57, 80, -25, -90, -9, 87, 43, -70 },
    { 90, 13, -88, -31, 82, 46, -73, -61 },
    { 64, -64, -64, 64, 64, -64, -64, 64 },
    { -4, -90, 22, 85, -38, -78, 54, 67 },
    { -70, -43, 87, 9, -90, 25, 80, -57 },
    { -90, 38, 67, -78, -22, 90, -31, -73 },
    { -50, 89, -18, -75, 75, 18, -89, 50 },
    { 22, 67, -85, 13, 73, -82, 4, 78 },
    { 80, -9, -70, 87, -25, -57, 90, -43 },
    { 85, -78, 13, 61, -90, 54, 22, -82 },
    { 36, -83, 83, -36, -36, 83, -83, 36 },
    { -38, -22, 73, -90, 67, -13, -46, 85 },
    { -87, 57, -9, -43, 80, -90, 70, -25 },
    { -78, 90, -82, 54, -13, -31, 67, -88 },
    { -18, 50, -75, 89, -89, 75, -50, 18 },
    { 54, -31, 4, 22, -46, 67, -82, 90 },
    { 90, -87, 80, -70, 57, -43, 25, -9 },
    { 67, -73, 78, -82, 85, -88, 90, -90 },
};

static const int16_t T8ODD16[4][8] = {
    { 89, 75, 50, 18, 89, 75, 50, 18 },
    { 75, -18, -89, -50, 75, -18, -89, -50 },
    { 50, -89, 18, 75, 50, -89, 18, 75 },
    { 18, -50, 75, -89, 18, -50, 75, -89 },
};

static const int32_t GT32S32A[8][4] = {
    { 90, 87, 80, 70 },
    { 87, 57, 9, -43 },
    { 80, 9, -70, -87 },
    { 70, -43, -87, 9 },
    { 57, -80, -25, 90 },
    { 43, -90, 57, 25 },
    { 25, -70, 90, -80 },
    { 9, -25, 43, -57 },
};

static const int32_t GT32S32B[8][4] = {
    { 57, 43, 25, 9 },
    { -80, -90, -70, -25 },
    { -25, 57, 90, 43 },
    { 90, 25, -80, -57 },
    { -9, -87, 43, 70 },
    { -87, 70, 9, -80 },
    { 43, 9, -57, 87 },
    { 70, -80, 87, -90 },
};

static const int32_t GT32S32A4[4][4] = {
    { 89, 75, 50, 18 },
    { 75, -18, -89, -50 },
    { 50, -89, 18, 75 },
    { 18, -50, 75, -89 },
};

static const int32_t T8E[4][4] = {
    { 64, 64, 64, 64 },
    { 83, 36, 83, 36 },
    { 64, -64, 64, -64 },
    { 36, -83, 36, -83 },
};

static inline void op_pass_4(const int16_t* src, int16_t* dst, intptr_t stride)
{
    const int line = 32;
    const int shift = 4;
    for (int i = 0; i < line; i += 4)
    {
                const int16x8_t r0_v0 = vld1q_s16(src + (i + 0)*stride+0);
                const int16x8_t r0_v1 = vld1q_s16(src + (i + 0)*stride+8);
                const int16x8_t r0_v2 = vld1q_s16(src + (i + 0)*stride+16);
                const int16x8_t r0_v3 = vld1q_s16(src + (i + 0)*stride+24);
                int16x8_t r0_v2r = rev16(r0_v2);
                int16x8_t r0_v3r = rev16(r0_v3);
                int16x8_t O_0_0 = vsubq_s16(r0_v0, r0_v3r);
                int16x8_t O_0_1 = vsubq_s16(r0_v1, r0_v2r);
                int16x4_t g0_0_a = vget_low_s16(r0_v0);
                int16x4_t g0_0_c = vget_low_s16(r0_v3r);
                int32x4_t E0_0 = vaddl_s16(g0_0_a, g0_0_c);
                int16x4_t g1_0_a = vget_high_s16(r0_v0);
                int16x4_t g1_0_c = vget_high_s16(r0_v3r);
                int32x4_t E1_0 = vaddl_s16(g1_0_a, g1_0_c);
                int16x4_t g2_0_a = vget_low_s16(r0_v1);
                int16x4_t g2_0_c = vget_low_s16(r0_v2r);
                int32x4_t E2_0 = vaddl_s16(g2_0_a, g2_0_c);
                int16x4_t g3_0_a = vget_high_s16(r0_v1);
                int16x4_t g3_0_c = vget_high_s16(r0_v2r);
                int32x4_t E3_0 = vaddl_s16(g3_0_a, g3_0_c);
                int32x4_t Er_0_3 = rev32(E3_0);
                int32x4_t Er_0_2 = rev32(E2_0);
                int32x4_t EOx_0_lo = vsubq_s32(E0_0, Er_0_3);
                int16x4_t EOn_0_lo = vmovn_s32(EOx_0_lo);
                int32x4_t EOx_0_hi = vsubq_s32(E1_0, Er_0_2);
                int16x4_t EOn_0_hi = vmovn_s32(EOx_0_hi);
                int16x8_t EO_0 = vcombine_s16(EOn_0_lo, EOn_0_hi);
                int32x4_t EEr_0_3 = rev32(E3_0);
                int32x4_t EEr_0_2 = rev32(E2_0);
                int32x4_t EE_0_0 = vaddq_s32(E0_0, EEr_0_3);
                int32x4_t EE_0_1 = vaddq_s32(E1_0, EEr_0_2);
                int32x4_t EEr2_0 = rev32(EE_0_1);
                int32x4_t EEE_0 = vaddq_s32(EE_0_0, EEr2_0);
                int32x4_t EEO_0 = vsubq_s32(EE_0_0, EEr2_0);
                const int16x8_t r1_v0 = vld1q_s16(src + (i + 1)*stride+0);
                const int16x8_t r1_v1 = vld1q_s16(src + (i + 1)*stride+8);
                const int16x8_t r1_v2 = vld1q_s16(src + (i + 1)*stride+16);
                const int16x8_t r1_v3 = vld1q_s16(src + (i + 1)*stride+24);
                int16x8_t r1_v2r = rev16(r1_v2);
                int16x8_t r1_v3r = rev16(r1_v3);
                int16x8_t O_1_0 = vsubq_s16(r1_v0, r1_v3r);
                int16x8_t O_1_1 = vsubq_s16(r1_v1, r1_v2r);
                int16x4_t g0_1_a = vget_low_s16(r1_v0);
                int16x4_t g0_1_c = vget_low_s16(r1_v3r);
                int32x4_t E0_1 = vaddl_s16(g0_1_a, g0_1_c);
                int16x4_t g1_1_a = vget_high_s16(r1_v0);
                int16x4_t g1_1_c = vget_high_s16(r1_v3r);
                int32x4_t E1_1 = vaddl_s16(g1_1_a, g1_1_c);
                int16x4_t g2_1_a = vget_low_s16(r1_v1);
                int16x4_t g2_1_c = vget_low_s16(r1_v2r);
                int32x4_t E2_1 = vaddl_s16(g2_1_a, g2_1_c);
                int16x4_t g3_1_a = vget_high_s16(r1_v1);
                int16x4_t g3_1_c = vget_high_s16(r1_v2r);
                int32x4_t E3_1 = vaddl_s16(g3_1_a, g3_1_c);
                int32x4_t Er_1_3 = rev32(E3_1);
                int32x4_t Er_1_2 = rev32(E2_1);
                int32x4_t EOx_1_lo = vsubq_s32(E0_1, Er_1_3);
                int16x4_t EOn_1_lo = vmovn_s32(EOx_1_lo);
                int32x4_t EOx_1_hi = vsubq_s32(E1_1, Er_1_2);
                int16x4_t EOn_1_hi = vmovn_s32(EOx_1_hi);
                int16x8_t EO_1 = vcombine_s16(EOn_1_lo, EOn_1_hi);
                int32x4_t EEr_1_3 = rev32(E3_1);
                int32x4_t EEr_1_2 = rev32(E2_1);
                int32x4_t EE_1_0 = vaddq_s32(E0_1, EEr_1_3);
                int32x4_t EE_1_1 = vaddq_s32(E1_1, EEr_1_2);
                int32x4_t EEr2_1 = rev32(EE_1_1);
                int32x4_t EEE_1 = vaddq_s32(EE_1_0, EEr2_1);
                int32x4_t EEO_1 = vsubq_s32(EE_1_0, EEr2_1);
                const int16x8_t r2_v0 = vld1q_s16(src + (i + 2)*stride+0);
                const int16x8_t r2_v1 = vld1q_s16(src + (i + 2)*stride+8);
                const int16x8_t r2_v2 = vld1q_s16(src + (i + 2)*stride+16);
                const int16x8_t r2_v3 = vld1q_s16(src + (i + 2)*stride+24);
                int16x8_t r2_v2r = rev16(r2_v2);
                int16x8_t r2_v3r = rev16(r2_v3);
                int16x8_t O_2_0 = vsubq_s16(r2_v0, r2_v3r);
                int16x8_t O_2_1 = vsubq_s16(r2_v1, r2_v2r);
                int16x4_t g0_2_a = vget_low_s16(r2_v0);
                int16x4_t g0_2_c = vget_low_s16(r2_v3r);
                int32x4_t E0_2 = vaddl_s16(g0_2_a, g0_2_c);
                int16x4_t g1_2_a = vget_high_s16(r2_v0);
                int16x4_t g1_2_c = vget_high_s16(r2_v3r);
                int32x4_t E1_2 = vaddl_s16(g1_2_a, g1_2_c);
                int16x4_t g2_2_a = vget_low_s16(r2_v1);
                int16x4_t g2_2_c = vget_low_s16(r2_v2r);
                int32x4_t E2_2 = vaddl_s16(g2_2_a, g2_2_c);
                int16x4_t g3_2_a = vget_high_s16(r2_v1);
                int16x4_t g3_2_c = vget_high_s16(r2_v2r);
                int32x4_t E3_2 = vaddl_s16(g3_2_a, g3_2_c);
                int32x4_t Er_2_3 = rev32(E3_2);
                int32x4_t Er_2_2 = rev32(E2_2);
                int32x4_t EOx_2_lo = vsubq_s32(E0_2, Er_2_3);
                int16x4_t EOn_2_lo = vmovn_s32(EOx_2_lo);
                int32x4_t EOx_2_hi = vsubq_s32(E1_2, Er_2_2);
                int16x4_t EOn_2_hi = vmovn_s32(EOx_2_hi);
                int16x8_t EO_2 = vcombine_s16(EOn_2_lo, EOn_2_hi);
                int32x4_t EEr_2_3 = rev32(E3_2);
                int32x4_t EEr_2_2 = rev32(E2_2);
                int32x4_t EE_2_0 = vaddq_s32(E0_2, EEr_2_3);
                int32x4_t EE_2_1 = vaddq_s32(E1_2, EEr_2_2);
                int32x4_t EEr2_2 = rev32(EE_2_1);
                int32x4_t EEE_2 = vaddq_s32(EE_2_0, EEr2_2);
                int32x4_t EEO_2 = vsubq_s32(EE_2_0, EEr2_2);
                const int16x8_t r3_v0 = vld1q_s16(src + (i + 3)*stride+0);
                const int16x8_t r3_v1 = vld1q_s16(src + (i + 3)*stride+8);
                const int16x8_t r3_v2 = vld1q_s16(src + (i + 3)*stride+16);
                const int16x8_t r3_v3 = vld1q_s16(src + (i + 3)*stride+24);
                int16x8_t r3_v2r = rev16(r3_v2);
                int16x8_t r3_v3r = rev16(r3_v3);
                int16x8_t O_3_0 = vsubq_s16(r3_v0, r3_v3r);
                int16x8_t O_3_1 = vsubq_s16(r3_v1, r3_v2r);
                int16x4_t g0_3_a = vget_low_s16(r3_v0);
                int16x4_t g0_3_c = vget_low_s16(r3_v3r);
                int32x4_t E0_3 = vaddl_s16(g0_3_a, g0_3_c);
                int16x4_t g1_3_a = vget_high_s16(r3_v0);
                int16x4_t g1_3_c = vget_high_s16(r3_v3r);
                int32x4_t E1_3 = vaddl_s16(g1_3_a, g1_3_c);
                int16x4_t g2_3_a = vget_low_s16(r3_v1);
                int16x4_t g2_3_c = vget_low_s16(r3_v2r);
                int32x4_t E2_3 = vaddl_s16(g2_3_a, g2_3_c);
                int16x4_t g3_3_a = vget_high_s16(r3_v1);
                int16x4_t g3_3_c = vget_high_s16(r3_v2r);
                int32x4_t E3_3 = vaddl_s16(g3_3_a, g3_3_c);
                int32x4_t Er_3_3 = rev32(E3_3);
                int32x4_t Er_3_2 = rev32(E2_3);
                int32x4_t EOx_3_lo = vsubq_s32(E0_3, Er_3_3);
                int16x4_t EOn_3_lo = vmovn_s32(EOx_3_lo);
                int32x4_t EOx_3_hi = vsubq_s32(E1_3, Er_3_2);
                int16x4_t EOn_3_hi = vmovn_s32(EOx_3_hi);
                int16x8_t EO_3 = vcombine_s16(EOn_3_lo, EOn_3_hi);
                int32x4_t EEr_3_3 = rev32(E3_3);
                int32x4_t EEr_3_2 = rev32(E2_3);
                int32x4_t EE_3_0 = vaddq_s32(E0_3, EEr_3_3);
                int32x4_t EE_3_1 = vaddq_s32(E1_3, EEr_3_2);
                int32x4_t EEr2_3 = rev32(EE_3_1);
                int32x4_t EEE_3 = vaddq_s32(EE_3_0, EEr2_3);
                int32x4_t EEO_3 = vsubq_s32(EE_3_0, EEr2_3);
                int32x4_t t0_0 = vreinterpretq_s32_s64(vzip1q_s64(vreinterpretq_s64_s32(EEE_0), vreinterpretq_s64_s32(EEE_1)));
                int32x4_t z2_0 = vreinterpretq_s32_s64(vzip2q_s64(vreinterpretq_s64_s32(EEE_0), vreinterpretq_s64_s32(EEE_1)));
                int32x4_t t1_0 = vrev64q_s32(z2_0);
                int32x4_t EEEE_0 = vaddq_s32(t0_0, t1_0);
                int32x4_t EEEO_0 = vsubq_s32(t0_0, t1_0);
                int32x4_t t0_1 = vreinterpretq_s32_s64(vzip1q_s64(vreinterpretq_s64_s32(EEE_2), vreinterpretq_s64_s32(EEE_3)));
                int32x4_t z2_1 = vreinterpretq_s32_s64(vzip2q_s64(vreinterpretq_s64_s32(EEE_2), vreinterpretq_s64_s32(EEE_3)));
                int32x4_t t1_1 = vrev64q_s32(z2_1);
                int32x4_t EEEE_1 = vaddq_s32(t0_1, t1_1);
                int32x4_t EEEO_1 = vsubq_s32(t0_1, t1_1);
        for (int k = 1; k < 32; k += 2)
        {
                    const int16x8_t c_GT32A_1_ = vld1q_s16(GT32A[k]);
                    int64x2_t t_1_0 = sdotq_s16(vdupq_n_s64(0), c_GT32A_1_, O_0_0);
                    const int16x8_t c_GT32B_1_ = vld1q_s16(GT32B[k]);
                    t_1_0 = sdotq_s16(t_1_0, c_GT32B_1_, O_0_1);
                    int64x2_t t_1_1 = sdotq_s16(vdupq_n_s64(0), c_GT32A_1_, O_1_0);
                    t_1_1 = sdotq_s16(t_1_1, c_GT32B_1_, O_1_1);
                    int64x2_t t_1_2 = sdotq_s16(vdupq_n_s64(0), c_GT32A_1_, O_2_0);
                    t_1_2 = sdotq_s16(t_1_2, c_GT32B_1_, O_2_1);
                    int64x2_t t_1_3 = sdotq_s16(vdupq_n_s64(0), c_GT32A_1_, O_3_0);
                    t_1_3 = sdotq_s16(t_1_3, c_GT32B_1_, O_3_1);
                    const int32x4_t t01_nn_1_0 = vcombine_s32(vmovn_s64(t_1_0), vmovn_s64(t_1_1));
                    const int32x4_t t23_nn_1_0 = vcombine_s32(vmovn_s64(t_1_2), vmovn_s64(t_1_3));
                    const int32x4_t w_nn_1_0 = vpaddq_s32(t01_nn_1_0, t23_nn_1_0);
                    int16x4_t nn_1_0 = vrshrn_n_s32(w_nn_1_0, shift);
                    vst1_s16(dst + 32*k + i, nn_1_0);
        }
        for (int k = 2; k < 32; k += 4)
        {
                    const int16x8_t c_GT32A_2_ = vld1q_s16(GT32A[k]);
                    int64x2_t t_2_0 = sdotq_s16(vdupq_n_s64(0), c_GT32A_2_, EO_0);
                    int64x2_t t_2_1 = sdotq_s16(vdupq_n_s64(0), c_GT32A_2_, EO_1);
                    int64x2_t t_2_2 = sdotq_s16(vdupq_n_s64(0), c_GT32A_2_, EO_2);
                    int64x2_t t_2_3 = sdotq_s16(vdupq_n_s64(0), c_GT32A_2_, EO_3);
                    const int32x4_t t01_nn_2_0 = vcombine_s32(vmovn_s64(t_2_0), vmovn_s64(t_2_1));
                    const int32x4_t t23_nn_2_0 = vcombine_s32(vmovn_s64(t_2_2), vmovn_s64(t_2_3));
                    const int32x4_t w_nn_2_0 = vpaddq_s32(t01_nn_2_0, t23_nn_2_0);
                    int16x4_t nn_2_0 = vrshrn_n_s32(w_nn_2_0, shift);
                    vst1_s16(dst + 32*k + i, nn_2_0);
        }
        for (int k = 4; k < 32; k += 8)
        {
                    const int32x4_t c_GT32S32A4_0_ = vld1q_s32(GT32S32A4[(k-4)/8]);
                    int32x4_t m_4_0 = vmulq_s32(c_GT32S32A4_0_, EEO_0);
                    int32x4_t m_4_1 = vmulq_s32(c_GT32S32A4_0_, EEO_1);
                    int32x4_t m_4_2 = vmulq_s32(c_GT32S32A4_0_, EEO_2);
                    int32x4_t m_4_3 = vmulq_s32(c_GT32S32A4_0_, EEO_3);
                    int32x4_t t01_4_0 = vpaddq_s32(m_4_0, m_4_1);
                    int32x4_t t23_4_0 = vpaddq_s32(m_4_2, m_4_3);
                    int32x4_t t_4_0 = vpaddq_s32(t01_4_0, t23_4_0);
                    int16x4_t nn_4_0 = vrshrn_n_s32(t_4_0, shift);
                    vst1_s16(dst + 32*k + i, nn_4_0);
        }
                int32x4_t pp_0_0 = vpaddq_s32(EEEE_0, EEEE_1);
                const int32x4_t c_T8E_0_ = vld1q_s32(T8E[0]);
                int32x4_t m_0_0 = vmulq_s32(c_T8E_0_, pp_0_0);
                int16x4_t nn_0_0 = vrshrn_n_s32(m_0_0, shift);
                vst1_s16(dst + 32*0 + i, nn_0_0);
                const int32x4_t c_T8E_1_ = vld1q_s32(T8E[1]);
                int32x4_t m0_8_0 = vmulq_s32(c_T8E_1_, EEEO_0);
                int32x4_t m1_8_0 = vmulq_s32(c_T8E_1_, EEEO_1);
                int32x4_t m_8_0 = vpaddq_s32(m0_8_0, m1_8_0);
                int16x4_t nn_8_0 = vrshrn_n_s32(m_8_0, shift);
                vst1_s16(dst + 32*8 + i, nn_8_0);
                const int32x4_t c_T8E_2_ = vld1q_s32(T8E[2]);
                int32x4_t m0_16_0 = vmulq_s32(c_T8E_2_, EEEE_0);
                int32x4_t m1_16_0 = vmulq_s32(c_T8E_2_, EEEE_1);
                int32x4_t m_16_0 = vpaddq_s32(m0_16_0, m1_16_0);
                int16x4_t nn_16_0 = vrshrn_n_s32(m_16_0, shift);
                vst1_s16(dst + 32*16 + i, nn_16_0);
                const int32x4_t c_T8E_3_ = vld1q_s32(T8E[3]);
                int32x4_t m0_24_0 = vmulq_s32(c_T8E_3_, EEEO_0);
                int32x4_t m1_24_0 = vmulq_s32(c_T8E_3_, EEEO_1);
                int32x4_t m_24_0 = vpaddq_s32(m0_24_0, m1_24_0);
                int16x4_t nn_24_0 = vrshrn_n_s32(m_24_0, shift);
                vst1_s16(dst + 32*24 + i, nn_24_0);
    }
}

static inline void op_pass_11(const int16_t* src, int16_t* dst)
{
    const int line = 32;
    const int shift = 11;
    for (int i = 0; i < line; i += 4)
    {
                const int16x8_t r0_v0 = vld1q_s16(src + (i + 0)*line+0);
                const int16x8_t r0_v1 = vld1q_s16(src + (i + 0)*line+8);
                const int16x8_t r0_v2 = vld1q_s16(src + (i + 0)*line+16);
                const int16x8_t r0_v3 = vld1q_s16(src + (i + 0)*line+24);
                int16x8_t r0_v2r = rev16(r0_v2);
                int16x8_t r0_v3r = rev16(r0_v3);
                int16x8_t O_0_0 = vsubq_s16(r0_v0, r0_v3r);
                int16x8_t O_0_1 = vsubq_s16(r0_v1, r0_v2r);
                int16x4_t g0_0_a = vget_low_s16(r0_v0);
                int16x4_t g0_0_c = vget_low_s16(r0_v3r);
                int32x4_t E0_0 = vaddl_s16(g0_0_a, g0_0_c);
                int16x4_t g1_0_a = vget_high_s16(r0_v0);
                int16x4_t g1_0_c = vget_high_s16(r0_v3r);
                int32x4_t E1_0 = vaddl_s16(g1_0_a, g1_0_c);
                int16x4_t g2_0_a = vget_low_s16(r0_v1);
                int16x4_t g2_0_c = vget_low_s16(r0_v2r);
                int32x4_t E2_0 = vaddl_s16(g2_0_a, g2_0_c);
                int16x4_t g3_0_a = vget_high_s16(r0_v1);
                int16x4_t g3_0_c = vget_high_s16(r0_v2r);
                int32x4_t E3_0 = vaddl_s16(g3_0_a, g3_0_c);
                int32x4_t Er_0_3 = rev32(E3_0);
                int32x4_t Er_0_2 = rev32(E2_0);
                int32x4_t EO_0_0 = vsubq_s32(E0_0, Er_0_3);
                int32x4_t EO_0_1 = vsubq_s32(E1_0, Er_0_2);
                int32x4_t EEr_0_3 = rev32(E3_0);
                int32x4_t EEr_0_2 = rev32(E2_0);
                int32x4_t EE_0_0 = vaddq_s32(E0_0, EEr_0_3);
                int32x4_t EE_0_1 = vaddq_s32(E1_0, EEr_0_2);
                int32x4_t EEr2_0 = rev32(EE_0_1);
                int32x4_t EEE_0 = vaddq_s32(EE_0_0, EEr2_0);
                int32x4_t EEO_0 = vsubq_s32(EE_0_0, EEr2_0);
                const int16x8_t r1_v0 = vld1q_s16(src + (i + 1)*line+0);
                const int16x8_t r1_v1 = vld1q_s16(src + (i + 1)*line+8);
                const int16x8_t r1_v2 = vld1q_s16(src + (i + 1)*line+16);
                const int16x8_t r1_v3 = vld1q_s16(src + (i + 1)*line+24);
                int16x8_t r1_v2r = rev16(r1_v2);
                int16x8_t r1_v3r = rev16(r1_v3);
                int16x8_t O_1_0 = vsubq_s16(r1_v0, r1_v3r);
                int16x8_t O_1_1 = vsubq_s16(r1_v1, r1_v2r);
                int16x4_t g0_1_a = vget_low_s16(r1_v0);
                int16x4_t g0_1_c = vget_low_s16(r1_v3r);
                int32x4_t E0_1 = vaddl_s16(g0_1_a, g0_1_c);
                int16x4_t g1_1_a = vget_high_s16(r1_v0);
                int16x4_t g1_1_c = vget_high_s16(r1_v3r);
                int32x4_t E1_1 = vaddl_s16(g1_1_a, g1_1_c);
                int16x4_t g2_1_a = vget_low_s16(r1_v1);
                int16x4_t g2_1_c = vget_low_s16(r1_v2r);
                int32x4_t E2_1 = vaddl_s16(g2_1_a, g2_1_c);
                int16x4_t g3_1_a = vget_high_s16(r1_v1);
                int16x4_t g3_1_c = vget_high_s16(r1_v2r);
                int32x4_t E3_1 = vaddl_s16(g3_1_a, g3_1_c);
                int32x4_t Er_1_3 = rev32(E3_1);
                int32x4_t Er_1_2 = rev32(E2_1);
                int32x4_t EO_1_0 = vsubq_s32(E0_1, Er_1_3);
                int32x4_t EO_1_1 = vsubq_s32(E1_1, Er_1_2);
                int32x4_t EEr_1_3 = rev32(E3_1);
                int32x4_t EEr_1_2 = rev32(E2_1);
                int32x4_t EE_1_0 = vaddq_s32(E0_1, EEr_1_3);
                int32x4_t EE_1_1 = vaddq_s32(E1_1, EEr_1_2);
                int32x4_t EEr2_1 = rev32(EE_1_1);
                int32x4_t EEE_1 = vaddq_s32(EE_1_0, EEr2_1);
                int32x4_t EEO_1 = vsubq_s32(EE_1_0, EEr2_1);
                const int16x8_t r2_v0 = vld1q_s16(src + (i + 2)*line+0);
                const int16x8_t r2_v1 = vld1q_s16(src + (i + 2)*line+8);
                const int16x8_t r2_v2 = vld1q_s16(src + (i + 2)*line+16);
                const int16x8_t r2_v3 = vld1q_s16(src + (i + 2)*line+24);
                int16x8_t r2_v2r = rev16(r2_v2);
                int16x8_t r2_v3r = rev16(r2_v3);
                int16x8_t O_2_0 = vsubq_s16(r2_v0, r2_v3r);
                int16x8_t O_2_1 = vsubq_s16(r2_v1, r2_v2r);
                int16x4_t g0_2_a = vget_low_s16(r2_v0);
                int16x4_t g0_2_c = vget_low_s16(r2_v3r);
                int32x4_t E0_2 = vaddl_s16(g0_2_a, g0_2_c);
                int16x4_t g1_2_a = vget_high_s16(r2_v0);
                int16x4_t g1_2_c = vget_high_s16(r2_v3r);
                int32x4_t E1_2 = vaddl_s16(g1_2_a, g1_2_c);
                int16x4_t g2_2_a = vget_low_s16(r2_v1);
                int16x4_t g2_2_c = vget_low_s16(r2_v2r);
                int32x4_t E2_2 = vaddl_s16(g2_2_a, g2_2_c);
                int16x4_t g3_2_a = vget_high_s16(r2_v1);
                int16x4_t g3_2_c = vget_high_s16(r2_v2r);
                int32x4_t E3_2 = vaddl_s16(g3_2_a, g3_2_c);
                int32x4_t Er_2_3 = rev32(E3_2);
                int32x4_t Er_2_2 = rev32(E2_2);
                int32x4_t EO_2_0 = vsubq_s32(E0_2, Er_2_3);
                int32x4_t EO_2_1 = vsubq_s32(E1_2, Er_2_2);
                int32x4_t EEr_2_3 = rev32(E3_2);
                int32x4_t EEr_2_2 = rev32(E2_2);
                int32x4_t EE_2_0 = vaddq_s32(E0_2, EEr_2_3);
                int32x4_t EE_2_1 = vaddq_s32(E1_2, EEr_2_2);
                int32x4_t EEr2_2 = rev32(EE_2_1);
                int32x4_t EEE_2 = vaddq_s32(EE_2_0, EEr2_2);
                int32x4_t EEO_2 = vsubq_s32(EE_2_0, EEr2_2);
                const int16x8_t r3_v0 = vld1q_s16(src + (i + 3)*line+0);
                const int16x8_t r3_v1 = vld1q_s16(src + (i + 3)*line+8);
                const int16x8_t r3_v2 = vld1q_s16(src + (i + 3)*line+16);
                const int16x8_t r3_v3 = vld1q_s16(src + (i + 3)*line+24);
                int16x8_t r3_v2r = rev16(r3_v2);
                int16x8_t r3_v3r = rev16(r3_v3);
                int16x8_t O_3_0 = vsubq_s16(r3_v0, r3_v3r);
                int16x8_t O_3_1 = vsubq_s16(r3_v1, r3_v2r);
                int16x4_t g0_3_a = vget_low_s16(r3_v0);
                int16x4_t g0_3_c = vget_low_s16(r3_v3r);
                int32x4_t E0_3 = vaddl_s16(g0_3_a, g0_3_c);
                int16x4_t g1_3_a = vget_high_s16(r3_v0);
                int16x4_t g1_3_c = vget_high_s16(r3_v3r);
                int32x4_t E1_3 = vaddl_s16(g1_3_a, g1_3_c);
                int16x4_t g2_3_a = vget_low_s16(r3_v1);
                int16x4_t g2_3_c = vget_low_s16(r3_v2r);
                int32x4_t E2_3 = vaddl_s16(g2_3_a, g2_3_c);
                int16x4_t g3_3_a = vget_high_s16(r3_v1);
                int16x4_t g3_3_c = vget_high_s16(r3_v2r);
                int32x4_t E3_3 = vaddl_s16(g3_3_a, g3_3_c);
                int32x4_t Er_3_3 = rev32(E3_3);
                int32x4_t Er_3_2 = rev32(E2_3);
                int32x4_t EO_3_0 = vsubq_s32(E0_3, Er_3_3);
                int32x4_t EO_3_1 = vsubq_s32(E1_3, Er_3_2);
                int32x4_t EEr_3_3 = rev32(E3_3);
                int32x4_t EEr_3_2 = rev32(E2_3);
                int32x4_t EE_3_0 = vaddq_s32(E0_3, EEr_3_3);
                int32x4_t EE_3_1 = vaddq_s32(E1_3, EEr_3_2);
                int32x4_t EEr2_3 = rev32(EE_3_1);
                int32x4_t EEE_3 = vaddq_s32(EE_3_0, EEr2_3);
                int32x4_t EEO_3 = vsubq_s32(EE_3_0, EEr2_3);
                int32x4_t t0_0 = vreinterpretq_s32_s64(vzip1q_s64(vreinterpretq_s64_s32(EEE_0), vreinterpretq_s64_s32(EEE_1)));
                int32x4_t z2_0 = vreinterpretq_s32_s64(vzip2q_s64(vreinterpretq_s64_s32(EEE_0), vreinterpretq_s64_s32(EEE_1)));
                int32x4_t t1_0 = vrev64q_s32(z2_0);
                int32x4_t EEEE_0 = vaddq_s32(t0_0, t1_0);
                int32x4_t EEEO_0 = vsubq_s32(t0_0, t1_0);
                int32x4_t t0_1 = vreinterpretq_s32_s64(vzip1q_s64(vreinterpretq_s64_s32(EEE_2), vreinterpretq_s64_s32(EEE_3)));
                int32x4_t z2_1 = vreinterpretq_s32_s64(vzip2q_s64(vreinterpretq_s64_s32(EEE_2), vreinterpretq_s64_s32(EEE_3)));
                int32x4_t t1_1 = vrev64q_s32(z2_1);
                int32x4_t EEEE_1 = vaddq_s32(t0_1, t1_1);
                int32x4_t EEEO_1 = vsubq_s32(t0_1, t1_1);
        for (int k = 1; k < 32; k += 2)
        {
                    const int16x8_t c_GT32A_1_ = vld1q_s16(GT32A[k]);
                    int64x2_t t_1_0 = sdotq_s16(vdupq_n_s64(0), c_GT32A_1_, O_0_0);
                    const int16x8_t c_GT32B_1_ = vld1q_s16(GT32B[k]);
                    t_1_0 = sdotq_s16(t_1_0, c_GT32B_1_, O_0_1);
                    int64x2_t t_1_1 = sdotq_s16(vdupq_n_s64(0), c_GT32A_1_, O_1_0);
                    t_1_1 = sdotq_s16(t_1_1, c_GT32B_1_, O_1_1);
                    int64x2_t t_1_2 = sdotq_s16(vdupq_n_s64(0), c_GT32A_1_, O_2_0);
                    t_1_2 = sdotq_s16(t_1_2, c_GT32B_1_, O_2_1);
                    int64x2_t t_1_3 = sdotq_s16(vdupq_n_s64(0), c_GT32A_1_, O_3_0);
                    t_1_3 = sdotq_s16(t_1_3, c_GT32B_1_, O_3_1);
                    const int32x4_t t01_nn_1_0 = vcombine_s32(vmovn_s64(t_1_0), vmovn_s64(t_1_1));
                    const int32x4_t t23_nn_1_0 = vcombine_s32(vmovn_s64(t_1_2), vmovn_s64(t_1_3));
                    const int32x4_t w_nn_1_0 = vpaddq_s32(t01_nn_1_0, t23_nn_1_0);
                    int16x4_t nn_1_0 = vrshrn_n_s32(w_nn_1_0, shift);
                    vst1_s16(dst + 32*k + i, nn_1_0);
        }
        for (int k = 2; k < 32; k += 4)
        {
                    const int32x4_t c_GT32S32A_0_ = vld1q_s32(GT32S32A[(k-2)/4]);
                    int32x4_t m_2_0 = vmulq_s32(c_GT32S32A_0_, EO_0_0);
                    const int32x4_t c_GT32S32B_0_ = vld1q_s32(GT32S32B[(k-2)/4]);
                    m_2_0 = vmlaq_s32(m_2_0, c_GT32S32B_0_, EO_0_1);
                    int32x4_t m_2_1 = vmulq_s32(c_GT32S32A_0_, EO_1_0);
                    m_2_1 = vmlaq_s32(m_2_1, c_GT32S32B_0_, EO_1_1);
                    int32x4_t m_2_2 = vmulq_s32(c_GT32S32A_0_, EO_2_0);
                    m_2_2 = vmlaq_s32(m_2_2, c_GT32S32B_0_, EO_2_1);
                    int32x4_t m_2_3 = vmulq_s32(c_GT32S32A_0_, EO_3_0);
                    m_2_3 = vmlaq_s32(m_2_3, c_GT32S32B_0_, EO_3_1);
                    int32x4_t t01_2_0 = vpaddq_s32(m_2_0, m_2_1);
                    int32x4_t t23_2_0 = vpaddq_s32(m_2_2, m_2_3);
                    int32x4_t t_2_0 = vpaddq_s32(t01_2_0, t23_2_0);
                    int16x4_t nn_2_0 = vrshrn_n_s32(t_2_0, shift);
                    vst1_s16(dst + 32*k + i, nn_2_0);
        }
        for (int k = 4; k < 32; k += 8)
        {
                    const int32x4_t c_GT32S32A4_0_ = vld1q_s32(GT32S32A4[(k-4)/8]);
                    int32x4_t m_4_0 = vmulq_s32(c_GT32S32A4_0_, EEO_0);
                    int32x4_t m_4_1 = vmulq_s32(c_GT32S32A4_0_, EEO_1);
                    int32x4_t m_4_2 = vmulq_s32(c_GT32S32A4_0_, EEO_2);
                    int32x4_t m_4_3 = vmulq_s32(c_GT32S32A4_0_, EEO_3);
                    int32x4_t t01_4_0 = vpaddq_s32(m_4_0, m_4_1);
                    int32x4_t t23_4_0 = vpaddq_s32(m_4_2, m_4_3);
                    int32x4_t t_4_0 = vpaddq_s32(t01_4_0, t23_4_0);
                    int16x4_t nn_4_0 = vrshrn_n_s32(t_4_0, shift);
                    vst1_s16(dst + 32*k + i, nn_4_0);
        }
                int32x4_t pp_0_0 = vpaddq_s32(EEEE_0, EEEE_1);
                const int32x4_t c_T8E_0_ = vld1q_s32(T8E[0]);
                int32x4_t m_0_0 = vmulq_s32(c_T8E_0_, pp_0_0);
                int16x4_t nn_0_0 = vrshrn_n_s32(m_0_0, shift);
                vst1_s16(dst + 32*0 + i, nn_0_0);
                const int32x4_t c_T8E_1_ = vld1q_s32(T8E[1]);
                int32x4_t m0_8_0 = vmulq_s32(c_T8E_1_, EEEO_0);
                int32x4_t m1_8_0 = vmulq_s32(c_T8E_1_, EEEO_1);
                int32x4_t m_8_0 = vpaddq_s32(m0_8_0, m1_8_0);
                int16x4_t nn_8_0 = vrshrn_n_s32(m_8_0, shift);
                vst1_s16(dst + 32*8 + i, nn_8_0);
                const int32x4_t c_T8E_2_ = vld1q_s32(T8E[2]);
                int32x4_t m0_16_0 = vmulq_s32(c_T8E_2_, EEEE_0);
                int32x4_t m1_16_0 = vmulq_s32(c_T8E_2_, EEEE_1);
                int32x4_t m_16_0 = vpaddq_s32(m0_16_0, m1_16_0);
                int16x4_t nn_16_0 = vrshrn_n_s32(m_16_0, shift);
                vst1_s16(dst + 32*16 + i, nn_16_0);
                const int32x4_t c_T8E_3_ = vld1q_s32(T8E[3]);
                int32x4_t m0_24_0 = vmulq_s32(c_T8E_3_, EEEO_0);
                int32x4_t m1_24_0 = vmulq_s32(c_T8E_3_, EEEO_1);
                int32x4_t m_24_0 = vpaddq_s32(m0_24_0, m1_24_0);
                int16x4_t nn_24_0 = vrshrn_n_s32(m_24_0, shift);
                vst1_s16(dst + 32*24 + i, nn_24_0);
    }
}

extern "C" void dynopt_dct32_sve2_shared(const int16_t* src, int16_t* dst, intptr_t srcStride)
{
    int16_t coef[1024];
    op_pass_4(src, coef, srcStride);
    op_pass_11(coef, dst);
}
