// Generated by tools/emit_dct32_vl128.py -- do not edit by hand.
// VL=128 migration baseline: upstream 8-lane E/O + sdot structure
// (upstream-exact at any SVE VL; structural axes applied later).
// pass1=fused pass2=fused

// Depth-8 contract, matching the gen_verify legacy oracle.
#define X265_DEPTH 8
#include <arm_neon.h>
#include <arm_sve.h>
#include <arm_neon_sve_bridge.h>
#include <cstdint>

const int16_t t8_odd[4][8] =
{
    { 89,  75,  50,  18, 89,  75,  50,  18 },
    { 75, -18, -89, -50, 75, -18, -89, -50 },
    { 50, -89,  18,  75, 50, -89,  18,  75 },
    { 18, -50,  75, -89, 18, -50,  75, -89 },
};

const int32_t t8_even[4][4] =
{
    { 64,  64, 64,  64 },
    { 83,  36, 83,  36 },
    { 64, -64, 64, -64 },
    { 36, -83, 36, -83 },
};

const uint8_t rev16_tbl[16] =
{
    14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1
};

const uint8_t rev32_tbl[16] =
{
    12, 13, 14, 15, 8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3
};

const int16_t g_t32[32][32] =
{
    { 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64 },
    { 90, 90, 88, 85, 82, 78, 73, 67, 61, 54, 46, 38, 31, 22, 13,  4, -4, -13, -22, -31, -38, -46, -54, -61, -67, -73, -78, -82, -85, -88, -90, -90 },
    { 90, 87, 80, 70, 57, 43, 25,  9, -9, -25, -43, -57, -70, -80, -87, -90, -90, -87, -80, -70, -57, -43, -25, -9,  9, 25, 43, 57, 70, 80, 87, 90 },
    { 90, 82, 67, 46, 22, -4, -31, -54, -73, -85, -90, -88, -78, -61, -38, -13, 13, 38, 61, 78, 88, 90, 85, 73, 54, 31,  4, -22, -46, -67, -82, -90 },
    { 89, 75, 50, 18, -18, -50, -75, -89, -89, -75, -50, -18, 18, 50, 75, 89, 89, 75, 50, 18, -18, -50, -75, -89, -89, -75, -50, -18, 18, 50, 75, 89 },
    { 88, 67, 31, -13, -54, -82, -90, -78, -46, -4, 38, 73, 90, 85, 61, 22, -22, -61, -85, -90, -73, -38,  4, 46, 78, 90, 82, 54, 13, -31, -67, -88 },
    { 87, 57,  9, -43, -80, -90, -70, -25, 25, 70, 90, 80, 43, -9, -57, -87, -87, -57, -9, 43, 80, 90, 70, 25, -25, -70, -90, -80, -43,  9, 57, 87 },
    { 85, 46, -13, -67, -90, -73, -22, 38, 82, 88, 54, -4, -61, -90, -78, -31, 31, 78, 90, 61,  4, -54, -88, -82, -38, 22, 73, 90, 67, 13, -46, -85 },
    { 83, 36, -36, -83, -83, -36, 36, 83, 83, 36, -36, -83, -83, -36, 36, 83, 83, 36, -36, -83, -83, -36, 36, 83, 83, 36, -36, -83, -83, -36, 36, 83 },
    { 82, 22, -54, -90, -61, 13, 78, 85, 31, -46, -90, -67,  4, 73, 88, 38, -38, -88, -73, -4, 67, 90, 46, -31, -85, -78, -13, 61, 90, 54, -22, -82 },
    { 80,  9, -70, -87, -25, 57, 90, 43, -43, -90, -57, 25, 87, 70, -9, -80, -80, -9, 70, 87, 25, -57, -90, -43, 43, 90, 57, -25, -87, -70,  9, 80 },
    { 78, -4, -82, -73, 13, 85, 67, -22, -88, -61, 31, 90, 54, -38, -90, -46, 46, 90, 38, -54, -90, -31, 61, 88, 22, -67, -85, -13, 73, 82,  4, -78 },
    { 75, -18, -89, -50, 50, 89, 18, -75, -75, 18, 89, 50, -50, -89, -18, 75, 75, -18, -89, -50, 50, 89, 18, -75, -75, 18, 89, 50, -50, -89, -18, 75 },
    { 73, -31, -90, -22, 78, 67, -38, -90, -13, 82, 61, -46, -88, -4, 85, 54, -54, -85,  4, 88, 46, -61, -82, 13, 90, 38, -67, -78, 22, 90, 31, -73 },
    { 70, -43, -87,  9, 90, 25, -80, -57, 57, 80, -25, -90, -9, 87, 43, -70, -70, 43, 87, -9, -90, -25, 80, 57, -57, -80, 25, 90,  9, -87, -43, 70 },
    { 67, -54, -78, 38, 85, -22, -90,  4, 90, 13, -88, -31, 82, 46, -73, -61, 61, 73, -46, -82, 31, 88, -13, -90, -4, 90, 22, -85, -38, 78, 54, -67 },
    { 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64 },
    { 61, -73, -46, 82, 31, -88, -13, 90, -4, -90, 22, 85, -38, -78, 54, 67, -67, -54, 78, 38, -85, -22, 90,  4, -90, 13, 88, -31, -82, 46, 73, -61 },
    { 57, -80, -25, 90, -9, -87, 43, 70, -70, -43, 87,  9, -90, 25, 80, -57, -57, 80, 25, -90,  9, 87, -43, -70, 70, 43, -87, -9, 90, -25, -80, 57 },
    { 54, -85, -4, 88, -46, -61, 82, 13, -90, 38, 67, -78, -22, 90, -31, -73, 73, 31, -90, 22, 78, -67, -38, 90, -13, -82, 61, 46, -88,  4, 85, -54 },
    { 50, -89, 18, 75, -75, -18, 89, -50, -50, 89, -18, -75, 75, 18, -89, 50, 50, -89, 18, 75, -75, -18, 89, -50, -50, 89, -18, -75, 75, 18, -89, 50 },
    { 46, -90, 38, 54, -90, 31, 61, -88, 22, 67, -85, 13, 73, -82,  4, 78, -78, -4, 82, -73, -13, 85, -67, -22, 88, -61, -31, 90, -54, -38, 90, -46 },
    { 43, -90, 57, 25, -87, 70,  9, -80, 80, -9, -70, 87, -25, -57, 90, -43, -43, 90, -57, -25, 87, -70, -9, 80, -80,  9, 70, -87, 25, 57, -90, 43 },
    { 38, -88, 73, -4, -67, 90, -46, -31, 85, -78, 13, 61, -90, 54, 22, -82, 82, -22, -54, 90, -61, -13, 78, -85, 31, 46, -90, 67,  4, -73, 88, -38 },
    { 36, -83, 83, -36, -36, 83, -83, 36, 36, -83, 83, -36, -36, 83, -83, 36, 36, -83, 83, -36, -36, 83, -83, 36, 36, -83, 83, -36, -36, 83, -83, 36 },
    { 31, -78, 90, -61,  4, 54, -88, 82, -38, -22, 73, -90, 67, -13, -46, 85, -85, 46, 13, -67, 90, -73, 22, 38, -82, 88, -54, -4, 61, -90, 78, -31 },
    { 25, -70, 90, -80, 43,  9, -57, 87, -87, 57, -9, -43, 80, -90, 70, -25, -25, 70, -90, 80, -43, -9, 57, -87, 87, -57,  9, 43, -80, 90, -70, 25 },
    { 22, -61, 85, -90, 73, -38, -4, 46, -78, 90, -82, 54, -13, -31, 67, -88, 88, -67, 31, 13, -54, 82, -90, 78, -46,  4, 38, -73, 90, -85, 61, -22 },
    { 18, -50, 75, -89, 89, -75, 50, -18, -18, 50, -75, 89, -89, 75, -50, 18, 18, -50, 75, -89, 89, -75, 50, -18, -18, 50, -75, 89, -89, 75, -50, 18 },
    { 13, -38, 61, -78, 88, -90, 85, -73, 54, -31,  4, 22, -46, 67, -82, 90, -90, 82, -67, 46, -22, -4, 31, -54, 73, -85, 90, -88, 78, -61, 38, -13 },
    {  9, -25, 43, -57, 70, -80, 87, -90, 90, -87, 80, -70, 57, -43, 25, -9, -9, 25, -43, 57, -70, 80, -87, 90, -90, 87, -80, 70, -57, 43, -25,  9 },
    {  4, -13, 22, -31, 38, -46, 54, -61, 67, -73, 78, -82, 85, -88, 90, -90, 90, -90, 88, -85, 82, -78, 73, -67, 61, -54, 46, -38, 31, -22, 13, -4 }
};

static inline int16x8_t rev16(const int16x8_t a)
{
    const uint8x16_t tbl = vld1q_u8(rev16_tbl);
    const int8x16_t a_s8 = vreinterpretq_s8_s16(a);

    return vreinterpretq_s16_s8(vqtbx1q_s8(a_s8, a_s8, tbl));
}

static inline int32x4_t rev32(const int32x4_t a)
{
    const uint8x16_t tbl = vld1q_u8(rev32_tbl);
    const int8x16_t a_s8 = vreinterpretq_s8_s32(a);

    return vreinterpretq_s32_s8(vqtbx1q_s8(a_s8, a_s8, tbl));
}

static inline int64x2_t sdotq_s16(int64x2_t acc, int16x8_t x, int16x8_t y)
{
    return svget_neonq_s64(svdot_s64(svset_neonq_s64(svundef_s64(), acc),
                                     svset_neonq_s16(svundef_s16(), x),
                                     svset_neonq_s16(svundef_s16(), y)));
}

static inline int32x4_t vld1sh_s32(const int16_t* p)
{
    return svget_neonq_s32(svld1sh_s32(svptrue_pat_b32(SV_VL4), p));
}

static inline void pass1Butterfly32_sve(const int16_t *src, int16_t *dst,
                                        intptr_t srcStride)
{
    const int shift = 4 + X265_DEPTH - 8;
    const int line = 32;

    for (int i = 0; i < line; i += 4)
    {
        int16x8x4_t in_lo_0 = vld1q_s16_x4(src + (i + 0) * srcStride);
        in_lo_0.val[2] = rev16(in_lo_0.val[2]);
        in_lo_0.val[3] = rev16(in_lo_0.val[3]);
        int16x8x4_t in_lo_1 = vld1q_s16_x4(src + (i + 1) * srcStride);
        in_lo_1.val[2] = rev16(in_lo_1.val[2]);
        in_lo_1.val[3] = rev16(in_lo_1.val[3]);
        int16x8x4_t in_lo_2 = vld1q_s16_x4(src + (i + 2) * srcStride);
        in_lo_2.val[2] = rev16(in_lo_2.val[2]);
        in_lo_2.val[3] = rev16(in_lo_2.val[3]);
        int16x8x4_t in_lo_3 = vld1q_s16_x4(src + (i + 3) * srcStride);
        in_lo_3.val[2] = rev16(in_lo_3.val[2]);
        in_lo_3.val[3] = rev16(in_lo_3.val[3]);

        int16x8_t O0_0 = vsubq_s16(in_lo_0.val[0], in_lo_0.val[3]);
        int16x8_t O0_1 = vsubq_s16(in_lo_0.val[1], in_lo_0.val[2]);
        int16x8_t O1_0 = vsubq_s16(in_lo_1.val[0], in_lo_1.val[3]);
        int16x8_t O1_1 = vsubq_s16(in_lo_1.val[1], in_lo_1.val[2]);
        int16x8_t O2_0 = vsubq_s16(in_lo_2.val[0], in_lo_2.val[3]);
        int16x8_t O2_1 = vsubq_s16(in_lo_2.val[1], in_lo_2.val[2]);
        int16x8_t O3_0 = vsubq_s16(in_lo_3.val[0], in_lo_3.val[3]);
        int16x8_t O3_1 = vsubq_s16(in_lo_3.val[1], in_lo_3.val[2]);

        int32x4_t E0_0 = vaddl_s16(vget_low_s16(in_lo_0.val[0]),
                                       vget_low_s16(in_lo_0.val[3]));
        int32x4_t E0_1 = vaddl_s16(vget_high_s16(in_lo_0.val[0]),
                                       vget_high_s16(in_lo_0.val[3]));
        int32x4_t E0_2 = vaddl_s16(vget_low_s16(in_lo_0.val[1]),
                                       vget_low_s16(in_lo_0.val[2]));
        int32x4_t E0_3 = vaddl_s16(vget_high_s16(in_lo_0.val[1]),
                                       vget_high_s16(in_lo_0.val[2]));
        int16x8_t EO0 = vcombine_s16(
            vmovn_s32(vsubq_s32(E0_0, rev32(E0_3))),
            vmovn_s32(vsubq_s32(E0_1, rev32(E0_2))));
        int32x4_t EE0_0 = vaddq_s32(E0_0, rev32(E0_3));
        int32x4_t EE0_1 = vaddq_s32(E0_1, rev32(E0_2));
        int32x4_t EEO0 = vsubq_s32(EE0_0, rev32(EE0_1));
        int32x4_t EEE0 = vaddq_s32(EE0_0, rev32(EE0_1));
        int32x4_t E1_0 = vaddl_s16(vget_low_s16(in_lo_1.val[0]),
                                       vget_low_s16(in_lo_1.val[3]));
        int32x4_t E1_1 = vaddl_s16(vget_high_s16(in_lo_1.val[0]),
                                       vget_high_s16(in_lo_1.val[3]));
        int32x4_t E1_2 = vaddl_s16(vget_low_s16(in_lo_1.val[1]),
                                       vget_low_s16(in_lo_1.val[2]));
        int32x4_t E1_3 = vaddl_s16(vget_high_s16(in_lo_1.val[1]),
                                       vget_high_s16(in_lo_1.val[2]));
        int16x8_t EO1 = vcombine_s16(
            vmovn_s32(vsubq_s32(E1_0, rev32(E1_3))),
            vmovn_s32(vsubq_s32(E1_1, rev32(E1_2))));
        int32x4_t EE1_0 = vaddq_s32(E1_0, rev32(E1_3));
        int32x4_t EE1_1 = vaddq_s32(E1_1, rev32(E1_2));
        int32x4_t EEO1 = vsubq_s32(EE1_0, rev32(EE1_1));
        int32x4_t EEE1 = vaddq_s32(EE1_0, rev32(EE1_1));
        int32x4_t E2_0 = vaddl_s16(vget_low_s16(in_lo_2.val[0]),
                                       vget_low_s16(in_lo_2.val[3]));
        int32x4_t E2_1 = vaddl_s16(vget_high_s16(in_lo_2.val[0]),
                                       vget_high_s16(in_lo_2.val[3]));
        int32x4_t E2_2 = vaddl_s16(vget_low_s16(in_lo_2.val[1]),
                                       vget_low_s16(in_lo_2.val[2]));
        int32x4_t E2_3 = vaddl_s16(vget_high_s16(in_lo_2.val[1]),
                                       vget_high_s16(in_lo_2.val[2]));
        int16x8_t EO2 = vcombine_s16(
            vmovn_s32(vsubq_s32(E2_0, rev32(E2_3))),
            vmovn_s32(vsubq_s32(E2_1, rev32(E2_2))));
        int32x4_t EE2_0 = vaddq_s32(E2_0, rev32(E2_3));
        int32x4_t EE2_1 = vaddq_s32(E2_1, rev32(E2_2));
        int32x4_t EEO2 = vsubq_s32(EE2_0, rev32(EE2_1));
        int32x4_t EEE2 = vaddq_s32(EE2_0, rev32(EE2_1));
        int32x4_t E3_0 = vaddl_s16(vget_low_s16(in_lo_3.val[0]),
                                       vget_low_s16(in_lo_3.val[3]));
        int32x4_t E3_1 = vaddl_s16(vget_high_s16(in_lo_3.val[0]),
                                       vget_high_s16(in_lo_3.val[3]));
        int32x4_t E3_2 = vaddl_s16(vget_low_s16(in_lo_3.val[1]),
                                       vget_low_s16(in_lo_3.val[2]));
        int32x4_t E3_3 = vaddl_s16(vget_high_s16(in_lo_3.val[1]),
                                       vget_high_s16(in_lo_3.val[2]));
        int16x8_t EO3 = vcombine_s16(
            vmovn_s32(vsubq_s32(E3_0, rev32(E3_3))),
            vmovn_s32(vsubq_s32(E3_1, rev32(E3_2))));
        int32x4_t EE3_0 = vaddq_s32(E3_0, rev32(E3_3));
        int32x4_t EE3_1 = vaddq_s32(E3_1, rev32(E3_2));
        int32x4_t EEO3 = vsubq_s32(EE3_0, rev32(EE3_1));
        int32x4_t EEE3 = vaddq_s32(EE3_0, rev32(EE3_1));

        int32x4_t t0_0 = vreinterpretq_s32_s64(
            vzip1q_s64(vreinterpretq_s64_s32(EEE0),
                       vreinterpretq_s64_s32(EEE1)));
        int32x4_t t0_1 = vrev64q_s32(vreinterpretq_s32_s64(
            vzip2q_s64(vreinterpretq_s64_s32(EEE0),
                       vreinterpretq_s64_s32(EEE1))));
        int32x4_t EEEE0 = vaddq_s32(t0_0, t0_1);
        int32x4_t EEEO0 = vsubq_s32(t0_0, t0_1);
        int32x4_t t1_0 = vreinterpretq_s32_s64(
            vzip1q_s64(vreinterpretq_s64_s32(EEE2),
                       vreinterpretq_s64_s32(EEE3)));
        int32x4_t t1_1 = vrev64q_s32(vreinterpretq_s32_s64(
            vzip2q_s64(vreinterpretq_s64_s32(EEE2),
                       vreinterpretq_s64_s32(EEE3))));
        int32x4_t EEEE1 = vaddq_s32(t1_0, t1_1);
        int32x4_t EEEO1 = vsubq_s32(t1_0, t1_1);

        for (int k = 1; k < 32; k += 2)
        {
            int16x8_t c0_c1 = vld1q_s16(&g_t32[k][0]);
            int16x8_t c2_c3 = vld1q_s16(&g_t32[k][8]);

            int64x2_t t0 = sdotq_s16(vdupq_n_s64(0), c0_c1, O0_0);
            t0 = sdotq_s16(t0, c2_c3, O0_1);
            int64x2_t t1 = sdotq_s16(vdupq_n_s64(0), c0_c1, O1_0);
            t1 = sdotq_s16(t1, c2_c3, O1_1);
            int64x2_t t2 = sdotq_s16(vdupq_n_s64(0), c0_c1, O2_0);
            t2 = sdotq_s16(t2, c2_c3, O2_1);
            int64x2_t t3 = sdotq_s16(vdupq_n_s64(0), c0_c1, O3_0);
            t3 = sdotq_s16(t3, c2_c3, O3_1);

            int32x4_t t01 = vcombine_s32(vmovn_s64(t0), vmovn_s64(t1));
            int32x4_t t23 = vcombine_s32(vmovn_s64(t2), vmovn_s64(t3));
            int16x4_t res = vrshrn_n_s32(vpaddq_s32(t01, t23), shift);
            vst1_s16(dst + k * line + i, res);
        }

        for (int k = 2; k < 32; k += 4)
        {
            int16x8_t c0 = vld1q_s16(&g_t32[k][0]);

            int64x2_t t0 = sdotq_s16(vdupq_n_s64(0), c0, EO0);
            int64x2_t t1 = sdotq_s16(vdupq_n_s64(0), c0, EO1);
            int64x2_t t2 = sdotq_s16(vdupq_n_s64(0), c0, EO2);
            int64x2_t t3 = sdotq_s16(vdupq_n_s64(0), c0, EO3);

            int32x4_t t01 = vcombine_s32(vmovn_s64(t0), vmovn_s64(t1));
            int32x4_t t23 = vcombine_s32(vmovn_s64(t2), vmovn_s64(t3));
            int16x4_t res = vrshrn_n_s32(vpaddq_s32(t01, t23), shift);
            vst1_s16(dst + k * line + i, res);

        }

        for (int k = 4; k < 32; k += 8)
        {
            int32x4_t c = vld1sh_s32(&g_t32[k][0]);

            int32x4_t t0 = vmulq_s32(c, EEO0);
            int32x4_t t1 = vmulq_s32(c, EEO1);
            int32x4_t t2 = vmulq_s32(c, EEO2);
            int32x4_t t3 = vmulq_s32(c, EEO3);

            int32x4_t t = vpaddq_s32(vpaddq_s32(t0, t1),
                                     vpaddq_s32(t2, t3));
            int16x4_t res = vrshrn_n_s32(t, shift);
            vst1_s16(dst + k * line + i, res);
        }

        int32x4_t c0 = vld1q_s32(t8_even[0]);
        int32x4_t c8 = vld1q_s32(t8_even[1]);
        int32x4_t c16 = vld1q_s32(t8_even[2]);
        int32x4_t c24 = vld1q_s32(t8_even[3]);

        int32x4_t t0 = vpaddq_s32(EEEE0, EEEE1);
        int32x4_t t1 = vmulq_s32(c0, t0);
        int16x4_t res0 = vrshrn_n_s32(t1, shift);
        vst1_s16(dst + 0 * line + i, res0);

        int32x4_t t2 = vmulq_s32(c8, EEEO0);
        int32x4_t t3 = vmulq_s32(c8, EEEO1);
        int16x4_t res8 = vrshrn_n_s32(vpaddq_s32(t2, t3), shift);
        vst1_s16(dst + 8 * line + i, res8);

        int32x4_t t4 = vmulq_s32(c16, EEEE0);
        int32x4_t t5 = vmulq_s32(c16, EEEE1);
        int16x4_t res16 = vrshrn_n_s32(vpaddq_s32(t4, t5), shift);
        vst1_s16(dst + 16 * line + i, res16);

        int32x4_t t6 = vmulq_s32(c24, EEEO0);
        int32x4_t t7 = vmulq_s32(c24, EEEO1);
        int16x4_t res24 = vrshrn_n_s32(vpaddq_s32(t6, t7), shift);
        vst1_s16(dst + 24 * line + i, res24);
    }

}


static inline void pass2Butterfly32_sve(const int16_t *src, int16_t *dst)
{
    const int shift = 11;
    const int line = 32;

    for (int i = 0; i < line; i += 4)
    {
        int16x8x4_t in_lo_0 = vld1q_s16_x4(src + (i + 0) * line);
        in_lo_0.val[2] = rev16(in_lo_0.val[2]);
        in_lo_0.val[3] = rev16(in_lo_0.val[3]);
        int16x8x4_t in_lo_1 = vld1q_s16_x4(src + (i + 1) * line);
        in_lo_1.val[2] = rev16(in_lo_1.val[2]);
        in_lo_1.val[3] = rev16(in_lo_1.val[3]);
        int16x8x4_t in_lo_2 = vld1q_s16_x4(src + (i + 2) * line);
        in_lo_2.val[2] = rev16(in_lo_2.val[2]);
        in_lo_2.val[3] = rev16(in_lo_2.val[3]);
        int16x8x4_t in_lo_3 = vld1q_s16_x4(src + (i + 3) * line);
        in_lo_3.val[2] = rev16(in_lo_3.val[2]);
        in_lo_3.val[3] = rev16(in_lo_3.val[3]);

        int16x8_t O0_0 = vsubq_s16(in_lo_0.val[0], in_lo_0.val[3]);
        int16x8_t O0_1 = vsubq_s16(in_lo_0.val[1], in_lo_0.val[2]);
        int16x8_t O1_0 = vsubq_s16(in_lo_1.val[0], in_lo_1.val[3]);
        int16x8_t O1_1 = vsubq_s16(in_lo_1.val[1], in_lo_1.val[2]);
        int16x8_t O2_0 = vsubq_s16(in_lo_2.val[0], in_lo_2.val[3]);
        int16x8_t O2_1 = vsubq_s16(in_lo_2.val[1], in_lo_2.val[2]);
        int16x8_t O3_0 = vsubq_s16(in_lo_3.val[0], in_lo_3.val[3]);
        int16x8_t O3_1 = vsubq_s16(in_lo_3.val[1], in_lo_3.val[2]);

        int32x4_t E0_0 = vaddl_s16(vget_low_s16(in_lo_0.val[0]),
                                       vget_low_s16(in_lo_0.val[3]));
        int32x4_t E0_1 = vaddl_s16(vget_high_s16(in_lo_0.val[0]),
                                       vget_high_s16(in_lo_0.val[3]));
        int32x4_t E0_2 = vaddl_s16(vget_low_s16(in_lo_0.val[1]),
                                       vget_low_s16(in_lo_0.val[2]));
        int32x4_t E0_3 = vaddl_s16(vget_high_s16(in_lo_0.val[1]),
                                       vget_high_s16(in_lo_0.val[2]));
        int32x4_t EO0_0 = vsubq_s32(E0_0, rev32(E0_3));
        int32x4_t EO0_1 = vsubq_s32(E0_1, rev32(E0_2));
        int32x4_t EE0_0 = vaddq_s32(E0_0, rev32(E0_3));
        int32x4_t EE0_1 = vaddq_s32(E0_1, rev32(E0_2));
        int32x4_t EEO0 = vsubq_s32(EE0_0, rev32(EE0_1));
        int32x4_t EEE0 = vaddq_s32(EE0_0, rev32(EE0_1));
        int32x4_t E1_0 = vaddl_s16(vget_low_s16(in_lo_1.val[0]),
                                       vget_low_s16(in_lo_1.val[3]));
        int32x4_t E1_1 = vaddl_s16(vget_high_s16(in_lo_1.val[0]),
                                       vget_high_s16(in_lo_1.val[3]));
        int32x4_t E1_2 = vaddl_s16(vget_low_s16(in_lo_1.val[1]),
                                       vget_low_s16(in_lo_1.val[2]));
        int32x4_t E1_3 = vaddl_s16(vget_high_s16(in_lo_1.val[1]),
                                       vget_high_s16(in_lo_1.val[2]));
        int32x4_t EO1_0 = vsubq_s32(E1_0, rev32(E1_3));
        int32x4_t EO1_1 = vsubq_s32(E1_1, rev32(E1_2));
        int32x4_t EE1_0 = vaddq_s32(E1_0, rev32(E1_3));
        int32x4_t EE1_1 = vaddq_s32(E1_1, rev32(E1_2));
        int32x4_t EEO1 = vsubq_s32(EE1_0, rev32(EE1_1));
        int32x4_t EEE1 = vaddq_s32(EE1_0, rev32(EE1_1));
        int32x4_t E2_0 = vaddl_s16(vget_low_s16(in_lo_2.val[0]),
                                       vget_low_s16(in_lo_2.val[3]));
        int32x4_t E2_1 = vaddl_s16(vget_high_s16(in_lo_2.val[0]),
                                       vget_high_s16(in_lo_2.val[3]));
        int32x4_t E2_2 = vaddl_s16(vget_low_s16(in_lo_2.val[1]),
                                       vget_low_s16(in_lo_2.val[2]));
        int32x4_t E2_3 = vaddl_s16(vget_high_s16(in_lo_2.val[1]),
                                       vget_high_s16(in_lo_2.val[2]));
        int32x4_t EO2_0 = vsubq_s32(E2_0, rev32(E2_3));
        int32x4_t EO2_1 = vsubq_s32(E2_1, rev32(E2_2));
        int32x4_t EE2_0 = vaddq_s32(E2_0, rev32(E2_3));
        int32x4_t EE2_1 = vaddq_s32(E2_1, rev32(E2_2));
        int32x4_t EEO2 = vsubq_s32(EE2_0, rev32(EE2_1));
        int32x4_t EEE2 = vaddq_s32(EE2_0, rev32(EE2_1));
        int32x4_t E3_0 = vaddl_s16(vget_low_s16(in_lo_3.val[0]),
                                       vget_low_s16(in_lo_3.val[3]));
        int32x4_t E3_1 = vaddl_s16(vget_high_s16(in_lo_3.val[0]),
                                       vget_high_s16(in_lo_3.val[3]));
        int32x4_t E3_2 = vaddl_s16(vget_low_s16(in_lo_3.val[1]),
                                       vget_low_s16(in_lo_3.val[2]));
        int32x4_t E3_3 = vaddl_s16(vget_high_s16(in_lo_3.val[1]),
                                       vget_high_s16(in_lo_3.val[2]));
        int32x4_t EO3_0 = vsubq_s32(E3_0, rev32(E3_3));
        int32x4_t EO3_1 = vsubq_s32(E3_1, rev32(E3_2));
        int32x4_t EE3_0 = vaddq_s32(E3_0, rev32(E3_3));
        int32x4_t EE3_1 = vaddq_s32(E3_1, rev32(E3_2));
        int32x4_t EEO3 = vsubq_s32(EE3_0, rev32(EE3_1));
        int32x4_t EEE3 = vaddq_s32(EE3_0, rev32(EE3_1));

        int32x4_t t0_0 = vreinterpretq_s32_s64(
            vzip1q_s64(vreinterpretq_s64_s32(EEE0),
                       vreinterpretq_s64_s32(EEE1)));
        int32x4_t t0_1 = vrev64q_s32(vreinterpretq_s32_s64(
            vzip2q_s64(vreinterpretq_s64_s32(EEE0),
                       vreinterpretq_s64_s32(EEE1))));
        int32x4_t EEEE0 = vaddq_s32(t0_0, t0_1);
        int32x4_t EEEO0 = vsubq_s32(t0_0, t0_1);
        int32x4_t t1_0 = vreinterpretq_s32_s64(
            vzip1q_s64(vreinterpretq_s64_s32(EEE2),
                       vreinterpretq_s64_s32(EEE3)));
        int32x4_t t1_1 = vrev64q_s32(vreinterpretq_s32_s64(
            vzip2q_s64(vreinterpretq_s64_s32(EEE2),
                       vreinterpretq_s64_s32(EEE3))));
        int32x4_t EEEE1 = vaddq_s32(t1_0, t1_1);
        int32x4_t EEEO1 = vsubq_s32(t1_0, t1_1);

        for (int k = 1; k < 32; k += 2)
        {
            int16x8_t c0_c1 = vld1q_s16(&g_t32[k][0]);
            int16x8_t c2_c3 = vld1q_s16(&g_t32[k][8]);

            int64x2_t t0 = sdotq_s16(vdupq_n_s64(0), c0_c1, O0_0);
            t0 = sdotq_s16(t0, c2_c3, O0_1);
            int64x2_t t1 = sdotq_s16(vdupq_n_s64(0), c0_c1, O1_0);
            t1 = sdotq_s16(t1, c2_c3, O1_1);
            int64x2_t t2 = sdotq_s16(vdupq_n_s64(0), c0_c1, O2_0);
            t2 = sdotq_s16(t2, c2_c3, O2_1);
            int64x2_t t3 = sdotq_s16(vdupq_n_s64(0), c0_c1, O3_0);
            t3 = sdotq_s16(t3, c2_c3, O3_1);

            int32x4_t t01 = vcombine_s32(vmovn_s64(t0), vmovn_s64(t1));
            int32x4_t t23 = vcombine_s32(vmovn_s64(t2), vmovn_s64(t3));
            int16x4_t res = vrshrn_n_s32(vpaddq_s32(t01, t23), shift);
            vst1_s16(dst + k * line + i, res);
        }

        for (int k = 2; k < 32; k += 4)
        {
            int32x4_t c0 = vld1sh_s32(&g_t32[k][0]);
            int32x4_t c1 = vld1sh_s32(&g_t32[k][4]);

            int32x4_t t0 = vmulq_s32(c0, EO0_0);
            t0 = vmlaq_s32(t0, c1, EO0_1);
            int32x4_t t1 = vmulq_s32(c0, EO1_0);
            t1 = vmlaq_s32(t1, c1, EO1_1);
            int32x4_t t2 = vmulq_s32(c0, EO2_0);
            t2 = vmlaq_s32(t2, c1, EO2_1);
            int32x4_t t3 = vmulq_s32(c0, EO3_0);
            t3 = vmlaq_s32(t3, c1, EO3_1);

            int32x4_t t0123 = vpaddq_s32(vpaddq_s32(t0, t1),
                                         vpaddq_s32(t2, t3));
            int16x4_t res = vrshrn_n_s32(t0123, shift);
            vst1_s16(dst + k * line + i, res);

        }

        for (int k = 4; k < 32; k += 8)
        {
            int32x4_t c = vld1sh_s32(&g_t32[k][0]);

            int32x4_t t0 = vmulq_s32(c, EEO0);
            int32x4_t t1 = vmulq_s32(c, EEO1);
            int32x4_t t2 = vmulq_s32(c, EEO2);
            int32x4_t t3 = vmulq_s32(c, EEO3);

            int32x4_t t = vpaddq_s32(vpaddq_s32(t0, t1),
                                     vpaddq_s32(t2, t3));
            int16x4_t res = vrshrn_n_s32(t, shift);
            vst1_s16(dst + k * line + i, res);
        }

        int32x4_t c0 = vld1q_s32(t8_even[0]);
        int32x4_t c8 = vld1q_s32(t8_even[1]);
        int32x4_t c16 = vld1q_s32(t8_even[2]);
        int32x4_t c24 = vld1q_s32(t8_even[3]);

        int32x4_t t0 = vpaddq_s32(EEEE0, EEEE1);
        int32x4_t t1 = vmulq_s32(c0, t0);
        int16x4_t res0 = vrshrn_n_s32(t1, shift);
        vst1_s16(dst + 0 * line + i, res0);

        int32x4_t t2 = vmulq_s32(c8, EEEO0);
        int32x4_t t3 = vmulq_s32(c8, EEEO1);
        int16x4_t res8 = vrshrn_n_s32(vpaddq_s32(t2, t3), shift);
        vst1_s16(dst + 8 * line + i, res8);

        int32x4_t t4 = vmulq_s32(c16, EEEE0);
        int32x4_t t5 = vmulq_s32(c16, EEEE1);
        int16x4_t res16 = vrshrn_n_s32(vpaddq_s32(t4, t5), shift);
        vst1_s16(dst + 16 * line + i, res16);

        int32x4_t t6 = vmulq_s32(c24, EEEO0);
        int32x4_t t7 = vmulq_s32(c24, EEEO1);
        int16x4_t res24 = vrshrn_n_s32(vpaddq_s32(t6, t7), shift);
        vst1_s16(dst + 24 * line + i, res24);
    }

}


extern "C" void dynopt_dct32_sve2_shared(const int16_t* src, int16_t* dst,
                                         intptr_t srcStride)
{
    int16_t coef[32 * 32];
    pass1Butterfly32_sve(src, coef, srcStride);
    pass2Butterfly32_sve(coef, dst);
}
