// Generated by tools/emit_interp4_sve2_shared.py -- do not edit.
// Chroma 4-tap vertical 8x64 (SVE2, VL=256).
#include <arm_sve.h>

static const int8_t CHROMA_C[8][4] = {
    { 0, 64, 0, 0 },
    { -2, 58, 10, -2 },
    { -4, 54, 16, -2 },
    { -6, 46, 28, -4 },
    { -4, 36, 36, -4 },
    { -4, 28, 46, -6 },
    { -2, 16, 54, -4 },
    { -2, 10, 58, -2 },
};

static inline svint16_t vrow(const uint8_t* p, intptr_t st, int k, int u,
                             svbool_t p16)
{
    svuint16_t w = svld1ub_u16(p16, p + k * st + u * 16);
    return svreinterpret_s16_u16(svsub_n_u16_x(p16, w, 128));
}

extern "C" void dynopt_interp4_8x64_sve2_vpp(const uint8_t* src, intptr_t srcStride,
                   uint8_t* dst, intptr_t dstStride, int coeffIdx)
{
    const svbool_t p16 = svptrue_b16();
    const svbool_t p16b = svwhilelt_b8((uint32_t)0, (uint32_t)16);
    const svbool_t p8b = svwhilelt_b8((uint32_t)0, (uint32_t)8);
    const int ph = coeffIdx & 7;
    const int8_t* cf = (const int8_t*)CHROMA_C[ph];
    const svint16_t c0 = svdup_n_s16(cf[0]);
    const svint16_t c1 = svdup_n_s16(cf[1]);
    const svint16_t c2 = svdup_n_s16(cf[2]);
    const svint16_t c3 = svdup_n_s16(cf[3]);
    const svint16_t zero = svdup_n_s16(0);
    const uint8_t* rb = src - srcStride;

    svint16_t v0_0 = vrow(rb, srcStride, 0, 0, p16);
    svint16_t v1_0 = vrow(rb, srcStride, 1, 0, p16);
    svint16_t v2_0 = vrow(rb, srcStride, 2, 0, p16);
    svint16_t v3_0 = vrow(rb, srcStride, 3, 0, p16);
    svint16_t v4_0 = vrow(rb, srcStride, 4, 0, p16);
    svint16_t v5_0 = vrow(rb, srcStride, 5, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v0_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v1_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v2_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v3_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 0 * dstStride + 0, uz);
    }
    svint16_t v6_0 = vrow(rb, srcStride, 6, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v1_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v2_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v3_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v4_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 1 * dstStride + 0, uz);
    }
    svint16_t v7_0 = vrow(rb, srcStride, 7, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v2_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v3_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v4_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v5_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 2 * dstStride + 0, uz);
    }
    svint16_t v8_0 = vrow(rb, srcStride, 8, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v3_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v4_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v5_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v6_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 3 * dstStride + 0, uz);
    }
    svint16_t v9_0 = vrow(rb, srcStride, 9, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v4_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v5_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v6_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v7_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 4 * dstStride + 0, uz);
    }
    svint16_t v10_0 = vrow(rb, srcStride, 10, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v5_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v6_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v7_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v8_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 5 * dstStride + 0, uz);
    }
    svint16_t v11_0 = vrow(rb, srcStride, 11, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v6_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v7_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v8_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v9_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 6 * dstStride + 0, uz);
    }
    svint16_t v12_0 = vrow(rb, srcStride, 12, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v7_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v8_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v9_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v10_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 7 * dstStride + 0, uz);
    }
    svint16_t v13_0 = vrow(rb, srcStride, 13, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v8_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v9_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v10_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v11_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 8 * dstStride + 0, uz);
    }
    svint16_t v14_0 = vrow(rb, srcStride, 14, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v9_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v10_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v11_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v12_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 9 * dstStride + 0, uz);
    }
    svint16_t v15_0 = vrow(rb, srcStride, 15, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v10_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v11_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v12_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v13_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 10 * dstStride + 0, uz);
    }
    svint16_t v16_0 = vrow(rb, srcStride, 16, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v11_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v12_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v13_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v14_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 11 * dstStride + 0, uz);
    }
    svint16_t v17_0 = vrow(rb, srcStride, 17, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v12_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v13_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v14_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v15_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 12 * dstStride + 0, uz);
    }
    svint16_t v18_0 = vrow(rb, srcStride, 18, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v13_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v14_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v15_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v16_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 13 * dstStride + 0, uz);
    }
    svint16_t v19_0 = vrow(rb, srcStride, 19, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v14_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v15_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v16_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v17_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 14 * dstStride + 0, uz);
    }
    svint16_t v20_0 = vrow(rb, srcStride, 20, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v15_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v16_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v17_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v18_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 15 * dstStride + 0, uz);
    }
    svint16_t v21_0 = vrow(rb, srcStride, 21, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v16_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v17_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v18_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v19_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 16 * dstStride + 0, uz);
    }
    svint16_t v22_0 = vrow(rb, srcStride, 22, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v17_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v18_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v19_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v20_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 17 * dstStride + 0, uz);
    }
    svint16_t v23_0 = vrow(rb, srcStride, 23, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v18_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v19_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v20_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v21_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 18 * dstStride + 0, uz);
    }
    svint16_t v24_0 = vrow(rb, srcStride, 24, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v19_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v20_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v21_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v22_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 19 * dstStride + 0, uz);
    }
    svint16_t v25_0 = vrow(rb, srcStride, 25, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v20_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v21_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v22_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v23_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 20 * dstStride + 0, uz);
    }
    svint16_t v26_0 = vrow(rb, srcStride, 26, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v21_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v22_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v23_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v24_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 21 * dstStride + 0, uz);
    }
    svint16_t v27_0 = vrow(rb, srcStride, 27, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v22_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v23_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v24_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v25_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 22 * dstStride + 0, uz);
    }
    svint16_t v28_0 = vrow(rb, srcStride, 28, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v23_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v24_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v25_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v26_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 23 * dstStride + 0, uz);
    }
    svint16_t v29_0 = vrow(rb, srcStride, 29, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v24_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v25_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v26_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v27_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 24 * dstStride + 0, uz);
    }
    svint16_t v30_0 = vrow(rb, srcStride, 30, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v25_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v26_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v27_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v28_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 25 * dstStride + 0, uz);
    }
    svint16_t v31_0 = vrow(rb, srcStride, 31, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v26_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v27_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v28_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v29_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 26 * dstStride + 0, uz);
    }
    svint16_t v32_0 = vrow(rb, srcStride, 32, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v27_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v28_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v29_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v30_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 27 * dstStride + 0, uz);
    }
    svint16_t v33_0 = vrow(rb, srcStride, 33, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v28_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v29_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v30_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v31_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 28 * dstStride + 0, uz);
    }
    svint16_t v34_0 = vrow(rb, srcStride, 34, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v29_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v30_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v31_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v32_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 29 * dstStride + 0, uz);
    }
    svint16_t v35_0 = vrow(rb, srcStride, 35, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v30_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v31_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v32_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v33_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 30 * dstStride + 0, uz);
    }
    svint16_t v36_0 = vrow(rb, srcStride, 36, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v31_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v32_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v33_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v34_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 31 * dstStride + 0, uz);
    }
    svint16_t v37_0 = vrow(rb, srcStride, 37, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v32_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v33_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v34_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v35_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 32 * dstStride + 0, uz);
    }
    svint16_t v38_0 = vrow(rb, srcStride, 38, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v33_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v34_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v35_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v36_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 33 * dstStride + 0, uz);
    }
    svint16_t v39_0 = vrow(rb, srcStride, 39, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v34_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v35_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v36_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v37_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 34 * dstStride + 0, uz);
    }
    svint16_t v40_0 = vrow(rb, srcStride, 40, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v35_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v36_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v37_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v38_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 35 * dstStride + 0, uz);
    }
    svint16_t v41_0 = vrow(rb, srcStride, 41, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v36_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v37_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v38_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v39_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 36 * dstStride + 0, uz);
    }
    svint16_t v42_0 = vrow(rb, srcStride, 42, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v37_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v38_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v39_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v40_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 37 * dstStride + 0, uz);
    }
    svint16_t v43_0 = vrow(rb, srcStride, 43, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v38_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v39_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v40_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v41_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 38 * dstStride + 0, uz);
    }
    svint16_t v44_0 = vrow(rb, srcStride, 44, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v39_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v40_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v41_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v42_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 39 * dstStride + 0, uz);
    }
    svint16_t v45_0 = vrow(rb, srcStride, 45, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v40_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v41_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v42_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v43_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 40 * dstStride + 0, uz);
    }
    svint16_t v46_0 = vrow(rb, srcStride, 46, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v41_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v42_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v43_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v44_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 41 * dstStride + 0, uz);
    }
    svint16_t v47_0 = vrow(rb, srcStride, 47, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v42_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v43_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v44_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v45_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 42 * dstStride + 0, uz);
    }
    svint16_t v48_0 = vrow(rb, srcStride, 48, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v43_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v44_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v45_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v46_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 43 * dstStride + 0, uz);
    }
    svint16_t v49_0 = vrow(rb, srcStride, 49, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v44_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v45_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v46_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v47_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 44 * dstStride + 0, uz);
    }
    svint16_t v50_0 = vrow(rb, srcStride, 50, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v45_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v46_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v47_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v48_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 45 * dstStride + 0, uz);
    }
    svint16_t v51_0 = vrow(rb, srcStride, 51, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v46_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v47_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v48_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v49_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 46 * dstStride + 0, uz);
    }
    svint16_t v52_0 = vrow(rb, srcStride, 52, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v47_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v48_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v49_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v50_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 47 * dstStride + 0, uz);
    }
    svint16_t v53_0 = vrow(rb, srcStride, 53, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v48_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v49_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v50_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v51_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 48 * dstStride + 0, uz);
    }
    svint16_t v54_0 = vrow(rb, srcStride, 54, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v49_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v50_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v51_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v52_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 49 * dstStride + 0, uz);
    }
    svint16_t v55_0 = vrow(rb, srcStride, 55, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v50_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v51_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v52_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v53_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 50 * dstStride + 0, uz);
    }
    svint16_t v56_0 = vrow(rb, srcStride, 56, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v51_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v52_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v53_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v54_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 51 * dstStride + 0, uz);
    }
    svint16_t v57_0 = vrow(rb, srcStride, 57, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v52_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v53_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v54_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v55_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 52 * dstStride + 0, uz);
    }
    svint16_t v58_0 = vrow(rb, srcStride, 58, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v53_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v54_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v55_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v56_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 53 * dstStride + 0, uz);
    }
    svint16_t v59_0 = vrow(rb, srcStride, 59, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v54_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v55_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v56_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v57_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 54 * dstStride + 0, uz);
    }
    svint16_t v60_0 = vrow(rb, srcStride, 60, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v55_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v56_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v57_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v58_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 55 * dstStride + 0, uz);
    }
    svint16_t v61_0 = vrow(rb, srcStride, 61, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v56_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v57_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v58_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v59_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 56 * dstStride + 0, uz);
    }
    svint16_t v62_0 = vrow(rb, srcStride, 62, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v57_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v58_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v59_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v60_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 57 * dstStride + 0, uz);
    }
    svint16_t v63_0 = vrow(rb, srcStride, 63, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v58_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v59_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v60_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v61_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 58 * dstStride + 0, uz);
    }
    svint16_t v64_0 = vrow(rb, srcStride, 64, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v59_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v60_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v61_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v62_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 59 * dstStride + 0, uz);
    }
    svint16_t v65_0 = vrow(rb, srcStride, 65, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v60_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v61_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v62_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v63_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 60 * dstStride + 0, uz);
    }
    svint16_t v66_0 = vrow(rb, srcStride, 66, 0, p16);
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v61_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v62_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v63_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v64_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 61 * dstStride + 0, uz);
    }
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v62_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v63_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v64_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v65_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 62 * dstStride + 0, uz);
    }
    {
        svint16_t acc0 = svmla_s16_x(p16, zero, v63_0, c0);
        svint16_t acc1 = svmla_s16_x(p16, acc0, v64_0, c1);
        svint16_t acc2 = svmla_s16_x(p16, acc1, v65_0, c2);
        svint16_t acc3 = svmla_s16_x(p16, acc2, v66_0, c3);
        svint16_t acc = svadd_n_s16_x(p16, acc3, 8192);
        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 63 * dstStride + 0, uz);
    }
}