// Generated by tools/emit_interp8_sve2_shared.py -- do not
// edit by hand. Vertical 8-tap luma 32x32 (SVE2, VL=256).
#include <arm_sve.h>

static inline svint16_t vrow(const uint8_t* p, intptr_t st, int k, int u, svbool_t p16)
{
    svuint16_t w = svld1ub_u16(p16, p + k * st + u * 16);
    // (b - 128) keeps 4-product s16 sums in range.
    return svreinterpret_s16_u16(svsub_n_u16_x(p16, w, 128));
}

extern "C" void dynopt_interp8_32x32_sve2_vpp(const uint8_t* src, intptr_t srcStride,
                   uint8_t* dst, intptr_t dstStride, int coeffIdx)
{
    const svbool_t p16 = svptrue_b16();
    const svbool_t p8b = svwhilelt_b8((uint32_t)0, (uint32_t)16);
    const int ph = (coeffIdx >= 1 && coeffIdx <= 3) ? coeffIdx : 2;
    const svint16_t c0 = svdup_n_s16(ph == 1 ? -1 : (ph == 3 ? 0 : -1));
    const svint16_t c1 = svdup_n_s16(ph == 1 ? 4 : (ph == 3 ? 1 : 4));
    const svint16_t c2 = svdup_n_s16(ph == 1 ? -10 : (ph == 3 ? -5 : -11));
    const svint16_t c3 = svdup_n_s16(ph == 1 ? 58 : (ph == 3 ? 17 : 40));
    const svint16_t c4 = svdup_n_s16(ph == 1 ? 17 : (ph == 3 ? 58 : 40));
    const svint16_t c5 = svdup_n_s16(ph == 1 ? -5 : (ph == 3 ? -10 : -11));
    const svint16_t c6 = svdup_n_s16(ph == 1 ? 1 : (ph == 3 ? 4 : 4));
    const svint16_t c7 = svdup_n_s16(ph == 1 ? 0 : (ph == 3 ? -1 : -1));
    // DC offset 8192 split across the accumulators
    // (2 accs -> 4096 each).
    const svint16_t off = svdup_n_s16(4096);
    const uint8_t* rb = src - 3 * srcStride;
    svint16_t v0_0 = vrow(rb, srcStride, 0, 0, p16);
    svint16_t v0_1 = vrow(rb, srcStride, 0, 1, p16);
    svint16_t v1_0 = vrow(rb, srcStride, 1, 0, p16);
    svint16_t v1_1 = vrow(rb, srcStride, 1, 1, p16);
    svint16_t v2_0 = vrow(rb, srcStride, 2, 0, p16);
    svint16_t v2_1 = vrow(rb, srcStride, 2, 1, p16);
    svint16_t v3_0 = vrow(rb, srcStride, 3, 0, p16);
    svint16_t v3_1 = vrow(rb, srcStride, 3, 1, p16);
    svint16_t v4_0 = vrow(rb, srcStride, 4, 0, p16);
    svint16_t v4_1 = vrow(rb, srcStride, 4, 1, p16);
    svint16_t v5_0 = vrow(rb, srcStride, 5, 0, p16);
    svint16_t v5_1 = vrow(rb, srcStride, 5, 1, p16);
    svint16_t v6_0 = vrow(rb, srcStride, 6, 0, p16);
    svint16_t v6_1 = vrow(rb, srcStride, 6, 1, p16);
    svint16_t v7_0 = vrow(rb, srcStride, 7, 0, p16);
    svint16_t v7_1 = vrow(rb, srcStride, 7, 1, p16);

    svint16_t v8_0 = vrow(rb, srcStride, 8, 0, p16);
    svint16_t v8_1 = vrow(rb, srcStride, 8, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v0_0, c0);
        a0 = svmla_s16_x(p16, a0, v2_0, c2);
        a0 = svmla_s16_x(p16, a0, v4_0, c4);
        a0 = svmla_s16_x(p16, a0, v6_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v1_0, c1);
        a1 = svmla_s16_x(p16, a1, v3_0, c3);
        a1 = svmla_s16_x(p16, a1, v5_0, c5);
        a1 = svmla_s16_x(p16, a1, v7_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 0 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v0_1, c0);
        a0 = svmla_s16_x(p16, a0, v2_1, c2);
        a0 = svmla_s16_x(p16, a0, v4_1, c4);
        a0 = svmla_s16_x(p16, a0, v6_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v1_1, c1);
        a1 = svmla_s16_x(p16, a1, v3_1, c3);
        a1 = svmla_s16_x(p16, a1, v5_1, c5);
        a1 = svmla_s16_x(p16, a1, v7_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 0 * dstStride + 16, uz);
    }
    svint16_t v9_0 = vrow(rb, srcStride, 9, 0, p16);
    svint16_t v9_1 = vrow(rb, srcStride, 9, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v1_0, c0);
        a0 = svmla_s16_x(p16, a0, v3_0, c2);
        a0 = svmla_s16_x(p16, a0, v5_0, c4);
        a0 = svmla_s16_x(p16, a0, v7_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v2_0, c1);
        a1 = svmla_s16_x(p16, a1, v4_0, c3);
        a1 = svmla_s16_x(p16, a1, v6_0, c5);
        a1 = svmla_s16_x(p16, a1, v8_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 1 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v1_1, c0);
        a0 = svmla_s16_x(p16, a0, v3_1, c2);
        a0 = svmla_s16_x(p16, a0, v5_1, c4);
        a0 = svmla_s16_x(p16, a0, v7_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v2_1, c1);
        a1 = svmla_s16_x(p16, a1, v4_1, c3);
        a1 = svmla_s16_x(p16, a1, v6_1, c5);
        a1 = svmla_s16_x(p16, a1, v8_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 1 * dstStride + 16, uz);
    }
    svint16_t v10_0 = vrow(rb, srcStride, 10, 0, p16);
    svint16_t v10_1 = vrow(rb, srcStride, 10, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v2_0, c0);
        a0 = svmla_s16_x(p16, a0, v4_0, c2);
        a0 = svmla_s16_x(p16, a0, v6_0, c4);
        a0 = svmla_s16_x(p16, a0, v8_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v3_0, c1);
        a1 = svmla_s16_x(p16, a1, v5_0, c3);
        a1 = svmla_s16_x(p16, a1, v7_0, c5);
        a1 = svmla_s16_x(p16, a1, v9_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 2 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v2_1, c0);
        a0 = svmla_s16_x(p16, a0, v4_1, c2);
        a0 = svmla_s16_x(p16, a0, v6_1, c4);
        a0 = svmla_s16_x(p16, a0, v8_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v3_1, c1);
        a1 = svmla_s16_x(p16, a1, v5_1, c3);
        a1 = svmla_s16_x(p16, a1, v7_1, c5);
        a1 = svmla_s16_x(p16, a1, v9_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 2 * dstStride + 16, uz);
    }
    svint16_t v11_0 = vrow(rb, srcStride, 11, 0, p16);
    svint16_t v11_1 = vrow(rb, srcStride, 11, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v3_0, c0);
        a0 = svmla_s16_x(p16, a0, v5_0, c2);
        a0 = svmla_s16_x(p16, a0, v7_0, c4);
        a0 = svmla_s16_x(p16, a0, v9_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v4_0, c1);
        a1 = svmla_s16_x(p16, a1, v6_0, c3);
        a1 = svmla_s16_x(p16, a1, v8_0, c5);
        a1 = svmla_s16_x(p16, a1, v10_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 3 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v3_1, c0);
        a0 = svmla_s16_x(p16, a0, v5_1, c2);
        a0 = svmla_s16_x(p16, a0, v7_1, c4);
        a0 = svmla_s16_x(p16, a0, v9_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v4_1, c1);
        a1 = svmla_s16_x(p16, a1, v6_1, c3);
        a1 = svmla_s16_x(p16, a1, v8_1, c5);
        a1 = svmla_s16_x(p16, a1, v10_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 3 * dstStride + 16, uz);
    }
    svint16_t v12_0 = vrow(rb, srcStride, 12, 0, p16);
    svint16_t v12_1 = vrow(rb, srcStride, 12, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v4_0, c0);
        a0 = svmla_s16_x(p16, a0, v6_0, c2);
        a0 = svmla_s16_x(p16, a0, v8_0, c4);
        a0 = svmla_s16_x(p16, a0, v10_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v5_0, c1);
        a1 = svmla_s16_x(p16, a1, v7_0, c3);
        a1 = svmla_s16_x(p16, a1, v9_0, c5);
        a1 = svmla_s16_x(p16, a1, v11_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 4 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v4_1, c0);
        a0 = svmla_s16_x(p16, a0, v6_1, c2);
        a0 = svmla_s16_x(p16, a0, v8_1, c4);
        a0 = svmla_s16_x(p16, a0, v10_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v5_1, c1);
        a1 = svmla_s16_x(p16, a1, v7_1, c3);
        a1 = svmla_s16_x(p16, a1, v9_1, c5);
        a1 = svmla_s16_x(p16, a1, v11_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 4 * dstStride + 16, uz);
    }
    svint16_t v13_0 = vrow(rb, srcStride, 13, 0, p16);
    svint16_t v13_1 = vrow(rb, srcStride, 13, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v5_0, c0);
        a0 = svmla_s16_x(p16, a0, v7_0, c2);
        a0 = svmla_s16_x(p16, a0, v9_0, c4);
        a0 = svmla_s16_x(p16, a0, v11_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v6_0, c1);
        a1 = svmla_s16_x(p16, a1, v8_0, c3);
        a1 = svmla_s16_x(p16, a1, v10_0, c5);
        a1 = svmla_s16_x(p16, a1, v12_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 5 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v5_1, c0);
        a0 = svmla_s16_x(p16, a0, v7_1, c2);
        a0 = svmla_s16_x(p16, a0, v9_1, c4);
        a0 = svmla_s16_x(p16, a0, v11_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v6_1, c1);
        a1 = svmla_s16_x(p16, a1, v8_1, c3);
        a1 = svmla_s16_x(p16, a1, v10_1, c5);
        a1 = svmla_s16_x(p16, a1, v12_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 5 * dstStride + 16, uz);
    }
    svint16_t v14_0 = vrow(rb, srcStride, 14, 0, p16);
    svint16_t v14_1 = vrow(rb, srcStride, 14, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v6_0, c0);
        a0 = svmla_s16_x(p16, a0, v8_0, c2);
        a0 = svmla_s16_x(p16, a0, v10_0, c4);
        a0 = svmla_s16_x(p16, a0, v12_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v7_0, c1);
        a1 = svmla_s16_x(p16, a1, v9_0, c3);
        a1 = svmla_s16_x(p16, a1, v11_0, c5);
        a1 = svmla_s16_x(p16, a1, v13_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 6 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v6_1, c0);
        a0 = svmla_s16_x(p16, a0, v8_1, c2);
        a0 = svmla_s16_x(p16, a0, v10_1, c4);
        a0 = svmla_s16_x(p16, a0, v12_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v7_1, c1);
        a1 = svmla_s16_x(p16, a1, v9_1, c3);
        a1 = svmla_s16_x(p16, a1, v11_1, c5);
        a1 = svmla_s16_x(p16, a1, v13_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 6 * dstStride + 16, uz);
    }
    svint16_t v15_0 = vrow(rb, srcStride, 15, 0, p16);
    svint16_t v15_1 = vrow(rb, srcStride, 15, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v7_0, c0);
        a0 = svmla_s16_x(p16, a0, v9_0, c2);
        a0 = svmla_s16_x(p16, a0, v11_0, c4);
        a0 = svmla_s16_x(p16, a0, v13_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v8_0, c1);
        a1 = svmla_s16_x(p16, a1, v10_0, c3);
        a1 = svmla_s16_x(p16, a1, v12_0, c5);
        a1 = svmla_s16_x(p16, a1, v14_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 7 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v7_1, c0);
        a0 = svmla_s16_x(p16, a0, v9_1, c2);
        a0 = svmla_s16_x(p16, a0, v11_1, c4);
        a0 = svmla_s16_x(p16, a0, v13_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v8_1, c1);
        a1 = svmla_s16_x(p16, a1, v10_1, c3);
        a1 = svmla_s16_x(p16, a1, v12_1, c5);
        a1 = svmla_s16_x(p16, a1, v14_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 7 * dstStride + 16, uz);
    }
    svint16_t v16_0 = vrow(rb, srcStride, 16, 0, p16);
    svint16_t v16_1 = vrow(rb, srcStride, 16, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v8_0, c0);
        a0 = svmla_s16_x(p16, a0, v10_0, c2);
        a0 = svmla_s16_x(p16, a0, v12_0, c4);
        a0 = svmla_s16_x(p16, a0, v14_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v9_0, c1);
        a1 = svmla_s16_x(p16, a1, v11_0, c3);
        a1 = svmla_s16_x(p16, a1, v13_0, c5);
        a1 = svmla_s16_x(p16, a1, v15_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 8 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v8_1, c0);
        a0 = svmla_s16_x(p16, a0, v10_1, c2);
        a0 = svmla_s16_x(p16, a0, v12_1, c4);
        a0 = svmla_s16_x(p16, a0, v14_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v9_1, c1);
        a1 = svmla_s16_x(p16, a1, v11_1, c3);
        a1 = svmla_s16_x(p16, a1, v13_1, c5);
        a1 = svmla_s16_x(p16, a1, v15_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 8 * dstStride + 16, uz);
    }
    svint16_t v17_0 = vrow(rb, srcStride, 17, 0, p16);
    svint16_t v17_1 = vrow(rb, srcStride, 17, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v9_0, c0);
        a0 = svmla_s16_x(p16, a0, v11_0, c2);
        a0 = svmla_s16_x(p16, a0, v13_0, c4);
        a0 = svmla_s16_x(p16, a0, v15_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v10_0, c1);
        a1 = svmla_s16_x(p16, a1, v12_0, c3);
        a1 = svmla_s16_x(p16, a1, v14_0, c5);
        a1 = svmla_s16_x(p16, a1, v16_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 9 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v9_1, c0);
        a0 = svmla_s16_x(p16, a0, v11_1, c2);
        a0 = svmla_s16_x(p16, a0, v13_1, c4);
        a0 = svmla_s16_x(p16, a0, v15_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v10_1, c1);
        a1 = svmla_s16_x(p16, a1, v12_1, c3);
        a1 = svmla_s16_x(p16, a1, v14_1, c5);
        a1 = svmla_s16_x(p16, a1, v16_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 9 * dstStride + 16, uz);
    }
    svint16_t v18_0 = vrow(rb, srcStride, 18, 0, p16);
    svint16_t v18_1 = vrow(rb, srcStride, 18, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v10_0, c0);
        a0 = svmla_s16_x(p16, a0, v12_0, c2);
        a0 = svmla_s16_x(p16, a0, v14_0, c4);
        a0 = svmla_s16_x(p16, a0, v16_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v11_0, c1);
        a1 = svmla_s16_x(p16, a1, v13_0, c3);
        a1 = svmla_s16_x(p16, a1, v15_0, c5);
        a1 = svmla_s16_x(p16, a1, v17_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 10 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v10_1, c0);
        a0 = svmla_s16_x(p16, a0, v12_1, c2);
        a0 = svmla_s16_x(p16, a0, v14_1, c4);
        a0 = svmla_s16_x(p16, a0, v16_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v11_1, c1);
        a1 = svmla_s16_x(p16, a1, v13_1, c3);
        a1 = svmla_s16_x(p16, a1, v15_1, c5);
        a1 = svmla_s16_x(p16, a1, v17_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 10 * dstStride + 16, uz);
    }
    svint16_t v19_0 = vrow(rb, srcStride, 19, 0, p16);
    svint16_t v19_1 = vrow(rb, srcStride, 19, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v11_0, c0);
        a0 = svmla_s16_x(p16, a0, v13_0, c2);
        a0 = svmla_s16_x(p16, a0, v15_0, c4);
        a0 = svmla_s16_x(p16, a0, v17_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v12_0, c1);
        a1 = svmla_s16_x(p16, a1, v14_0, c3);
        a1 = svmla_s16_x(p16, a1, v16_0, c5);
        a1 = svmla_s16_x(p16, a1, v18_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 11 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v11_1, c0);
        a0 = svmla_s16_x(p16, a0, v13_1, c2);
        a0 = svmla_s16_x(p16, a0, v15_1, c4);
        a0 = svmla_s16_x(p16, a0, v17_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v12_1, c1);
        a1 = svmla_s16_x(p16, a1, v14_1, c3);
        a1 = svmla_s16_x(p16, a1, v16_1, c5);
        a1 = svmla_s16_x(p16, a1, v18_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 11 * dstStride + 16, uz);
    }
    svint16_t v20_0 = vrow(rb, srcStride, 20, 0, p16);
    svint16_t v20_1 = vrow(rb, srcStride, 20, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v12_0, c0);
        a0 = svmla_s16_x(p16, a0, v14_0, c2);
        a0 = svmla_s16_x(p16, a0, v16_0, c4);
        a0 = svmla_s16_x(p16, a0, v18_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v13_0, c1);
        a1 = svmla_s16_x(p16, a1, v15_0, c3);
        a1 = svmla_s16_x(p16, a1, v17_0, c5);
        a1 = svmla_s16_x(p16, a1, v19_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 12 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v12_1, c0);
        a0 = svmla_s16_x(p16, a0, v14_1, c2);
        a0 = svmla_s16_x(p16, a0, v16_1, c4);
        a0 = svmla_s16_x(p16, a0, v18_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v13_1, c1);
        a1 = svmla_s16_x(p16, a1, v15_1, c3);
        a1 = svmla_s16_x(p16, a1, v17_1, c5);
        a1 = svmla_s16_x(p16, a1, v19_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 12 * dstStride + 16, uz);
    }
    svint16_t v21_0 = vrow(rb, srcStride, 21, 0, p16);
    svint16_t v21_1 = vrow(rb, srcStride, 21, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v13_0, c0);
        a0 = svmla_s16_x(p16, a0, v15_0, c2);
        a0 = svmla_s16_x(p16, a0, v17_0, c4);
        a0 = svmla_s16_x(p16, a0, v19_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v14_0, c1);
        a1 = svmla_s16_x(p16, a1, v16_0, c3);
        a1 = svmla_s16_x(p16, a1, v18_0, c5);
        a1 = svmla_s16_x(p16, a1, v20_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 13 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v13_1, c0);
        a0 = svmla_s16_x(p16, a0, v15_1, c2);
        a0 = svmla_s16_x(p16, a0, v17_1, c4);
        a0 = svmla_s16_x(p16, a0, v19_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v14_1, c1);
        a1 = svmla_s16_x(p16, a1, v16_1, c3);
        a1 = svmla_s16_x(p16, a1, v18_1, c5);
        a1 = svmla_s16_x(p16, a1, v20_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 13 * dstStride + 16, uz);
    }
    svint16_t v22_0 = vrow(rb, srcStride, 22, 0, p16);
    svint16_t v22_1 = vrow(rb, srcStride, 22, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v14_0, c0);
        a0 = svmla_s16_x(p16, a0, v16_0, c2);
        a0 = svmla_s16_x(p16, a0, v18_0, c4);
        a0 = svmla_s16_x(p16, a0, v20_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v15_0, c1);
        a1 = svmla_s16_x(p16, a1, v17_0, c3);
        a1 = svmla_s16_x(p16, a1, v19_0, c5);
        a1 = svmla_s16_x(p16, a1, v21_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 14 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v14_1, c0);
        a0 = svmla_s16_x(p16, a0, v16_1, c2);
        a0 = svmla_s16_x(p16, a0, v18_1, c4);
        a0 = svmla_s16_x(p16, a0, v20_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v15_1, c1);
        a1 = svmla_s16_x(p16, a1, v17_1, c3);
        a1 = svmla_s16_x(p16, a1, v19_1, c5);
        a1 = svmla_s16_x(p16, a1, v21_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 14 * dstStride + 16, uz);
    }
    svint16_t v23_0 = vrow(rb, srcStride, 23, 0, p16);
    svint16_t v23_1 = vrow(rb, srcStride, 23, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v15_0, c0);
        a0 = svmla_s16_x(p16, a0, v17_0, c2);
        a0 = svmla_s16_x(p16, a0, v19_0, c4);
        a0 = svmla_s16_x(p16, a0, v21_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v16_0, c1);
        a1 = svmla_s16_x(p16, a1, v18_0, c3);
        a1 = svmla_s16_x(p16, a1, v20_0, c5);
        a1 = svmla_s16_x(p16, a1, v22_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 15 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v15_1, c0);
        a0 = svmla_s16_x(p16, a0, v17_1, c2);
        a0 = svmla_s16_x(p16, a0, v19_1, c4);
        a0 = svmla_s16_x(p16, a0, v21_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v16_1, c1);
        a1 = svmla_s16_x(p16, a1, v18_1, c3);
        a1 = svmla_s16_x(p16, a1, v20_1, c5);
        a1 = svmla_s16_x(p16, a1, v22_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 15 * dstStride + 16, uz);
    }
    svint16_t v24_0 = vrow(rb, srcStride, 24, 0, p16);
    svint16_t v24_1 = vrow(rb, srcStride, 24, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v16_0, c0);
        a0 = svmla_s16_x(p16, a0, v18_0, c2);
        a0 = svmla_s16_x(p16, a0, v20_0, c4);
        a0 = svmla_s16_x(p16, a0, v22_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v17_0, c1);
        a1 = svmla_s16_x(p16, a1, v19_0, c3);
        a1 = svmla_s16_x(p16, a1, v21_0, c5);
        a1 = svmla_s16_x(p16, a1, v23_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 16 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v16_1, c0);
        a0 = svmla_s16_x(p16, a0, v18_1, c2);
        a0 = svmla_s16_x(p16, a0, v20_1, c4);
        a0 = svmla_s16_x(p16, a0, v22_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v17_1, c1);
        a1 = svmla_s16_x(p16, a1, v19_1, c3);
        a1 = svmla_s16_x(p16, a1, v21_1, c5);
        a1 = svmla_s16_x(p16, a1, v23_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 16 * dstStride + 16, uz);
    }
    svint16_t v25_0 = vrow(rb, srcStride, 25, 0, p16);
    svint16_t v25_1 = vrow(rb, srcStride, 25, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v17_0, c0);
        a0 = svmla_s16_x(p16, a0, v19_0, c2);
        a0 = svmla_s16_x(p16, a0, v21_0, c4);
        a0 = svmla_s16_x(p16, a0, v23_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v18_0, c1);
        a1 = svmla_s16_x(p16, a1, v20_0, c3);
        a1 = svmla_s16_x(p16, a1, v22_0, c5);
        a1 = svmla_s16_x(p16, a1, v24_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 17 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v17_1, c0);
        a0 = svmla_s16_x(p16, a0, v19_1, c2);
        a0 = svmla_s16_x(p16, a0, v21_1, c4);
        a0 = svmla_s16_x(p16, a0, v23_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v18_1, c1);
        a1 = svmla_s16_x(p16, a1, v20_1, c3);
        a1 = svmla_s16_x(p16, a1, v22_1, c5);
        a1 = svmla_s16_x(p16, a1, v24_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 17 * dstStride + 16, uz);
    }
    svint16_t v26_0 = vrow(rb, srcStride, 26, 0, p16);
    svint16_t v26_1 = vrow(rb, srcStride, 26, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v18_0, c0);
        a0 = svmla_s16_x(p16, a0, v20_0, c2);
        a0 = svmla_s16_x(p16, a0, v22_0, c4);
        a0 = svmla_s16_x(p16, a0, v24_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v19_0, c1);
        a1 = svmla_s16_x(p16, a1, v21_0, c3);
        a1 = svmla_s16_x(p16, a1, v23_0, c5);
        a1 = svmla_s16_x(p16, a1, v25_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 18 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v18_1, c0);
        a0 = svmla_s16_x(p16, a0, v20_1, c2);
        a0 = svmla_s16_x(p16, a0, v22_1, c4);
        a0 = svmla_s16_x(p16, a0, v24_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v19_1, c1);
        a1 = svmla_s16_x(p16, a1, v21_1, c3);
        a1 = svmla_s16_x(p16, a1, v23_1, c5);
        a1 = svmla_s16_x(p16, a1, v25_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 18 * dstStride + 16, uz);
    }
    svint16_t v27_0 = vrow(rb, srcStride, 27, 0, p16);
    svint16_t v27_1 = vrow(rb, srcStride, 27, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v19_0, c0);
        a0 = svmla_s16_x(p16, a0, v21_0, c2);
        a0 = svmla_s16_x(p16, a0, v23_0, c4);
        a0 = svmla_s16_x(p16, a0, v25_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v20_0, c1);
        a1 = svmla_s16_x(p16, a1, v22_0, c3);
        a1 = svmla_s16_x(p16, a1, v24_0, c5);
        a1 = svmla_s16_x(p16, a1, v26_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 19 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v19_1, c0);
        a0 = svmla_s16_x(p16, a0, v21_1, c2);
        a0 = svmla_s16_x(p16, a0, v23_1, c4);
        a0 = svmla_s16_x(p16, a0, v25_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v20_1, c1);
        a1 = svmla_s16_x(p16, a1, v22_1, c3);
        a1 = svmla_s16_x(p16, a1, v24_1, c5);
        a1 = svmla_s16_x(p16, a1, v26_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 19 * dstStride + 16, uz);
    }
    svint16_t v28_0 = vrow(rb, srcStride, 28, 0, p16);
    svint16_t v28_1 = vrow(rb, srcStride, 28, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v20_0, c0);
        a0 = svmla_s16_x(p16, a0, v22_0, c2);
        a0 = svmla_s16_x(p16, a0, v24_0, c4);
        a0 = svmla_s16_x(p16, a0, v26_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v21_0, c1);
        a1 = svmla_s16_x(p16, a1, v23_0, c3);
        a1 = svmla_s16_x(p16, a1, v25_0, c5);
        a1 = svmla_s16_x(p16, a1, v27_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 20 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v20_1, c0);
        a0 = svmla_s16_x(p16, a0, v22_1, c2);
        a0 = svmla_s16_x(p16, a0, v24_1, c4);
        a0 = svmla_s16_x(p16, a0, v26_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v21_1, c1);
        a1 = svmla_s16_x(p16, a1, v23_1, c3);
        a1 = svmla_s16_x(p16, a1, v25_1, c5);
        a1 = svmla_s16_x(p16, a1, v27_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 20 * dstStride + 16, uz);
    }
    svint16_t v29_0 = vrow(rb, srcStride, 29, 0, p16);
    svint16_t v29_1 = vrow(rb, srcStride, 29, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v21_0, c0);
        a0 = svmla_s16_x(p16, a0, v23_0, c2);
        a0 = svmla_s16_x(p16, a0, v25_0, c4);
        a0 = svmla_s16_x(p16, a0, v27_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v22_0, c1);
        a1 = svmla_s16_x(p16, a1, v24_0, c3);
        a1 = svmla_s16_x(p16, a1, v26_0, c5);
        a1 = svmla_s16_x(p16, a1, v28_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 21 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v21_1, c0);
        a0 = svmla_s16_x(p16, a0, v23_1, c2);
        a0 = svmla_s16_x(p16, a0, v25_1, c4);
        a0 = svmla_s16_x(p16, a0, v27_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v22_1, c1);
        a1 = svmla_s16_x(p16, a1, v24_1, c3);
        a1 = svmla_s16_x(p16, a1, v26_1, c5);
        a1 = svmla_s16_x(p16, a1, v28_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 21 * dstStride + 16, uz);
    }
    svint16_t v30_0 = vrow(rb, srcStride, 30, 0, p16);
    svint16_t v30_1 = vrow(rb, srcStride, 30, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v22_0, c0);
        a0 = svmla_s16_x(p16, a0, v24_0, c2);
        a0 = svmla_s16_x(p16, a0, v26_0, c4);
        a0 = svmla_s16_x(p16, a0, v28_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v23_0, c1);
        a1 = svmla_s16_x(p16, a1, v25_0, c3);
        a1 = svmla_s16_x(p16, a1, v27_0, c5);
        a1 = svmla_s16_x(p16, a1, v29_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 22 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v22_1, c0);
        a0 = svmla_s16_x(p16, a0, v24_1, c2);
        a0 = svmla_s16_x(p16, a0, v26_1, c4);
        a0 = svmla_s16_x(p16, a0, v28_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v23_1, c1);
        a1 = svmla_s16_x(p16, a1, v25_1, c3);
        a1 = svmla_s16_x(p16, a1, v27_1, c5);
        a1 = svmla_s16_x(p16, a1, v29_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 22 * dstStride + 16, uz);
    }
    svint16_t v31_0 = vrow(rb, srcStride, 31, 0, p16);
    svint16_t v31_1 = vrow(rb, srcStride, 31, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v23_0, c0);
        a0 = svmla_s16_x(p16, a0, v25_0, c2);
        a0 = svmla_s16_x(p16, a0, v27_0, c4);
        a0 = svmla_s16_x(p16, a0, v29_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v24_0, c1);
        a1 = svmla_s16_x(p16, a1, v26_0, c3);
        a1 = svmla_s16_x(p16, a1, v28_0, c5);
        a1 = svmla_s16_x(p16, a1, v30_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 23 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v23_1, c0);
        a0 = svmla_s16_x(p16, a0, v25_1, c2);
        a0 = svmla_s16_x(p16, a0, v27_1, c4);
        a0 = svmla_s16_x(p16, a0, v29_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v24_1, c1);
        a1 = svmla_s16_x(p16, a1, v26_1, c3);
        a1 = svmla_s16_x(p16, a1, v28_1, c5);
        a1 = svmla_s16_x(p16, a1, v30_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 23 * dstStride + 16, uz);
    }
    svint16_t v32_0 = vrow(rb, srcStride, 32, 0, p16);
    svint16_t v32_1 = vrow(rb, srcStride, 32, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v24_0, c0);
        a0 = svmla_s16_x(p16, a0, v26_0, c2);
        a0 = svmla_s16_x(p16, a0, v28_0, c4);
        a0 = svmla_s16_x(p16, a0, v30_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v25_0, c1);
        a1 = svmla_s16_x(p16, a1, v27_0, c3);
        a1 = svmla_s16_x(p16, a1, v29_0, c5);
        a1 = svmla_s16_x(p16, a1, v31_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 24 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v24_1, c0);
        a0 = svmla_s16_x(p16, a0, v26_1, c2);
        a0 = svmla_s16_x(p16, a0, v28_1, c4);
        a0 = svmla_s16_x(p16, a0, v30_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v25_1, c1);
        a1 = svmla_s16_x(p16, a1, v27_1, c3);
        a1 = svmla_s16_x(p16, a1, v29_1, c5);
        a1 = svmla_s16_x(p16, a1, v31_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 24 * dstStride + 16, uz);
    }
    svint16_t v33_0 = vrow(rb, srcStride, 33, 0, p16);
    svint16_t v33_1 = vrow(rb, srcStride, 33, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v25_0, c0);
        a0 = svmla_s16_x(p16, a0, v27_0, c2);
        a0 = svmla_s16_x(p16, a0, v29_0, c4);
        a0 = svmla_s16_x(p16, a0, v31_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v26_0, c1);
        a1 = svmla_s16_x(p16, a1, v28_0, c3);
        a1 = svmla_s16_x(p16, a1, v30_0, c5);
        a1 = svmla_s16_x(p16, a1, v32_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 25 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v25_1, c0);
        a0 = svmla_s16_x(p16, a0, v27_1, c2);
        a0 = svmla_s16_x(p16, a0, v29_1, c4);
        a0 = svmla_s16_x(p16, a0, v31_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v26_1, c1);
        a1 = svmla_s16_x(p16, a1, v28_1, c3);
        a1 = svmla_s16_x(p16, a1, v30_1, c5);
        a1 = svmla_s16_x(p16, a1, v32_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 25 * dstStride + 16, uz);
    }
    svint16_t v34_0 = vrow(rb, srcStride, 34, 0, p16);
    svint16_t v34_1 = vrow(rb, srcStride, 34, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v26_0, c0);
        a0 = svmla_s16_x(p16, a0, v28_0, c2);
        a0 = svmla_s16_x(p16, a0, v30_0, c4);
        a0 = svmla_s16_x(p16, a0, v32_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v27_0, c1);
        a1 = svmla_s16_x(p16, a1, v29_0, c3);
        a1 = svmla_s16_x(p16, a1, v31_0, c5);
        a1 = svmla_s16_x(p16, a1, v33_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 26 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v26_1, c0);
        a0 = svmla_s16_x(p16, a0, v28_1, c2);
        a0 = svmla_s16_x(p16, a0, v30_1, c4);
        a0 = svmla_s16_x(p16, a0, v32_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v27_1, c1);
        a1 = svmla_s16_x(p16, a1, v29_1, c3);
        a1 = svmla_s16_x(p16, a1, v31_1, c5);
        a1 = svmla_s16_x(p16, a1, v33_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 26 * dstStride + 16, uz);
    }
    svint16_t v35_0 = vrow(rb, srcStride, 35, 0, p16);
    svint16_t v35_1 = vrow(rb, srcStride, 35, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v27_0, c0);
        a0 = svmla_s16_x(p16, a0, v29_0, c2);
        a0 = svmla_s16_x(p16, a0, v31_0, c4);
        a0 = svmla_s16_x(p16, a0, v33_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v28_0, c1);
        a1 = svmla_s16_x(p16, a1, v30_0, c3);
        a1 = svmla_s16_x(p16, a1, v32_0, c5);
        a1 = svmla_s16_x(p16, a1, v34_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 27 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v27_1, c0);
        a0 = svmla_s16_x(p16, a0, v29_1, c2);
        a0 = svmla_s16_x(p16, a0, v31_1, c4);
        a0 = svmla_s16_x(p16, a0, v33_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v28_1, c1);
        a1 = svmla_s16_x(p16, a1, v30_1, c3);
        a1 = svmla_s16_x(p16, a1, v32_1, c5);
        a1 = svmla_s16_x(p16, a1, v34_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 27 * dstStride + 16, uz);
    }
    svint16_t v36_0 = vrow(rb, srcStride, 36, 0, p16);
    svint16_t v36_1 = vrow(rb, srcStride, 36, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v28_0, c0);
        a0 = svmla_s16_x(p16, a0, v30_0, c2);
        a0 = svmla_s16_x(p16, a0, v32_0, c4);
        a0 = svmla_s16_x(p16, a0, v34_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v29_0, c1);
        a1 = svmla_s16_x(p16, a1, v31_0, c3);
        a1 = svmla_s16_x(p16, a1, v33_0, c5);
        a1 = svmla_s16_x(p16, a1, v35_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 28 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v28_1, c0);
        a0 = svmla_s16_x(p16, a0, v30_1, c2);
        a0 = svmla_s16_x(p16, a0, v32_1, c4);
        a0 = svmla_s16_x(p16, a0, v34_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v29_1, c1);
        a1 = svmla_s16_x(p16, a1, v31_1, c3);
        a1 = svmla_s16_x(p16, a1, v33_1, c5);
        a1 = svmla_s16_x(p16, a1, v35_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 28 * dstStride + 16, uz);
    }
    svint16_t v37_0 = vrow(rb, srcStride, 37, 0, p16);
    svint16_t v37_1 = vrow(rb, srcStride, 37, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v29_0, c0);
        a0 = svmla_s16_x(p16, a0, v31_0, c2);
        a0 = svmla_s16_x(p16, a0, v33_0, c4);
        a0 = svmla_s16_x(p16, a0, v35_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v30_0, c1);
        a1 = svmla_s16_x(p16, a1, v32_0, c3);
        a1 = svmla_s16_x(p16, a1, v34_0, c5);
        a1 = svmla_s16_x(p16, a1, v36_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 29 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v29_1, c0);
        a0 = svmla_s16_x(p16, a0, v31_1, c2);
        a0 = svmla_s16_x(p16, a0, v33_1, c4);
        a0 = svmla_s16_x(p16, a0, v35_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v30_1, c1);
        a1 = svmla_s16_x(p16, a1, v32_1, c3);
        a1 = svmla_s16_x(p16, a1, v34_1, c5);
        a1 = svmla_s16_x(p16, a1, v36_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 29 * dstStride + 16, uz);
    }
    svint16_t v38_0 = vrow(rb, srcStride, 38, 0, p16);
    svint16_t v38_1 = vrow(rb, srcStride, 38, 1, p16);
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v30_0, c0);
        a0 = svmla_s16_x(p16, a0, v32_0, c2);
        a0 = svmla_s16_x(p16, a0, v34_0, c4);
        a0 = svmla_s16_x(p16, a0, v36_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v31_0, c1);
        a1 = svmla_s16_x(p16, a1, v33_0, c3);
        a1 = svmla_s16_x(p16, a1, v35_0, c5);
        a1 = svmla_s16_x(p16, a1, v37_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 30 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v30_1, c0);
        a0 = svmla_s16_x(p16, a0, v32_1, c2);
        a0 = svmla_s16_x(p16, a0, v34_1, c4);
        a0 = svmla_s16_x(p16, a0, v36_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v31_1, c1);
        a1 = svmla_s16_x(p16, a1, v33_1, c3);
        a1 = svmla_s16_x(p16, a1, v35_1, c5);
        a1 = svmla_s16_x(p16, a1, v37_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 30 * dstStride + 16, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v31_0, c0);
        a0 = svmla_s16_x(p16, a0, v33_0, c2);
        a0 = svmla_s16_x(p16, a0, v35_0, c4);
        a0 = svmla_s16_x(p16, a0, v37_0, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v32_0, c1);
        a1 = svmla_s16_x(p16, a1, v34_0, c3);
        a1 = svmla_s16_x(p16, a1, v36_0, c5);
        a1 = svmla_s16_x(p16, a1, v38_0, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 31 * dstStride + 0, uz);
    }
    {
        svint16_t a0 = off;
        a0 = svmla_s16_x(p16, a0, v31_1, c0);
        a0 = svmla_s16_x(p16, a0, v33_1, c2);
        a0 = svmla_s16_x(p16, a0, v35_1, c4);
        a0 = svmla_s16_x(p16, a0, v37_1, c6);
        svint16_t a1 = off;
        a1 = svmla_s16_x(p16, a1, v32_1, c1);
        a1 = svmla_s16_x(p16, a1, v34_1, c3);
        a1 = svmla_s16_x(p16, a1, v36_1, c5);
        a1 = svmla_s16_x(p16, a1, v38_1, c7);
        svint16_t pixels = a0;
        pixels = svadd_s16_x(p16, pixels, a1);
        svuint8_t u8 = svqrshrunb_n_s16(pixels, 6);
        svuint8_t uz = svuzp1_u8(u8, u8);
        svst1_u8(p8b, dst + 31 * dstStride + 16, uz);
    }
}