"""CADD Butterfly 模板：svcadd<rot>(x,x) 一条指令实现 [a+b, a-b] 蝴蝶。

成功案例：
- psy-cost best_cadd（permute_ratio 30.8% -> 17.4%，fused 176 -> 97）
- satd-16 best_sve2_cadd（fused 172 -> 138，tbl 48->16 + mul 32->0）

核心模式：
1. SVE2 `cadd<rot>(x, x)`：相邻 lane 对的和/差一次算出
   （rot=270：even lane a[2i]-b[2i+1]、odd lane a[2i+1]+b[2i]；
    x==y 时即 [x-y, x+y] 蝴蝶）
2. 蝴蝶级之间用单次 tbl 重排（kHADPermuteTbl 型索引），使下一级
   cadd 的 lane 对正确配对
3. SVE1 无原生 cadd：软件模拟（tbl swap + mul sign + add，3-4 条
   指令，见 best_sve1.cpp dynopt_cadd90_s16）——SVE2 目标用原生
   1 条 svcadd 替换
4. 4 点 hadamard = cadd -> tbl -> cadd（2 级蝴蝶 + 1 次重排）；
   8 点 = 3 级（psy-cost calc_energy_h_8x8 4 段：cadd->tbl->cadd->
   tbl->cadd）

适用场景：
- 8/4 点 hadamard 类块内变换（satd/sa8d/psy_cost/sao 等）
- VL=256 的 SVE2 目标（950/710）；SVE1 目标（920B）退回软件模拟
- 替换手写 trn1/trn2 转置链（每 8x8 块 24 trn -> 8 tbl + 16 cadd）

ISA 映射：
- SVE2: svcadd_s16(op1, op2, 270)（无谓词 ACLE 版本）
- SVE1: svtbl swap + svmul sign + svadd（软件 cadd，best_sve1 模式）
- NEON: vtrn1q/vtrn2q 转置链（保守基线，不动）
"""

from __future__ import annotations
from typing import Any

from .base import RegionScheduleTemplate, TemplateConstraints, TemplateResult


class CADDButterflyTemplate(RegionScheduleTemplate):
    name = "cadd_butterfly"
    description = "svcadd<rot>(x,x) 蝴蝶 + tbl 重排（替代 trn 转置链）"
    isa_support = ["sve2", "sve2p1", "sve2p3"]
    kernel_types = ["satd16", "satd", "sa8d", "psy_cost"]

    def applicable(self, kernel_type: str,
                   constraints: TemplateConstraints) -> bool:
        if not super().applicable(kernel_type, constraints):
            return False
        if constraints.vl < 32:
            # 128-bit 下 cadd 蝴蝶的 lane 分组收益有限，NEON trn 基线
            # 即可；模板面向 VL=256 的宽度原生目标。
            return False
        return True

    def predict_permute_ratio(self) -> float:
        """按成功案例估计：16 次/块 的 tbl 重排，ratio < 0.20。"""
        return 0.15

    def emit(self, func_name: str, **kwargs: Any) -> TemplateResult:
        """生成宽度原生 SVE2 cadd 蝴蝶候选（satd-16 pack=2 模式）。

        kwargs:
            kernel_type: 当前实现生成 satd16（参考 best_sve2_cadd.cpp）
            width/height: 预留参数化
        """
        code = _satd16_cadd_source(func_name)
        return TemplateResult(
            code=code,
            func_name=func_name,
            template_name=self.name,
            estimated_permute_ratio=self.predict_permute_ratio(),
            estimated_fused_uop=138,
            notes=("SVE2 原生 svcadd<270> 替换软件 cadd（best_sve1 的 "
                   "tbl swap + mul sign）；fused 172->138、tbl 48->16。"
                   "950-only：920B(SVE1) 必须用软件模拟版本。"),
        )


def _satd16_cadd_source(func_name: str) -> str:
    return f"""// Generated by optimizer/templates/cadd_butterfly.py
// Native SVE2 cadd butterfly SATD 16x16 (pack=2 width-native).
#include <arm_sve.h>

static inline svint16_t cadd90_s16(svint16_t a)
{{
    return svcadd_s16(a, a, 270);
}}

#define CADD90(a) cadd90_s16((a))

static const uint16_t HAD_IDX16[16] =
    {{ 0, 2, 4, 6, 1, 3, 5, 7, 8, 10, 12, 14, 9, 11, 13, 15 }};

extern "C" int {func_name}(const uint8_t* pix1, intptr_t sp1,
              const uint8_t* pix2, intptr_t sp2)
{{
    const svbool_t p16 = svptrue_b16();
    const svuint16_t had_idx = svld1_u16(p16, HAD_IDX16);

    #define LD(r) svreinterpret_s16_u16(svsub_u16_x(           \\
        p16,                                                  \\
        svld1ub_u16(p16, pix1 + (r) * sp1),                   \\
        svld1ub_u16(p16, pix2 + (r) * sp2)))
    #define ROWH4(p)                                           \\
        p = CADD90(p);                                        \\
        p = svtbl_s16(p, had_idx);                            \\
        p = CADD90(p);                                        \\
        (void)0

    svuint16_t total = svdup_n_u16(0);
    for (int g = 0; g < 4; g++)
    {{
        svint16_t r0 = LD(g * 4 + 0); ROWH4(r0);
        svint16_t r1 = LD(g * 4 + 1); ROWH4(r1);
        svint16_t r2 = LD(g * 4 + 2); ROWH4(r2);
        svint16_t r3 = LD(g * 4 + 3); ROWH4(r3);
        svint16_t a0 = svabs_s16_x(p16, svadd_s16_x(p16, r0, r1));
        svint16_t d0 = svabd_s16_x(p16, r0, r1);
        svint16_t a1 = svabs_s16_x(p16, svadd_s16_x(p16, r2, r3));
        svint16_t d1 = svabd_s16_x(p16, r2, r3);
        svint16_t m0 = svmax_s16_x(p16, a0, a1);
        svint16_t m1 = svmax_s16_x(p16, d0, d1);
        svint16_t gs = svadd_s16_x(p16, m0, m1);
        total = svadd_u16_x(p16, total, svreinterpret_u16_s16(gs));
    }}
    return (int)svaddv_u16(p16, total);
}}
"""
