"""P4 butterfly-quarter template (AGO P4; known win = dct fused8).

The dct16 fused-quarter structure, parameterized by coefficient tables
so any butterfly/fir kernel with the same quarter dataflow can reuse
it: for each 4-row group, split rows into lo/hi halves, form
O = lo - rev(hi) and even sums E0/E1, then emit the three output
families:
  k odd      : sdot(GT[k], O_0..O_3) -> addp4 -> rshrn
  k = 2 mod 4: sdot(T8ODD, EO)      -> addp4 -> rshrn
  k = 0 mod 4: mul(T8E, EEE/EEO)    -> addp4 -> rshrn
The emitted pass is complete and compilable with the pure-SVE helper
set (optimizer/ir/pure_sve_helpers.py), so a kernel that supplies the
three coefficient tables gets a gated candidate directly.  The dct16
pass1 is the canonical instance (docs/65; kernels/dct16
best_ir_pure_sve.cpp), validated by tools/test_butterfly_template.py.
"""

from __future__ import annotations

from typing import Dict, List, Tuple

from ago.rules import (  # noqa: E402
    CoverTemplate, Pattern, ProofObligation, RewriteRule, RuleBinding)


def _c_table(name: str, ctype: str, rows: List[List[int]]) -> str:
    body = ",\n    ".join("{ " + ", ".join(str(x) for x in row) + " }"
                          for row in rows)
    return "static const %s %s[%d][%d] = {\n    %s\n};\n" % (
        ctype, name, len(rows), len(rows[0]), body)


def coef_c_arrays(coefs: Dict[str, List[List[int]]]) -> str:
    out = []
    if "gt" in coefs:
        out.append(_c_table("GT", "int16_t", coefs["gt"]))
    if "gt32a" in coefs:
        out.append(_c_table("GT32A", "int16_t", coefs["gt32a"]))
    if "gt32b" in coefs:
        out.append(_c_table("GT32B", "int16_t", coefs["gt32b"]))
    if "t8odd" in coefs:
        out.append(_c_table("T8ODD", "int16_t", coefs["t8odd"]))
    if "gt16s32" in coefs:
        out.append(_c_table("GT16S32", "int32_t", coefs["gt16s32"]))
    if "gt16s16" in coefs:
        out.append(_c_table("GT16S16", "int16_t", coefs["gt16s16"]))
    if "gt32s32a" in coefs:
        out.append(_c_table("GT32S32A", "int32_t", coefs["gt32s32a"]))
    if "gt32s32b" in coefs:
        out.append(_c_table("GT32S32B", "int32_t", coefs["gt32s32b"]))
    if "k4" in coefs:
        out.append(_c_table("K4", "int32_t", coefs["k4"]))
    if "k4s16" in coefs:
        out.append(_c_table("K4S16", "int16_t", coefs["k4s16"]))
    if "k2s16a" in coefs:
        out.append(_c_table("K2S16A", "int16_t", coefs["k2s16a"]))
    if "k2s16b" in coefs:
        out.append(_c_table("K2S16B", "int16_t", coefs["k2s16b"]))
    if "t8e" in coefs:
        out.append(_c_table("T8E", "int32_t", coefs["t8e"]))
    return "\n".join(out)


def _dct16_defaults() -> Dict[str, List[List[int]]]:
    try:
        from optimizer.ir.dct16_op_ir import G16, T8E  # noqa: E402
        gt = G16
        t8e = T8E
    except Exception:
        gt = [[1] * 8 for _ in range(16)]
        t8e = [[1] * 4 for _ in range(4)]
    t8odd = [row[:4] + row[:4] for row in (gt[2], gt[6], gt[10], gt[14])]
    return {"gt": gt, "t8odd": t8odd, "t8e": t8e}


def emit_quarter_pass(n: int = 16, coefs: Dict[str, List[List[int]]] = None,
                      target: str = "sve2", fn: str = "quarter_pass1",
                      shift: int = 0, include_coefs: bool = True) -> str:
    """Emit a complete dct16-style fused-quarter pass1 (8-lane,
    VL=128-fixed).  Requires the pure-SVE helper set and the three
    coefficient tables (gt 16x8, t8odd 4x8, t8e 4x4)."""
    if coefs is None:
        coefs = _dct16_defaults()
    if shift == 0:
        shift = 3 if n <= 16 else 4
    if target.startswith("neon"):
        return emit_quarter_pass_neon(n=n, coefs=coefs, fn=fn,
                                      shift=shift,
                                      include_coefs=include_coefs)
    arrays = coef_c_arrays(coefs) if include_coefs else ""
    lines = [
        "// Generated by ago.templates.butterfly_quarter (P4) -- "
        "fused-quarter pass1 (dct16 canonical instance).",
        "#include <arm_sve.h>",
        "#include <cstdint>",
        "",
        arrays,
        "",
        "static inline void %s(const int16_t* src, int16_t* dst, "
        "intptr_t stride)" % fn,
        "{",
        "    const int line = %d;" % n,
        "    const int shift = %d;" % shift,
        "    for (int i = 0; i < line; i += 4)",
        "    {",
    ]
    rows = []
    for r in range(4):
        rows.append((
            "        const svint16_t s%d_lo = psv_load8(src + (i + %d) "
            "* stride);" % (r, r),
            "        const svint16_t s%d_hi = psv_rev16(psv_load8("
            "src + (i + %d) * stride + 8));" % (r, r),
            "        svint16_t O_%d = svsub_s16_x(psv_pg8_s16(), "
            "s%d_lo, s%d_hi);" % (r, r, r),
            "        svint32_t E0_%d = psv_saddl_s16("
            "psv_get_lo4_s16(s%d_lo), psv_get_lo4_s16(s%d_hi));"
            % (r, r, r),
            "        svint32_t E1_%d = psv_saddl_s16("
            "psv_get_hi4_s16(s%d_lo), psv_get_hi4_s16(s%d_hi));"
            % (r, r, r),
        ))
    # O/E per row
    for block in rows:
        lines.extend(block)
    # EO pair packs (rows 0+1 -> EO_0, rows 2+3 -> EO_1)
    lines.extend([
        "        svint32_t EOa_0 = svsub_s32_x(psv_pg4_s32(), E0_0, "
        "psv_rev32_s32(E1_0));",
        "        svint32_t EOb_0 = svsub_s32_x(psv_pg4_s32(), E0_1, "
        "psv_rev32_s32(E1_1));",
        "        svint16_t EO_0 = psv_combine4_s16("
        "psv_vmovn_s32(EOa_0), psv_vmovn_s32(EOb_0));",
        "        svint32_t EOa_1 = svsub_s32_x(psv_pg4_s32(), E0_2, "
        "psv_rev32_s32(E1_2));",
        "        svint32_t EOb_1 = svsub_s32_x(psv_pg4_s32(), E0_3, "
        "psv_rev32_s32(E1_3));",
        "        svint16_t EO_1 = psv_combine4_s16("
        "psv_vmovn_s32(EOa_1), psv_vmovn_s32(EOb_1));",
        # EE -> EEE/EEO per row pair
        "        svint32_t EE_0 = svadd_s32_x(psv_pg4_s32(), E0_0, "
        "psv_rev32_s32(E1_0));",
        "        svint32_t EE_1 = svadd_s32_x(psv_pg4_s32(), E0_1, "
        "psv_rev32_s32(E1_1));",
        "        svint32_t t0_0 = svreinterpret_s32_s64(svzip1_s64("
        "svreinterpret_s64_s32(EE_0), svreinterpret_s64_s32(EE_1)));",
        "        svint32_t z2_0 = svreinterpret_s32_s64(svzip2_s64("
        "svreinterpret_s64_s32(EE_0), svreinterpret_s64_s32(EE_1)));",
        "        svint32_t EEE_0 = svadd_s32_x(psv_pg4_s32(), t0_0, "
        "psv_rev64_s32(z2_0));",
        "        svint32_t EEO_0 = svsub_s32_x(psv_pg4_s32(), t0_0, "
        "psv_rev64_s32(z2_0));",
        "        svint32_t EE_2 = svadd_s32_x(psv_pg4_s32(), E0_2, "
        "psv_rev32_s32(E1_2));",
        "        svint32_t EE_3 = svadd_s32_x(psv_pg4_s32(), E0_3, "
        "psv_rev32_s32(E1_3));",
        "        svint32_t t0_1 = svreinterpret_s32_s64(svzip1_s64("
        "svreinterpret_s64_s32(EE_2), svreinterpret_s64_s32(EE_3)));",
        "        svint32_t z2_1 = svreinterpret_s32_s64(svzip2_s64("
        "svreinterpret_s64_s32(EE_2), svreinterpret_s64_s32(EE_3)));",
        "        svint32_t EEE_1 = svadd_s32_x(psv_pg4_s32(), t0_1, "
        "psv_rev64_s32(z2_1));",
        "        svint32_t EEO_1 = svsub_s32_x(psv_pg4_s32(), t0_1, "
        "psv_rev64_s32(z2_1));",
        "",
    ])
    # k odd family
    lines.extend([
        "        for (int k = 1; k < %d; k += 2)" % n,
        "        {",
        "            const svint16_t c = psv_load8(GT[k]);",
        "            svint64_t t0 = psv_sdot(psv_zero_s64(), c, O_0);",
        "            svint64_t t1 = psv_sdot(psv_zero_s64(), c, O_1);",
        "            svint64_t t2 = psv_sdot(psv_zero_s64(), c, O_2);",
        "            svint64_t t3 = psv_sdot(psv_zero_s64(), c, O_3);",
        "            const svint32_t t01 = psv_combine4_s32("
        "psv_vmovn_s64(t0), psv_vmovn_s64(t1));",
        "            const svint32_t t23 = psv_combine4_s32("
        "psv_vmovn_s64(t2), psv_vmovn_s64(t3));",
        "            svint16_t nn = psv_rshrn_s32<shift>("
        "psv_addp4_s32(t01, t23));",
        "            psv_store4_s16(dst + %d * k + i, nn);" % n,
        "        }",
        "",
    ])
    # k = 2 mod 4 family
    lines.extend([
        "        for (int k = 2; k < %d; k += 4)" % n,
        "        {",
        "            const svint16_t c = psv_load8(T8ODD[(k - 2) / 4]);",
        "            svint64_t t0 = psv_sdot(psv_zero_s64(), c, EO_0);",
        "            svint64_t t1 = psv_sdot(psv_zero_s64(), c, EO_1);",
        "            const svint32_t tnn = psv_combine4_s32("
        "psv_vmovn_s64(t0), psv_vmovn_s64(t1));",
        "            svint16_t nn = psv_rshrn_s32<shift>(tnn);",
        "            psv_store4_s16(dst + %d * k + i, nn);" % n,
        "        }",
        "",
    ])
    # even family k = 0,4,8,12 (n=16) / 0,8,16,24 (n=32)
    kstep = 4 if n <= 16 else 8
    evens = [(0, "EEE", False), (kstep, "EEO", True),
             (2 * kstep, "EEE", True), (3 * kstep, "EEO", True)]
    for k, which, mul_first in evens:
        lines.extend([
            "        {",
            "            const svint32_t c = psv_load4_s32(T8E[%d]);"
            % (k // kstep),
        ])
        if mul_first:
            lines.extend([
                "            svint32_t m0 = svmul_s32_x(psv_pg4_s32(), "
                "c, %s_0);" % which,
                "            svint32_t m1 = svmul_s32_x(psv_pg4_s32(), "
                "c, %s_1);" % which,
                "            svint32_t m = psv_addp4_s32(m0, m1);",
            ])
        else:
            lines.extend([
                "            svint32_t pp = psv_addp4_s32(%s_0, %s_1);"
                % (which, which),
                "            svint32_t m = svmul_s32_x(psv_pg4_s32(), "
                "c, pp);",
            ])
        lines.extend([
            "            svint16_t nn = psv_rshrn_s32<shift>(m);",
            "            psv_store4_s16(dst + %d * %d + i, nn);"
            % (n, k),
            "        }",
        ])
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def emit_quarter_pass_neon(n: int = 16,
                           coefs: Dict[str, List[List[int]]] = None,
                           fn: str = "quarter_pass1_neon",
                           shift: int = 0,
                           include_coefs: bool = True) -> str:
    """NEON target of the fused-quarter pass1 (dct16 canonical
    instance, mirrors kernels/dct16/candidates/best_neon_vl128.cpp
    pass1Butterfly16_sve: vmull/vmlal + vpadd trees).  The NEON
    intermediate grouping differs from the SVE sdot path but the
    pass1 coefficients are upstream-exact and identical."""
    if coefs is None:
        coefs = _dct16_defaults()
    if shift == 0:
        shift = 3 if n <= 16 else 4
    arrays = coef_c_arrays(coefs) if include_coefs else ""
    lines = [
        "// Generated by ago.templates.butterfly_quarter (P4) -- "
        "dct16 fused-quarter pass1 (NEON target).",
        "#include <arm_neon.h>",
        "#include <cstdint>",
        "",
        arrays,
        "",
        "static const uint8_t DQ_REV16_TBL[16] =",
        "    { 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1 };",
        "static const uint8_t DQ_REV32_TBL[16] =",
        "    { 12, 13, 14, 15, 8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3 };",
        "",
        "static inline int16x8_t dq_rev16(const int16x8_t a)",
        "{",
        "    const uint8x16_t tbl = vld1q_u8(DQ_REV16_TBL);",
        "    const int8x16_t s = vreinterpretq_s8_s16(a);",
        "    return vreinterpretq_s16_s8(vqtbx1q_s8(s, s, tbl));",
        "}",
        "",
        "static inline int32x4_t dq_rev32(const int32x4_t a)",
        "{",
        "    const uint8x16_t tbl = vld1q_u8(DQ_REV32_TBL);",
        "    const int8x16_t s = vreinterpretq_s8_s32(a);",
        "    return vreinterpretq_s32_s8(vqtbx1q_s8(s, s, tbl));",
        "}",
        "",
        "static inline void %s(const int16_t* src, int16_t* dst, "
        "intptr_t stride)" % fn,
        "{",
        "    const int shift = %d;" % shift,
        "    const int line = %d;" % n,
        "    for (int i = 0; i < line; i += 4)",
        "    {",
    ]
    for r in range(4):
        lines.extend([
            "        int16x8_t s%d_lo = vld1q_s16(src + (i + %d) * "
            "stride);" % (r, r),
            "        int16x8_t s%d_hi = dq_rev16(vld1q_s16("
            "src + (i + %d) * stride + 8));" % (r, r),
            "        int16x8_t O%d = vsubq_s16(s%d_lo, s%d_hi);"
            % (r, r, r),
            "        int32x4_t e%d_0 = vaddl_s16(vget_low_s16(s%d_lo), "
            "vget_low_s16(s%d_hi));" % (r, r, r),
            "        int32x4_t e%d_1 = vaddl_s16(vget_high_s16(s%d_lo), "
            "vget_high_s16(s%d_hi));" % (r, r, r),
        ])
    lines.extend([
        "        int16x8_t EO0 = vcombine_s16("
        "vmovn_s32(vsubq_s32(e0_0, dq_rev32(e0_1))), "
        "vmovn_s32(vsubq_s32(e1_0, dq_rev32(e1_1))));",
        "        int32x4_t EEE0 = vaddq_s32("
        "vreinterpretq_s32_s64(vzip1q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(e0_0, dq_rev32(e0_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(e1_0, dq_rev32(e1_1))))), "
        "vrev64q_s32(vreinterpretq_s32_s64(vzip2q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(e0_0, dq_rev32(e0_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(e1_0, dq_rev32(e1_1)))))));",
        "        int32x4_t EEO0 = vsubq_s32("
        "vreinterpretq_s32_s64(vzip1q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(e0_0, dq_rev32(e0_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(e1_0, dq_rev32(e1_1))))), "
        "vrev64q_s32(vreinterpretq_s32_s64(vzip2q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(e0_0, dq_rev32(e0_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(e1_0, dq_rev32(e1_1)))))));",
        "        int16x8_t EO1 = vcombine_s16("
        "vmovn_s32(vsubq_s32(e2_0, dq_rev32(e2_1))), "
        "vmovn_s32(vsubq_s32(e3_0, dq_rev32(e3_1))));",
        "        int32x4_t EEE1 = vaddq_s32("
        "vreinterpretq_s32_s64(vzip1q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(e2_0, dq_rev32(e2_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(e3_0, dq_rev32(e3_1))))), "
        "vrev64q_s32(vreinterpretq_s32_s64(vzip2q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(e2_0, dq_rev32(e2_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(e3_0, dq_rev32(e3_1)))))));",
        "        int32x4_t EEO1 = vsubq_s32("
        "vreinterpretq_s32_s64(vzip1q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(e2_0, dq_rev32(e2_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(e3_0, dq_rev32(e3_1))))), "
        "vrev64q_s32(vreinterpretq_s32_s64(vzip2q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(e2_0, dq_rev32(e2_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(e3_0, dq_rev32(e3_1)))))));",
        "",
    ])
    lines.extend([
        "        for (int k = 1; k < %d; k += 2)" % n,
        "        {",
        "            int16x8_t c = vld1q_s16(GT[k]);",
        "            int32x4_t a0 = vmull_s16(vget_low_s16(c), "
        "vget_low_s16(O0));",
        "            a0 = vmlal_s16(a0, vget_high_s16(c), "
        "vget_high_s16(O0));",
        "            int32x4_t a1 = vmull_s16(vget_low_s16(c), "
        "vget_low_s16(O1));",
        "            a1 = vmlal_s16(a1, vget_high_s16(c), "
        "vget_high_s16(O1));",
        "            int32x4_t a2 = vmull_s16(vget_low_s16(c), "
        "vget_low_s16(O2));",
        "            a2 = vmlal_s16(a2, vget_high_s16(c), "
        "vget_high_s16(O2));",
        "            int32x4_t a3 = vmull_s16(vget_low_s16(c), "
        "vget_low_s16(O3));",
        "            a3 = vmlal_s16(a3, vget_high_s16(c), "
        "vget_high_s16(O3));",
        "            int16x4_t res = vrshrn_n_s32(vpaddq_s32("
        "vpaddq_s32(a0, a1), vpaddq_s32(a2, a3)), shift);",
        "            vst1_s16(dst + %d * k + i, res);" % n,
        "        }",
        "",
        "        for (int k = 2; k < %d; k += 4)" % n,
        "        {",
        "            int16x8_t c = vld1q_s16(T8ODD[(k - 2) / 4]);",
        "            int32x4_t p0 = vmull_s16(vget_low_s16(c), "
        "vget_low_s16(EO0));",
        "            int32x4_t p1 = vmull_s16(vget_high_s16(c), "
        "vget_high_s16(EO0));",
        "            int32x4_t p2 = vmull_s16(vget_low_s16(c), "
        "vget_low_s16(EO1));",
        "            int32x4_t p3 = vmull_s16(vget_high_s16(c), "
        "vget_high_s16(EO1));",
        "            int16x4_t res = vrshrn_n_s32(vpaddq_s32("
        "vpaddq_s32(p0, p1), vpaddq_s32(p2, p3)), shift);",
        "            vst1_s16(dst + %d * k + i, res);" % n,
        "        }",
        "",
    ])
    kstep = 4 if n <= 16 else 8
    evens = [(0, "EEE", False), (kstep, "EEO", True),
             (2 * kstep, "EEE", True), (3 * kstep, "EEO", True)]
    for idx, (k, which, mul_first) in enumerate(evens):
        lines.extend([
            "        {",
            "            int32x4_t c = vld1q_s32(T8E[%d]);" % idx,
        ])
        if mul_first:
            lines.extend([
                "            int32x4_t m = vpaddq_s32("
                "vmulq_s32(c, %s0), vmulq_s32(c, %s1));"
                % (which, which),
            ])
        else:
            lines.extend([
                "            int32x4_t m = vmulq_s32(c, "
                "vpaddq_s32(%s0, %s1));" % (which, which),
            ])
        lines.extend([
            "            int16x4_t res = vrshrn_n_s32(m, shift);",
            "            vst1_s16(dst + %d * %d + i, res);" % (n, k),
            "        }",
        ])
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


_NEON_HEADER = """\
static const uint8_t DQ_REV16_TBL[16] =
    { 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1 };
static const uint8_t DQ_REV32_TBL[16] =
    { 12, 13, 14, 15, 8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3 };

static inline int16x8_t dq_rev16(const int16x8_t a)
{
    const uint8x16_t tbl = vld1q_u8(DQ_REV16_TBL);
    const int8x16_t s = vreinterpretq_s8_s16(a);
    return vreinterpretq_s16_s8(vqtbx1q_s8(s, s, tbl));
}

static inline int32x4_t dq_rev32(const int32x4_t a)
{
    const uint8x16_t tbl = vld1q_u8(DQ_REV32_TBL);
    const int8x16_t s = vreinterpretq_s8_s32(a);
    return vreinterpretq_s32_s8(vqtbx1q_s8(s, s, tbl));
}
"""


def emit_quarter_pass32(coefs: Dict[str, List[List[int]]] = None,
                        target: str = "sve2",
                        fn: str = "quarter_pass1_32",
                        include_coefs: bool = True) -> str:
    """Complete dct32-style fused-quarter pass1 (4 chunks per row:
    O_0 = v0-rev(v3), O_1 = v1-rev(v2); families odd/k2/k4/even).
    Coefs: gt32a 32x8, gt32b 32x8, k4 8x4, t8e 4x4."""
    if coefs is None:
        raise ValueError("dct32 quarter pass requires gt32a/gt32b/k4/t8e "
                         "coefficient tables")
    arrays = coef_c_arrays(coefs) if include_coefs else ""
    lines = [
        "// Generated by ago.templates.butterfly_quarter (P4) -- "
        "dct32 fused-quarter pass1.",
        "#include <arm_sve.h>",
        "#include <cstdint>",
        "",
        arrays,
        "",
        "static inline void %s(const int16_t* src, int16_t* dst, "
        "intptr_t stride)" % fn,
        "{",
        "    const int line = 32;",
        "    const int shift = 4;",
        "    for (int i = 0; i < line; i += 4)",
        "    {",
    ]
    for r in range(4):
        lines.extend([
            "        const svint16_t r%d_v0 = psv_load8("
            "src + (i + %d) * stride + 0);" % (r, r),
            "        const svint16_t r%d_v1 = psv_load8("
            "src + (i + %d) * stride + 8);" % (r, r),
            "        const svint16_t r%d_v2r = psv_rev16(psv_load8("
            "src + (i + %d) * stride + 16));" % (r, r),
            "        const svint16_t r%d_v3r = psv_rev16(psv_load8("
            "src + (i + %d) * stride + 24));" % (r, r),
            "        svint16_t O_%d_0 = svsub_s16_x(psv_pg8_s16(), "
            "r%d_v0, r%d_v3r);" % (r, r, r),
            "        svint16_t O_%d_1 = svsub_s16_x(psv_pg8_s16(), "
            "r%d_v1, r%d_v2r);" % (r, r, r),
            "        svint32_t E0_%d = psv_saddl_s16("
            "psv_get_lo4_s16(r%d_v0), psv_get_lo4_s16(r%d_v3r));"
            % (r, r, r),
            "        svint32_t E1_%d = psv_saddl_s16("
            "psv_get_hi4_s16(r%d_v0), psv_get_hi4_s16(r%d_v3r));"
            % (r, r, r),
            "        svint32_t E2_%d = psv_saddl_s16("
            "psv_get_lo4_s16(r%d_v1), psv_get_lo4_s16(r%d_v2r));"
            % (r, r, r),
            "        svint32_t E3_%d = psv_saddl_s16("
            "psv_get_hi4_s16(r%d_v1), psv_get_hi4_s16(r%d_v2r));"
            % (r, r, r),
            "        svint16_t EO_%d = psv_combine4_s16("
            "psv_vmovn_s32(svsub_s32_x(psv_pg4_s32(), E0_%d, "
            "psv_rev32_s32(E3_%d))), "
            "psv_vmovn_s32(svsub_s32_x(psv_pg4_s32(), E1_%d, "
            "psv_rev32_s32(E2_%d))));" % (r, r, r, r, r),
            "        svint32_t EE_%d_0 = svadd_s32_x(psv_pg4_s32(), "
            "E0_%d, psv_rev32_s32(E3_%d));" % (r, r, r),
            "        svint32_t EE_%d_1 = svadd_s32_x(psv_pg4_s32(), "
            "E1_%d, psv_rev32_s32(E2_%d));" % (r, r, r),
            "        svint32_t EEE_%d = svadd_s32_x(psv_pg4_s32(), "
            "EE_%d_0, psv_rev32_s32(EE_%d_1));" % (r, r, r),
            "        svint32_t EEO_%d = svsub_s32_x(psv_pg4_s32(), "
            "EE_%d_0, psv_rev32_s32(EE_%d_1));" % (r, r, r),
        ])
    for pair, r0, r1 in ((0, 0, 1), (1, 2, 3)):
        lines.extend([
            "        svint32_t t0_%d = svreinterpret_s32_s64("
            "svzip1_s64(svreinterpret_s64_s32(EEE_%d), "
            "svreinterpret_s64_s32(EEE_%d)));" % (pair, r0, r1),
            "        svint32_t z2_%d = svreinterpret_s32_s64("
            "svzip2_s64(svreinterpret_s64_s32(EEE_%d), "
            "svreinterpret_s64_s32(EEE_%d)));" % (pair, r0, r1),
            "        svint32_t EEEE_%d = svadd_s32_x(psv_pg4_s32(), "
            "t0_%d, psv_rev64_s32(z2_%d));" % (pair, pair, pair),
            "        svint32_t EEEO_%d = svsub_s32_x(psv_pg4_s32(), "
            "t0_%d, psv_rev64_s32(z2_%d));" % (pair, pair, pair),
        ])
    lines.append("")
    # k odd: two dot segments per row
    lines.extend([
        "        for (int k = 1; k < 32; k += 2)",
        "        {",
        "            const svint16_t cA = psv_load8(GT32A[k]);",
        "            const svint16_t cB = psv_load8(GT32B[k]);",
        "            svint64_t t0 = psv_sdot(psv_zero_s64(), cA, O_0_0);",
        "            t0 = psv_sdot(t0, cB, O_0_1);",
        "            svint64_t t1 = psv_sdot(psv_zero_s64(), cA, O_1_0);",
        "            t1 = psv_sdot(t1, cB, O_1_1);",
        "            svint64_t t2 = psv_sdot(psv_zero_s64(), cA, O_2_0);",
        "            t2 = psv_sdot(t2, cB, O_2_1);",
        "            svint64_t t3 = psv_sdot(psv_zero_s64(), cA, O_3_0);",
        "            t3 = psv_sdot(t3, cB, O_3_1);",
        "            const svint32_t t01 = psv_combine4_s32("
        "psv_vmovn_s64(t0), psv_vmovn_s64(t1));",
        "            const svint32_t t23 = psv_combine4_s32("
        "psv_vmovn_s64(t2), psv_vmovn_s64(t3));",
        "            svint16_t nn = psv_rshrn_s32<shift>("
        "psv_addp4_s32(t01, t23));",
        "            psv_store4_s16(dst + 32 * k + i, nn);",
        "        }",
        "",
        "        for (int k = 2; k < 32; k += 4)",
        "        {",
        "            const svint16_t c = psv_load8(GT32A[k]);",
        "            svint64_t t0 = psv_sdot(psv_zero_s64(), c, EO_0);",
        "            svint64_t t1 = psv_sdot(psv_zero_s64(), c, EO_1);",
        "            svint64_t t2 = psv_sdot(psv_zero_s64(), c, EO_2);",
        "            svint64_t t3 = psv_sdot(psv_zero_s64(), c, EO_3);",
        "            const svint32_t t01 = psv_combine4_s32("
        "psv_vmovn_s64(t0), psv_vmovn_s64(t1));",
        "            const svint32_t t23 = psv_combine4_s32("
        "psv_vmovn_s64(t2), psv_vmovn_s64(t3));",
        "            svint16_t nn = psv_rshrn_s32<shift>("
        "psv_addp4_s32(t01, t23));",
        "            psv_store4_s16(dst + 32 * k + i, nn);",
        "        }",
        "",
        "        for (int k = 4; k < 32; k += 8)",
        "        {",
        "            const svint32_t c = psv_load4_s32(K4[(k - 4) / 8]);",
        "            svint32_t m0 = svmul_s32_x(psv_pg4_s32(), c, EEO_0);",
        "            svint32_t m1 = svmul_s32_x(psv_pg4_s32(), c, EEO_1);",
        "            svint32_t m2 = svmul_s32_x(psv_pg4_s32(), c, EEO_2);",
        "            svint32_t m3 = svmul_s32_x(psv_pg4_s32(), c, EEO_3);",
        "            svint32_t t = psv_addp4_s32("
        "psv_addp4_s32(m0, m1), psv_addp4_s32(m2, m3));",
        "            svint16_t nn = psv_rshrn_s32<shift>(t);",
        "            psv_store4_s16(dst + 32 * k + i, nn);",
        "        }",
        "",
    ])
    for idx, (k, which, mul_first) in enumerate(
            ((0, "EEEE", False), (8, "EEEO", True),
             (16, "EEEE", True), (24, "EEEO", True))):
        lines.extend([
            "        {",
            "            const svint32_t c = psv_load4_s32(T8E[%d]);"
            % idx,
        ])
        if mul_first:
            lines.extend([
                "            svint32_t m0 = svmul_s32_x(psv_pg4_s32(), "
                "c, %s_0);" % which,
                "            svint32_t m1 = svmul_s32_x(psv_pg4_s32(), "
                "c, %s_1);" % which,
                "            svint32_t m = psv_addp4_s32(m0, m1);",
            ])
        else:
            lines.extend([
                "            svint32_t pp = psv_addp4_s32(%s_0, %s_1);"
                % (which, which),
                "            svint32_t m = svmul_s32_x(psv_pg4_s32(), "
                "c, pp);",
            ])
        lines.extend([
            "            svint16_t nn = psv_rshrn_s32<shift>(m);",
            "            psv_store4_s16(dst + 32 * %d + i, nn);" % k,
            "        }",
        ])
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def emit_quarter_pass2_neon16(coefs: Dict[str, List[List[int]]],
                              fn: str = "quarter_pass2_neon16",
                              include_coefs: bool = True,
                              include_header: bool = True) -> str:
    """NEON dct16 fused-quarter pass2: per-row s32 EO (EO*_a/_b),
    k-odd vmull/vmlal, k2 s32 mul+vpadd (first-4 coeffs widened),
    even T8E family; shift=10, square line strides."""
    arrays = coef_c_arrays(coefs) if include_coefs else ""
    lines = [
        "// Generated by ago.templates.butterfly_quarter (P4) -- "
        "dct16 fused-quarter pass2 (NEON target).",
        "#include <arm_neon.h>",
        "#include <cstdint>",
        "",
        arrays,
        "",
        _NEON_HEADER if include_header else "",
        "",
        "static inline void %s(const int16_t* src, int16_t* dst)" % fn,
        "{",
        "    const int shift = 10;",
        "    const int line = 16;",
        "    for (int i = 0; i < line; i += 4)",
        "    {",
    ]
    for r in range(4):
        lines.extend([
            "        int16x8_t s%d_lo = vld1q_s16(src + (i + %d) * "
            "line);" % (r, r),
            "        int16x8_t s%d_hi = dq_rev16(vld1q_s16("
            "src + (i + %d) * line + 8));" % (r, r),
            "        int16x8_t O%d = vsubq_s16(s%d_lo, s%d_hi);"
            % (r, r, r),
            "        int32x4_t s%d_0 = vaddl_s16(vget_low_s16(s%d_lo), "
            "vget_low_s16(s%d_hi));" % (r, r, r),
            "        int32x4_t s%d_1 = vaddl_s16(vget_high_s16(s%d_lo), "
            "vget_high_s16(s%d_hi));" % (r, r, r),
        ])
    lines.extend([
        "        int32x4_t EO0_a = vsubq_s32(s0_0, dq_rev32(s0_1));",
        "        int32x4_t EO0_b = vsubq_s32(s1_0, dq_rev32(s1_1));",
        "        int32x4_t EO1_a = vsubq_s32(s2_0, dq_rev32(s2_1));",
        "        int32x4_t EO1_b = vsubq_s32(s3_0, dq_rev32(s3_1));",
        "        int32x4_t EEE0 = vaddq_s32("
        "vreinterpretq_s32_s64(vzip1q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(s0_0, dq_rev32(s0_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(s1_0, dq_rev32(s1_1))))), "
        "vrev64q_s32(vreinterpretq_s32_s64(vzip2q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(s0_0, dq_rev32(s0_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(s1_0, dq_rev32(s1_1)))))));",
        "        int32x4_t EEO0 = vsubq_s32("
        "vreinterpretq_s32_s64(vzip1q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(s0_0, dq_rev32(s0_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(s1_0, dq_rev32(s1_1))))), "
        "vrev64q_s32(vreinterpretq_s32_s64(vzip2q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(s0_0, dq_rev32(s0_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(s1_0, dq_rev32(s1_1)))))));",
        "        int32x4_t EEE1 = vaddq_s32("
        "vreinterpretq_s32_s64(vzip1q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(s2_0, dq_rev32(s2_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(s3_0, dq_rev32(s3_1))))), "
        "vrev64q_s32(vreinterpretq_s32_s64(vzip2q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(s2_0, dq_rev32(s2_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(s3_0, dq_rev32(s3_1)))))));",
        "        int32x4_t EEO1 = vsubq_s32("
        "vreinterpretq_s32_s64(vzip1q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(s2_0, dq_rev32(s2_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(s3_0, dq_rev32(s3_1))))), "
        "vrev64q_s32(vreinterpretq_s32_s64(vzip2q_s64("
        "vreinterpretq_s64_s32(vaddq_s32(s2_0, dq_rev32(s2_1))), "
        "vreinterpretq_s64_s32(vaddq_s32(s3_0, dq_rev32(s3_1)))))));",
        "",
    ])
    lines.extend([
        "        for (int k = 1; k < 16; k += 2)",
        "        {",
        "            int16x8_t c = vld1q_s16(GT[k]);",
        "            int32x4_t a0 = vmull_s16(vget_low_s16(c), "
        "vget_low_s16(O0));",
        "            a0 = vmlal_s16(a0, vget_high_s16(c), "
        "vget_high_s16(O0));",
        "            int32x4_t a1 = vmull_s16(vget_low_s16(c), "
        "vget_low_s16(O1));",
        "            a1 = vmlal_s16(a1, vget_high_s16(c), "
        "vget_high_s16(O1));",
        "            int32x4_t a2 = vmull_s16(vget_low_s16(c), "
        "vget_low_s16(O2));",
        "            a2 = vmlal_s16(a2, vget_high_s16(c), "
        "vget_high_s16(O2));",
        "            int32x4_t a3 = vmull_s16(vget_low_s16(c), "
        "vget_low_s16(O3));",
        "            a3 = vmlal_s16(a3, vget_high_s16(c), "
        "vget_high_s16(O3));",
        "            int16x4_t res = vrshrn_n_s32(vpaddq_s32("
        "vpaddq_s32(a0, a1), vpaddq_s32(a2, a3)), shift);",
        "            vst1_s16(dst + 16 * k + i, res);",
        "        }",
        "",
        "        for (int k = 2; k < 16; k += 4)",
        "        {",
        "            int32x4_t c0 = vmovl_s16(vld1_s16("
        "GT16S16[(k - 2) / 4]));",
        "            int32x4_t t = vpaddq_s32(vpaddq_s32("
        "vmulq_s32(c0, EO0_a), vmulq_s32(c0, EO0_b)), "
        "vpaddq_s32(vmulq_s32(c0, EO1_a), vmulq_s32(c0, EO1_b)));",
        "            int16x4_t res = vrshrn_n_s32(t, shift);",
        "            vst1_s16(dst + 16 * k + i, res);",
        "        }",
        "",
    ])
    for idx, (k, which, mul_first) in enumerate(
            ((0, "EEE", False), (4, "EEO", True),
             (8, "EEE", True), (12, "EEO", True))):
        lines.extend([
            "        {",
            "            int32x4_t c = vld1q_s32(T8E[%d]);" % idx,
        ])
        if mul_first:
            lines.extend([
                "            int32x4_t m = vpaddq_s32("
                "vmulq_s32(c, %s0), vmulq_s32(c, %s1));"
                % (which, which),
            ])
        else:
            lines.extend([
                "            int32x4_t m = vmulq_s32(c, "
                "vpaddq_s32(%s0, %s1));" % (which, which),
            ])
        lines.extend([
            "            int16x4_t res = vrshrn_n_s32(m, shift);",
            "            vst1_s16(dst + 16 * %d + i, res);" % k,
            "        }",
        ])
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def emit_quarter_pass32_neon(coefs: Dict[str, List[List[int]]],
                             fn: str = "quarter_pass1_32_neon",
                             include_coefs: bool = True,
                             include_header: bool = True) -> str:
    """NEON dct32 fused-quarter pass1 (4 chunks/row; mirrors
    kernels/dct32/candidates/best_neon_vl128.cpp pass1Butterfly32_sve:
    vmull/vmlal + vpadd for odd/k2, vmul for k4/even)."""
    arrays = coef_c_arrays(coefs) if include_coefs else ""
    lines = [
        "// Generated by ago.templates.butterfly_quarter (P4) -- "
        "dct32 fused-quarter pass1 (NEON target).",
        "#include <arm_neon.h>",
        "#include <cstdint>",
        "",
        arrays,
        "",
        _NEON_HEADER if include_header else "",
        "",
        "static inline void %s(const int16_t* src, int16_t* dst, "
        "intptr_t stride)" % fn,
        "{",
        "    const int shift = 4;",
        "    const int line = 32;",
        "    for (int i = 0; i < line; i += 4)",
        "    {",
    ]
    for r in range(4):
        lines.extend([
            "        int16x8x4_t in_%d = vld1q_s16_x4("
            "src + (i + %d) * stride);" % (r, r),
            "        in_%d.val[2] = dq_rev16(in_%d.val[2]);"
            % (r, r),
            "        in_%d.val[3] = dq_rev16(in_%d.val[3]);"
            % (r, r),
            "        int16x8_t O%d_0 = vsubq_s16(in_%d.val[0], "
            "in_%d.val[3]);" % (r, r, r),
            "        int16x8_t O%d_1 = vsubq_s16(in_%d.val[1], "
            "in_%d.val[2]);" % (r, r, r),
            "        int32x4_t E%d_0 = vaddl_s16("
            "vget_low_s16(in_%d.val[0]), vget_low_s16(in_%d.val[3]));"
            % (r, r, r),
            "        int32x4_t E%d_1 = vaddl_s16("
            "vget_high_s16(in_%d.val[0]), "
            "vget_high_s16(in_%d.val[3]));" % (r, r, r),
            "        int32x4_t E%d_2 = vaddl_s16("
            "vget_low_s16(in_%d.val[1]), vget_low_s16(in_%d.val[2]));"
            % (r, r, r),
            "        int32x4_t E%d_3 = vaddl_s16("
            "vget_high_s16(in_%d.val[1]), "
            "vget_high_s16(in_%d.val[2]));" % (r, r, r),
            "        int16x8_t EO%d = vcombine_s16("
            "vmovn_s32(vsubq_s32(E%d_0, dq_rev32(E%d_3))), "
            "vmovn_s32(vsubq_s32(E%d_1, dq_rev32(E%d_2))));"
            % (r, r, r, r, r),
            "        int32x4_t EE%d_0 = vaddq_s32(E%d_0, "
            "dq_rev32(E%d_3));" % (r, r, r),
            "        int32x4_t EE%d_1 = vaddq_s32(E%d_1, "
            "dq_rev32(E%d_2));" % (r, r, r),
            "        int32x4_t EEE%d = vaddq_s32(EE%d_0, "
            "dq_rev32(EE%d_1));" % (r, r, r),
            "        int32x4_t EEO%d = vsubq_s32(EE%d_0, "
            "dq_rev32(EE%d_1));" % (r, r, r),
        ])
    for pair, r0, r1 in ((0, 0, 1), (1, 2, 3)):
        lines.extend([
            "        int32x4_t t%d_0 = vreinterpretq_s32_s64("
            "vzip1q_s64(vreinterpretq_s64_s32(EEE%d), "
            "vreinterpretq_s64_s32(EEE%d)));" % (pair, r0, r1),
            "        int32x4_t t%d_1 = vrev64q_s32("
            "vreinterpretq_s32_s64(vzip2q_s64("
            "vreinterpretq_s64_s32(EEE%d), "
            "vreinterpretq_s64_s32(EEE%d))));" % (pair, r0, r1),
            "        int32x4_t EEEE%d = vaddq_s32(t%d_0, t%d_1);"
            % (pair, pair, pair),
            "        int32x4_t EEEO%d = vsubq_s32(t%d_0, t%d_1);"
            % (pair, pair, pair),
        ])
    lines.append("")
    lines.extend([
        "        for (int k = 1; k < 32; k += 2)",
        "        {",
        "            int16x8_t c0_c1 = vld1q_s16(GT32A[k]);",
        "            int16x8_t c2_c3 = vld1q_s16(GT32B[k]);",
    ])
    for r in range(4):
        lines.extend([
            "            int32x4_t a%d = vmull_s16("
            "vget_low_s16(c0_c1), vget_low_s16(O%d_0));" % (r, r),
            "            a%d = vmlal_s16(a%d, vget_high_s16(c0_c1), "
            "vget_high_s16(O%d_0));" % (r, r, r),
            "            int32x4_t b%d = vmull_s16("
            "vget_low_s16(c2_c3), vget_low_s16(O%d_1));" % (r, r),
            "            b%d = vmlal_s16(b%d, vget_high_s16(c2_c3), "
            "vget_high_s16(O%d_1));" % (r, r, r),
        ])
    lines.extend([
        "            int32x4_t r0 = vpaddq_s32(a0, b0);",
        "            int32x4_t r1 = vpaddq_s32(a1, b1);",
        "            int32x4_t r2 = vpaddq_s32(a2, b2);",
        "            int32x4_t r3 = vpaddq_s32(a3, b3);",
        "            int16x4_t res = vrshrn_n_s32(vpaddq_s32("
        "vpaddq_s32(r0, r1), vpaddq_s32(r2, r3)), shift);",
        "            vst1_s16(dst + 32 * k + i, res);",
        "        }",
        "",
        "        for (int k = 2; k < 32; k += 4)",
        "        {",
        "            int16x8_t c0 = vld1q_s16(GT32A[k]);",
    ])
    for r in range(4):
        lines.extend([
            "            int32x4_t a%d = vmull_s16("
            "vget_low_s16(c0), vget_low_s16(EO%d));" % (r, r),
            "            a%d = vmlal_s16(a%d, vget_high_s16(c0), "
            "vget_high_s16(EO%d));" % (r, r, r),
        ])
    lines.extend([
        "            int16x4_t res = vrshrn_n_s32(vpaddq_s32("
        "vpaddq_s32(a0, a1), vpaddq_s32(a2, a3)), shift);",
        "            vst1_s16(dst + 32 * k + i, res);",
        "        }",
        "",
        "        for (int k = 4; k < 32; k += 8)",
        "        {",
        "            int32x4_t c = vmovl_s16(vld1_s16("
        "K4S16[(k - 4) / 8]));",
        "            int16x4_t res = vrshrn_n_s32(vpaddq_s32("
        "vpaddq_s32(vmulq_s32(c, EEO0), vmulq_s32(c, EEO1)), "
        "vpaddq_s32(vmulq_s32(c, EEO2), vmulq_s32(c, EEO3))), shift);",
        "            vst1_s16(dst + 32 * k + i, res);",
        "        }",
        "",
    ])
    for idx, (k, which, mul_first) in enumerate(
            ((0, "EEEE", False), (8, "EEEO", True),
             (16, "EEEE", True), (24, "EEEO", True))):
        lines.extend([
            "        {",
            "            int32x4_t c = vld1q_s32(T8E[%d]);" % idx,
        ])
        if mul_first:
            lines.extend([
                "            int32x4_t m = vpaddq_s32("
                "vmulq_s32(c, %s0), vmulq_s32(c, %s1));"
                % (which, which),
            ])
        else:
            lines.extend([
                "            int32x4_t m = vmulq_s32(c, "
                "vpaddq_s32(%s0, %s1));" % (which, which),
            ])
        lines.extend([
            "            int16x4_t res = vrshrn_n_s32(m, shift);",
            "            vst1_s16(dst + 32 * %d + i, res);" % k,
            "        }",
        ])
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def emit_quarter_pass2_neon32(coefs: Dict[str, List[List[int]]],
                              fn: str = "quarter_pass2_32_neon",
                              include_coefs: bool = True,
                              include_header: bool = True) -> str:
    """NEON dct32 fused-quarter pass2 (mirrors pass2Butterfly32_sve:
    dual per-row s32 EO, k-odd double vmull/vmlal, k2 dual s32 mla,
    k4 vmul, even EEEE/EEEO; shift=11)."""
    arrays = coef_c_arrays(coefs) if include_coefs else ""
    lines = [
        "// Generated by ago.templates.butterfly_quarter (P4) -- "
        "dct32 fused-quarter pass2 (NEON target).",
        "#include <arm_neon.h>",
        "#include <cstdint>",
        "",
        arrays,
        "",
        _NEON_HEADER if include_header else "",
        "",
        "static inline void %s(const int16_t* src, int16_t* dst)" % fn,
        "{",
        "    const int shift = 11;",
        "    const int line = 32;",
        "    for (int i = 0; i < line; i += 4)",
        "    {",
    ]
    for r in range(4):
        lines.extend([
            "        int16x8x4_t in_%d = vld1q_s16_x4("
            "src + (i + %d) * line);" % (r, r),
            "        in_%d.val[2] = dq_rev16(in_%d.val[2]);"
            % (r, r),
            "        in_%d.val[3] = dq_rev16(in_%d.val[3]);"
            % (r, r),
            "        int16x8_t O%d_0 = vsubq_s16(in_%d.val[0], "
            "in_%d.val[3]);" % (r, r, r),
            "        int16x8_t O%d_1 = vsubq_s16(in_%d.val[1], "
            "in_%d.val[2]);" % (r, r, r),
            "        int32x4_t E%d_0 = vaddl_s16("
            "vget_low_s16(in_%d.val[0]), vget_low_s16(in_%d.val[3]));"
            % (r, r, r),
            "        int32x4_t E%d_1 = vaddl_s16("
            "vget_high_s16(in_%d.val[0]), "
            "vget_high_s16(in_%d.val[3]));" % (r, r, r),
            "        int32x4_t E%d_2 = vaddl_s16("
            "vget_low_s16(in_%d.val[1]), vget_low_s16(in_%d.val[2]));"
            % (r, r, r),
            "        int32x4_t E%d_3 = vaddl_s16("
            "vget_high_s16(in_%d.val[1]), "
            "vget_high_s16(in_%d.val[2]));" % (r, r, r),
            "        int32x4_t EO%d_0 = vsubq_s32(E%d_0, "
            "dq_rev32(E%d_3));" % (r, r, r),
            "        int32x4_t EO%d_1 = vsubq_s32(E%d_1, "
            "dq_rev32(E%d_2));" % (r, r, r),
            "        int32x4_t EE%d_0 = vaddq_s32(E%d_0, "
            "dq_rev32(E%d_3));" % (r, r, r),
            "        int32x4_t EE%d_1 = vaddq_s32(E%d_1, "
            "dq_rev32(E%d_2));" % (r, r, r),
            "        int32x4_t EEE%d = vaddq_s32(EE%d_0, "
            "dq_rev32(EE%d_1));" % (r, r, r),
            "        int32x4_t EEO%d = vsubq_s32(EE%d_0, "
            "dq_rev32(EE%d_1));" % (r, r, r),
        ])
    for pair, r0, r1 in ((0, 0, 1), (1, 2, 3)):
        lines.extend([
            "        int32x4_t t%d_0 = vreinterpretq_s32_s64("
            "vzip1q_s64(vreinterpretq_s64_s32(EEE%d), "
            "vreinterpretq_s64_s32(EEE%d)));" % (pair, r0, r1),
            "        int32x4_t t%d_1 = vrev64q_s32("
            "vreinterpretq_s32_s64(vzip2q_s64("
            "vreinterpretq_s64_s32(EEE%d), "
            "vreinterpretq_s64_s32(EEE%d))));" % (pair, r0, r1),
            "        int32x4_t EEEE%d = vaddq_s32(t%d_0, t%d_1);"
            % (pair, pair, pair),
            "        int32x4_t EEEO%d = vsubq_s32(t%d_0, t%d_1);"
            % (pair, pair, pair),
        ])
    lines.append("")
    lines.extend([
        "        for (int k = 1; k < 32; k += 2)",
        "        {",
        "            int16x8_t c0_c1 = vld1q_s16(GT32A[k]);",
        "            int16x8_t c2_c3 = vld1q_s16(GT32B[k]);",
    ])
    for r in range(4):
        lines.extend([
            "            int32x4_t a%d = vmull_s16("
            "vget_low_s16(c0_c1), vget_low_s16(O%d_0));" % (r, r),
            "            a%d = vmlal_s16(a%d, vget_high_s16(c0_c1), "
            "vget_high_s16(O%d_0));" % (r, r, r),
            "            int32x4_t b%d = vmull_s16("
            "vget_low_s16(c2_c3), vget_low_s16(O%d_1));" % (r, r),
            "            b%d = vmlal_s16(b%d, vget_high_s16(c2_c3), "
            "vget_high_s16(O%d_1));" % (r, r, r),
        ])
    lines.extend([
        "            int32x4_t r0 = vpaddq_s32(a0, b0);",
        "            int32x4_t r1 = vpaddq_s32(a1, b1);",
        "            int32x4_t r2 = vpaddq_s32(a2, b2);",
        "            int32x4_t r3 = vpaddq_s32(a3, b3);",
        "            int16x4_t res = vrshrn_n_s32(vpaddq_s32("
        "vpaddq_s32(r0, r1), vpaddq_s32(r2, r3)), shift);",
        "            vst1_s16(dst + 32 * k + i, res);",
        "        }",
        "",
        "        for (int k = 2; k < 32; k += 4)",
        "        {",
        "            int32x4_t c0 = vmovl_s16(vld1_s16("
        "K2S16A[(k - 2) / 4]));",
        "            int32x4_t c1 = vmovl_s16(vld1_s16("
        "K2S16B[(k - 2) / 4]));",
    ])
    for r in range(4):
        lines.extend([
            "            int32x4_t t%d = vmulq_s32(c0, EO%d_0);"
            % (r, r),
            "            t%d = vmlaq_s32(t%d, c1, EO%d_1);"
            % (r, r, r),
        ])
    lines.extend([
        "            int16x4_t res = vrshrn_n_s32(vpaddq_s32("
        "vpaddq_s32(t0, t1), vpaddq_s32(t2, t3)), shift);",
        "            vst1_s16(dst + 32 * k + i, res);",
        "        }",
        "",
        "        for (int k = 4; k < 32; k += 8)",
        "        {",
        "            int32x4_t c = vmovl_s16(vld1_s16("
        "K4S16[(k - 4) / 8]));",
        "            int16x4_t res = vrshrn_n_s32(vpaddq_s32("
        "vpaddq_s32(vmulq_s32(c, EEO0), vmulq_s32(c, EEO1)), "
        "vpaddq_s32(vmulq_s32(c, EEO2), vmulq_s32(c, EEO3))), shift);",
        "            vst1_s16(dst + 32 * k + i, res);",
        "        }",
        "",
    ])
    for idx, (k, which, mul_first) in enumerate(
            ((0, "EEEE", False), (8, "EEEO", True),
             (16, "EEEE", True), (24, "EEEO", True))):
        lines.extend([
            "        {",
            "            int32x4_t c = vld1q_s32(T8E[%d]);" % idx,
        ])
        if mul_first:
            lines.extend([
                "            int32x4_t m = vpaddq_s32("
                "vmulq_s32(c, %s0), vmulq_s32(c, %s1));"
                % (which, which),
            ])
        else:
            lines.extend([
                "            int32x4_t m = vmulq_s32(c, "
                "vpaddq_s32(%s0, %s1));" % (which, which),
            ])
        lines.extend([
            "            int16x4_t res = vrshrn_n_s32(m, shift);",
            "            vst1_s16(dst + 32 * %d + i, res);" % k,
            "        }",
        ])
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def emit_quarter_pass2_16(coefs: Dict[str, List[List[int]]],
                          fn: str = "quarter_pass2_16",
                          include_coefs: bool = True) -> str:
    """Complete dct16-style fused-quarter pass2: per-row s32 EO,
    k-odd sdot over O, k=2 mod4 s32 mul+addp over EO, even T8E
    family; shift=10, square line strides (pass1 coef buffer)."""
    arrays = coef_c_arrays(coefs) if include_coefs else ""
    lines = [
        "// Generated by ago.templates.butterfly_quarter (P4) -- "
        "dct16 fused-quarter pass2.",
        "#include <arm_sve.h>",
        "#include <cstdint>",
        "",
        arrays,
        "",
        "static inline void %s(const int16_t* src, int16_t* dst)"
        % fn,
        "{",
        "    const int line = 16;",
        "    const int shift = 10;",
        "    for (int i = 0; i < line; i += 4)",
        "    {",
    ]
    for r in range(4):
        lines.extend([
            "        const svint16_t s%d_lo = psv_load8("
            "src + (i + %d) * line);" % (r, r),
            "        const svint16_t s%d_hi = psv_rev16(psv_load8("
            "src + (i + %d) * line + 8));" % (r, r),
            "        svint16_t O_%d = svsub_s16_x(psv_pg8_s16(), "
            "s%d_lo, s%d_hi);" % (r, r, r),
            "        svint32_t E0_%d = psv_saddl_s16("
            "psv_get_lo4_s16(s%d_lo), psv_get_lo4_s16(s%d_hi));"
            % (r, r, r),
            "        svint32_t E1_%d = psv_saddl_s16("
            "psv_get_hi4_s16(s%d_lo), psv_get_hi4_s16(s%d_hi));"
            % (r, r, r),
            "        svint32_t EO_%d = svsub_s32_x(psv_pg4_s32(), "
            "E0_%d, psv_rev32_s32(E1_%d));" % (r, r, r),
        ])
    for pair, r0, r1 in ((0, 0, 1), (1, 2, 3)):
        e0, e1 = 2 * pair, 2 * pair + 1
        lines.extend([
            "        svint32_t EE_%d = svadd_s32_x(psv_pg4_s32(), "
            "E0_%d, psv_rev32_s32(E1_%d));" % (e0, r0, r0),
            "        svint32_t EE_%d = svadd_s32_x(psv_pg4_s32(), "
            "E0_%d, psv_rev32_s32(E1_%d));" % (e1, r1, r1),
            "        svint32_t t0_%d = svreinterpret_s32_s64("
            "svzip1_s64(svreinterpret_s64_s32(EE_%d), "
            "svreinterpret_s64_s32(EE_%d)));" % (pair, e0, e1),
            "        svint32_t z2_%d = svreinterpret_s32_s64("
            "svzip2_s64(svreinterpret_s64_s32(EE_%d), "
            "svreinterpret_s64_s32(EE_%d)));" % (pair, e0, e1),
            "        svint32_t EEE_%d = svadd_s32_x(psv_pg4_s32(), "
            "t0_%d, psv_rev64_s32(z2_%d));" % (pair, pair, pair),
            "        svint32_t EEO_%d = svsub_s32_x(psv_pg4_s32(), "
            "t0_%d, psv_rev64_s32(z2_%d));" % (pair, pair, pair),
        ])
    lines.append("")
    lines.extend([
        "        for (int k = 1; k < 16; k += 2)",
        "        {",
        "            const svint16_t c = psv_load8(GT[k]);",
        "            svint64_t t0 = psv_sdot(psv_zero_s64(), c, O_0);",
        "            svint64_t t1 = psv_sdot(psv_zero_s64(), c, O_1);",
        "            svint64_t t2 = psv_sdot(psv_zero_s64(), c, O_2);",
        "            svint64_t t3 = psv_sdot(psv_zero_s64(), c, O_3);",
        "            const svint32_t t01 = psv_combine4_s32("
        "psv_vmovn_s64(t0), psv_vmovn_s64(t1));",
        "            const svint32_t t23 = psv_combine4_s32("
        "psv_vmovn_s64(t2), psv_vmovn_s64(t3));",
        "            svint16_t nn = psv_rshrn_s32<shift>("
        "psv_addp4_s32(t01, t23));",
        "            psv_store4_s16(dst + 16 * k + i, nn);",
        "        }",
        "",
        "        for (int k = 2; k < 16; k += 4)",
        "        {",
        "            const svint32_t c = psv_load4_s32("
        "GT16S32[(k - 2) / 4]);",
        "            svint32_t m0 = svmul_s32_x(psv_pg4_s32(), c, EO_0);",
        "            svint32_t m1 = svmul_s32_x(psv_pg4_s32(), c, EO_1);",
        "            svint32_t m2 = svmul_s32_x(psv_pg4_s32(), c, EO_2);",
        "            svint32_t m3 = svmul_s32_x(psv_pg4_s32(), c, EO_3);",
        "            svint32_t t = psv_addp4_s32("
        "psv_addp4_s32(m0, m1), psv_addp4_s32(m2, m3));",
        "            svint16_t nn = psv_rshrn_s32<shift>(t);",
        "            psv_store4_s16(dst + 16 * k + i, nn);",
        "        }",
        "",
    ])
    for idx, (k, which, mul_first) in enumerate(
            ((0, "EEE", False), (4, "EEO", True),
             (8, "EEE", True), (12, "EEO", True))):
        lines.extend([
            "        {",
            "            const svint32_t c = psv_load4_s32(T8E[%d]);"
            % idx,
        ])
        if mul_first:
            lines.extend([
                "            svint32_t m0 = svmul_s32_x(psv_pg4_s32(), "
                "c, %s_0);" % which,
                "            svint32_t m1 = svmul_s32_x(psv_pg4_s32(), "
                "c, %s_1);" % which,
                "            svint32_t m = psv_addp4_s32(m0, m1);",
            ])
        else:
            lines.extend([
                "            svint32_t pp = psv_addp4_s32(%s_0, %s_1);"
                % (which, which),
                "            svint32_t m = svmul_s32_x(psv_pg4_s32(), "
                "c, pp);",
            ])
        lines.extend([
            "            svint16_t nn = psv_rshrn_s32<shift>(m);",
            "            psv_store4_s16(dst + 16 * %d + i, nn);" % k,
            "        }",
        ])
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def emit_quarter_pass2_32(coefs: Dict[str, List[List[int]]],
                          fn: str = "quarter_pass2_32",
                          include_coefs: bool = True) -> str:
    """Complete dct32 fused-quarter pass2: per-row dual s32 EO,
    k-odd double sdot, k2 dual mla (GT32S32A/B), k4 mul (K4),
    even EEEE/EEEO; shift=11."""
    arrays = coef_c_arrays(coefs) if include_coefs else ""
    lines = [
        "// Generated by ago.templates.butterfly_quarter (P4) -- "
        "dct32 fused-quarter pass2.",
        "#include <arm_sve.h>",
        "#include <cstdint>",
        "",
        arrays,
        "",
        "static inline void %s(const int16_t* src, int16_t* dst)"
        % fn,
        "{",
        "    const int line = 32;",
        "    const int shift = 11;",
        "    for (int i = 0; i < line; i += 4)",
        "    {",
    ]
    for r in range(4):
        lines.extend([
            "        const svint16_t r%d_v0 = psv_load8("
            "src + (i + %d) * line + 0);" % (r, r),
            "        const svint16_t r%d_v1 = psv_load8("
            "src + (i + %d) * line + 8);" % (r, r),
            "        const svint16_t r%d_v2r = psv_rev16(psv_load8("
            "src + (i + %d) * line + 16));" % (r, r),
            "        const svint16_t r%d_v3r = psv_rev16(psv_load8("
            "src + (i + %d) * line + 24));" % (r, r),
            "        svint16_t O_%d_0 = svsub_s16_x(psv_pg8_s16(), "
            "r%d_v0, r%d_v3r);" % (r, r, r),
            "        svint16_t O_%d_1 = svsub_s16_x(psv_pg8_s16(), "
            "r%d_v1, r%d_v2r);" % (r, r, r),
            "        svint32_t E0_%d = psv_saddl_s16("
            "psv_get_lo4_s16(r%d_v0), psv_get_lo4_s16(r%d_v3r));"
            % (r, r, r),
            "        svint32_t E1_%d = psv_saddl_s16("
            "psv_get_hi4_s16(r%d_v0), psv_get_hi4_s16(r%d_v3r));"
            % (r, r, r),
            "        svint32_t E2_%d = psv_saddl_s16("
            "psv_get_lo4_s16(r%d_v1), psv_get_lo4_s16(r%d_v2r));"
            % (r, r, r),
            "        svint32_t E3_%d = psv_saddl_s16("
            "psv_get_hi4_s16(r%d_v1), psv_get_hi4_s16(r%d_v2r));"
            % (r, r, r),
            "        svint32_t EO_%d_0 = svsub_s32_x(psv_pg4_s32(), "
            "E0_%d, psv_rev32_s32(E3_%d));" % (r, r, r),
            "        svint32_t EO_%d_1 = svsub_s32_x(psv_pg4_s32(), "
            "E1_%d, psv_rev32_s32(E2_%d));" % (r, r, r),
            "        svint32_t EE_%d_0 = svadd_s32_x(psv_pg4_s32(), "
            "E0_%d, psv_rev32_s32(E3_%d));" % (r, r, r),
            "        svint32_t EE_%d_1 = svadd_s32_x(psv_pg4_s32(), "
            "E1_%d, psv_rev32_s32(E2_%d));" % (r, r, r),
            "        svint32_t EEE_%d = svadd_s32_x(psv_pg4_s32(), "
            "EE_%d_0, psv_rev32_s32(EE_%d_1));" % (r, r, r),
            "        svint32_t EEO_%d = svsub_s32_x(psv_pg4_s32(), "
            "EE_%d_0, psv_rev32_s32(EE_%d_1));" % (r, r, r),
        ])
    for pair, r0, r1 in ((0, 0, 1), (1, 2, 3)):
        lines.extend([
            "        svint32_t t0_%d = svreinterpret_s32_s64("
            "svzip1_s64(svreinterpret_s64_s32(EEE_%d), "
            "svreinterpret_s64_s32(EEE_%d)));" % (pair, r0, r1),
            "        svint32_t z2_%d = svreinterpret_s32_s64("
            "svzip2_s64(svreinterpret_s64_s32(EEE_%d), "
            "svreinterpret_s64_s32(EEE_%d)));" % (pair, r0, r1),
            "        svint32_t EEEE_%d = svadd_s32_x(psv_pg4_s32(), "
            "t0_%d, psv_rev64_s32(z2_%d));" % (pair, pair, pair),
            "        svint32_t EEEO_%d = svsub_s32_x(psv_pg4_s32(), "
            "t0_%d, psv_rev64_s32(z2_%d));" % (pair, pair, pair),
        ])
    lines.append("")
    lines.extend([
        "        for (int k = 1; k < 32; k += 2)",
        "        {",
        "            const svint16_t cA = psv_load8(GT32A[k]);",
        "            const svint16_t cB = psv_load8(GT32B[k]);",
        "            svint64_t t0 = psv_sdot(psv_zero_s64(), cA, O_0_0);",
        "            t0 = psv_sdot(t0, cB, O_0_1);",
        "            svint64_t t1 = psv_sdot(psv_zero_s64(), cA, O_1_0);",
        "            t1 = psv_sdot(t1, cB, O_1_1);",
        "            svint64_t t2 = psv_sdot(psv_zero_s64(), cA, O_2_0);",
        "            t2 = psv_sdot(t2, cB, O_2_1);",
        "            svint64_t t3 = psv_sdot(psv_zero_s64(), cA, O_3_0);",
        "            t3 = psv_sdot(t3, cB, O_3_1);",
        "            const svint32_t t01 = psv_combine4_s32("
        "psv_vmovn_s64(t0), psv_vmovn_s64(t1));",
        "            const svint32_t t23 = psv_combine4_s32("
        "psv_vmovn_s64(t2), psv_vmovn_s64(t3));",
        "            svint16_t nn = psv_rshrn_s32<shift>("
        "psv_addp4_s32(t01, t23));",
        "            psv_store4_s16(dst + 32 * k + i, nn);",
        "        }",
        "",
        "        for (int k = 2; k < 32; k += 4)",
        "        {",
        "            const svint32_t cA = psv_load4_s32("
        "GT32S32A[(k - 2) / 4]);",
        "            const svint32_t cB = psv_load4_s32("
        "GT32S32B[(k - 2) / 4]);",
        "            svint32_t m0 = svmul_s32_x(psv_pg4_s32(), cA, "
        "EO_0_0);",
        "            m0 = svmla_s32_x(psv_pg4_s32(), m0, cB, EO_0_1);",
        "            svint32_t m1 = svmul_s32_x(psv_pg4_s32(), cA, "
        "EO_1_0);",
        "            m1 = svmla_s32_x(psv_pg4_s32(), m1, cB, EO_1_1);",
        "            svint32_t m2 = svmul_s32_x(psv_pg4_s32(), cA, "
        "EO_2_0);",
        "            m2 = svmla_s32_x(psv_pg4_s32(), m2, cB, EO_2_1);",
        "            svint32_t m3 = svmul_s32_x(psv_pg4_s32(), cA, "
        "EO_3_0);",
        "            m3 = svmla_s32_x(psv_pg4_s32(), m3, cB, EO_3_1);",
        "            svint32_t t = psv_addp4_s32("
        "psv_addp4_s32(m0, m1), psv_addp4_s32(m2, m3));",
        "            svint16_t nn = psv_rshrn_s32<shift>(t);",
        "            psv_store4_s16(dst + 32 * k + i, nn);",
        "        }",
        "",
        "        for (int k = 4; k < 32; k += 8)",
        "        {",
        "            const svint32_t c = psv_load4_s32(K4[(k - 4) / 8]);",
        "            svint32_t m0 = svmul_s32_x(psv_pg4_s32(), c, EEO_0);",
        "            svint32_t m1 = svmul_s32_x(psv_pg4_s32(), c, EEO_1);",
        "            svint32_t m2 = svmul_s32_x(psv_pg4_s32(), c, EEO_2);",
        "            svint32_t m3 = svmul_s32_x(psv_pg4_s32(), c, EEO_3);",
        "            svint32_t t = psv_addp4_s32("
        "psv_addp4_s32(m0, m1), psv_addp4_s32(m2, m3));",
        "            svint16_t nn = psv_rshrn_s32<shift>(t);",
        "            psv_store4_s16(dst + 32 * k + i, nn);",
        "        }",
        "",
    ])
    for idx, (k, which, mul_first) in enumerate(
            ((0, "EEEE", False), (8, "EEEO", True),
             (16, "EEEE", True), (24, "EEEO", True))):
        lines.extend([
            "        {",
            "            const svint32_t c = psv_load4_s32(T8E[%d]);"
            % idx,
        ])
        if mul_first:
            lines.extend([
                "            svint32_t m0 = svmul_s32_x(psv_pg4_s32(), "
                "c, %s_0);" % which,
                "            svint32_t m1 = svmul_s32_x(psv_pg4_s32(), "
                "c, %s_1);" % which,
                "            svint32_t m = psv_addp4_s32(m0, m1);",
            ])
        else:
            lines.extend([
                "            svint32_t pp = psv_addp4_s32(%s_0, %s_1);"
                % (which, which),
                "            svint32_t m = svmul_s32_x(psv_pg4_s32(), "
                "c, pp);",
            ])
        lines.extend([
            "            svint16_t nn = psv_rshrn_s32<shift>(m);",
            "            psv_store4_s16(dst + 32 * %d + i, nn);" % k,
            "        }",
        ])
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def _obligations(n: int) -> List[ProofObligation]:
    return [
        ProofObligation("quarter-%d" % n, "differential",
                        {"kind": "fused quarter pass1 vs upstream C dct",
                         "domain": "20k QEMU diff (vq=1, VL=128-fixed) "
                                   "vs golden 8-lane pass1 (which itself "
                                   "passed TestBenchLite multi-seed)",
                         "rounding": "rshrn after each family"}),
    ]


class ButterflyQuarterPattern(Pattern):
    name = "butterfly-quarter"

    def match(self, region):
        # region: (n:int, coefficient_tables:dict[, pass:int])
        if isinstance(region, tuple) and len(region) in (2, 3) \
                and isinstance(region[0], int) and region[0] in (8, 16, 32):
            p = region[2] if len(region) == 3 else 1
            return RuleBinding({"n": region[0], "coefs": region[1],
                                "pass": p})
        return None


class ButterflyQuarterRewrite(RewriteRule):
    id = "butterfly-quarter"
    phase = "fuse-quarter"
    effect = "lo/hi split + O/EO/EE dataflow + three output families"
    measure = "sdot/mul family count per 4-row group"

    def preconditions(self, region, bindings):
        return bindings.values["n"] in (8, 16, 32)

    def apply(self, region, bindings):
        return region, _obligations(region[0])

    def fallback(self, region):
        return region


class ButterflyQuarterTemplate(CoverTemplate):
    id = "butterfly-quarter"
    target = "sve1|sve2"

    def preconditions(self, region, bindings):
        return ButterflyQuarterRewrite().preconditions(region, bindings)

    def emit(self, region, bindings, target="") -> Tuple[str,
                                                          List[ProofObligation]]:
        n = bindings.values["n"]
        coefs = bindings.values["coefs"]
        p = bindings.values.get("pass", 1)
        if p == 2 and n == 16 and target.startswith("neon"):
            src = emit_quarter_pass2_neon16(coefs=coefs)
        elif p == 2 and n == 16:
            src = emit_quarter_pass2_16(coefs=coefs)
        elif p == 2 and n == 32 and target.startswith("neon"):
            src = emit_quarter_pass2_neon32(coefs=coefs)
        elif p == 2 and n == 32:
            src = emit_quarter_pass2_32(coefs=coefs)
        elif n == 32 and target.startswith("neon"):
            src = emit_quarter_pass32_neon(coefs=coefs)
        elif n == 32:
            src = emit_quarter_pass32(coefs=coefs,
                                      target=target or "sve2")
        else:
            src = emit_quarter_pass(n=n, coefs=coefs,
                                    target=target or "sve2")
        return src, \
            _obligations(n)
