"""DFA state-table template for costCoeffRemain (AGO M3, round-0032).

Rewrite: per-coefficient reference formula (branchy scalar)
-> (goRice x phase x value) finite table with inline fallback for
values >= 256. The table is generated from the reference formula, so
the proof obligation is an exhaustive equality over the whole domain
(5 goRice states x 3 phases x 256 values = 3840 entries).
"""

from __future__ import annotations

from typing import List, Tuple

from ago.rules import (  # noqa: E402
    CoverTemplate, Pattern, ProofObligation, RewriteRule, RuleBinding)


def dfa_step(g: int, base: int, v: int) -> Tuple[int, int]:
    """Exactly reproduce one costCoeffRemain_c iteration (dct.cpp)."""
    code = v - base
    if code < 0:
        return (0, g)
    cn = (code >> g) - 3
    if cn < 0:
        add = 4 + g + cn
    else:
        length = (cn + 1).bit_length() - 1
        add = 4 + g + length + length
    ng = g
    if v > (3 << g):
        ng = (g + 1) - (g >> 2)
    return (add, ng)


def phase_base(phase: int) -> int:
    return 3 if phase == 0 else (1 if phase == 2 else 2)


def gen_dfa_tables() -> Tuple[List[int], List[int]]:
    add_tbl: List[int] = []
    nxt_tbl: List[int] = []
    for g in range(5):
        for phase in range(3):
            base = phase_base(phase)
            for v in range(256):
                add, ng = dfa_step(g, base, v)
                add_tbl.append(add)
                nxt_tbl.append(ng)
    return add_tbl, nxt_tbl


def emit_dfa(func_name: str = "dynopt_cost_coeff_remain_sve2") -> str:
    add_tbl, nxt_tbl = gen_dfa_tables()
    add_src = ", ".join(str(x) for x in add_tbl)
    nxt_src = ", ".join(str(x) for x in nxt_tbl)
    return r"""\
// Generated by optimizer/ago/templates/dfa_table.py -- do not edit.
#include <stdint.h>
#include <stddef.h>

static const uint8_t DYNOPT_REM_ADD[5][3][256] = {
    %s
};
static const uint8_t DYNOPT_REM_NEXT[5][3][256] = {
    %s
};

extern "C" uint32_t %s(
    uint16_t* absCoeff, int numNonZero, int idx)
{
    uint32_t goRice = 0;
    uint32_t sum = 0;
    int phase = (idx >= 8) ? 2 : 0;
    while (idx < numNonZero)
    {
        const uint32_t v = absCoeff[idx];
        if (v < 256)
        {
            sum += DYNOPT_REM_ADD[goRice][phase][v];
            goRice = DYNOPT_REM_NEXT[goRice][phase][v];
        }
        else
        {
            const int baseLevel = phase == 0 ? 3
                               : phase == 2 ? 1 : 2;
            const int codeNumber = (int)v - baseLevel;
            if (codeNumber >= 0)
            {
                uint32_t cn = ((uint32_t)codeNumber >> goRice) - 3;
                uint32_t length = 0;
                if ((int32_t)cn >= 0)
                {
                    length = (uint32_t)(31 - __builtin_clz(cn + 1));
                    cn = length + length;
                }
                sum += 4 + goRice + cn;
                if (v > (3u << goRice))
                    goRice = (goRice + 1) - (goRice >> 2);
            }
        }
        idx++;
        phase = (idx >= 8) ? 2 : 1;
    }
    return sum;
}
""" % (add_src, nxt_src, func_name)


def proof_obligations() -> List[ProofObligation]:
    return [
        ProofObligation("dfa-exhaustive", "exhaustive_table",
                        {"domain": "5 goRice x 3 phases x 256 values "
                                   "= 3840 entries"}),
    ]


def proof_c_source() -> str:
    add_tbl, nxt_tbl = gen_dfa_tables()
    add_src = ", ".join(str(x) for x in add_tbl)
    nxt_src = ", ".join(str(x) for x in nxt_tbl)
    src = r"""\
#include <stdint.h>
#include <stdio.h>
static const uint8_t DYNOPT_REM_ADD[5][3][256] = { ADDSRC };
static const uint8_t DYNOPT_REM_NEXT[5][3][256] = { NXTSRC };
static int ref_step(int g, int base, int v, int* ng)
{
    const int code = v - base;
    if (code < 0) { *ng = g; return 0; }
    int cn = (code >> g) - 3;
    int add;
    if (cn < 0) add = 4 + g + cn;
    else
    {
        int length = 0, t = cn + 1;
        while (t >>= 1) length++;
        add = 4 + g + length + length;
    }
    *ng = (v > (3 << g)) ? (g + 1) - (g >> 2) : g;
    return add;
}
int main(void)
{
    int bad = 0;
    for (int g = 0; g < 5 && bad < 5; g++)
        for (int phase = 0; phase < 3 && bad < 5; phase++)
        {
            const int base = phase == 0 ? 3 : (phase == 2 ? 1 : 2);
            for (int v = 0; v < 256; v++)
            {
                int ng = 0;
                const int want = ref_step(g, base, v, &ng);
                const int add = DYNOPT_REM_ADD[g][phase][v];
                const int nxt = DYNOPT_REM_NEXT[g][phase][v];
                if (add != want || nxt != ng)
                {
                    printf("dfa bad g=%d phase=%d v=%d add=%d want=%d "
                           "nxt=%d wantng=%d\n",
                           g, phase, v, add, want, nxt, ng);
                    bad++;
                }
            }
        }
    printf("dfa exhaustive bad=%d\n", bad);
    return bad != 0;
}
"""
    return src.replace("ADDSRC", add_src).replace("NXTSRC", nxt_src)


class DfaPattern(Pattern):
    name = "cost_coeff_remain"

    def match(self, region):
        if isinstance(region, dict) and region.get("kernel") == \
                "cost_coeff_remain":
            return RuleBinding({})
        return None


class DfaRewrite(RewriteRule):
    id = "dfa-state-table"
    phase = "table-ize"
    effect = "branchy per-coeff formula -> (goRice x phase x value) table"
    measure = "per-coefficient branch count -> two byte loads"

    def apply(self, region, bindings):
        return region, proof_obligations()


class DfaTemplate(CoverTemplate):
    id = "dfa-neon-scalar"
    target = "scalar"

    def emit(self, region, bindings, target=""):
        return emit_dfa(), proof_obligations()
