"""P4 dot-fusion template (AGO P4; known win in dct/interp8 sdot).

Rewrite a per-lane mul+add (or fused mla) reduction over groups of
L lanes into a single dot product (NEON vdot / SVE sdot).  The
template emits both the grouped dot source and a reference mul+add
chain; the proof obligation is exhaustive equality on a small signed
domain plus random differential on the full domain.
"""

from __future__ import annotations

from typing import List, Tuple

from ago.rules import (  # noqa: E402
    CoverTemplate, Pattern, ProofObligation, RewriteRule, RuleBinding)


DOT_LANES = {"s8": 4, "s16": 4, "s32": 2}


class DotFusionPattern(Pattern):
    name = "mul-add-lane-group"

    def match(self, region):
        # region: (a:List[int], b:List[int], lanes_per_dot:int)
        if (isinstance(region, tuple) and len(region) == 3
                and isinstance(region[0], list) and isinstance(region[1], list)
                and len(region[0]) == len(region[1])
                and len(region[0]) % region[2] == 0):
            return RuleBinding({"a": region[0], "b": region[1],
                                "lanes": region[2]})
        return None


def ref_muladd(a: List[int], b: List[int]) -> int:
    return sum(x * y for x, y in zip(a, b))


def dot_groups(a: List[int], b: List[int], lanes: int) -> List[int]:
    return [ref_muladd(a[i:i + lanes], b[i:i + lanes])
            for i in range(0, len(a), lanes)]


def emit_dot_fusion(a_ty: str = "int16_t", acc_ty: str = "int32_t",
                    lanes: int = 4, n: int = 8, target: str = "sve2",
                    fn: str = "dot_fused") -> str:
    if target.startswith("sve"):
        if a_ty == "int8_t":
            acc_ty = "int32_t"
            return (
                "// Generated by ago.templates.dot_fusion (P4).\n"
                "#include <arm_sve.h>\n"
                "static inline %s %s(const %s* a, const %s* b)\n{\n"
                "    svint32_t acc = svdup_s32_x(svptrue_b32(), 0);\n"
                "    for (int g = 0; g < %d; g += %d)\n"
                "    {\n"
                "        svint8_t x = svld1_s8(svptrue_b8(), a + g);\n"
                "        svint8_t y = svld1_s8(svptrue_b8(), b + g);\n"
                "        acc = svdot_s32(acc, x, y);\n"
                "    }\n"
                "    return svlasta_s32(svptrue_b32(), acc);\n"
                "}\n" % (acc_ty, fn, a_ty, a_ty, n, lanes))
        if a_ty == "int16_t":
            acc_ty = "int64_t"
            return (
                "// Generated by ago.templates.dot_fusion (P4).\n"
                "#include <arm_sve.h>\n"
                "static inline %s %s(const %s* a, const %s* b)\n{\n"
                "    svint64_t acc = svdup_s64_x(svptrue_b64(), 0);\n"
                "    for (int g = 0; g < %d; g += %d)\n"
                "    {\n"
                "        svint16_t x = svld1_s16(svptrue_b16(), a + g);\n"
                "        svint16_t y = svld1_s16(svptrue_b16(), b + g);\n"
                "        acc = svdot_s64(acc, x, y);\n"
                "    }\n"
                "    return svlasta_s64(svptrue_b64(), acc);\n"
                "}\n" % (acc_ty, fn, a_ty, a_ty, n, lanes))
        raise ValueError("SVE dot supports int8_t/int16_t lanes only")
    if target.startswith("neon"):
        if a_ty != "int8_t":
            raise ValueError("NEON vdot is s8 x s8 -> s32 only")
        acc_ty = "int32_t"
        return (
            "// Generated by ago.templates.dot_fusion (P4).\n"
            "#include <arm_neon.h>\n"
            "static inline %s %s(const %s* a, const %s* b)\n{\n"
            "    int32x4_t acc = vdupq_n_s32(0);\n"
            "    for (int g = 0; g < %d; g += %d)\n"
            "    {\n"
            "        int8x16_t x = vld1q_s8(a + g);\n"
            "        int8x16_t y = vld1q_s8(b + g);\n"
            "        acc = vdotq_s32(acc, x, y);\n"
            "    }\n"
            "    return vaddvq_s32(acc);\n"
            "}\n" % (acc_ty, fn, a_ty, a_ty, n, lanes))
    raise ValueError("unknown target %r" % target)


def proof_c_source(a_ty: str = "int16_t", lanes: int = 4,
                   n: int = 8) -> str:
    """Exhaustive single-group ({-1,0,1}^8 = 6561) + 20k random
    differential vs per-lane mul+add."""
    if a_ty == "int16_t":
        dom_t = "int16_t"
        wrap = "int64_t"
        ref = ("static int64_t ref4(const int16_t* a, const int16_t* b)\n"
               "{\n    return (int64_t)a[0]*b[0] + a[1]*b[1] + "
               "a[2]*b[2] + a[3]*b[3];\n}\n"
               "static int64_t refn(const int16_t* a, const int16_t* b, "
               "int n)\n{\n    int64_t s = 0;\n"
               "    for (int i = 0; i < n; i++) "
               "s += (int64_t)a[i] * b[i];\n    return s;\n}\n")
    else:
        dom_t = "int8_t"
        wrap = "int32_t"
        ref = ("static int32_t ref4(const int8_t* a, const int8_t* b)\n"
               "{\n    return (int32_t)a[0]*b[0] + a[1]*b[1] + "
               "a[2]*b[2] + a[3]*b[3];\n}\n"
               "static int32_t refn(const int8_t* a, const int8_t* b, "
               "int n)\n{\n    int32_t s = 0;\n"
               "    for (int i = 0; i < n; i++) "
               "s += (int32_t)a[i] * b[i];\n    return s;\n}\n")
    one = emit_dot_fusion(a_ty=a_ty, lanes=lanes, n=lanes, target="sve2",
                          fn="dot_fused_1g")
    full = emit_dot_fusion(a_ty=a_ty, lanes=lanes, n=n, target="sve2",
                           fn="dot_fused")
    return (
        "#include <stdint.h>\n#include <stdio.h>\n#include <stdlib.h>\n"
        + ref + one + "\n" + full + "\n" +
        "int main(void)\n{\n"
        "    const %s dom[3] = {-1, 0, 1};\n"
        "    long bad = 0, total = 0;\n"
        "    %s a[%d], b[%d];\n"
        "    for (int ca = 0; ca < 81 && bad < 5; ca++)\n"
        "    for (int cb = 0; cb < 81 && bad < 5; cb++)\n"
        "    {\n"
        "        int c = ca;\n"
        "        for (int i = 0; i < 8; i++)\n"
        "        { a[i] = dom[c %% 3]; c /= 3; }\n"
        "        c = cb;\n"
        "        for (int i = 0; i < 8; i++)\n"
        "        { b[i] = dom[c %% 3]; c /= 3; }\n"
        "        if (dot_fused_1g(a, b) != (%s)ref4(a, b))\n"
        "            { bad++; printf(\"small bad ca=%%d cb=%%d\\n\", "
        "ca, cb); }\n"
        "        total++;\n"
        "    }\n"
        "    srand(7);\n"
        "    for (int it = 0; it < 20000; it++)\n"
        "    {\n"
        "        for (int i = 0; i < %d; i++)\n"
        "        { a[i] = (%s)(rand() %% 60000 - 30000);\n"
        "          b[i] = (%s)(rand() %% 60000 - 30000); }\n"
        "        if (dot_fused(a, b) != (%s)refn(a, b, %d))\n"
        "            { bad++; printf(\"rand bad it=%%d\\n\", it); break; }\n"
        "    }\n"
        "    printf(\"dot fusion exhaustive+random total=%%ld bad=%%ld\\n\",\n"
        "           total, bad);\n"
        "    return bad != 0;\n"
        "}\n" % (dom_t, dom_t, n, n, wrap, n, dom_t, dom_t, wrap, n))


def _obligations(lanes: int, n: int) -> List[ProofObligation]:
    return [
        ProofObligation("dot-fusion-%d-%d" % (lanes, n), "differential",
                        {"kind": "grouped dot vs per-lane mul+add",
                         "domain": "exhaustive { -1,0,1 }^8 per group "
                                   "(%d pairs) + 20k random %s pairs"
                                   % (3 ** 8, "int16" if lanes == 4
                                      else "int8"),
                         "wrap": "accumulate wraps mod 2^32/2^64"}),
    ]


class DotFusionRewrite(RewriteRule):
    id = "dot-fusion"
    phase = "dot-ize"
    effect = "per-lane mul+add group -> one dot (fewer uops)"
    measure = "lane ops -> lanes/dot uops"

    def preconditions(self, region, bindings):
        lanes = bindings.values["lanes"]
        return lanes in DOT_LANES.values()

    def apply(self, region, bindings):
        return region, _obligations(region[2], len(region[0]))

    def fallback(self, region):
        return region


class DotFusionTemplate(CoverTemplate):
    id = "dot-fusion"
    target = "neon|sve1|sve2"

    def preconditions(self, region, bindings):
        return DotFusionRewrite().preconditions(region, bindings)

    def emit(self, region, bindings, target="") -> Tuple[str,
                                                          List[ProofObligation]]:
        lanes = bindings.values["lanes"]
        n = len(bindings.values["a"])
        return emit_dot_fusion(lanes=lanes, n=n, target=target or "sve2"), \
            _obligations(lanes, n)
