// Generated by optimizer/ir/dct16_op_emit.py -- do not edit by hand.
// OpIR backend slice (no grouped C++ blocks).
#include <arm_sve.h>
#include <arm_neon.h>
#include <arm_neon_sve_bridge.h>
#include <cstdint>

static const uint16_t idx_rev[16] =
    { 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 };

static const uint8_t rev16_tbl[16] =
    { 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1 };

static const uint8_t rev32_tbl[16] =
    { 12, 13, 14, 15, 8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3 };


static const uint16_t idx_lo[16] =
    { 0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23 };

static const uint16_t idx_qa[16] =
    { 0, 1, 2, 3, 8, 9, 10, 11, 16, 17, 18, 19, 24, 25, 26, 27 };

static const uint16_t idx_qb[16] =
    { 4, 5, 6, 7, 12, 13, 14, 15, 20, 21, 22, 23, 28, 29, 30, 31 };


static inline int16x8_t rev16(const int16x8_t a)
{
    return vreinterpretq_s16_s8(vqtbx1q_s8(
        vreinterpretq_s8_s16(a), vreinterpretq_s8_s16(a),
        vld1q_u8(rev16_tbl)));
}

static inline int32x4_t rev32(const int32x4_t a)
{
    return vreinterpretq_s32_s8(vqtbx1q_s8(
        vreinterpretq_s8_s32(a), vreinterpretq_s8_s32(a),
        vld1q_u8(rev32_tbl)));
}

static inline int64x2_t sdotq_s16(int64x2_t acc, int16x8_t x, int16x8_t y)
{
    return svget_neonq_s64(svdot_s64(
        svset_neonq_s64(svundef_s64(), acc),
        svset_neonq_s16(svundef_s16(), x),
        svset_neonq_s16(svundef_s16(), y)));
}

static inline svint16_t revh_d(svint16_t x)
{
    svint16_t r;
    asm volatile("revh %[r].d, %[p]/m, %[x].d"
                 : [r] "=w" (r)
                 : [x] "w" (x), [p] "Upl" (svptrue_b64()));
    return r;
}

static inline svint32_t revw_d32(svint32_t x)
{
    svint32_t r;
    asm volatile("revw %[r].d, %[p]/m, %[x].d"
                 : [r] "=w" (r)
                 : [x] "w" (x), [p] "Upl" (svptrue_b64()));
    return r;
}

static inline svint64_t revw_d64(svint64_t x)
{
    svint64_t r;
    asm volatile("revw %[r].d, %[p]/m, %[x].d"
                 : [r] "=w" (r)
                 : [x] "w" (x), [p] "Upl" (svptrue_b64()));
    return r;
}

static inline svint32_t addp_s32(svint32_t a, svint32_t b)
{
    svint32_t r = a;
    asm volatile("addp %[r].s, %[p]/m, %[r].s, %[b].s"
                 : [r] "+w" (r)
                 : [b] "w" (b), [p] "Upl" (svptrue_b32()));
    return r;
}

static inline void st1d_scatter_s16(int16_t* base, svint64_t offs,
                                    svint16_t data)
{
    asm volatile("st1d {%[d].d}, %[p], [%[b], %[o].d]"
                 :
                 : [d] "w" (data), [b] "r" (base), [o] "w" (offs),
                   [p] "Upl" (svptrue_b64())
                 : "memory");
}

static const int16_t C8[16][8] = {
    { 64, 64, 64, 64, 64, 64, 64, 64 },
    { 90, 87, 80, 70, 57, 43, 25, 9 },
    { 89, 75, 50, 18, -18, -50, -75, -89 },
    { 87, 57, 9, -43, -80, -90, -70, -25 },
    { 83, 36, -36, -83, -83, -36, 36, 83 },
    { 80, 9, -70, -87, -25, 57, 90, 43 },
    { 75, -18, -89, -50, 50, 89, 18, -75 },
    { 70, -43, -87, 9, 90, 25, -80, -57 },
    { 64, -64, -64, 64, 64, -64, -64, 64 },
    { 57, -80, -25, 90, -9, -87, 43, 70 },
    { 50, -89, 18, 75, -75, -18, 89, -50 },
    { 43, -90, 57, 25, -87, 70, 9, -80 },
    { 36, -83, 83, -36, -36, 83, -83, 36 },
    { 25, -70, 90, -80, 43, 9, -57, 87 },
    { 18, -50, 75, -89, 89, -75, 50, -18 },
    { 9, -25, 43, -57, 70, -80, 87, -90 },
};

static const int16_t GT16[16][8] = {
    { 64, 64, 64, 64, 64, 64, 64, 64 },
    { 90, 87, 80, 70, 57, 43, 25, 9 },
    { 89, 75, 50, 18, -18, -50, -75, -89 },
    { 87, 57, 9, -43, -80, -90, -70, -25 },
    { 83, 36, -36, -83, -83, -36, 36, 83 },
    { 80, 9, -70, -87, -25, 57, 90, 43 },
    { 75, -18, -89, -50, 50, 89, 18, -75 },
    { 70, -43, -87, 9, 90, 25, -80, -57 },
    { 64, -64, -64, 64, 64, -64, -64, 64 },
    { 57, -80, -25, 90, -9, -87, 43, 70 },
    { 50, -89, 18, 75, -75, -18, 89, -50 },
    { 43, -90, 57, 25, -87, 70, 9, -80 },
    { 36, -83, 83, -36, -36, 83, -83, 36 },
    { 25, -70, 90, -80, 43, 9, -57, 87 },
    { 18, -50, 75, -89, 89, -75, 50, -18 },
    { 9, -25, 43, -57, 70, -80, 87, -90 },
};

static const int32_t GT16_S32[4][4] = {
    { 89, 75, 50, 18 },
    { 75, -18, -89, -50 },
    { 50, -89, 18, 75 },
    { 18, -50, 75, -89 },
};

static const int32_t T8E[4][4] = {
    { 64, 64, 64, 64 },
    { 83, 36, 83, 36 },
    { 64, -64, 64, -64 },
    { 36, -83, 36, -83 },
};

static const int16_t CQ_LO[16][16] = {
    { 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64 },
    { 90, 87, 80, 70, 90, 87, 80, 70, 90, 87, 80, 70, 90, 87, 80, 70 },
    { 89, 75, 50, 18, 89, 75, 50, 18, 89, 75, 50, 18, 89, 75, 50, 18 },
    { 87, 57, 9, -43, 87, 57, 9, -43, 87, 57, 9, -43, 87, 57, 9, -43 },
    { 83, 36, -36, -83, 83, 36, -36, -83, 83, 36, -36, -83, 83, 36, -36, -83 },
    { 80, 9, -70, -87, 80, 9, -70, -87, 80, 9, -70, -87, 80, 9, -70, -87 },
    { 75, -18, -89, -50, 75, -18, -89, -50, 75, -18, -89, -50, 75, -18, -89, -50 },
    { 70, -43, -87, 9, 70, -43, -87, 9, 70, -43, -87, 9, 70, -43, -87, 9 },
    { 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64 },
    { 57, -80, -25, 90, 57, -80, -25, 90, 57, -80, -25, 90, 57, -80, -25, 90 },
    { 50, -89, 18, 75, 50, -89, 18, 75, 50, -89, 18, 75, 50, -89, 18, 75 },
    { 43, -90, 57, 25, 43, -90, 57, 25, 43, -90, 57, 25, 43, -90, 57, 25 },
    { 36, -83, 83, -36, 36, -83, 83, -36, 36, -83, 83, -36, 36, -83, 83, -36 },
    { 25, -70, 90, -80, 25, -70, 90, -80, 25, -70, 90, -80, 25, -70, 90, -80 },
    { 18, -50, 75, -89, 18, -50, 75, -89, 18, -50, 75, -89, 18, -50, 75, -89 },
    { 9, -25, 43, -57, 9, -25, 43, -57, 9, -25, 43, -57, 9, -25, 43, -57 },
};
static const int16_t CQ_HI[16][16] = {
    { 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64 },
    { 57, 43, 25, 9, 57, 43, 25, 9, 57, 43, 25, 9, 57, 43, 25, 9 },
    { -18, -50, -75, -89, -18, -50, -75, -89, -18, -50, -75, -89, -18, -50, -75, -89 },
    { -80, -90, -70, -25, -80, -90, -70, -25, -80, -90, -70, -25, -80, -90, -70, -25 },
    { -83, -36, 36, 83, -83, -36, 36, 83, -83, -36, 36, 83, -83, -36, 36, 83 },
    { -25, 57, 90, 43, -25, 57, 90, 43, -25, 57, 90, 43, -25, 57, 90, 43 },
    { 50, 89, 18, -75, 50, 89, 18, -75, 50, 89, 18, -75, 50, 89, 18, -75 },
    { 90, 25, -80, -57, 90, 25, -80, -57, 90, 25, -80, -57, 90, 25, -80, -57 },
    { 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64 },
    { -9, -87, 43, 70, -9, -87, 43, 70, -9, -87, 43, 70, -9, -87, 43, 70 },
    { -75, -18, 89, -50, -75, -18, 89, -50, -75, -18, 89, -50, -75, -18, 89, -50 },
    { -87, 70, 9, -80, -87, 70, 9, -80, -87, 70, 9, -80, -87, 70, 9, -80 },
    { -36, 83, -83, 36, -36, 83, -83, 36, -36, 83, -83, 36, -36, 83, -83, 36 },
    { 43, 9, -57, 87, 43, 9, -57, 87, 43, 9, -57, 87, 43, 9, -57, 87 },
    { 89, -75, 50, -18, 89, -75, 50, -18, 89, -75, 50, -18, 89, -75, 50, -18 },
    { 70, -80, 87, -90, 70, -80, 87, -90, 70, -80, 87, -90, 70, -80, 87, -90 },
};
static const int32_t T8E8[4][8] = {
    { 64, 64, 64, 64, 64, 64, 64, 64 },
    { 83, 36, 83, 36, 83, 36, 83, 36 },
    { 64, -64, 64, -64, 64, -64, 64, -64 },
    { 36, -83, 36, -83, 36, -83, 36, -83 },
};
static const int64_t EVEN_OFFS[4] = { 0, 128, 256, 384 };

static __attribute__((noinline)) void op_pass_4(const int16_t* src, int16_t* dst, intptr_t stride)
{
    const svbool_t p16 = svptrue_b16();
    const svint64_t zero64 = svdup_n_s64(0);
    const svbool_t p8 = svwhilelt_b16(0, 8);
    svint16_t z_0 = svld1_s16(p16, src + 0 * stride);
    svint16_t z_1 = svld1_s16(p16, src + 1 * stride);
    svint16_t z_2 = svld1_s16(p16, src + 2 * stride);
    svint16_t z_3 = svld1_s16(p16, src + 3 * stride);
    svint64_t pa0_0 = svreinterpret_s64_s16(z_0);
    svint64_t pa1_0 = svreinterpret_s64_s16(z_1);
    svint64_t pa2_0 = svreinterpret_s64_s16(z_2);
    svint64_t pa3_0 = svreinterpret_s64_s16(z_3);
    svint64_t pt0_0 = svzip1_s64(pa0_0, pa2_0);
    svint64_t pt1_0 = svzip2_s64(pa0_0, pa2_0);
    svint64_t pt2_0 = svzip1_s64(pa1_0, pa3_0);
    svint64_t pt3_0 = svzip2_s64(pa1_0, pa3_0);
    svint64_t pp0_0 = svzip1_s64(pt0_0, pt2_0);
    svint64_t pp1_0 = svzip2_s64(pt0_0, pt2_0);
    svint64_t pp2_0 = svzip1_s64(pt1_0, pt3_0);
    svint64_t pp3_0 = svzip2_s64(pt1_0, pt3_0);
    svint16_t q0_0 = svreinterpret_s16_s64(pp0_0);
    svint16_t q1_0 = svreinterpret_s16_s64(pp1_0);
    svint16_t v2_0 = svreinterpret_s16_s64(pp2_0);
    svint16_t q2_0 = revh_d(v2_0);
    svint16_t v3_0 = svreinterpret_s16_s64(pp3_0);
    svint16_t q3_0 = revh_d(v3_0);
    svint16_t QO0_0 = svsub_s16_x(p16, q0_0, q3_0);
    svint16_t QO1_0 = svsub_s16_x(p16, q1_0, q2_0);
    svint16_t QE0_0 = svadd_s16_x(p16, q0_0, q3_0);
    svint16_t QE1_0 = svadd_s16_x(p16, q1_0, q2_0);
    svint16_t QR1_0 = revh_d(QE1_0);
    svint16_t EEF_0 = svadd_s16_x(p16, QE0_0, QR1_0);
    svint16_t EOF_0 = svsub_s16_x(p16, QE0_0, QR1_0);
    svint16_t z_4 = svld1_s16(p16, src + 4 * stride);
    svint16_t z_5 = svld1_s16(p16, src + 5 * stride);
    svint16_t z_6 = svld1_s16(p16, src + 6 * stride);
    svint16_t z_7 = svld1_s16(p16, src + 7 * stride);
    svint64_t pa0_1 = svreinterpret_s64_s16(z_4);
    svint64_t pa1_1 = svreinterpret_s64_s16(z_5);
    svint64_t pa2_1 = svreinterpret_s64_s16(z_6);
    svint64_t pa3_1 = svreinterpret_s64_s16(z_7);
    svint64_t pt0_1 = svzip1_s64(pa0_1, pa2_1);
    svint64_t pt1_1 = svzip2_s64(pa0_1, pa2_1);
    svint64_t pt2_1 = svzip1_s64(pa1_1, pa3_1);
    svint64_t pt3_1 = svzip2_s64(pa1_1, pa3_1);
    svint64_t pp0_1 = svzip1_s64(pt0_1, pt2_1);
    svint64_t pp1_1 = svzip2_s64(pt0_1, pt2_1);
    svint64_t pp2_1 = svzip1_s64(pt1_1, pt3_1);
    svint64_t pp3_1 = svzip2_s64(pt1_1, pt3_1);
    svint16_t q0_1 = svreinterpret_s16_s64(pp0_1);
    svint16_t q1_1 = svreinterpret_s16_s64(pp1_1);
    svint16_t v2_1 = svreinterpret_s16_s64(pp2_1);
    svint16_t q2_1 = revh_d(v2_1);
    svint16_t v3_1 = svreinterpret_s16_s64(pp3_1);
    svint16_t q3_1 = revh_d(v3_1);
    svint16_t QO0_1 = svsub_s16_x(p16, q0_1, q3_1);
    svint16_t QO1_1 = svsub_s16_x(p16, q1_1, q2_1);
    svint16_t QE0_1 = svadd_s16_x(p16, q0_1, q3_1);
    svint16_t QE1_1 = svadd_s16_x(p16, q1_1, q2_1);
    svint16_t QR1_1 = revh_d(QE1_1);
    svint16_t EEF_1 = svadd_s16_x(p16, QE0_1, QR1_1);
    svint16_t EOF_1 = svsub_s16_x(p16, QE0_1, QR1_1);
    svint16_t z_8 = svld1_s16(p16, src + 8 * stride);
    svint16_t z_9 = svld1_s16(p16, src + 9 * stride);
    svint16_t z_10 = svld1_s16(p16, src + 10 * stride);
    svint16_t z_11 = svld1_s16(p16, src + 11 * stride);
    svint64_t pa0_2 = svreinterpret_s64_s16(z_8);
    svint64_t pa1_2 = svreinterpret_s64_s16(z_9);
    svint64_t pa2_2 = svreinterpret_s64_s16(z_10);
    svint64_t pa3_2 = svreinterpret_s64_s16(z_11);
    svint64_t pt0_2 = svzip1_s64(pa0_2, pa2_2);
    svint64_t pt1_2 = svzip2_s64(pa0_2, pa2_2);
    svint64_t pt2_2 = svzip1_s64(pa1_2, pa3_2);
    svint64_t pt3_2 = svzip2_s64(pa1_2, pa3_2);
    svint64_t pp0_2 = svzip1_s64(pt0_2, pt2_2);
    svint64_t pp1_2 = svzip2_s64(pt0_2, pt2_2);
    svint64_t pp2_2 = svzip1_s64(pt1_2, pt3_2);
    svint64_t pp3_2 = svzip2_s64(pt1_2, pt3_2);
    svint16_t q0_2 = svreinterpret_s16_s64(pp0_2);
    svint16_t q1_2 = svreinterpret_s16_s64(pp1_2);
    svint16_t v2_2 = svreinterpret_s16_s64(pp2_2);
    svint16_t q2_2 = revh_d(v2_2);
    svint16_t v3_2 = svreinterpret_s16_s64(pp3_2);
    svint16_t q3_2 = revh_d(v3_2);
    svint16_t QO0_2 = svsub_s16_x(p16, q0_2, q3_2);
    svint16_t QO1_2 = svsub_s16_x(p16, q1_2, q2_2);
    svint16_t QE0_2 = svadd_s16_x(p16, q0_2, q3_2);
    svint16_t QE1_2 = svadd_s16_x(p16, q1_2, q2_2);
    svint16_t QR1_2 = revh_d(QE1_2);
    svint16_t EEF_2 = svadd_s16_x(p16, QE0_2, QR1_2);
    svint16_t EOF_2 = svsub_s16_x(p16, QE0_2, QR1_2);
    svint16_t z_12 = svld1_s16(p16, src + 12 * stride);
    svint16_t z_13 = svld1_s16(p16, src + 13 * stride);
    svint16_t z_14 = svld1_s16(p16, src + 14 * stride);
    svint16_t z_15 = svld1_s16(p16, src + 15 * stride);
    svint64_t pa0_3 = svreinterpret_s64_s16(z_12);
    svint64_t pa1_3 = svreinterpret_s64_s16(z_13);
    svint64_t pa2_3 = svreinterpret_s64_s16(z_14);
    svint64_t pa3_3 = svreinterpret_s64_s16(z_15);
    svint64_t pt0_3 = svzip1_s64(pa0_3, pa2_3);
    svint64_t pt1_3 = svzip2_s64(pa0_3, pa2_3);
    svint64_t pt2_3 = svzip1_s64(pa1_3, pa3_3);
    svint64_t pt3_3 = svzip2_s64(pa1_3, pa3_3);
    svint64_t pp0_3 = svzip1_s64(pt0_3, pt2_3);
    svint64_t pp1_3 = svzip2_s64(pt0_3, pt2_3);
    svint64_t pp2_3 = svzip1_s64(pt1_3, pt3_3);
    svint64_t pp3_3 = svzip2_s64(pt1_3, pt3_3);
    svint16_t q0_3 = svreinterpret_s16_s64(pp0_3);
    svint16_t q1_3 = svreinterpret_s16_s64(pp1_3);
    svint16_t v2_3 = svreinterpret_s16_s64(pp2_3);
    svint16_t q2_3 = revh_d(v2_3);
    svint16_t v3_3 = svreinterpret_s16_s64(pp3_3);
    svint16_t q3_3 = revh_d(v3_3);
    svint16_t QO0_3 = svsub_s16_x(p16, q0_3, q3_3);
    svint16_t QO1_3 = svsub_s16_x(p16, q1_3, q2_3);
    svint16_t QE0_3 = svadd_s16_x(p16, q0_3, q3_3);
    svint16_t QE1_3 = svadd_s16_x(p16, q1_3, q2_3);
    svint16_t QR1_3 = revh_d(QE1_3);
    svint16_t EEF_3 = svadd_s16_x(p16, QE0_3, QR1_3);
    svint16_t EOF_3 = svsub_s16_x(p16, QE0_3, QR1_3);
    const svint16_t ck_clo_0 = svld1_s16(p16, CQ_LO[0]);
    svint64_t d_0_0 = svdot_s64(zero64, EEF_0, ck_clo_0);
    svint64_t d_0_1 = svdot_s64(zero64, EEF_1, ck_clo_0);
    svint64_t d_0_2 = svdot_s64(zero64, EEF_2, ck_clo_0);
    svint64_t d_0_3 = svdot_s64(zero64, EEF_3, ck_clo_0);
    const svint32_t w_nn_0_0 = svuzp1_s32(svreinterpret_s32_s64(d_0_0), svreinterpret_s32_s64(d_0_1));
    svint16_t nn_0_0 = svqrshrnb_n_s32(w_nn_0_0, 3);
    nn_0_0 = svuzp1_s16(nn_0_0, nn_0_0);
    svst1_s16(p8, dst + 16 * 0 + 0, nn_0_0);
    const svint32_t w_nn_0_2 = svuzp1_s32(svreinterpret_s32_s64(d_0_2), svreinterpret_s32_s64(d_0_3));
    svint16_t nn_0_2 = svqrshrnb_n_s32(w_nn_0_2, 3);
    nn_0_2 = svuzp1_s16(nn_0_2, nn_0_2);
    svst1_s16(p8, dst + 16 * 0 + 8, nn_0_2);
    const svint16_t ck_clo_4 = svld1_s16(p16, CQ_LO[4]);
    svint64_t d_4_0 = svdot_s64(zero64, EEF_0, ck_clo_4);
    svint64_t d_4_1 = svdot_s64(zero64, EEF_1, ck_clo_4);
    svint64_t d_4_2 = svdot_s64(zero64, EEF_2, ck_clo_4);
    svint64_t d_4_3 = svdot_s64(zero64, EEF_3, ck_clo_4);
    const svint32_t w_nn_4_0 = svuzp1_s32(svreinterpret_s32_s64(d_4_0), svreinterpret_s32_s64(d_4_1));
    svint16_t nn_4_0 = svqrshrnb_n_s32(w_nn_4_0, 3);
    nn_4_0 = svuzp1_s16(nn_4_0, nn_4_0);
    svst1_s16(p8, dst + 16 * 4 + 0, nn_4_0);
    const svint32_t w_nn_4_2 = svuzp1_s32(svreinterpret_s32_s64(d_4_2), svreinterpret_s32_s64(d_4_3));
    svint16_t nn_4_2 = svqrshrnb_n_s32(w_nn_4_2, 3);
    nn_4_2 = svuzp1_s16(nn_4_2, nn_4_2);
    svst1_s16(p8, dst + 16 * 4 + 8, nn_4_2);
    const svint16_t ck_clo_8 = svld1_s16(p16, CQ_LO[8]);
    svint64_t d_8_0 = svdot_s64(zero64, EEF_0, ck_clo_8);
    svint64_t d_8_1 = svdot_s64(zero64, EEF_1, ck_clo_8);
    svint64_t d_8_2 = svdot_s64(zero64, EEF_2, ck_clo_8);
    svint64_t d_8_3 = svdot_s64(zero64, EEF_3, ck_clo_8);
    const svint32_t w_nn_8_0 = svuzp1_s32(svreinterpret_s32_s64(d_8_0), svreinterpret_s32_s64(d_8_1));
    svint16_t nn_8_0 = svqrshrnb_n_s32(w_nn_8_0, 3);
    nn_8_0 = svuzp1_s16(nn_8_0, nn_8_0);
    svst1_s16(p8, dst + 16 * 8 + 0, nn_8_0);
    const svint32_t w_nn_8_2 = svuzp1_s32(svreinterpret_s32_s64(d_8_2), svreinterpret_s32_s64(d_8_3));
    svint16_t nn_8_2 = svqrshrnb_n_s32(w_nn_8_2, 3);
    nn_8_2 = svuzp1_s16(nn_8_2, nn_8_2);
    svst1_s16(p8, dst + 16 * 8 + 8, nn_8_2);
    const svint16_t ck_clo_12 = svld1_s16(p16, CQ_LO[12]);
    svint64_t d_12_0 = svdot_s64(zero64, EEF_0, ck_clo_12);
    svint64_t d_12_1 = svdot_s64(zero64, EEF_1, ck_clo_12);
    svint64_t d_12_2 = svdot_s64(zero64, EEF_2, ck_clo_12);
    svint64_t d_12_3 = svdot_s64(zero64, EEF_3, ck_clo_12);
    const svint32_t w_nn_12_0 = svuzp1_s32(svreinterpret_s32_s64(d_12_0), svreinterpret_s32_s64(d_12_1));
    svint16_t nn_12_0 = svqrshrnb_n_s32(w_nn_12_0, 3);
    nn_12_0 = svuzp1_s16(nn_12_0, nn_12_0);
    svst1_s16(p8, dst + 16 * 12 + 0, nn_12_0);
    const svint32_t w_nn_12_2 = svuzp1_s32(svreinterpret_s32_s64(d_12_2), svreinterpret_s32_s64(d_12_3));
    svint16_t nn_12_2 = svqrshrnb_n_s32(w_nn_12_2, 3);
    nn_12_2 = svuzp1_s16(nn_12_2, nn_12_2);
    svst1_s16(p8, dst + 16 * 12 + 8, nn_12_2);
    const svint16_t ck_clo_2 = svld1_s16(p16, CQ_LO[2]);
    svint64_t d_2_0 = svdot_s64(zero64, EOF_0, ck_clo_2);
    svint64_t d_2_1 = svdot_s64(zero64, EOF_1, ck_clo_2);
    svint64_t d_2_2 = svdot_s64(zero64, EOF_2, ck_clo_2);
    svint64_t d_2_3 = svdot_s64(zero64, EOF_3, ck_clo_2);
    const svint32_t w_nn_2_0 = svuzp1_s32(svreinterpret_s32_s64(d_2_0), svreinterpret_s32_s64(d_2_1));
    svint16_t nn_2_0 = svqrshrnb_n_s32(w_nn_2_0, 3);
    nn_2_0 = svuzp1_s16(nn_2_0, nn_2_0);
    svst1_s16(p8, dst + 16 * 2 + 0, nn_2_0);
    const svint32_t w_nn_2_2 = svuzp1_s32(svreinterpret_s32_s64(d_2_2), svreinterpret_s32_s64(d_2_3));
    svint16_t nn_2_2 = svqrshrnb_n_s32(w_nn_2_2, 3);
    nn_2_2 = svuzp1_s16(nn_2_2, nn_2_2);
    svst1_s16(p8, dst + 16 * 2 + 8, nn_2_2);
    const svint16_t ck_clo_6 = svld1_s16(p16, CQ_LO[6]);
    svint64_t d_6_0 = svdot_s64(zero64, EOF_0, ck_clo_6);
    svint64_t d_6_1 = svdot_s64(zero64, EOF_1, ck_clo_6);
    svint64_t d_6_2 = svdot_s64(zero64, EOF_2, ck_clo_6);
    svint64_t d_6_3 = svdot_s64(zero64, EOF_3, ck_clo_6);
    const svint32_t w_nn_6_0 = svuzp1_s32(svreinterpret_s32_s64(d_6_0), svreinterpret_s32_s64(d_6_1));
    svint16_t nn_6_0 = svqrshrnb_n_s32(w_nn_6_0, 3);
    nn_6_0 = svuzp1_s16(nn_6_0, nn_6_0);
    svst1_s16(p8, dst + 16 * 6 + 0, nn_6_0);
    const svint32_t w_nn_6_2 = svuzp1_s32(svreinterpret_s32_s64(d_6_2), svreinterpret_s32_s64(d_6_3));
    svint16_t nn_6_2 = svqrshrnb_n_s32(w_nn_6_2, 3);
    nn_6_2 = svuzp1_s16(nn_6_2, nn_6_2);
    svst1_s16(p8, dst + 16 * 6 + 8, nn_6_2);
    const svint16_t ck_clo_10 = svld1_s16(p16, CQ_LO[10]);
    svint64_t d_10_0 = svdot_s64(zero64, EOF_0, ck_clo_10);
    svint64_t d_10_1 = svdot_s64(zero64, EOF_1, ck_clo_10);
    svint64_t d_10_2 = svdot_s64(zero64, EOF_2, ck_clo_10);
    svint64_t d_10_3 = svdot_s64(zero64, EOF_3, ck_clo_10);
    const svint32_t w_nn_10_0 = svuzp1_s32(svreinterpret_s32_s64(d_10_0), svreinterpret_s32_s64(d_10_1));
    svint16_t nn_10_0 = svqrshrnb_n_s32(w_nn_10_0, 3);
    nn_10_0 = svuzp1_s16(nn_10_0, nn_10_0);
    svst1_s16(p8, dst + 16 * 10 + 0, nn_10_0);
    const svint32_t w_nn_10_2 = svuzp1_s32(svreinterpret_s32_s64(d_10_2), svreinterpret_s32_s64(d_10_3));
    svint16_t nn_10_2 = svqrshrnb_n_s32(w_nn_10_2, 3);
    nn_10_2 = svuzp1_s16(nn_10_2, nn_10_2);
    svst1_s16(p8, dst + 16 * 10 + 8, nn_10_2);
    const svint16_t ck_clo_14 = svld1_s16(p16, CQ_LO[14]);
    svint64_t d_14_0 = svdot_s64(zero64, EOF_0, ck_clo_14);
    svint64_t d_14_1 = svdot_s64(zero64, EOF_1, ck_clo_14);
    svint64_t d_14_2 = svdot_s64(zero64, EOF_2, ck_clo_14);
    svint64_t d_14_3 = svdot_s64(zero64, EOF_3, ck_clo_14);
    const svint32_t w_nn_14_0 = svuzp1_s32(svreinterpret_s32_s64(d_14_0), svreinterpret_s32_s64(d_14_1));
    svint16_t nn_14_0 = svqrshrnb_n_s32(w_nn_14_0, 3);
    nn_14_0 = svuzp1_s16(nn_14_0, nn_14_0);
    svst1_s16(p8, dst + 16 * 14 + 0, nn_14_0);
    const svint32_t w_nn_14_2 = svuzp1_s32(svreinterpret_s32_s64(d_14_2), svreinterpret_s32_s64(d_14_3));
    svint16_t nn_14_2 = svqrshrnb_n_s32(w_nn_14_2, 3);
    nn_14_2 = svuzp1_s16(nn_14_2, nn_14_2);
    svst1_s16(p8, dst + 16 * 14 + 8, nn_14_2);
    const svint16_t ck_clo_1 = svld1_s16(p16, CQ_LO[1]);
    const svint16_t ck_chi_1 = svld1_s16(p16, CQ_HI[1]);
    svint64_t d0_1_0 = svdot_s64(zero64, QO0_0, ck_clo_1);
    svint64_t d1_1_0 = svdot_s64(d0_1_0, QO1_0, ck_chi_1);
    svint64_t d0_1_1 = svdot_s64(zero64, QO0_1, ck_clo_1);
    svint64_t d1_1_1 = svdot_s64(d0_1_1, QO1_1, ck_chi_1);
    svint64_t d0_1_2 = svdot_s64(zero64, QO0_2, ck_clo_1);
    svint64_t d1_1_2 = svdot_s64(d0_1_2, QO1_2, ck_chi_1);
    svint64_t d0_1_3 = svdot_s64(zero64, QO0_3, ck_clo_1);
    svint64_t d1_1_3 = svdot_s64(d0_1_3, QO1_3, ck_chi_1);
    const svint32_t w_nn_1_0 = svuzp1_s32(svreinterpret_s32_s64(d1_1_0), svreinterpret_s32_s64(d1_1_1));
    svint16_t nn_1_0 = svqrshrnb_n_s32(w_nn_1_0, 3);
    nn_1_0 = svuzp1_s16(nn_1_0, nn_1_0);
    svst1_s16(p8, dst + 16 * 1 + 0, nn_1_0);
    const svint32_t w_nn_1_2 = svuzp1_s32(svreinterpret_s32_s64(d1_1_2), svreinterpret_s32_s64(d1_1_3));
    svint16_t nn_1_2 = svqrshrnb_n_s32(w_nn_1_2, 3);
    nn_1_2 = svuzp1_s16(nn_1_2, nn_1_2);
    svst1_s16(p8, dst + 16 * 1 + 8, nn_1_2);
    const svint16_t ck_clo_3 = svld1_s16(p16, CQ_LO[3]);
    const svint16_t ck_chi_3 = svld1_s16(p16, CQ_HI[3]);
    svint64_t d0_3_0 = svdot_s64(zero64, QO0_0, ck_clo_3);
    svint64_t d1_3_0 = svdot_s64(d0_3_0, QO1_0, ck_chi_3);
    svint64_t d0_3_1 = svdot_s64(zero64, QO0_1, ck_clo_3);
    svint64_t d1_3_1 = svdot_s64(d0_3_1, QO1_1, ck_chi_3);
    svint64_t d0_3_2 = svdot_s64(zero64, QO0_2, ck_clo_3);
    svint64_t d1_3_2 = svdot_s64(d0_3_2, QO1_2, ck_chi_3);
    svint64_t d0_3_3 = svdot_s64(zero64, QO0_3, ck_clo_3);
    svint64_t d1_3_3 = svdot_s64(d0_3_3, QO1_3, ck_chi_3);
    const svint32_t w_nn_3_0 = svuzp1_s32(svreinterpret_s32_s64(d1_3_0), svreinterpret_s32_s64(d1_3_1));
    svint16_t nn_3_0 = svqrshrnb_n_s32(w_nn_3_0, 3);
    nn_3_0 = svuzp1_s16(nn_3_0, nn_3_0);
    svst1_s16(p8, dst + 16 * 3 + 0, nn_3_0);
    const svint32_t w_nn_3_2 = svuzp1_s32(svreinterpret_s32_s64(d1_3_2), svreinterpret_s32_s64(d1_3_3));
    svint16_t nn_3_2 = svqrshrnb_n_s32(w_nn_3_2, 3);
    nn_3_2 = svuzp1_s16(nn_3_2, nn_3_2);
    svst1_s16(p8, dst + 16 * 3 + 8, nn_3_2);
    const svint16_t ck_clo_5 = svld1_s16(p16, CQ_LO[5]);
    const svint16_t ck_chi_5 = svld1_s16(p16, CQ_HI[5]);
    svint64_t d0_5_0 = svdot_s64(zero64, QO0_0, ck_clo_5);
    svint64_t d1_5_0 = svdot_s64(d0_5_0, QO1_0, ck_chi_5);
    svint64_t d0_5_1 = svdot_s64(zero64, QO0_1, ck_clo_5);
    svint64_t d1_5_1 = svdot_s64(d0_5_1, QO1_1, ck_chi_5);
    svint64_t d0_5_2 = svdot_s64(zero64, QO0_2, ck_clo_5);
    svint64_t d1_5_2 = svdot_s64(d0_5_2, QO1_2, ck_chi_5);
    svint64_t d0_5_3 = svdot_s64(zero64, QO0_3, ck_clo_5);
    svint64_t d1_5_3 = svdot_s64(d0_5_3, QO1_3, ck_chi_5);
    const svint32_t w_nn_5_0 = svuzp1_s32(svreinterpret_s32_s64(d1_5_0), svreinterpret_s32_s64(d1_5_1));
    svint16_t nn_5_0 = svqrshrnb_n_s32(w_nn_5_0, 3);
    nn_5_0 = svuzp1_s16(nn_5_0, nn_5_0);
    svst1_s16(p8, dst + 16 * 5 + 0, nn_5_0);
    const svint32_t w_nn_5_2 = svuzp1_s32(svreinterpret_s32_s64(d1_5_2), svreinterpret_s32_s64(d1_5_3));
    svint16_t nn_5_2 = svqrshrnb_n_s32(w_nn_5_2, 3);
    nn_5_2 = svuzp1_s16(nn_5_2, nn_5_2);
    svst1_s16(p8, dst + 16 * 5 + 8, nn_5_2);
    const svint16_t ck_clo_7 = svld1_s16(p16, CQ_LO[7]);
    const svint16_t ck_chi_7 = svld1_s16(p16, CQ_HI[7]);
    svint64_t d0_7_0 = svdot_s64(zero64, QO0_0, ck_clo_7);
    svint64_t d1_7_0 = svdot_s64(d0_7_0, QO1_0, ck_chi_7);
    svint64_t d0_7_1 = svdot_s64(zero64, QO0_1, ck_clo_7);
    svint64_t d1_7_1 = svdot_s64(d0_7_1, QO1_1, ck_chi_7);
    svint64_t d0_7_2 = svdot_s64(zero64, QO0_2, ck_clo_7);
    svint64_t d1_7_2 = svdot_s64(d0_7_2, QO1_2, ck_chi_7);
    svint64_t d0_7_3 = svdot_s64(zero64, QO0_3, ck_clo_7);
    svint64_t d1_7_3 = svdot_s64(d0_7_3, QO1_3, ck_chi_7);
    const svint32_t w_nn_7_0 = svuzp1_s32(svreinterpret_s32_s64(d1_7_0), svreinterpret_s32_s64(d1_7_1));
    svint16_t nn_7_0 = svqrshrnb_n_s32(w_nn_7_0, 3);
    nn_7_0 = svuzp1_s16(nn_7_0, nn_7_0);
    svst1_s16(p8, dst + 16 * 7 + 0, nn_7_0);
    const svint32_t w_nn_7_2 = svuzp1_s32(svreinterpret_s32_s64(d1_7_2), svreinterpret_s32_s64(d1_7_3));
    svint16_t nn_7_2 = svqrshrnb_n_s32(w_nn_7_2, 3);
    nn_7_2 = svuzp1_s16(nn_7_2, nn_7_2);
    svst1_s16(p8, dst + 16 * 7 + 8, nn_7_2);
    const svint16_t ck_clo_9 = svld1_s16(p16, CQ_LO[9]);
    const svint16_t ck_chi_9 = svld1_s16(p16, CQ_HI[9]);
    svint64_t d0_9_0 = svdot_s64(zero64, QO0_0, ck_clo_9);
    svint64_t d1_9_0 = svdot_s64(d0_9_0, QO1_0, ck_chi_9);
    svint64_t d0_9_1 = svdot_s64(zero64, QO0_1, ck_clo_9);
    svint64_t d1_9_1 = svdot_s64(d0_9_1, QO1_1, ck_chi_9);
    svint64_t d0_9_2 = svdot_s64(zero64, QO0_2, ck_clo_9);
    svint64_t d1_9_2 = svdot_s64(d0_9_2, QO1_2, ck_chi_9);
    svint64_t d0_9_3 = svdot_s64(zero64, QO0_3, ck_clo_9);
    svint64_t d1_9_3 = svdot_s64(d0_9_3, QO1_3, ck_chi_9);
    const svint32_t w_nn_9_0 = svuzp1_s32(svreinterpret_s32_s64(d1_9_0), svreinterpret_s32_s64(d1_9_1));
    svint16_t nn_9_0 = svqrshrnb_n_s32(w_nn_9_0, 3);
    nn_9_0 = svuzp1_s16(nn_9_0, nn_9_0);
    svst1_s16(p8, dst + 16 * 9 + 0, nn_9_0);
    const svint32_t w_nn_9_2 = svuzp1_s32(svreinterpret_s32_s64(d1_9_2), svreinterpret_s32_s64(d1_9_3));
    svint16_t nn_9_2 = svqrshrnb_n_s32(w_nn_9_2, 3);
    nn_9_2 = svuzp1_s16(nn_9_2, nn_9_2);
    svst1_s16(p8, dst + 16 * 9 + 8, nn_9_2);
    const svint16_t ck_clo_11 = svld1_s16(p16, CQ_LO[11]);
    const svint16_t ck_chi_11 = svld1_s16(p16, CQ_HI[11]);
    svint64_t d0_11_0 = svdot_s64(zero64, QO0_0, ck_clo_11);
    svint64_t d1_11_0 = svdot_s64(d0_11_0, QO1_0, ck_chi_11);
    svint64_t d0_11_1 = svdot_s64(zero64, QO0_1, ck_clo_11);
    svint64_t d1_11_1 = svdot_s64(d0_11_1, QO1_1, ck_chi_11);
    svint64_t d0_11_2 = svdot_s64(zero64, QO0_2, ck_clo_11);
    svint64_t d1_11_2 = svdot_s64(d0_11_2, QO1_2, ck_chi_11);
    svint64_t d0_11_3 = svdot_s64(zero64, QO0_3, ck_clo_11);
    svint64_t d1_11_3 = svdot_s64(d0_11_3, QO1_3, ck_chi_11);
    const svint32_t w_nn_11_0 = svuzp1_s32(svreinterpret_s32_s64(d1_11_0), svreinterpret_s32_s64(d1_11_1));
    svint16_t nn_11_0 = svqrshrnb_n_s32(w_nn_11_0, 3);
    nn_11_0 = svuzp1_s16(nn_11_0, nn_11_0);
    svst1_s16(p8, dst + 16 * 11 + 0, nn_11_0);
    const svint32_t w_nn_11_2 = svuzp1_s32(svreinterpret_s32_s64(d1_11_2), svreinterpret_s32_s64(d1_11_3));
    svint16_t nn_11_2 = svqrshrnb_n_s32(w_nn_11_2, 3);
    nn_11_2 = svuzp1_s16(nn_11_2, nn_11_2);
    svst1_s16(p8, dst + 16 * 11 + 8, nn_11_2);
    const svint16_t ck_clo_13 = svld1_s16(p16, CQ_LO[13]);
    const svint16_t ck_chi_13 = svld1_s16(p16, CQ_HI[13]);
    svint64_t d0_13_0 = svdot_s64(zero64, QO0_0, ck_clo_13);
    svint64_t d1_13_0 = svdot_s64(d0_13_0, QO1_0, ck_chi_13);
    svint64_t d0_13_1 = svdot_s64(zero64, QO0_1, ck_clo_13);
    svint64_t d1_13_1 = svdot_s64(d0_13_1, QO1_1, ck_chi_13);
    svint64_t d0_13_2 = svdot_s64(zero64, QO0_2, ck_clo_13);
    svint64_t d1_13_2 = svdot_s64(d0_13_2, QO1_2, ck_chi_13);
    svint64_t d0_13_3 = svdot_s64(zero64, QO0_3, ck_clo_13);
    svint64_t d1_13_3 = svdot_s64(d0_13_3, QO1_3, ck_chi_13);
    const svint32_t w_nn_13_0 = svuzp1_s32(svreinterpret_s32_s64(d1_13_0), svreinterpret_s32_s64(d1_13_1));
    svint16_t nn_13_0 = svqrshrnb_n_s32(w_nn_13_0, 3);
    nn_13_0 = svuzp1_s16(nn_13_0, nn_13_0);
    svst1_s16(p8, dst + 16 * 13 + 0, nn_13_0);
    const svint32_t w_nn_13_2 = svuzp1_s32(svreinterpret_s32_s64(d1_13_2), svreinterpret_s32_s64(d1_13_3));
    svint16_t nn_13_2 = svqrshrnb_n_s32(w_nn_13_2, 3);
    nn_13_2 = svuzp1_s16(nn_13_2, nn_13_2);
    svst1_s16(p8, dst + 16 * 13 + 8, nn_13_2);
    const svint16_t ck_clo_15 = svld1_s16(p16, CQ_LO[15]);
    const svint16_t ck_chi_15 = svld1_s16(p16, CQ_HI[15]);
    svint64_t d0_15_0 = svdot_s64(zero64, QO0_0, ck_clo_15);
    svint64_t d1_15_0 = svdot_s64(d0_15_0, QO1_0, ck_chi_15);
    svint64_t d0_15_1 = svdot_s64(zero64, QO0_1, ck_clo_15);
    svint64_t d1_15_1 = svdot_s64(d0_15_1, QO1_1, ck_chi_15);
    svint64_t d0_15_2 = svdot_s64(zero64, QO0_2, ck_clo_15);
    svint64_t d1_15_2 = svdot_s64(d0_15_2, QO1_2, ck_chi_15);
    svint64_t d0_15_3 = svdot_s64(zero64, QO0_3, ck_clo_15);
    svint64_t d1_15_3 = svdot_s64(d0_15_3, QO1_3, ck_chi_15);
    const svint32_t w_nn_15_0 = svuzp1_s32(svreinterpret_s32_s64(d1_15_0), svreinterpret_s32_s64(d1_15_1));
    svint16_t nn_15_0 = svqrshrnb_n_s32(w_nn_15_0, 3);
    nn_15_0 = svuzp1_s16(nn_15_0, nn_15_0);
    svst1_s16(p8, dst + 16 * 15 + 0, nn_15_0);
    const svint32_t w_nn_15_2 = svuzp1_s32(svreinterpret_s32_s64(d1_15_2), svreinterpret_s32_s64(d1_15_3));
    svint16_t nn_15_2 = svqrshrnb_n_s32(w_nn_15_2, 3);
    nn_15_2 = svuzp1_s16(nn_15_2, nn_15_2);
    svst1_s16(p8, dst + 16 * 15 + 8, nn_15_2);
}
static __attribute__((noinline)) void op_pass_11(const int16_t* src, int16_t* dst)
{
    const int line = 16;
    const svbool_t p16 = svptrue_b16();
    const svint64_t zero64 = svdup_n_s64(0);
    const svbool_t p32 = svptrue_b32();
    const svbool_t p64 = svptrue_b64();
    svint16_t z_0 = svld1_s16(p16, src + 0 * line);
    svint16_t z_1 = svld1_s16(p16, src + 1 * line);
    svint16_t z_2 = svld1_s16(p16, src + 2 * line);
    svint16_t z_3 = svld1_s16(p16, src + 3 * line);
    svint64_t pa0_0 = svreinterpret_s64_s16(z_0);
    svint64_t pa1_0 = svreinterpret_s64_s16(z_1);
    svint64_t pa2_0 = svreinterpret_s64_s16(z_2);
    svint64_t pa3_0 = svreinterpret_s64_s16(z_3);
    svint64_t pt0_0 = svzip1_s64(pa0_0, pa2_0);
    svint64_t pt1_0 = svzip2_s64(pa0_0, pa2_0);
    svint64_t pt2_0 = svzip1_s64(pa1_0, pa3_0);
    svint64_t pt3_0 = svzip2_s64(pa1_0, pa3_0);
    svint64_t pp0_0 = svzip1_s64(pt0_0, pt2_0);
    svint64_t pp1_0 = svzip2_s64(pt0_0, pt2_0);
    svint64_t pp2_0 = svzip1_s64(pt1_0, pt3_0);
    svint64_t pp3_0 = svzip2_s64(pt1_0, pt3_0);
    svint16_t q0_0 = svreinterpret_s16_s64(pp0_0);
    svint16_t q1_0 = svreinterpret_s16_s64(pp1_0);
    svint16_t v2_0 = svreinterpret_s16_s64(pp2_0);
    svint16_t q2_0 = revh_d(v2_0);
    svint16_t v3_0 = svreinterpret_s16_s64(pp3_0);
    svint16_t q3_0 = revh_d(v3_0);
    svint16_t QO0_0 = svsub_s16_x(p16, q0_0, q3_0);
    svint16_t QO1_0 = svsub_s16_x(p16, q1_0, q2_0);
    svint32_t e0_0 = svaddlb_s32(q0_0, q3_0);
    svint32_t e1_0 = svaddlt_s32(q0_0, q3_0);
    svint32_t e2_0 = svaddlb_s32(q1_0, q2_0);
    svint32_t e3_0 = svaddlt_s32(q1_0, q2_0);
    svint32_t w0_0 = svzip1_s32(e0_0, e1_0);
    svint32_t w1_0 = svzip2_s32(e0_0, e1_0);
    svint32_t u2_0 = revw_d32(e2_0);
    svint32_t u3_0 = revw_d32(e3_0);
    svint32_t w2_0 = svzip1_s32(u3_0, u2_0);
    svint32_t w3_0 = svzip2_s32(u3_0, u2_0);
    svint32_t s0_0 = svsub_s32_x(p32, w0_0, w2_0);
    svint32_t s1_0 = svsub_s32_x(p32, w1_0, w3_0);
    svint32_t s2_0 = svadd_s32_x(p32, w0_0, w2_0);
    svint32_t s3_0 = svadd_s32_x(p32, w1_0, w3_0);
    svint16_t QEOW_0 = svuzp1_s16(svreinterpret_s16_s32(s0_0), svreinterpret_s16_s32(s1_0));
    svint64_t v0_0 = svuzp1_s64(svreinterpret_s64_s32(s2_0), svreinterpret_s64_s32(s3_0));
    svint64_t v1_0 = svuzp2_s64(svreinterpret_s64_s32(s2_0), svreinterpret_s64_s32(s3_0));
    svint64_t v1r_0 = revw_d64(v1_0);
    svint32_t EEp_0 = svadd_s32_x(p32, svreinterpret_s32_s64(v0_0), svreinterpret_s32_s64(v1r_0));
    svint32_t EOp_0 = svsub_s32_x(p32, svreinterpret_s32_s64(v0_0), svreinterpret_s32_s64(v1r_0));
    const svint32_t c_ct_0_0 = svld1_s32(p32, T8E8[0]);
    svint32_t m0_0 = svmul_s32_x(p32, EEp_0, c_ct_0_0);
    const svint32_t c_ct_1_0 = svld1_s32(p32, T8E8[1]);
    svint32_t m1_0 = svmul_s32_x(p32, EOp_0, c_ct_1_0);
    const svint32_t c_ct_2_0 = svld1_s32(p32, T8E8[2]);
    svint32_t m2_0 = svmul_s32_x(p32, EEp_0, c_ct_2_0);
    const svint32_t c_ct_3_0 = svld1_s32(p32, T8E8[3]);
    svint32_t m3_0 = svmul_s32_x(p32, EOp_0, c_ct_3_0);
    svint32_t pa_0 = addp_s32(m0_0, m2_0);
    svint32_t pb_0 = addp_s32(m1_0, m3_0);
    svint32_t xa_0 = svuzp1_s32(pa_0, pb_0);
    svint32_t xb_0 = svuzp2_s32(pa_0, pb_0);
    svint16_t na_0 = svqrshrnb_n_s32(xa_0, 10);
    svint16_t nb_0 = svqrshrnb_n_s32(xb_0, 10);
    svint16_t n16_0 = svuzp1_s16(na_0, nb_0);
    const svint64_t evoffs = svld1_s64(p64, EVEN_OFFS);
    st1d_scatter_s16(dst + 0, evoffs, n16_0);
    svint16_t z_4 = svld1_s16(p16, src + 4 * line);
    svint16_t z_5 = svld1_s16(p16, src + 5 * line);
    svint16_t z_6 = svld1_s16(p16, src + 6 * line);
    svint16_t z_7 = svld1_s16(p16, src + 7 * line);
    svint64_t pa0_1 = svreinterpret_s64_s16(z_4);
    svint64_t pa1_1 = svreinterpret_s64_s16(z_5);
    svint64_t pa2_1 = svreinterpret_s64_s16(z_6);
    svint64_t pa3_1 = svreinterpret_s64_s16(z_7);
    svint64_t pt0_1 = svzip1_s64(pa0_1, pa2_1);
    svint64_t pt1_1 = svzip2_s64(pa0_1, pa2_1);
    svint64_t pt2_1 = svzip1_s64(pa1_1, pa3_1);
    svint64_t pt3_1 = svzip2_s64(pa1_1, pa3_1);
    svint64_t pp0_1 = svzip1_s64(pt0_1, pt2_1);
    svint64_t pp1_1 = svzip2_s64(pt0_1, pt2_1);
    svint64_t pp2_1 = svzip1_s64(pt1_1, pt3_1);
    svint64_t pp3_1 = svzip2_s64(pt1_1, pt3_1);
    svint16_t q0_1 = svreinterpret_s16_s64(pp0_1);
    svint16_t q1_1 = svreinterpret_s16_s64(pp1_1);
    svint16_t v2_1 = svreinterpret_s16_s64(pp2_1);
    svint16_t q2_1 = revh_d(v2_1);
    svint16_t v3_1 = svreinterpret_s16_s64(pp3_1);
    svint16_t q3_1 = revh_d(v3_1);
    svint16_t QO0_1 = svsub_s16_x(p16, q0_1, q3_1);
    svint16_t QO1_1 = svsub_s16_x(p16, q1_1, q2_1);
    svint32_t e0_1 = svaddlb_s32(q0_1, q3_1);
    svint32_t e1_1 = svaddlt_s32(q0_1, q3_1);
    svint32_t e2_1 = svaddlb_s32(q1_1, q2_1);
    svint32_t e3_1 = svaddlt_s32(q1_1, q2_1);
    svint32_t w0_1 = svzip1_s32(e0_1, e1_1);
    svint32_t w1_1 = svzip2_s32(e0_1, e1_1);
    svint32_t u2_1 = revw_d32(e2_1);
    svint32_t u3_1 = revw_d32(e3_1);
    svint32_t w2_1 = svzip1_s32(u3_1, u2_1);
    svint32_t w3_1 = svzip2_s32(u3_1, u2_1);
    svint32_t s0_1 = svsub_s32_x(p32, w0_1, w2_1);
    svint32_t s1_1 = svsub_s32_x(p32, w1_1, w3_1);
    svint32_t s2_1 = svadd_s32_x(p32, w0_1, w2_1);
    svint32_t s3_1 = svadd_s32_x(p32, w1_1, w3_1);
    svint16_t QEOW_1 = svuzp1_s16(svreinterpret_s16_s32(s0_1), svreinterpret_s16_s32(s1_1));
    svint64_t v0_1 = svuzp1_s64(svreinterpret_s64_s32(s2_1), svreinterpret_s64_s32(s3_1));
    svint64_t v1_1 = svuzp2_s64(svreinterpret_s64_s32(s2_1), svreinterpret_s64_s32(s3_1));
    svint64_t v1r_1 = revw_d64(v1_1);
    svint32_t EEp_1 = svadd_s32_x(p32, svreinterpret_s32_s64(v0_1), svreinterpret_s32_s64(v1r_1));
    svint32_t EOp_1 = svsub_s32_x(p32, svreinterpret_s32_s64(v0_1), svreinterpret_s32_s64(v1r_1));
    svint32_t m0_1 = svmul_s32_x(p32, EEp_1, c_ct_0_0);
    svint32_t m1_1 = svmul_s32_x(p32, EOp_1, c_ct_1_0);
    svint32_t m2_1 = svmul_s32_x(p32, EEp_1, c_ct_2_0);
    svint32_t m3_1 = svmul_s32_x(p32, EOp_1, c_ct_3_0);
    svint32_t pa_1 = addp_s32(m0_1, m2_1);
    svint32_t pb_1 = addp_s32(m1_1, m3_1);
    svint32_t xa_1 = svuzp1_s32(pa_1, pb_1);
    svint32_t xb_1 = svuzp2_s32(pa_1, pb_1);
    svint16_t na_1 = svqrshrnb_n_s32(xa_1, 10);
    svint16_t nb_1 = svqrshrnb_n_s32(xb_1, 10);
    svint16_t n16_1 = svuzp1_s16(na_1, nb_1);
    st1d_scatter_s16(dst + 4, evoffs, n16_1);
    svint16_t z_8 = svld1_s16(p16, src + 8 * line);
    svint16_t z_9 = svld1_s16(p16, src + 9 * line);
    svint16_t z_10 = svld1_s16(p16, src + 10 * line);
    svint16_t z_11 = svld1_s16(p16, src + 11 * line);
    svint64_t pa0_2 = svreinterpret_s64_s16(z_8);
    svint64_t pa1_2 = svreinterpret_s64_s16(z_9);
    svint64_t pa2_2 = svreinterpret_s64_s16(z_10);
    svint64_t pa3_2 = svreinterpret_s64_s16(z_11);
    svint64_t pt0_2 = svzip1_s64(pa0_2, pa2_2);
    svint64_t pt1_2 = svzip2_s64(pa0_2, pa2_2);
    svint64_t pt2_2 = svzip1_s64(pa1_2, pa3_2);
    svint64_t pt3_2 = svzip2_s64(pa1_2, pa3_2);
    svint64_t pp0_2 = svzip1_s64(pt0_2, pt2_2);
    svint64_t pp1_2 = svzip2_s64(pt0_2, pt2_2);
    svint64_t pp2_2 = svzip1_s64(pt1_2, pt3_2);
    svint64_t pp3_2 = svzip2_s64(pt1_2, pt3_2);
    svint16_t q0_2 = svreinterpret_s16_s64(pp0_2);
    svint16_t q1_2 = svreinterpret_s16_s64(pp1_2);
    svint16_t v2_2 = svreinterpret_s16_s64(pp2_2);
    svint16_t q2_2 = revh_d(v2_2);
    svint16_t v3_2 = svreinterpret_s16_s64(pp3_2);
    svint16_t q3_2 = revh_d(v3_2);
    svint16_t QO0_2 = svsub_s16_x(p16, q0_2, q3_2);
    svint16_t QO1_2 = svsub_s16_x(p16, q1_2, q2_2);
    svint32_t e0_2 = svaddlb_s32(q0_2, q3_2);
    svint32_t e1_2 = svaddlt_s32(q0_2, q3_2);
    svint32_t e2_2 = svaddlb_s32(q1_2, q2_2);
    svint32_t e3_2 = svaddlt_s32(q1_2, q2_2);
    svint32_t w0_2 = svzip1_s32(e0_2, e1_2);
    svint32_t w1_2 = svzip2_s32(e0_2, e1_2);
    svint32_t u2_2 = revw_d32(e2_2);
    svint32_t u3_2 = revw_d32(e3_2);
    svint32_t w2_2 = svzip1_s32(u3_2, u2_2);
    svint32_t w3_2 = svzip2_s32(u3_2, u2_2);
    svint32_t s0_2 = svsub_s32_x(p32, w0_2, w2_2);
    svint32_t s1_2 = svsub_s32_x(p32, w1_2, w3_2);
    svint32_t s2_2 = svadd_s32_x(p32, w0_2, w2_2);
    svint32_t s3_2 = svadd_s32_x(p32, w1_2, w3_2);
    svint16_t QEOW_2 = svuzp1_s16(svreinterpret_s16_s32(s0_2), svreinterpret_s16_s32(s1_2));
    svint64_t v0_2 = svuzp1_s64(svreinterpret_s64_s32(s2_2), svreinterpret_s64_s32(s3_2));
    svint64_t v1_2 = svuzp2_s64(svreinterpret_s64_s32(s2_2), svreinterpret_s64_s32(s3_2));
    svint64_t v1r_2 = revw_d64(v1_2);
    svint32_t EEp_2 = svadd_s32_x(p32, svreinterpret_s32_s64(v0_2), svreinterpret_s32_s64(v1r_2));
    svint32_t EOp_2 = svsub_s32_x(p32, svreinterpret_s32_s64(v0_2), svreinterpret_s32_s64(v1r_2));
    svint32_t m0_2 = svmul_s32_x(p32, EEp_2, c_ct_0_0);
    svint32_t m1_2 = svmul_s32_x(p32, EOp_2, c_ct_1_0);
    svint32_t m2_2 = svmul_s32_x(p32, EEp_2, c_ct_2_0);
    svint32_t m3_2 = svmul_s32_x(p32, EOp_2, c_ct_3_0);
    svint32_t pa_2 = addp_s32(m0_2, m2_2);
    svint32_t pb_2 = addp_s32(m1_2, m3_2);
    svint32_t xa_2 = svuzp1_s32(pa_2, pb_2);
    svint32_t xb_2 = svuzp2_s32(pa_2, pb_2);
    svint16_t na_2 = svqrshrnb_n_s32(xa_2, 10);
    svint16_t nb_2 = svqrshrnb_n_s32(xb_2, 10);
    svint16_t n16_2 = svuzp1_s16(na_2, nb_2);
    st1d_scatter_s16(dst + 8, evoffs, n16_2);
    svint16_t z_12 = svld1_s16(p16, src + 12 * line);
    svint16_t z_13 = svld1_s16(p16, src + 13 * line);
    svint16_t z_14 = svld1_s16(p16, src + 14 * line);
    svint16_t z_15 = svld1_s16(p16, src + 15 * line);
    svint64_t pa0_3 = svreinterpret_s64_s16(z_12);
    svint64_t pa1_3 = svreinterpret_s64_s16(z_13);
    svint64_t pa2_3 = svreinterpret_s64_s16(z_14);
    svint64_t pa3_3 = svreinterpret_s64_s16(z_15);
    svint64_t pt0_3 = svzip1_s64(pa0_3, pa2_3);
    svint64_t pt1_3 = svzip2_s64(pa0_3, pa2_3);
    svint64_t pt2_3 = svzip1_s64(pa1_3, pa3_3);
    svint64_t pt3_3 = svzip2_s64(pa1_3, pa3_3);
    svint64_t pp0_3 = svzip1_s64(pt0_3, pt2_3);
    svint64_t pp1_3 = svzip2_s64(pt0_3, pt2_3);
    svint64_t pp2_3 = svzip1_s64(pt1_3, pt3_3);
    svint64_t pp3_3 = svzip2_s64(pt1_3, pt3_3);
    svint16_t q0_3 = svreinterpret_s16_s64(pp0_3);
    svint16_t q1_3 = svreinterpret_s16_s64(pp1_3);
    svint16_t v2_3 = svreinterpret_s16_s64(pp2_3);
    svint16_t q2_3 = revh_d(v2_3);
    svint16_t v3_3 = svreinterpret_s16_s64(pp3_3);
    svint16_t q3_3 = revh_d(v3_3);
    svint16_t QO0_3 = svsub_s16_x(p16, q0_3, q3_3);
    svint16_t QO1_3 = svsub_s16_x(p16, q1_3, q2_3);
    svint32_t e0_3 = svaddlb_s32(q0_3, q3_3);
    svint32_t e1_3 = svaddlt_s32(q0_3, q3_3);
    svint32_t e2_3 = svaddlb_s32(q1_3, q2_3);
    svint32_t e3_3 = svaddlt_s32(q1_3, q2_3);
    svint32_t w0_3 = svzip1_s32(e0_3, e1_3);
    svint32_t w1_3 = svzip2_s32(e0_3, e1_3);
    svint32_t u2_3 = revw_d32(e2_3);
    svint32_t u3_3 = revw_d32(e3_3);
    svint32_t w2_3 = svzip1_s32(u3_3, u2_3);
    svint32_t w3_3 = svzip2_s32(u3_3, u2_3);
    svint32_t s0_3 = svsub_s32_x(p32, w0_3, w2_3);
    svint32_t s1_3 = svsub_s32_x(p32, w1_3, w3_3);
    svint32_t s2_3 = svadd_s32_x(p32, w0_3, w2_3);
    svint32_t s3_3 = svadd_s32_x(p32, w1_3, w3_3);
    svint16_t QEOW_3 = svuzp1_s16(svreinterpret_s16_s32(s0_3), svreinterpret_s16_s32(s1_3));
    svint64_t v0_3 = svuzp1_s64(svreinterpret_s64_s32(s2_3), svreinterpret_s64_s32(s3_3));
    svint64_t v1_3 = svuzp2_s64(svreinterpret_s64_s32(s2_3), svreinterpret_s64_s32(s3_3));
    svint64_t v1r_3 = revw_d64(v1_3);
    svint32_t EEp_3 = svadd_s32_x(p32, svreinterpret_s32_s64(v0_3), svreinterpret_s32_s64(v1r_3));
    svint32_t EOp_3 = svsub_s32_x(p32, svreinterpret_s32_s64(v0_3), svreinterpret_s32_s64(v1r_3));
    svint32_t m0_3 = svmul_s32_x(p32, EEp_3, c_ct_0_0);
    svint32_t m1_3 = svmul_s32_x(p32, EOp_3, c_ct_1_0);
    svint32_t m2_3 = svmul_s32_x(p32, EEp_3, c_ct_2_0);
    svint32_t m3_3 = svmul_s32_x(p32, EOp_3, c_ct_3_0);
    svint32_t pa_3 = addp_s32(m0_3, m2_3);
    svint32_t pb_3 = addp_s32(m1_3, m3_3);
    svint32_t xa_3 = svuzp1_s32(pa_3, pb_3);
    svint32_t xb_3 = svuzp2_s32(pa_3, pb_3);
    svint16_t na_3 = svqrshrnb_n_s32(xa_3, 10);
    svint16_t nb_3 = svqrshrnb_n_s32(xb_3, 10);
    svint16_t n16_3 = svuzp1_s16(na_3, nb_3);
    st1d_scatter_s16(dst + 12, evoffs, n16_3);
    const svint16_t c_clo_1 = svld1_s16(p16, CQ_LO[1]);
    const svint16_t c_chi_1 = svld1_s16(p16, CQ_HI[1]);
    svint64_t d0_1_0 = svdot_s64(zero64, QO0_0, c_clo_1);
    svint64_t d1_1_0 = svdot_s64(d0_1_0, QO1_0, c_chi_1);
    svint64_t d0_1_1 = svdot_s64(zero64, QO0_1, c_clo_1);
    svint64_t d1_1_1 = svdot_s64(d0_1_1, QO1_1, c_chi_1);
    svint64_t d0_1_2 = svdot_s64(zero64, QO0_2, c_clo_1);
    svint64_t d1_1_2 = svdot_s64(d0_1_2, QO1_2, c_chi_1);
    svint64_t d0_1_3 = svdot_s64(zero64, QO0_3, c_clo_1);
    svint64_t d1_1_3 = svdot_s64(d0_1_3, QO1_3, c_chi_1);
    const svint32_t w01_nn_1 = svuzp1_s32(svreinterpret_s32_s64(d1_1_0), svreinterpret_s32_s64(d1_1_1));
    const svint32_t w23_nn_1 = svuzp1_s32(svreinterpret_s32_s64(d1_1_2), svreinterpret_s32_s64(d1_1_3));
    const svint16_t nb_nn_1 = svqrshrnb_n_s32(w01_nn_1, 10);
    const svint16_t nt_nn_1 = svqrshrnb_n_s32(w23_nn_1, 10);
    svint16_t nn_1 = svuzp1_s16(nb_nn_1, nt_nn_1);
    svst1_s16(p16, dst + 16 * 1 + 0, nn_1);
    const svint16_t c_clo_3 = svld1_s16(p16, CQ_LO[3]);
    const svint16_t c_chi_3 = svld1_s16(p16, CQ_HI[3]);
    svint64_t d0_3_0 = svdot_s64(zero64, QO0_0, c_clo_3);
    svint64_t d1_3_0 = svdot_s64(d0_3_0, QO1_0, c_chi_3);
    svint64_t d0_3_1 = svdot_s64(zero64, QO0_1, c_clo_3);
    svint64_t d1_3_1 = svdot_s64(d0_3_1, QO1_1, c_chi_3);
    svint64_t d0_3_2 = svdot_s64(zero64, QO0_2, c_clo_3);
    svint64_t d1_3_2 = svdot_s64(d0_3_2, QO1_2, c_chi_3);
    svint64_t d0_3_3 = svdot_s64(zero64, QO0_3, c_clo_3);
    svint64_t d1_3_3 = svdot_s64(d0_3_3, QO1_3, c_chi_3);
    const svint32_t w01_nn_3 = svuzp1_s32(svreinterpret_s32_s64(d1_3_0), svreinterpret_s32_s64(d1_3_1));
    const svint32_t w23_nn_3 = svuzp1_s32(svreinterpret_s32_s64(d1_3_2), svreinterpret_s32_s64(d1_3_3));
    const svint16_t nb_nn_3 = svqrshrnb_n_s32(w01_nn_3, 10);
    const svint16_t nt_nn_3 = svqrshrnb_n_s32(w23_nn_3, 10);
    svint16_t nn_3 = svuzp1_s16(nb_nn_3, nt_nn_3);
    svst1_s16(p16, dst + 16 * 3 + 0, nn_3);
    const svint16_t c_clo_5 = svld1_s16(p16, CQ_LO[5]);
    const svint16_t c_chi_5 = svld1_s16(p16, CQ_HI[5]);
    svint64_t d0_5_0 = svdot_s64(zero64, QO0_0, c_clo_5);
    svint64_t d1_5_0 = svdot_s64(d0_5_0, QO1_0, c_chi_5);
    svint64_t d0_5_1 = svdot_s64(zero64, QO0_1, c_clo_5);
    svint64_t d1_5_1 = svdot_s64(d0_5_1, QO1_1, c_chi_5);
    svint64_t d0_5_2 = svdot_s64(zero64, QO0_2, c_clo_5);
    svint64_t d1_5_2 = svdot_s64(d0_5_2, QO1_2, c_chi_5);
    svint64_t d0_5_3 = svdot_s64(zero64, QO0_3, c_clo_5);
    svint64_t d1_5_3 = svdot_s64(d0_5_3, QO1_3, c_chi_5);
    const svint32_t w01_nn_5 = svuzp1_s32(svreinterpret_s32_s64(d1_5_0), svreinterpret_s32_s64(d1_5_1));
    const svint32_t w23_nn_5 = svuzp1_s32(svreinterpret_s32_s64(d1_5_2), svreinterpret_s32_s64(d1_5_3));
    const svint16_t nb_nn_5 = svqrshrnb_n_s32(w01_nn_5, 10);
    const svint16_t nt_nn_5 = svqrshrnb_n_s32(w23_nn_5, 10);
    svint16_t nn_5 = svuzp1_s16(nb_nn_5, nt_nn_5);
    svst1_s16(p16, dst + 16 * 5 + 0, nn_5);
    const svint16_t c_clo_7 = svld1_s16(p16, CQ_LO[7]);
    const svint16_t c_chi_7 = svld1_s16(p16, CQ_HI[7]);
    svint64_t d0_7_0 = svdot_s64(zero64, QO0_0, c_clo_7);
    svint64_t d1_7_0 = svdot_s64(d0_7_0, QO1_0, c_chi_7);
    svint64_t d0_7_1 = svdot_s64(zero64, QO0_1, c_clo_7);
    svint64_t d1_7_1 = svdot_s64(d0_7_1, QO1_1, c_chi_7);
    svint64_t d0_7_2 = svdot_s64(zero64, QO0_2, c_clo_7);
    svint64_t d1_7_2 = svdot_s64(d0_7_2, QO1_2, c_chi_7);
    svint64_t d0_7_3 = svdot_s64(zero64, QO0_3, c_clo_7);
    svint64_t d1_7_3 = svdot_s64(d0_7_3, QO1_3, c_chi_7);
    const svint32_t w01_nn_7 = svuzp1_s32(svreinterpret_s32_s64(d1_7_0), svreinterpret_s32_s64(d1_7_1));
    const svint32_t w23_nn_7 = svuzp1_s32(svreinterpret_s32_s64(d1_7_2), svreinterpret_s32_s64(d1_7_3));
    const svint16_t nb_nn_7 = svqrshrnb_n_s32(w01_nn_7, 10);
    const svint16_t nt_nn_7 = svqrshrnb_n_s32(w23_nn_7, 10);
    svint16_t nn_7 = svuzp1_s16(nb_nn_7, nt_nn_7);
    svst1_s16(p16, dst + 16 * 7 + 0, nn_7);
    const svint16_t c_clo_9 = svld1_s16(p16, CQ_LO[9]);
    const svint16_t c_chi_9 = svld1_s16(p16, CQ_HI[9]);
    svint64_t d0_9_0 = svdot_s64(zero64, QO0_0, c_clo_9);
    svint64_t d1_9_0 = svdot_s64(d0_9_0, QO1_0, c_chi_9);
    svint64_t d0_9_1 = svdot_s64(zero64, QO0_1, c_clo_9);
    svint64_t d1_9_1 = svdot_s64(d0_9_1, QO1_1, c_chi_9);
    svint64_t d0_9_2 = svdot_s64(zero64, QO0_2, c_clo_9);
    svint64_t d1_9_2 = svdot_s64(d0_9_2, QO1_2, c_chi_9);
    svint64_t d0_9_3 = svdot_s64(zero64, QO0_3, c_clo_9);
    svint64_t d1_9_3 = svdot_s64(d0_9_3, QO1_3, c_chi_9);
    const svint32_t w01_nn_9 = svuzp1_s32(svreinterpret_s32_s64(d1_9_0), svreinterpret_s32_s64(d1_9_1));
    const svint32_t w23_nn_9 = svuzp1_s32(svreinterpret_s32_s64(d1_9_2), svreinterpret_s32_s64(d1_9_3));
    const svint16_t nb_nn_9 = svqrshrnb_n_s32(w01_nn_9, 10);
    const svint16_t nt_nn_9 = svqrshrnb_n_s32(w23_nn_9, 10);
    svint16_t nn_9 = svuzp1_s16(nb_nn_9, nt_nn_9);
    svst1_s16(p16, dst + 16 * 9 + 0, nn_9);
    const svint16_t c_clo_11 = svld1_s16(p16, CQ_LO[11]);
    const svint16_t c_chi_11 = svld1_s16(p16, CQ_HI[11]);
    svint64_t d0_11_0 = svdot_s64(zero64, QO0_0, c_clo_11);
    svint64_t d1_11_0 = svdot_s64(d0_11_0, QO1_0, c_chi_11);
    svint64_t d0_11_1 = svdot_s64(zero64, QO0_1, c_clo_11);
    svint64_t d1_11_1 = svdot_s64(d0_11_1, QO1_1, c_chi_11);
    svint64_t d0_11_2 = svdot_s64(zero64, QO0_2, c_clo_11);
    svint64_t d1_11_2 = svdot_s64(d0_11_2, QO1_2, c_chi_11);
    svint64_t d0_11_3 = svdot_s64(zero64, QO0_3, c_clo_11);
    svint64_t d1_11_3 = svdot_s64(d0_11_3, QO1_3, c_chi_11);
    const svint32_t w01_nn_11 = svuzp1_s32(svreinterpret_s32_s64(d1_11_0), svreinterpret_s32_s64(d1_11_1));
    const svint32_t w23_nn_11 = svuzp1_s32(svreinterpret_s32_s64(d1_11_2), svreinterpret_s32_s64(d1_11_3));
    const svint16_t nb_nn_11 = svqrshrnb_n_s32(w01_nn_11, 10);
    const svint16_t nt_nn_11 = svqrshrnb_n_s32(w23_nn_11, 10);
    svint16_t nn_11 = svuzp1_s16(nb_nn_11, nt_nn_11);
    svst1_s16(p16, dst + 16 * 11 + 0, nn_11);
    const svint16_t c_clo_13 = svld1_s16(p16, CQ_LO[13]);
    const svint16_t c_chi_13 = svld1_s16(p16, CQ_HI[13]);
    svint64_t d0_13_0 = svdot_s64(zero64, QO0_0, c_clo_13);
    svint64_t d1_13_0 = svdot_s64(d0_13_0, QO1_0, c_chi_13);
    svint64_t d0_13_1 = svdot_s64(zero64, QO0_1, c_clo_13);
    svint64_t d1_13_1 = svdot_s64(d0_13_1, QO1_1, c_chi_13);
    svint64_t d0_13_2 = svdot_s64(zero64, QO0_2, c_clo_13);
    svint64_t d1_13_2 = svdot_s64(d0_13_2, QO1_2, c_chi_13);
    svint64_t d0_13_3 = svdot_s64(zero64, QO0_3, c_clo_13);
    svint64_t d1_13_3 = svdot_s64(d0_13_3, QO1_3, c_chi_13);
    const svint32_t w01_nn_13 = svuzp1_s32(svreinterpret_s32_s64(d1_13_0), svreinterpret_s32_s64(d1_13_1));
    const svint32_t w23_nn_13 = svuzp1_s32(svreinterpret_s32_s64(d1_13_2), svreinterpret_s32_s64(d1_13_3));
    const svint16_t nb_nn_13 = svqrshrnb_n_s32(w01_nn_13, 10);
    const svint16_t nt_nn_13 = svqrshrnb_n_s32(w23_nn_13, 10);
    svint16_t nn_13 = svuzp1_s16(nb_nn_13, nt_nn_13);
    svst1_s16(p16, dst + 16 * 13 + 0, nn_13);
    const svint16_t c_clo_15 = svld1_s16(p16, CQ_LO[15]);
    const svint16_t c_chi_15 = svld1_s16(p16, CQ_HI[15]);
    svint64_t d0_15_0 = svdot_s64(zero64, QO0_0, c_clo_15);
    svint64_t d1_15_0 = svdot_s64(d0_15_0, QO1_0, c_chi_15);
    svint64_t d0_15_1 = svdot_s64(zero64, QO0_1, c_clo_15);
    svint64_t d1_15_1 = svdot_s64(d0_15_1, QO1_1, c_chi_15);
    svint64_t d0_15_2 = svdot_s64(zero64, QO0_2, c_clo_15);
    svint64_t d1_15_2 = svdot_s64(d0_15_2, QO1_2, c_chi_15);
    svint64_t d0_15_3 = svdot_s64(zero64, QO0_3, c_clo_15);
    svint64_t d1_15_3 = svdot_s64(d0_15_3, QO1_3, c_chi_15);
    const svint32_t w01_nn_15 = svuzp1_s32(svreinterpret_s32_s64(d1_15_0), svreinterpret_s32_s64(d1_15_1));
    const svint32_t w23_nn_15 = svuzp1_s32(svreinterpret_s32_s64(d1_15_2), svreinterpret_s32_s64(d1_15_3));
    const svint16_t nb_nn_15 = svqrshrnb_n_s32(w01_nn_15, 10);
    const svint16_t nt_nn_15 = svqrshrnb_n_s32(w23_nn_15, 10);
    svint16_t nn_15 = svuzp1_s16(nb_nn_15, nt_nn_15);
    svst1_s16(p16, dst + 16 * 15 + 0, nn_15);
    const svint16_t c_clo_2 = svld1_s16(p16, CQ_LO[2]);
    svint64_t d_2_0 = svdot_s64(zero64, QEOW_0, c_clo_2);
    svint64_t d_2_1 = svdot_s64(zero64, QEOW_1, c_clo_2);
    svint64_t d_2_2 = svdot_s64(zero64, QEOW_2, c_clo_2);
    svint64_t d_2_3 = svdot_s64(zero64, QEOW_3, c_clo_2);
    const svint32_t w01_nn_2 = svuzp1_s32(svreinterpret_s32_s64(d_2_0), svreinterpret_s32_s64(d_2_1));
    const svint32_t w23_nn_2 = svuzp1_s32(svreinterpret_s32_s64(d_2_2), svreinterpret_s32_s64(d_2_3));
    const svint16_t nb_nn_2 = svqrshrnb_n_s32(w01_nn_2, 10);
    const svint16_t nt_nn_2 = svqrshrnb_n_s32(w23_nn_2, 10);
    svint16_t nn_2 = svuzp1_s16(nb_nn_2, nt_nn_2);
    svst1_s16(p16, dst + 16 * 2 + 0, nn_2);
    const svint16_t c_clo_6 = svld1_s16(p16, CQ_LO[6]);
    svint64_t d_6_0 = svdot_s64(zero64, QEOW_0, c_clo_6);
    svint64_t d_6_1 = svdot_s64(zero64, QEOW_1, c_clo_6);
    svint64_t d_6_2 = svdot_s64(zero64, QEOW_2, c_clo_6);
    svint64_t d_6_3 = svdot_s64(zero64, QEOW_3, c_clo_6);
    const svint32_t w01_nn_6 = svuzp1_s32(svreinterpret_s32_s64(d_6_0), svreinterpret_s32_s64(d_6_1));
    const svint32_t w23_nn_6 = svuzp1_s32(svreinterpret_s32_s64(d_6_2), svreinterpret_s32_s64(d_6_3));
    const svint16_t nb_nn_6 = svqrshrnb_n_s32(w01_nn_6, 10);
    const svint16_t nt_nn_6 = svqrshrnb_n_s32(w23_nn_6, 10);
    svint16_t nn_6 = svuzp1_s16(nb_nn_6, nt_nn_6);
    svst1_s16(p16, dst + 16 * 6 + 0, nn_6);
    const svint16_t c_clo_10 = svld1_s16(p16, CQ_LO[10]);
    svint64_t d_10_0 = svdot_s64(zero64, QEOW_0, c_clo_10);
    svint64_t d_10_1 = svdot_s64(zero64, QEOW_1, c_clo_10);
    svint64_t d_10_2 = svdot_s64(zero64, QEOW_2, c_clo_10);
    svint64_t d_10_3 = svdot_s64(zero64, QEOW_3, c_clo_10);
    const svint32_t w01_nn_10 = svuzp1_s32(svreinterpret_s32_s64(d_10_0), svreinterpret_s32_s64(d_10_1));
    const svint32_t w23_nn_10 = svuzp1_s32(svreinterpret_s32_s64(d_10_2), svreinterpret_s32_s64(d_10_3));
    const svint16_t nb_nn_10 = svqrshrnb_n_s32(w01_nn_10, 10);
    const svint16_t nt_nn_10 = svqrshrnb_n_s32(w23_nn_10, 10);
    svint16_t nn_10 = svuzp1_s16(nb_nn_10, nt_nn_10);
    svst1_s16(p16, dst + 16 * 10 + 0, nn_10);
    const svint16_t c_clo_14 = svld1_s16(p16, CQ_LO[14]);
    svint64_t d_14_0 = svdot_s64(zero64, QEOW_0, c_clo_14);
    svint64_t d_14_1 = svdot_s64(zero64, QEOW_1, c_clo_14);
    svint64_t d_14_2 = svdot_s64(zero64, QEOW_2, c_clo_14);
    svint64_t d_14_3 = svdot_s64(zero64, QEOW_3, c_clo_14);
    const svint32_t w01_nn_14 = svuzp1_s32(svreinterpret_s32_s64(d_14_0), svreinterpret_s32_s64(d_14_1));
    const svint32_t w23_nn_14 = svuzp1_s32(svreinterpret_s32_s64(d_14_2), svreinterpret_s32_s64(d_14_3));
    const svint16_t nb_nn_14 = svqrshrnb_n_s32(w01_nn_14, 10);
    const svint16_t nt_nn_14 = svqrshrnb_n_s32(w23_nn_14, 10);
    svint16_t nn_14 = svuzp1_s16(nb_nn_14, nt_nn_14);
    svst1_s16(p16, dst + 16 * 14 + 0, nn_14);
}

extern "C" void dynopt_dct16_sve2_shared(const int16_t* src, int16_t* dst, intptr_t srcStride)
{
    int16_t coef[256];
    op_pass_4(src, coef, srcStride);
    op_pass_11(coef, dst);
}

extern "C" void dynopt_dct16_op_pass1(
    const int16_t* src, int16_t* dst, intptr_t srcStride)
{
    op_pass_4(src, dst, srcStride);
}

extern "C" void dynopt_dct16_op_pass2(
    const int16_t* src, int16_t* dst)
{
    op_pass_11(src, dst);
}
