// Generated by optimizer/ir/dct16_dual_sve_emit.py -- dual-group 16-lane SVE (VL=256-fixed, zero NEON).
#include <arm_sve.h>
#include <cstdint>


// Pure-SVE primitives (8 s16 lanes active at any VL).
static inline svint16_t psv_load8(const int16_t* p)
{
    svint16_t v;
    asm volatile("ld1h {%0.h}, %1/z, [%2]"
                 : "=w"(v)
                 : "Upl"(svptrue_pat_b16(SV_VL8)), "r"(p));
    return v;
}

static inline void psv_store8(int16_t* p, svint16_t v)
{
    asm volatile("st1h {%0.h}, %1, [%2]"
                 :
                 : "w"(v), "Upl"(svptrue_pat_b16(SV_VL8)), "r"(p));
}

static inline svint64_t psv_zero_s64(void)
{
    svint64_t v;
    asm volatile("mov %0.d, #0" : "=w"(v));
    return v;
}

static inline svuint16_t psv_load_idx(const uint16_t* p)
{
    svuint16_t v;
    asm volatile("ld1h {%0.h}, %1/z, [%2]"
                 : "=w"(v)
                 : "Upl"(svptrue_pat_b16(SV_VL8)), "r"(p));
    return v;
}

static inline svuint32_t psv_load_idx_u32(const uint32_t* p)
{
    svuint32_t v;
    asm volatile("ld1w {%0.s}, %1/z, [%2]"
                 : "=w"(v)
                 : "Upl"(svptrue_pat_b32(SV_VL4)), "r"(p));
    return v;
}

static inline svint16_t psv_rev16(svint16_t x)
{
    static const uint16_t idx[8] = { 7, 6, 5, 4, 3, 2, 1, 0 };
    svuint16_t i = psv_load_idx(idx);
    return svtbl_s16(x, i);
}

static inline svint16_t psv_rev32(svint16_t x)
{
    static const uint16_t idx[8] = { 1, 0, 3, 2, 5, 4, 7, 6 };
    svuint16_t i = psv_load_idx(idx);
    return svtbl_s16(x, i);
}

static inline svint64_t psv_sdot(svint64_t acc, svint16_t x, svint16_t y)
{
    return svdot_s64(acc, x, y);
}

static inline svint16_t psv_rshrn_s32_6(svint32_t x)
{
    return svrshrnb_n_s32(x, 6);
}

static inline svint16_t psv_addp_pair(svint16_t a, svint16_t b)
{
    // Pairwise add of adjacent 16-bit lanes: (a0+a1, a2+a3, b0+b1, ...)
    svint16_t lo = svuzp1_s16(a, b);
    svint16_t hi = svuzp2_s16(a, b);
    return svadd_s16_x(svptrue_pat_b16(SV_VL8), lo, hi);
}

// --- dct16 fused8 pure-SVE primitives (4-lane halves) ---
static inline svbool_t psv_pg8_s16(void) { return svptrue_pat_b16(SV_VL8); }
static inline svbool_t psv_pg4_s32(void) { return svptrue_pat_b32(SV_VL4); }
static inline svbool_t psv_pg2_s64(void) { return svptrue_pat_b64(SV_VL2); }

static inline svint32_t psv_load4_s32(const int32_t* p)
{
    svint32_t v;
    asm volatile("ld1w {%0.s}, %1/z, [%2]"
                 : "=w"(v)
                 : "Upl"(svptrue_pat_b32(SV_VL4)), "r"(p));
    return v;
}

static inline svint32_t psv_ld1sh_s32(const int16_t* p)
{
    svint32_t v;
    asm volatile("ld1sh {%0.s}, %1/z, [%2]"
                 : "=w"(v)
                 : "Upl"(svptrue_pat_b32(SV_VL4)), "r"(p));
    return v;
}

static inline void psv_store4_s16(int16_t* p, svint16_t v)
{
    asm volatile("st1h {%0.h}, %1, [%2]"
                 :
                 : "w"(v), "Upl"(svptrue_pat_b16(SV_VL4)), "r"(p));
}

static inline svint16_t psv_get_lo4_s16(svint16_t x)
{
    static const uint16_t idx[8] = { 0, 1, 2, 3, 0, 0, 0, 0 };
    return svtbl_s16(x, psv_load_idx(idx));
}

static inline svint16_t psv_get_hi4_s16(svint16_t x)
{
    static const uint16_t idx[8] = { 4, 5, 6, 7, 0, 0, 0, 0 };
    return svtbl_s16(x, psv_load_idx(idx));
}

static inline svint32_t psv_saddl_s16(svint16_t a, svint16_t b)
{
    return svadd_s32_x(svptrue_pat_b32(SV_VL4),
                       svunpklo_s32(a), svunpklo_s32(b));
}

static inline svint16_t psv_vmovn_s32(svint32_t x)
{
    // Truncating 32->16: take the low 16 bits of each lane (even lanes
    // of the reinterpreted s16 view).
    svint16_t r = svreinterpret_s16_s32(x);
    return svuzp1_s16(r, r);
}

static inline svint32_t psv_vmovn_s64(svint64_t x)
{
    svint32_t r = svreinterpret_s32_s64(x);
    return svuzp1_s32(r, r);
}

static inline svint16_t psv_combine4_s16(svint16_t a, svint16_t b)
{
    static const uint16_t idx[8] = { 0, 1, 2, 3, 8, 9, 10, 11 };
    svuint16x2_t t = svcreate2_u16(svreinterpret_u16_s16(a),
                                   svreinterpret_u16_s16(b));
    return svreinterpret_s16_u16(svtbl2_u16(t, psv_load_idx(idx)));
}

static inline svint32_t psv_combine4_s32(svint32_t a, svint32_t b)
{
    static const uint32_t idx[4] = { 0, 1, 4, 5 };
    svuint32_t i = psv_load_idx_u32(idx);
    svuint32x2_t t = svcreate2_u32(svreinterpret_u32_s32(a),
                                   svreinterpret_u32_s32(b));
    return svreinterpret_s32_u32(svtbl2_u32(t, i));
}

static inline svint32_t psv_addp4_s32(svint32_t a, svint32_t b)
{
    svint32_t lo = svuzp1_s32(a, b);
    svint32_t hi = svuzp2_s32(a, b);
    return svadd_s32_x(svptrue_pat_b32(SV_VL4), lo, hi);
}

static inline svint32_t psv_rev64_s32(svint32_t x)
{
    static const uint32_t idx[4] = { 1, 0, 3, 2 };
    svuint32_t i = psv_load_idx_u32(idx);
    return svreinterpret_s32_u32(svtbl_u32(svreinterpret_u32_s32(x), i));
}

static inline svint32_t psv_rev32_s32(svint32_t x)
{
    static const uint32_t idx[4] = { 3, 2, 1, 0 };
    svuint32_t i = psv_load_idx_u32(idx);
    return svreinterpret_s32_u32(svtbl_u32(svreinterpret_u32_s32(x), i));
}

template <int S>
static inline svint16_t psv_rshrn_s32(svint32_t x)
{
    svint32_t r = svasr_n_s32_x(svptrue_pat_b32(SV_VL4),
                                svadd_s32_x(svptrue_pat_b32(SV_VL4), x,
                                            svdup_s32_x(
                                                svptrue_pat_b32(SV_VL4),
                                                1 << (S - 1))), S);
    svint16_t n = svreinterpret_s16_s32(r);
    return svuzp1_s16(n, n);
}

// --- 16-lane (full-VL) primitives for the VL=256 emitter ---
static inline svint16_t psv16_load(const int16_t* p)
{
    return svld1_s16(svptrue_b16(), p);
}

static inline void psv16_store(int16_t* p, svint16_t v)
{
    svst1_s16(svptrue_b16(), p, v);
}

static inline svint16_t psv16_rev(svint16_t x)
{
    return svrev_s16(x);
}

static inline svint64_t psv16_sdot(svint64_t acc, svint16_t x, svint16_t y)
{
    return svdot_s64(acc, x, y);
}

static inline svint16_t psv16_rshrn6(svint32_t x)
{
    return svrshrnb_n_s32(x, 6);
}

static inline svint32_t psv16_rshrn_s64_12(svint64_t x)
{
    return svrshrnb_n_s64(x, 12);
}

// Packed dual-group 16-lane primitives for the VL=256 emitter: each
// 16-lane register carries two independent 8-lane groups (lanes 0-7,
// 8-15). Operations below act on both groups simultaneously.
static inline svint16_t psv16_dual_rev16(svint16_t x)
{
    static const uint16_t idx[16] =
        { 7, 6, 5, 4, 3, 2, 1, 0, 15, 14, 13, 12, 11, 10, 9, 8 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    return svreinterpret_s16_u16(svtbl_u16(svreinterpret_u16_s16(x), i));
}

static inline svint16_t psv16_dual_vget_lo4(svint16_t x)
{
    // low 4 lanes of each 8-lane group -> lanes 0-3 and 8-11.
    static const uint16_t idx[16] =
        { 0, 1, 2, 3, 0, 0, 0, 0, 8, 9, 10, 11, 0, 0, 0, 0 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    return svreinterpret_s16_u16(svtbl_u16(svreinterpret_u16_s16(x), i));
}

static inline svint16_t psv16_dual_vget_hi4(svint16_t x)
{
    static const uint16_t idx[16] =
        { 4, 5, 6, 7, 0, 0, 0, 0, 12, 13, 14, 15, 0, 0, 0, 0 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    return svreinterpret_s16_u16(svtbl_u16(svreinterpret_u16_s16(x), i));
}

static inline svint16_t psv16_rev_hi(svint16_t x)
{
    static const uint16_t idx[16] =
        { 0, 1, 2, 3, 4, 5, 6, 7, 15, 14, 13, 12, 11, 10, 9, 8 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    return svreinterpret_s16_u16(svtbl_u16(svreinterpret_u16_s16(x), i));
}

static inline svint16_t psv16_rev_lo(svint16_t x)
{
    static const uint16_t idx[16] =
        { 7, 6, 5, 4, 3, 2, 1, 0, 8, 9, 10, 11, 12, 13, 14, 15 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    return svreinterpret_s16_u16(svtbl_u16(svreinterpret_u16_s16(x), i));
}

// Dual widening add: group0 (s16 lanes 0-7) and group1 (s16 lanes
// 8-15); each group's low-4 widen to s32 -> result s32 lanes 0-3
// (group0) and 4-7 (group1).
static inline svint32_t psv16_dual_saddl(svint16_t a, svint16_t b)
{
    svint16_t al = psv16_dual_vget_lo4(a);
    svint16_t bl = psv16_dual_vget_lo4(b);
    svint32_t a0 = svunpklo_s32(al);  // lanes 0-3 = a[0..3] widened
    svint32_t a1 = svunpkhi_s32(al);  // lanes 0-3 = a[8..11] widened
    svint32_t b0 = svunpklo_s32(bl);
    svint32_t b1 = svunpkhi_s32(bl);
    svint32_t s0 = svadd_s32_x(svptrue_b32(), a0, b0);
    svint32_t s1 = svadd_s32_x(svptrue_b32(), a1, b1);
    static const uint32_t idx[8] = { 0, 1, 2, 3, 8, 9, 10, 11 };
    svuint32_t i = svld1_u32(svptrue_b32(), idx);
    svuint32x2_t t = svcreate2_u32(svreinterpret_u32_s32(s0),
                                   svreinterpret_u32_s32(s1));
    return svreinterpret_s32_u32(svtbl2_u32(t, i));
}

// Truncating narrow of both s32 groups (input lanes 0-3 / 4-7) to a
// dual 4-lane s16 result (group0 lanes 0-3, group1 lanes 8-11).
static inline svint16_t psv16_dual_vmovn_s32(svint32_t x)
{
    svint16_t r = svreinterpret_s16_s32(x);
    static const uint16_t idx[16] =
        { 0, 2, 4, 6, 0, 0, 0, 0, 8, 10, 12, 14, 0, 0, 0, 0 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    return svreinterpret_s16_u16(svtbl_u16(svreinterpret_u16_s16(r), i));
}

// Combine two dual 4-lane s16 values (a/b) into a 16-lane dual value:
// lanes 0-7 = [a_g0_lo, b_g0_hi], lanes 8-15 = [a_g1_lo, b_g1_hi].
static inline svint16_t psv16_dual_combine4_s16(svint16_t a, svint16_t b)
{
    static const uint16_t idx[16] =
        { 0, 1, 2, 3, 16, 17, 18, 19, 8, 9, 10, 11, 24, 25, 26, 27 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    svuint16x2_t t = svcreate2_u16(svreinterpret_u16_s16(a),
                                   svreinterpret_u16_s16(b));
    return svreinterpret_s16_u16(svtbl2_u16(t, i));
}

// Pairwise add within each s32 group (a/b each 8 lanes: g0 lanes 0-3,
// g1 lanes 4-7) -> result lanes: g0 = [a0+a1,a2+a3,b0+b1,b2+b3],
// g1 = [a4+a5,a6+a7,b4+b5,b6+b7].
static inline svint32_t psv16_dual_addp4_s32(svint32_t a, svint32_t b)
{
    svint32_t lo = svuzp1_s32(a, b);
    svint32_t hi = svuzp2_s32(a, b);
    svint32_t s = svadd_s32_x(svptrue_b32(), lo, hi);
    static const uint32_t idx[8] = { 0, 1, 4, 5, 2, 3, 6, 7 };
    svuint32_t i = svld1_u32(svptrue_b32(), idx);
    return svreinterpret_s32_u32(svtbl_u32(svreinterpret_u32_s32(s), i));
}

// Pack two 8-lane loads (from a and b) into one 16-lane register.
static inline svint16_t psv16_dual_load8(const int16_t* a, const int16_t* b)
{
    static const uint16_t idx[16] =
        { 0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    svuint16x2_t t = svcreate2_u16(
        svreinterpret_u16_s16(psv16_load(a)),
        svreinterpret_u16_s16(psv16_load(b)));
    return svreinterpret_s16_u16(svtbl2_u16(t, i));
}

static inline svint32_t psv16_dual_rev32_s32(svint32_t x)
{
    static const uint32_t idx[8] = { 3, 2, 1, 0, 7, 6, 5, 4 };
    svuint32_t i = svld1_u32(svptrue_b32(), idx);
    return svreinterpret_s32_u32(svtbl_u32(svreinterpret_u32_s32(x), i));
}

static inline svint32_t psv16_dual_rev64_s32(svint32_t x)
{
    static const uint32_t idx[8] = { 1, 0, 3, 2, 5, 4, 7, 6 };
    svuint32_t i = svld1_u32(svptrue_b32(), idx);
    return svreinterpret_s32_u32(svtbl_u32(svreinterpret_u32_s32(x), i));
}

// Truncating narrow of both s64 groups (input lanes 0-1 / 2-3) to a
// dual s32 result (group0 lanes 0-1, group1 lanes 2-3).
static inline svint32_t psv16_dual_vmovn_s64(svint64_t x)
{
    svint32_t r = svreinterpret_s32_s64(x);
    static const uint32_t idx[8] = { 0, 2, 4, 6, 0, 0, 0, 0 };
    svuint32_t i = svld1_u32(svptrue_b32(), idx);
    return svreinterpret_s32_u32(svtbl_u32(svreinterpret_u32_s32(r), i));
}

template <int S>
static inline svint16_t psv16_dual_rshrn_s32(svint32_t x)
{
    svint32_t r = svasr_n_s32_x(svptrue_b32(),
                                svadd_s32_x(svptrue_b32(), x,
                                            svdup_s32_x(svptrue_b32(),
                                                        1 << (S - 1))), S);
    return psv16_dual_vmovn_s32(r);
}

// Store a dual 4-lane s16 value: group0 (lanes 0-3) -> *pa, group1
// (lanes 8-11) -> *pb.
static inline void psv16_dual_store4_s16(int16_t* pa, int16_t* pb,
                                         svint16_t v)
{
    psv_store4_s16(pa, v);
    static const uint16_t idx[16] =
        { 8, 9, 10, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    svint16_t g = svreinterpret_s16_u16(
        svtbl_u16(svreinterpret_u16_s16(v), i));
    psv_store4_s16(pb, g);
}

// --- dual-group helper additions for the VL=256 emitter (docs/72) ---
// Safe 8-lane dual load: loads exactly 8 lanes from a and b (no
// full-VL over-read), packs group0 = a[0..7], group1 = b[0..7].
static inline svint16_t psv16_dual_load8_safe(const int16_t* a,
                                               const int16_t* b)
{
    svint16_t la = psv_load8(a);
    svint16_t lb = psv_load8(b);
    static const uint16_t idx[16] =
        { 0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    svuint16x2_t t = svcreate2_u16(svreinterpret_u16_s16(la),
                                   svreinterpret_u16_s16(lb));
    return svreinterpret_s16_u16(svtbl2_u16(t, i));
}

// Duplicate one 8-lane constant row into both groups (g0 = g1 = row).
static inline svint16_t psv16_dup8_s16(const int16_t* p)
{
    svint16_t v = psv_load8(p);
    static const uint16_t idx[16] =
        { 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    return svreinterpret_s16_u16(
        svtbl_u16(svreinterpret_u16_s16(v), i));
}

// Duplicate one 4-lane s32 constant row into both groups.
static inline svint32_t psv16_dup4_s32(const int32_t* p)
{
    svint32_t v = psv_load4_s32(p);
    static const uint32_t idx[8] = { 0, 1, 2, 3, 0, 1, 2, 3 };
    svuint32_t i = svld1_u32(svptrue_b32(), idx);
    return svreinterpret_s32_u32(
        svtbl_u32(svreinterpret_u32_s32(v), i));
}

// Pack two pair-form s16 dual registers into one quad-form register:
// a = [r0(0-3), pad, r1(8-11), pad], b = [r2(0-3), pad, r3(8-11), pad]
// -> lanes [r0, r1, r2, r3] at 0-3/4-7/8-11/12-15.
static inline svint16_t psv16_quad_pack_s16(svint16_t a, svint16_t b)
{
    static const uint16_t idx[16] =
        { 0, 1, 2, 3, 8, 9, 10, 11, 16, 17, 18, 19, 24, 25, 26, 27 };
    svuint16_t i = svld1_u16(svptrue_b16(), idx);
    svuint16x2_t t = svcreate2_u16(svreinterpret_u16_s16(a),
                                   svreinterpret_u16_s16(b));
    return svreinterpret_s16_u16(svtbl2_u16(t, i));
}

// Raw pairwise-add helper: uzp1(a,b)+uzp2(a,b) with NO lane
// permutation (the dual_addp4 helper permutes; this one keeps the
// natural [g0 partials, g1 partials] order).
static inline svint32_t psv16_pairwise_add_s32(svint32_t a, svint32_t b)
{
    return svadd_s32_x(svptrue_b32(), svuzp1_s32(a, b),
                       svuzp2_s32(a, b));
}

// Cross-pack the g0 (lanes 0-3) of two dual s32 registers into one
// 8-lane s32 register: out = [a.g0, b.g0].  The 8-lane pairwise-add
// pattern (uzp1/uzp2 + add) is only layout-correct when both groups'
// values are contiguous in one register, so this pack must precede it.
static inline svint32_t psv16_combine_g0_s32(svint32_t a, svint32_t b)
{
    static const uint32_t idx[8] = { 0, 1, 2, 3, 8, 9, 10, 11 };
    svuint32_t i = svld1_u32(svptrue_b32(), idx);
    svuint32x2_t t = svcreate2_u32(svreinterpret_u32_s32(a),
                                   svreinterpret_u32_s32(b));
    return svreinterpret_s32_u32(svtbl2_u32(t, i));
}

static const int16_t C8[16][8] = {
    { 64, 64, 64, 64, 64, 64, 64, 64 },
    { 90, 87, 80, 70, 57, 43, 25, 9 },
    { 89, 75, 50, 18, -18, -50, -75, -89 },
    { 87, 57, 9, -43, -80, -90, -70, -25 },
    { 83, 36, -36, -83, -83, -36, 36, 83 },
    { 80, 9, -70, -87, -25, 57, 90, 43 },
    { 75, -18, -89, -50, 50, 89, 18, -75 },
    { 70, -43, -87, 9, 90, 25, -80, -57 },
    { 64, -64, -64, 64, 64, -64, -64, 64 },
    { 57, -80, -25, 90, -9, -87, 43, 70 },
    { 50, -89, 18, 75, -75, -18, 89, -50 },
    { 43, -90, 57, 25, -87, 70, 9, -80 },
    { 36, -83, 83, -36, -36, 83, -83, 36 },
    { 25, -70, 90, -80, 43, 9, -57, 87 },
    { 18, -50, 75, -89, 89, -75, 50, -18 },
    { 9, -25, 43, -57, 70, -80, 87, -90 },
};

static const int16_t GT16[16][8] = {
    { 64, 64, 64, 64, 64, 64, 64, 64 },
    { 90, 87, 80, 70, 57, 43, 25, 9 },
    { 89, 75, 50, 18, -18, -50, -75, -89 },
    { 87, 57, 9, -43, -80, -90, -70, -25 },
    { 83, 36, -36, -83, -83, -36, 36, 83 },
    { 80, 9, -70, -87, -25, 57, 90, 43 },
    { 75, -18, -89, -50, 50, 89, 18, -75 },
    { 70, -43, -87, 9, 90, 25, -80, -57 },
    { 64, -64, -64, 64, 64, -64, -64, 64 },
    { 57, -80, -25, 90, -9, -87, 43, 70 },
    { 50, -89, 18, 75, -75, -18, 89, -50 },
    { 43, -90, 57, 25, -87, 70, 9, -80 },
    { 36, -83, 83, -36, -36, 83, -83, 36 },
    { 25, -70, 90, -80, 43, 9, -57, 87 },
    { 18, -50, 75, -89, 89, -75, 50, -18 },
    { 9, -25, 43, -57, 70, -80, 87, -90 },
};

static const int32_t GT16_S32[4][4] = {
    { 89, 75, 50, 18 },
    { 75, -18, -89, -50 },
    { 50, -89, 18, 75 },
    { 18, -50, 75, -89 },
};

static const int32_t T8E[4][4] = {
    { 64, 64, 64, 64 },
    { 83, 36, 83, 36 },
    { 64, -64, 64, -64 },
    { 36, -83, 36, -83 },
};

static const int16_t T8ODD16[4][8] = {
    { 89,  75,  50,  18, 89,  75,  50,  18 },
    { 75, -18, -89, -50, 75, -18, -89, -50 },
    { 50, -89,  18,  75, 50, -89,  18,  75 },
    { 18, -50,  75, -89, 18, -50,  75, -89 },
};
static const int16_t CQ_LO[16][16] = {
    { 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64 },
    { 90, 87, 80, 70, 90, 87, 80, 70, 90, 87, 80, 70, 90, 87, 80, 70 },
    { 89, 75, 50, 18, 89, 75, 50, 18, 89, 75, 50, 18, 89, 75, 50, 18 },
    { 87, 57, 9, -43, 87, 57, 9, -43, 87, 57, 9, -43, 87, 57, 9, -43 },
    { 83, 36, -36, -83, 83, 36, -36, -83, 83, 36, -36, -83, 83, 36, -36, -83 },
    { 80, 9, -70, -87, 80, 9, -70, -87, 80, 9, -70, -87, 80, 9, -70, -87 },
    { 75, -18, -89, -50, 75, -18, -89, -50, 75, -18, -89, -50, 75, -18, -89, -50 },
    { 70, -43, -87, 9, 70, -43, -87, 9, 70, -43, -87, 9, 70, -43, -87, 9 },
    { 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64 },
    { 57, -80, -25, 90, 57, -80, -25, 90, 57, -80, -25, 90, 57, -80, -25, 90 },
    { 50, -89, 18, 75, 50, -89, 18, 75, 50, -89, 18, 75, 50, -89, 18, 75 },
    { 43, -90, 57, 25, 43, -90, 57, 25, 43, -90, 57, 25, 43, -90, 57, 25 },
    { 36, -83, 83, -36, 36, -83, 83, -36, 36, -83, 83, -36, 36, -83, 83, -36 },
    { 25, -70, 90, -80, 25, -70, 90, -80, 25, -70, 90, -80, 25, -70, 90, -80 },
    { 18, -50, 75, -89, 18, -50, 75, -89, 18, -50, 75, -89, 18, -50, 75, -89 },
    { 9, -25, 43, -57, 9, -25, 43, -57, 9, -25, 43, -57, 9, -25, 43, -57 },
};
static const int16_t CQ_HI[16][16] = {
    { 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64 },
    { 57, 43, 25, 9, 57, 43, 25, 9, 57, 43, 25, 9, 57, 43, 25, 9 },
    { -18, -50, -75, -89, -18, -50, -75, -89, -18, -50, -75, -89, -18, -50, -75, -89 },
    { -80, -90, -70, -25, -80, -90, -70, -25, -80, -90, -70, -25, -80, -90, -70, -25 },
    { -83, -36, 36, 83, -83, -36, 36, 83, -83, -36, 36, 83, -83, -36, 36, 83 },
    { -25, 57, 90, 43, -25, 57, 90, 43, -25, 57, 90, 43, -25, 57, 90, 43 },
    { 50, 89, 18, -75, 50, 89, 18, -75, 50, 89, 18, -75, 50, 89, 18, -75 },
    { 90, 25, -80, -57, 90, 25, -80, -57, 90, 25, -80, -57, 90, 25, -80, -57 },
    { 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64 },
    { -9, -87, 43, 70, -9, -87, 43, 70, -9, -87, 43, 70, -9, -87, 43, 70 },
    { -75, -18, 89, -50, -75, -18, 89, -50, -75, -18, 89, -50, -75, -18, 89, -50 },
    { -87, 70, 9, -80, -87, 70, 9, -80, -87, 70, 9, -80, -87, 70, 9, -80 },
    { -36, 83, -83, 36, -36, 83, -83, 36, -36, 83, -83, 36, -36, 83, -83, 36 },
    { 43, 9, -57, 87, 43, 9, -57, 87, 43, 9, -57, 87, 43, 9, -57, 87 },
    { 89, -75, 50, -18, 89, -75, 50, -18, 89, -75, 50, -18, 89, -75, 50, -18 },
    { 70, -80, 87, -90, 70, -80, 87, -90, 70, -80, 87, -90, 70, -80, 87, -90 },
};
static const int32_t T8E8[4][8] = {
    { 64, 64, 64, 64, 64, 64, 64, 64 },
    { 83, 36, 83, 36, 83, 36, 83, 36 },
    { 64, -64, 64, -64, 64, -64, 64, -64 },
    { 36, -83, 36, -83, 36, -83, 36, -83 },
};
static const int64_t EVEN_OFFS[4] = { 0, 128, 256, 384 };


static inline void op_pass_4_dual(const int16_t* src, int16_t* dst,
                                  intptr_t stride)
{
    const int line = 16;
    const int shift = 3;
    for (int i = 0; i < line; i += 4)
    {
        // Pair A: rows i+0, i+1; pair B: rows i+2, i+3.
        const svint16_t sA_lo = psv16_dual_load8_safe(
            src + (i + 0) * stride, src + (i + 1) * stride);
        const svint16_t sA_hi_raw = psv16_dual_load8_safe(
            src + (i + 0) * stride + 8, src + (i + 1) * stride + 8);
        svint16_t sA_hi = psv16_dual_rev16(sA_hi_raw);
        svint16_t O_A = svsub_s16_x(svptrue_b16(), sA_lo, sA_hi);
        svint16_t g0_A_a = psv16_dual_vget_lo4(sA_lo);
        svint16_t g0_A_c = psv16_dual_vget_lo4(sA_hi);
        svint32_t E0_A = psv16_dual_saddl(g0_A_a, g0_A_c);
        svint16_t g1_A_a = psv16_dual_vget_hi4(sA_lo);
        svint16_t g1_A_c = psv16_dual_vget_hi4(sA_hi);
        svint32_t E1_A = psv16_dual_saddl(g1_A_a, g1_A_c);
        svint32_t EO_A = svsub_s32_x(svptrue_b32(), E0_A,
                                     psv16_dual_rev32_s32(E1_A));
        svint16_t EO_A_s16 = psv16_dual_vmovn_s32(EO_A);

        const svint16_t sB_lo = psv16_dual_load8_safe(
            src + (i + 2) * stride, src + (i + 3) * stride);
        const svint16_t sB_hi_raw = psv16_dual_load8_safe(
            src + (i + 2) * stride + 8, src + (i + 3) * stride + 8);
        svint16_t sB_hi = psv16_dual_rev16(sB_hi_raw);
        svint16_t O_B = svsub_s16_x(svptrue_b16(), sB_lo, sB_hi);
        svint16_t g0_B_a = psv16_dual_vget_lo4(sB_lo);
        svint16_t g0_B_c = psv16_dual_vget_lo4(sB_hi);
        svint32_t E0_B = psv16_dual_saddl(g0_B_a, g0_B_c);
        svint16_t g1_B_a = psv16_dual_vget_hi4(sB_lo);
        svint16_t g1_B_c = psv16_dual_vget_hi4(sB_hi);
        svint32_t E1_B = psv16_dual_saddl(g1_B_a, g1_B_c);
        svint32_t EO_B = svsub_s32_x(svptrue_b32(), E0_B,
                                     psv16_dual_rev32_s32(E1_B));
        svint16_t EO_B_s16 = psv16_dual_vmovn_s32(EO_B);

        // Quad-form EO for the k = 2 mod 4 sdot loop:
        // lanes [r0, r1, r2, r3] at 0-3/4-7/8-11/12-15.
        svint16_t EO_quad = psv16_quad_pack_s16(EO_A_s16, EO_B_s16);

        // Even-even/even-odd values per row pair (g1 = 0 by
        // construction, mirroring the 8-lane per-pair 4-lane values).
        svint32_t EE_A = svadd_s32_x(svptrue_b32(), E0_A,
                                     psv16_dual_rev32_s32(E1_A));
        svint32_t t0_A = svreinterpret_s32_s64(svuzp1_s64(
            svreinterpret_s64_s32(EE_A), psv_zero_s64()));
        svint32_t z2_A = svreinterpret_s32_s64(svuzp2_s64(
            svreinterpret_s64_s32(EE_A), psv_zero_s64()));
        svint32_t t1_A = psv16_dual_rev64_s32(z2_A);
        svint32_t EEE_A = svadd_s32_x(svptrue_b32(), t0_A, t1_A);
        svint32_t EEO_A = svsub_s32_x(svptrue_b32(), t0_A, t1_A);

        svint32_t EE_B = svadd_s32_x(svptrue_b32(), E0_B,
                                     psv16_dual_rev32_s32(E1_B));
        svint32_t t0_B = svreinterpret_s32_s64(svuzp1_s64(
            svreinterpret_s64_s32(EE_B), psv_zero_s64()));
        svint32_t z2_B = svreinterpret_s32_s64(svuzp2_s64(
            svreinterpret_s64_s32(EE_B), psv_zero_s64()));
        svint32_t t1_B = psv16_dual_rev64_s32(z2_B);
        svint32_t EEE_B = svadd_s32_x(svptrue_b32(), t0_B, t1_B);
        svint32_t EEO_B = svsub_s32_x(svptrue_b32(), t0_B, t1_B);

        for (int k = 1; k < 16; k += 2)
        {
            const svint16_t c = psv16_dup8_s16(GT16[k]);
            svint64_t t_A = psv16_sdot(psv_zero_s64(), c, O_A);
            svint64_t t_B = psv16_sdot(psv_zero_s64(), c, O_B);
            const svint32_t t01 = psv16_dual_vmovn_s64(t_A);
            const svint32_t t23 = psv16_dual_vmovn_s64(t_B);
            const svint32_t cmb = psv16_combine_g0_s32(t01, t23);
            const svint32_t w = psv16_pairwise_add_s32(cmb, cmb);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(w);
            psv_store4_s16(dst + 16 * k + i, nn);
        }

        for (int k = 2; k < 16; k += 4)
        {
            const svint16_t c = psv16_dup8_s16(T8ODD16[(k - 2) / 4]);
            svint64_t t = psv16_sdot(psv_zero_s64(), c, EO_quad);
            const svint32_t w = psv16_dual_vmovn_s64(t);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(w);
            psv_store4_s16(dst + 16 * k + i, nn);
        }

        {
            const svint32_t c = psv16_dup4_s32(T8E[0]);
            svint32_t cmb = psv16_combine_g0_s32(EEE_A, EEE_B);
            svint32_t pp = psv16_pairwise_add_s32(cmb, cmb);
            svint32_t m = svmul_s32_x(svptrue_b32(), c, pp);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(m);
            psv_store4_s16(dst + 16 * 0 + i, nn);
        }
        {
            const svint32_t c = psv16_dup4_s32(T8E[1]);
            svint32_t m0 = svmul_s32_x(svptrue_b32(), c, EEO_A);
            svint32_t m1 = svmul_s32_x(svptrue_b32(), c, EEO_B);
            svint32_t cmb = psv16_combine_g0_s32(m0, m1);
            svint32_t m = psv16_pairwise_add_s32(cmb, cmb);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(m);
            psv_store4_s16(dst + 16 * 4 + i, nn);
        }
        {
            const svint32_t c = psv16_dup4_s32(T8E[2]);
            svint32_t m0 = svmul_s32_x(svptrue_b32(), c, EEE_A);
            svint32_t m1 = svmul_s32_x(svptrue_b32(), c, EEE_B);
            svint32_t cmb = psv16_combine_g0_s32(m0, m1);
            svint32_t m = psv16_pairwise_add_s32(cmb, cmb);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(m);
            psv_store4_s16(dst + 16 * 8 + i, nn);
        }
        {
            const svint32_t c = psv16_dup4_s32(T8E[3]);
            svint32_t m0 = svmul_s32_x(svptrue_b32(), c, EEO_A);
            svint32_t m1 = svmul_s32_x(svptrue_b32(), c, EEO_B);
            svint32_t cmb = psv16_combine_g0_s32(m0, m1);
            svint32_t m = psv16_pairwise_add_s32(cmb, cmb);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(m);
            psv_store4_s16(dst + 16 * 12 + i, nn);
        }
    }
}


static inline void op_pass_11_dual(const int16_t* src, int16_t* dst)
{
    const int line = 16;
    const int shift = 10;
    for (int i = 0; i < line; i += 4)
    {
        // Pair A: rows i+0, i+1; pair B: rows i+2, i+3.
        const svint16_t sA_lo = psv16_dual_load8_safe(
            src + (i + 0) * line, src + (i + 1) * line);
        const svint16_t sA_hi_raw = psv16_dual_load8_safe(
            src + (i + 0) * line + 8, src + (i + 1) * line + 8);
        svint16_t sA_hi = psv16_dual_rev16(sA_hi_raw);
        svint16_t O_A = svsub_s16_x(svptrue_b16(), sA_lo, sA_hi);
        svint16_t g0_A_a = psv16_dual_vget_lo4(sA_lo);
        svint16_t g0_A_c = psv16_dual_vget_lo4(sA_hi);
        svint32_t E0_A = psv16_dual_saddl(g0_A_a, g0_A_c);
        svint16_t g1_A_a = psv16_dual_vget_hi4(sA_lo);
        svint16_t g1_A_c = psv16_dual_vget_hi4(sA_hi);
        svint32_t E1_A = psv16_dual_saddl(g1_A_a, g1_A_c);
        svint32_t EO_A = svsub_s32_x(svptrue_b32(), E0_A,
                                     psv16_dual_rev32_s32(E1_A));

        const svint16_t sB_lo = psv16_dual_load8_safe(
            src + (i + 2) * line, src + (i + 3) * line);
        const svint16_t sB_hi_raw = psv16_dual_load8_safe(
            src + (i + 2) * line + 8, src + (i + 3) * line + 8);
        svint16_t sB_hi = psv16_dual_rev16(sB_hi_raw);
        svint16_t O_B = svsub_s16_x(svptrue_b16(), sB_lo, sB_hi);
        svint16_t g0_B_a = psv16_dual_vget_lo4(sB_lo);
        svint16_t g0_B_c = psv16_dual_vget_lo4(sB_hi);
        svint32_t E0_B = psv16_dual_saddl(g0_B_a, g0_B_c);
        svint16_t g1_B_a = psv16_dual_vget_hi4(sB_lo);
        svint16_t g1_B_c = psv16_dual_vget_hi4(sB_hi);
        svint32_t E1_B = psv16_dual_saddl(g1_B_a, g1_B_c);
        svint32_t EO_B = svsub_s32_x(svptrue_b32(), E0_B,
                                     psv16_dual_rev32_s32(E1_B));

        // Quad-form EO for the k = 2 mod 4 sdot loop:
        // lanes [r0, r1, r2, r3] at 0-3/4-7/8-11/12-15.

        // Even-even/even-odd values per row pair (g1 = 0 by
        // construction, mirroring the 8-lane per-pair 4-lane values).
        svint32_t EE_A = svadd_s32_x(svptrue_b32(), E0_A,
                                     psv16_dual_rev32_s32(E1_A));
        svint32_t t0_A = svreinterpret_s32_s64(svuzp1_s64(
            svreinterpret_s64_s32(EE_A), psv_zero_s64()));
        svint32_t z2_A = svreinterpret_s32_s64(svuzp2_s64(
            svreinterpret_s64_s32(EE_A), psv_zero_s64()));
        svint32_t t1_A = psv16_dual_rev64_s32(z2_A);
        svint32_t EEE_A = svadd_s32_x(svptrue_b32(), t0_A, t1_A);
        svint32_t EEO_A = svsub_s32_x(svptrue_b32(), t0_A, t1_A);

        svint32_t EE_B = svadd_s32_x(svptrue_b32(), E0_B,
                                     psv16_dual_rev32_s32(E1_B));
        svint32_t t0_B = svreinterpret_s32_s64(svuzp1_s64(
            svreinterpret_s64_s32(EE_B), psv_zero_s64()));
        svint32_t z2_B = svreinterpret_s32_s64(svuzp2_s64(
            svreinterpret_s64_s32(EE_B), psv_zero_s64()));
        svint32_t t1_B = psv16_dual_rev64_s32(z2_B);
        svint32_t EEE_B = svadd_s32_x(svptrue_b32(), t0_B, t1_B);
        svint32_t EEO_B = svsub_s32_x(svptrue_b32(), t0_B, t1_B);

        for (int k = 1; k < 16; k += 2)
        {
            const svint16_t c = psv16_dup8_s16(GT16[k]);
            svint64_t t_A = psv16_sdot(psv_zero_s64(), c, O_A);
            svint64_t t_B = psv16_sdot(psv_zero_s64(), c, O_B);
            const svint32_t t01 = psv16_dual_vmovn_s64(t_A);
            const svint32_t t23 = psv16_dual_vmovn_s64(t_B);
            const svint32_t cmb = psv16_combine_g0_s32(t01, t23);
            const svint32_t w = psv16_pairwise_add_s32(cmb, cmb);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(w);
            psv_store4_s16(dst + 16 * k + i, nn);
        }

        for (int k = 2; k < 16; k += 4)
        {
            const svint32_t c = psv16_dup4_s32(GT16_S32[(k - 2) / 4]);
            svint32_t m_A = svmul_s32_x(svptrue_b32(), c, EO_A);
            svint32_t m_B = svmul_s32_x(svptrue_b32(), c, EO_B);
            // Stage 1: per-row partials (g0 = rows 0/1, g1 = rows 2/3).
            svint32_t s1 = psv16_pairwise_add_s32(m_A, m_B);
            // Stage 2: per-row totals -> lanes 0-3.
            svint32_t w = psv16_pairwise_add_s32(s1, s1);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(w);
            psv_store4_s16(dst + 16 * k + i, nn);
        }

        {
            const svint32_t c = psv16_dup4_s32(T8E[0]);
            svint32_t cmb = psv16_combine_g0_s32(EEE_A, EEE_B);
            svint32_t pp = psv16_pairwise_add_s32(cmb, cmb);
            svint32_t m = svmul_s32_x(svptrue_b32(), c, pp);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(m);
            psv_store4_s16(dst + 16 * 0 + i, nn);
        }
        {
            const svint32_t c = psv16_dup4_s32(T8E[1]);
            svint32_t m0 = svmul_s32_x(svptrue_b32(), c, EEO_A);
            svint32_t m1 = svmul_s32_x(svptrue_b32(), c, EEO_B);
            svint32_t cmb = psv16_combine_g0_s32(m0, m1);
            svint32_t m = psv16_pairwise_add_s32(cmb, cmb);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(m);
            psv_store4_s16(dst + 16 * 4 + i, nn);
        }
        {
            const svint32_t c = psv16_dup4_s32(T8E[2]);
            svint32_t m0 = svmul_s32_x(svptrue_b32(), c, EEE_A);
            svint32_t m1 = svmul_s32_x(svptrue_b32(), c, EEE_B);
            svint32_t cmb = psv16_combine_g0_s32(m0, m1);
            svint32_t m = psv16_pairwise_add_s32(cmb, cmb);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(m);
            psv_store4_s16(dst + 16 * 8 + i, nn);
        }
        {
            const svint32_t c = psv16_dup4_s32(T8E[3]);
            svint32_t m0 = svmul_s32_x(svptrue_b32(), c, EEO_A);
            svint32_t m1 = svmul_s32_x(svptrue_b32(), c, EEO_B);
            svint32_t cmb = psv16_combine_g0_s32(m0, m1);
            svint32_t m = psv16_pairwise_add_s32(cmb, cmb);
            svint16_t nn = psv16_dual_rshrn_s32<shift>(m);
            psv_store4_s16(dst + 16 * 12 + i, nn);
        }
    }
}

extern "C" void dynopt_dct16_sve16(const int16_t* src, int16_t* dst, intptr_t srcStride)
{
    if (svcntb() != 32) return;
    int16_t coef[256];
    op_pass_4_dual(src, coef, srcStride);
    op_pass_11_dual(coef, dst);
}
