// Generated by tools/emit_dct16_sve2_shared.py -- do not edit by hand.
// SVE2 VL=256 shared-leaf DCT16: E/O leaves + SDOT + NEON-bridge narrow.
#include <arm_sve.h>
#include <arm_neon.h>
#include <arm_neon_sve_bridge.h>
#include <cstdint>

namespace {

static inline svint16_t revh_d(svint16_t x)
{
    // SVE REVH with .d register view: reverse 16-bit lanes within each
    // 64-bit element (per-row 4-lane reversal).
    svint16_t r;
    asm volatile("revh %[r].d, %[p]/m, %[x].d"
                 : [r] "=w" (r)
                 : [x] "w" (x), [p] "Upl" (svptrue_b64()));
    return r;
}

static inline svint32_t revw_d32(svint32_t x)
{
    // REVW .d: swap the two 32-bit halves of each 64-bit element.
    svint32_t r;
    asm volatile("revw %[r].d, %[p]/m, %[x].d"
                 : [r] "=w" (r)
                 : [x] "w" (x), [p] "Upl" (svptrue_b64()));
    return r;
}

static inline svint64_t revw_d64(svint64_t x)
{
    svint64_t r;
    asm volatile("revw %[r].d, %[p]/m, %[x].d"
                 : [r] "=w" (r)
                 : [x] "w" (x), [p] "Upl" (svptrue_b64()));
    return r;
}

static inline svint32_t addp_s32(svint32_t a, svint32_t b)
{
    // SVE2 ADDP (Zd must equal Zn): out[2k]=a[2k]+a[2k+1],
    // out[2k+1]=b[2k]+b[2k+1].
    svint32_t r = a;
    asm volatile("addp %[r].s, %[p]/m, %[r].s, %[b].s"
                 : [r] "+w" (r)
                 : [b] "w" (b), [p] "Upl" (svptrue_b32()));
    return r;
}

static inline void st1d_scatter_s16(int16_t* base, svint64_t offs,
                                    svint16_t data)
{
    asm volatile("st1d {%[d].d}, %[p], [%[b], %[o].d]"
                 :
                 : [d] "w" (data), [b] "r" (base), [o] "w" (offs),
                   [p] "Upl" (svptrue_b64())
                 : "memory");
}

static const int16_t C8[16][8] = {
    { 64, 64, 64, 64, 64, 64, 64, 64 },
    { 90, 87, 80, 70, 57, 43, 25, 9 },
    { 89, 75, 50, 18, -18, -50, -75, -89 },
    { 87, 57, 9, -43, -80, -90, -70, -25 },
    { 83, 36, -36, -83, -83, -36, 36, 83 },
    { 80, 9, -70, -87, -25, 57, 90, 43 },
    { 75, -18, -89, -50, 50, 89, 18, -75 },
    { 70, -43, -87, 9, 90, 25, -80, -57 },
    { 64, -64, -64, 64, 64, -64, -64, 64 },
    { 57, -80, -25, 90, -9, -87, 43, 70 },
    { 50, -89, 18, 75, -75, -18, 89, -50 },
    { 43, -90, 57, 25, -87, 70, 9, -80 },
    { 36, -83, 83, -36, -36, 83, -83, 36 },
    { 25, -70, 90, -80, 43, 9, -57, 87 },
    { 18, -50, 75, -89, 89, -75, 50, -18 },
    { 9, -25, 43, -57, 70, -80, 87, -90 },
};

static const int16_t GT16[16][8] = {
    { 64, 64, 64, 64, 64, 64, 64, 64 },
    { 90, 87, 80, 70, 57, 43, 25, 9 },
    { 89, 75, 50, 18, -18, -50, -75, -89 },
    { 87, 57, 9, -43, -80, -90, -70, -25 },
    { 83, 36, -36, -83, -83, -36, 36, 83 },
    { 80, 9, -70, -87, -25, 57, 90, 43 },
    { 75, -18, -89, -50, 50, 89, 18, -75 },
    { 70, -43, -87, 9, 90, 25, -80, -57 },
    { 64, -64, -64, 64, 64, -64, -64, 64 },
    { 57, -80, -25, 90, -9, -87, 43, 70 },
    { 50, -89, 18, 75, -75, -18, 89, -50 },
    { 43, -90, 57, 25, -87, 70, 9, -80 },
    { 36, -83, 83, -36, -36, 83, -83, 36 },
    { 25, -70, 90, -80, 43, 9, -57, 87 },
    { 18, -50, 75, -89, 89, -75, 50, -18 },
    { 9, -25, 43, -57, 70, -80, 87, -90 },
};

static const int32_t GT16_S32[4][4] = {
    { 89, 75, 50, 18 },
    { 75, -18, -89, -50 },
    { 50, -89, 18, 75 },
    { 18, -50, 75, -89 },
};

static const int32_t T8E[4][4] = {
    { 64, 64, 64, 64 },
    { 83, 36, 83, 36 },
    { 64, -64, 64, -64 },
    { 36, -83, 36, -83 },
};

static const int32_t T8E8[4][8] = {
    { 64, 64, 64, 64, 64, 64, 64, 64 },
    { 83, 36, 83, 36, 83, 36, 83, 36 },
    { 64, -64, 64, -64, 64, -64, 64, -64 },
    { 36, -83, 36, -83, 36, -83, 36, -83 },
};

static const int64_t EVEN_OFFS[4] = { 0, 128, 256, 384 };

static const int16_t CQ_LO[16][16] = {
    { 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64 },
    { 90, 87, 80, 70, 90, 87, 80, 70, 90, 87, 80, 70, 90, 87, 80, 70 },
    { 89, 75, 50, 18, 89, 75, 50, 18, 89, 75, 50, 18, 89, 75, 50, 18 },
    { 87, 57, 9, -43, 87, 57, 9, -43, 87, 57, 9, -43, 87, 57, 9, -43 },
    { 83, 36, -36, -83, 83, 36, -36, -83, 83, 36, -36, -83, 83, 36, -36, -83 },
    { 80, 9, -70, -87, 80, 9, -70, -87, 80, 9, -70, -87, 80, 9, -70, -87 },
    { 75, -18, -89, -50, 75, -18, -89, -50, 75, -18, -89, -50, 75, -18, -89, -50 },
    { 70, -43, -87, 9, 70, -43, -87, 9, 70, -43, -87, 9, 70, -43, -87, 9 },
    { 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64 },
    { 57, -80, -25, 90, 57, -80, -25, 90, 57, -80, -25, 90, 57, -80, -25, 90 },
    { 50, -89, 18, 75, 50, -89, 18, 75, 50, -89, 18, 75, 50, -89, 18, 75 },
    { 43, -90, 57, 25, 43, -90, 57, 25, 43, -90, 57, 25, 43, -90, 57, 25 },
    { 36, -83, 83, -36, 36, -83, 83, -36, 36, -83, 83, -36, 36, -83, 83, -36 },
    { 25, -70, 90, -80, 25, -70, 90, -80, 25, -70, 90, -80, 25, -70, 90, -80 },
    { 18, -50, 75, -89, 18, -50, 75, -89, 18, -50, 75, -89, 18, -50, 75, -89 },
    { 9, -25, 43, -57, 9, -25, 43, -57, 9, -25, 43, -57, 9, -25, 43, -57 },
};

static const int16_t CQ_HI[16][16] = {
    { 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64 },
    { 57, 43, 25, 9, 57, 43, 25, 9, 57, 43, 25, 9, 57, 43, 25, 9 },
    { -18, -50, -75, -89, -18, -50, -75, -89, -18, -50, -75, -89, -18, -50, -75, -89 },
    { -80, -90, -70, -25, -80, -90, -70, -25, -80, -90, -70, -25, -80, -90, -70, -25 },
    { -83, -36, 36, 83, -83, -36, 36, 83, -83, -36, 36, 83, -83, -36, 36, 83 },
    { -25, 57, 90, 43, -25, 57, 90, 43, -25, 57, 90, 43, -25, 57, 90, 43 },
    { 50, 89, 18, -75, 50, 89, 18, -75, 50, 89, 18, -75, 50, 89, 18, -75 },
    { 90, 25, -80, -57, 90, 25, -80, -57, 90, 25, -80, -57, 90, 25, -80, -57 },
    { 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64, 64, -64, -64, 64 },
    { -9, -87, 43, 70, -9, -87, 43, 70, -9, -87, 43, 70, -9, -87, 43, 70 },
    { -75, -18, 89, -50, -75, -18, 89, -50, -75, -18, 89, -50, -75, -18, 89, -50 },
    { -87, 70, 9, -80, -87, 70, 9, -80, -87, 70, 9, -80, -87, 70, 9, -80 },
    { -36, 83, -83, 36, -36, 83, -83, 36, -36, 83, -83, 36, -36, 83, -83, 36 },
    { 43, 9, -57, 87, 43, 9, -57, 87, 43, 9, -57, 87, 43, 9, -57, 87 },
    { 89, -75, 50, -18, 89, -75, 50, -18, 89, -75, 50, -18, 89, -75, 50, -18 },
    { 70, -80, 87, -90, 70, -80, 87, -90, 70, -80, 87, -90, 70, -80, 87, -90 },
};

static const uint8_t rev16_tbl[16] =
    { 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 2, 3, 0, 1 };
static const uint8_t rev32_tbl[16] =
    { 12, 13, 14, 15, 8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3 };

static inline int16x8_t rev16(const int16x8_t a)
{
    return vreinterpretq_s16_s8(vqtbx1q_s8(
        vreinterpretq_s8_s16(a), vreinterpretq_s8_s16(a),
        vld1q_u8(rev16_tbl)));
}

static inline int32x4_t rev32(const int32x4_t a)
{
    return vreinterpretq_s32_s8(vqtbx1q_s8(
        vreinterpretq_s8_s32(a), vreinterpretq_s8_s32(a),
        vld1q_u8(rev32_tbl)));
}

static inline int64x2_t sdotq_s16(int64x2_t acc, int16x8_t x, int16x8_t y)
{
    return svget_neonq_s64(svdot_s64(
        svset_neonq_s64(svundef_s64(), acc),
        svset_neonq_s16(svundef_s16(), x),
        svset_neonq_s16(svundef_s16(), y)));
}

// tbl2 index: low 8 lanes of {z_a, z_b} -> [z_a[0..7], z_b[0..7]]
// hi: [z_a[8..15], z_b[8..15]]
static const uint16_t idx_rev[16] =
    { 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 };
static const uint16_t idx_lo[16] =
    { 0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23 };
static const uint16_t idx_q0[16] =
    { 0, 1, 2, 3, 8, 9, 10, 11, 16, 17, 18, 19, 24, 25, 26, 27 };
static const uint16_t idx_q1[16] =
    { 4, 5, 6, 7, 12, 13, 14, 15, 20, 21, 22, 23, 28, 29, 30, 31 };
static const uint16_t idx_qa[16] =
    { 0, 1, 2, 3, 8, 9, 10, 11, 16, 17, 18, 19, 24, 25, 26, 27 };
static const uint16_t idx_qb[16] =
    { 4, 5, 6, 7, 12, 13, 14, 15, 20, 21, 22, 23, 28, 29, 30, 31 };

template <int shift>
static void pass(const int16_t* src, int16_t* dst, intptr_t stride)
{
    const svbool_t p16 = svptrue_b16();
    const svuint16_t irv = svld1_u16(p16, idx_rev);
    const svint64_t zacc = svdup_n_s64(0);

    // E/O leaves: low 8 lanes per row; rows are unrolled (ACLE: no arrays
    // of SVE types).
    svint16_t E0, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13,
              E14, E15;
    svint16_t O0, O1, O2, O3, O4, O5, O6, O7, O8, O9, O10, O11, O12, O13,
              O14, O15;
        {
            const svint16_t z = svld1_s16(p16, src + 0 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E0 = svadd_s16_x(p16, z, rr);
            O0 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 1 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E1 = svadd_s16_x(p16, z, rr);
            O1 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 2 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E2 = svadd_s16_x(p16, z, rr);
            O2 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 3 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E3 = svadd_s16_x(p16, z, rr);
            O3 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 4 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E4 = svadd_s16_x(p16, z, rr);
            O4 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 5 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E5 = svadd_s16_x(p16, z, rr);
            O5 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 6 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E6 = svadd_s16_x(p16, z, rr);
            O6 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 7 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E7 = svadd_s16_x(p16, z, rr);
            O7 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 8 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E8 = svadd_s16_x(p16, z, rr);
            O8 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 9 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E9 = svadd_s16_x(p16, z, rr);
            O9 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 10 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E10 = svadd_s16_x(p16, z, rr);
            O10 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 11 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E11 = svadd_s16_x(p16, z, rr);
            O11 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 12 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E12 = svadd_s16_x(p16, z, rr);
            O12 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 13 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E13 = svadd_s16_x(p16, z, rr);
            O13 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 14 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E14 = svadd_s16_x(p16, z, rr);
            O14 = svsub_s16_x(p16, z, rr);
        }
        {
            const svint16_t z = svld1_s16(p16, src + 15 * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E15 = svadd_s16_x(p16, z, rr);
            O15 = svsub_s16_x(p16, z, rr);
        }

    for (int k = 0; k < 16; k++)
    {
        const svint16_t ck = svld1_s16(p16, C8[k]);   // [C | C]
            const svint16_t x0 = (k & 1) ? O0 : E0;
            const svint64_t d0 = svdot_s64(zacc, x0, ck);
            const svint16_t x1 = (k & 1) ? O1 : E1;
            const svint64_t d1 = svdot_s64(zacc, x1, ck);
            const svint16_t x2 = (k & 1) ? O2 : E2;
            const svint64_t d2 = svdot_s64(zacc, x2, ck);
            const svint16_t x3 = (k & 1) ? O3 : E3;
            const svint64_t d3 = svdot_s64(zacc, x3, ck);
        {
            const int64x2_t t0 = svget_neonq_s64(d0);
            const int64x2_t t1 = svget_neonq_s64(d1);
            const int64x2_t t2 = svget_neonq_s64(d2);
            const int64x2_t t3 = svget_neonq_s64(d3);
            const int32x4_t t01 = vcombine_s32(vmovn_s64(t0), vmovn_s64(t1));
            const int32x4_t t23 = vcombine_s32(vmovn_s64(t2), vmovn_s64(t3));
            const int32x4_t w = vpaddq_s32(t01, t23);
            const int16x4_t n = vrshrn_n_s32(w, shift);
            vst1_s16(dst + 16 * k + 0, n);
        }
            const svint16_t x4 = (k & 1) ? O4 : E4;
            const svint64_t d4 = svdot_s64(zacc, x4, ck);
            const svint16_t x5 = (k & 1) ? O5 : E5;
            const svint64_t d5 = svdot_s64(zacc, x5, ck);
            const svint16_t x6 = (k & 1) ? O6 : E6;
            const svint64_t d6 = svdot_s64(zacc, x6, ck);
            const svint16_t x7 = (k & 1) ? O7 : E7;
            const svint64_t d7 = svdot_s64(zacc, x7, ck);
        {
            const int64x2_t t0 = svget_neonq_s64(d4);
            const int64x2_t t1 = svget_neonq_s64(d5);
            const int64x2_t t2 = svget_neonq_s64(d6);
            const int64x2_t t3 = svget_neonq_s64(d7);
            const int32x4_t t01 = vcombine_s32(vmovn_s64(t0), vmovn_s64(t1));
            const int32x4_t t23 = vcombine_s32(vmovn_s64(t2), vmovn_s64(t3));
            const int32x4_t w = vpaddq_s32(t01, t23);
            const int16x4_t n = vrshrn_n_s32(w, shift);
            vst1_s16(dst + 16 * k + 4, n);
        }
            const svint16_t x8 = (k & 1) ? O8 : E8;
            const svint64_t d8 = svdot_s64(zacc, x8, ck);
            const svint16_t x9 = (k & 1) ? O9 : E9;
            const svint64_t d9 = svdot_s64(zacc, x9, ck);
            const svint16_t x10 = (k & 1) ? O10 : E10;
            const svint64_t d10 = svdot_s64(zacc, x10, ck);
            const svint16_t x11 = (k & 1) ? O11 : E11;
            const svint64_t d11 = svdot_s64(zacc, x11, ck);
        {
            const int64x2_t t0 = svget_neonq_s64(d8);
            const int64x2_t t1 = svget_neonq_s64(d9);
            const int64x2_t t2 = svget_neonq_s64(d10);
            const int64x2_t t3 = svget_neonq_s64(d11);
            const int32x4_t t01 = vcombine_s32(vmovn_s64(t0), vmovn_s64(t1));
            const int32x4_t t23 = vcombine_s32(vmovn_s64(t2), vmovn_s64(t3));
            const int32x4_t w = vpaddq_s32(t01, t23);
            const int16x4_t n = vrshrn_n_s32(w, shift);
            vst1_s16(dst + 16 * k + 8, n);
        }
            const svint16_t x12 = (k & 1) ? O12 : E12;
            const svint64_t d12 = svdot_s64(zacc, x12, ck);
            const svint16_t x13 = (k & 1) ? O13 : E13;
            const svint64_t d13 = svdot_s64(zacc, x13, ck);
            const svint16_t x14 = (k & 1) ? O14 : E14;
            const svint64_t d14 = svdot_s64(zacc, x14, ck);
            const svint16_t x15 = (k & 1) ? O15 : E15;
            const svint64_t d15 = svdot_s64(zacc, x15, ck);
        {
            const int64x2_t t0 = svget_neonq_s64(d12);
            const int64x2_t t1 = svget_neonq_s64(d13);
            const int64x2_t t2 = svget_neonq_s64(d14);
            const int64x2_t t3 = svget_neonq_s64(d15);
            const int32x4_t t01 = vcombine_s32(vmovn_s64(t0), vmovn_s64(t1));
            const int32x4_t t23 = vcombine_s32(vmovn_s64(t2), vmovn_s64(t3));
            const int32x4_t w = vpaddq_s32(t01, t23);
            const int16x4_t n = vrshrn_n_s32(w, shift);
            vst1_s16(dst + 16 * k + 12, n);
        }
    }
}

template <int shift>
static void pass_quarter(const int16_t* src, int16_t* dst, intptr_t stride)
{
    const svbool_t p16 = svptrue_b16();
    const svbool_t p64 = svptrue_b64();
    const svbool_t p4h = svwhilelt_b16(0, 4);
    const svbool_t p8h = svwhilelt_b16(0, 8);
    const svuint16_t ilo = svld1_u16(p16, idx_lo);
    const svuint16_t qa = svld1_u16(p16, idx_qa);
    const svuint16_t qb = svld1_u16(p16, idx_qb);
    const svint64_t zacc = svdup_n_s64(0);

    svint16_t QE0_0, QE1_0, QO0_0, QO1_0;
    svint16_t QE0_1, QE1_1, QO0_1, QO1_1;
    svint16_t QE0_2, QE1_2, QO0_2, QO1_2;
    svint16_t QE0_3, QE1_3, QO0_3, QO1_3;
    svint16_t EEF_0, EOF_0;
    svint16_t EEF_1, EOF_1;
    svint16_t EEF_2, EOF_2;
    svint16_t EEF_3, EOF_3;

        {
            const svint16_t r0 = svld1_s16(p16, src + 0 * stride);
            const svint16_t r1 = svld1_s16(p16, src + 1 * stride);
            const svint16_t r2 = svld1_s16(p16, src + 2 * stride);
            const svint16_t r3 = svld1_s16(p16, src + 3 * stride);
            const svint64_t a0 = svreinterpret_s64_s16(r0);
            const svint64_t a1 = svreinterpret_s64_s16(r1);
            const svint64_t a2 = svreinterpret_s64_s16(r2);
            const svint64_t a3 = svreinterpret_s64_s16(r3);
            const svint64_t t0 = svzip1_s64(a0, a2);
            const svint64_t t1 = svzip2_s64(a0, a2);
            const svint64_t t2 = svzip1_s64(a1, a3);
            const svint64_t t3 = svzip2_s64(a1, a3);
            const svint64_t p0 = svzip1_s64(t0, t2);
            const svint64_t p1 = svzip2_s64(t0, t2);
            const svint64_t p2 = svzip1_s64(t1, t3);
            const svint64_t p3 = svzip2_s64(t1, t3);
            const svint16_t q0 = svreinterpret_s16_s64(p0);
            const svint16_t q1 = svreinterpret_s16_s64(p1);
            const svint16_t q2 = revh_d(svreinterpret_s16_s64(p2));
            const svint16_t q3 = revh_d(svreinterpret_s16_s64(p3));
            QO0_0 = svsub_s16_x(p16, q0, q3);
            QO1_0 = svsub_s16_x(p16, q1, q2);
            QE0_0 = svadd_s16_x(p16, q0, q3);
            QE1_0 = svadd_s16_x(p16, q1, q2);
            const svint16_t QR1_0 = revh_d(QE1_0);
            EEF_0 = svadd_s16_x(p16, QE0_0, QR1_0);
            EOF_0 = svsub_s16_x(p16, QE0_0, QR1_0);

        }
        {
            const svint16_t r0 = svld1_s16(p16, src + 4 * stride);
            const svint16_t r1 = svld1_s16(p16, src + 5 * stride);
            const svint16_t r2 = svld1_s16(p16, src + 6 * stride);
            const svint16_t r3 = svld1_s16(p16, src + 7 * stride);
            const svint64_t a0 = svreinterpret_s64_s16(r0);
            const svint64_t a1 = svreinterpret_s64_s16(r1);
            const svint64_t a2 = svreinterpret_s64_s16(r2);
            const svint64_t a3 = svreinterpret_s64_s16(r3);
            const svint64_t t0 = svzip1_s64(a0, a2);
            const svint64_t t1 = svzip2_s64(a0, a2);
            const svint64_t t2 = svzip1_s64(a1, a3);
            const svint64_t t3 = svzip2_s64(a1, a3);
            const svint64_t p0 = svzip1_s64(t0, t2);
            const svint64_t p1 = svzip2_s64(t0, t2);
            const svint64_t p2 = svzip1_s64(t1, t3);
            const svint64_t p3 = svzip2_s64(t1, t3);
            const svint16_t q0 = svreinterpret_s16_s64(p0);
            const svint16_t q1 = svreinterpret_s16_s64(p1);
            const svint16_t q2 = revh_d(svreinterpret_s16_s64(p2));
            const svint16_t q3 = revh_d(svreinterpret_s16_s64(p3));
            QO0_1 = svsub_s16_x(p16, q0, q3);
            QO1_1 = svsub_s16_x(p16, q1, q2);
            QE0_1 = svadd_s16_x(p16, q0, q3);
            QE1_1 = svadd_s16_x(p16, q1, q2);
            const svint16_t QR1_1 = revh_d(QE1_1);
            EEF_1 = svadd_s16_x(p16, QE0_1, QR1_1);
            EOF_1 = svsub_s16_x(p16, QE0_1, QR1_1);

        }
        {
            const svint16_t r0 = svld1_s16(p16, src + 8 * stride);
            const svint16_t r1 = svld1_s16(p16, src + 9 * stride);
            const svint16_t r2 = svld1_s16(p16, src + 10 * stride);
            const svint16_t r3 = svld1_s16(p16, src + 11 * stride);
            const svint64_t a0 = svreinterpret_s64_s16(r0);
            const svint64_t a1 = svreinterpret_s64_s16(r1);
            const svint64_t a2 = svreinterpret_s64_s16(r2);
            const svint64_t a3 = svreinterpret_s64_s16(r3);
            const svint64_t t0 = svzip1_s64(a0, a2);
            const svint64_t t1 = svzip2_s64(a0, a2);
            const svint64_t t2 = svzip1_s64(a1, a3);
            const svint64_t t3 = svzip2_s64(a1, a3);
            const svint64_t p0 = svzip1_s64(t0, t2);
            const svint64_t p1 = svzip2_s64(t0, t2);
            const svint64_t p2 = svzip1_s64(t1, t3);
            const svint64_t p3 = svzip2_s64(t1, t3);
            const svint16_t q0 = svreinterpret_s16_s64(p0);
            const svint16_t q1 = svreinterpret_s16_s64(p1);
            const svint16_t q2 = revh_d(svreinterpret_s16_s64(p2));
            const svint16_t q3 = revh_d(svreinterpret_s16_s64(p3));
            QO0_2 = svsub_s16_x(p16, q0, q3);
            QO1_2 = svsub_s16_x(p16, q1, q2);
            QE0_2 = svadd_s16_x(p16, q0, q3);
            QE1_2 = svadd_s16_x(p16, q1, q2);
            const svint16_t QR1_2 = revh_d(QE1_2);
            EEF_2 = svadd_s16_x(p16, QE0_2, QR1_2);
            EOF_2 = svsub_s16_x(p16, QE0_2, QR1_2);

        }
        {
            const svint16_t r0 = svld1_s16(p16, src + 12 * stride);
            const svint16_t r1 = svld1_s16(p16, src + 13 * stride);
            const svint16_t r2 = svld1_s16(p16, src + 14 * stride);
            const svint16_t r3 = svld1_s16(p16, src + 15 * stride);
            const svint64_t a0 = svreinterpret_s64_s16(r0);
            const svint64_t a1 = svreinterpret_s64_s16(r1);
            const svint64_t a2 = svreinterpret_s64_s16(r2);
            const svint64_t a3 = svreinterpret_s64_s16(r3);
            const svint64_t t0 = svzip1_s64(a0, a2);
            const svint64_t t1 = svzip2_s64(a0, a2);
            const svint64_t t2 = svzip1_s64(a1, a3);
            const svint64_t t3 = svzip2_s64(a1, a3);
            const svint64_t p0 = svzip1_s64(t0, t2);
            const svint64_t p1 = svzip2_s64(t0, t2);
            const svint64_t p2 = svzip1_s64(t1, t3);
            const svint64_t p3 = svzip2_s64(t1, t3);
            const svint16_t q0 = svreinterpret_s16_s64(p0);
            const svint16_t q1 = svreinterpret_s16_s64(p1);
            const svint16_t q2 = revh_d(svreinterpret_s16_s64(p2));
            const svint16_t q3 = revh_d(svreinterpret_s16_s64(p3));
            QO0_3 = svsub_s16_x(p16, q0, q3);
            QO1_3 = svsub_s16_x(p16, q1, q2);
            QE0_3 = svadd_s16_x(p16, q0, q3);
            QE1_3 = svadd_s16_x(p16, q1, q2);
            const svint16_t QR1_3 = revh_d(QE1_3);
            EEF_3 = svadd_s16_x(p16, QE0_3, QR1_3);
            EOF_3 = svsub_s16_x(p16, QE0_3, QR1_3);

        }

    for (int kb = 0; kb < 16; kb += 4)
    {
        const svint16_t cq_lo = svld1_s16(p16, CQ_LO[kb]);

            svint64_t d_0 = svdot_s64(zacc, EEF_0, cq_lo);

            svint64_t d_1 = svdot_s64(zacc, EEF_1, cq_lo);

            svint64_t d_2 = svdot_s64(zacc, EEF_2, cq_lo);

            svint64_t d_3 = svdot_s64(zacc, EEF_3, cq_lo);

            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_0),
                    svreinterpret_s32_s64(d_1));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb) + 0, n);
            }
            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_2),
                    svreinterpret_s32_s64(d_3));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb) + 8, n);
            }
    }
    for (int kb = 2; kb < 16; kb += 4)
    {
        const svint16_t cq_lo = svld1_s16(p16, CQ_LO[kb]);

            svint64_t d_0 = svdot_s64(zacc, EOF_0, cq_lo);

            svint64_t d_1 = svdot_s64(zacc, EOF_1, cq_lo);

            svint64_t d_2 = svdot_s64(zacc, EOF_2, cq_lo);

            svint64_t d_3 = svdot_s64(zacc, EOF_3, cq_lo);

            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_0),
                    svreinterpret_s32_s64(d_1));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb) + 0, n);
            }
            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_2),
                    svreinterpret_s32_s64(d_3));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb) + 8, n);
            }
    }
    for (int kb = 1; kb < 16; kb += 8)
    {
{
        const svint16_t cq_lo0 = svld1_s16(p16, CQ_LO[kb + 0]);
        const svint16_t cq_hi0 = svld1_s16(p16, CQ_HI[kb + 0]);

            const svint16_t x0_0 = (kb + 0 & 1) ? QO0_0 : QE0_0;
            const svint16_t x1_0 = (kb + 0 & 1) ? QO1_0 : QE1_0;
            svint64_t d_0 = svdot_s64(zacc, x0_0, cq_lo0);
            d_0 = svdot_s64(d_0, x1_0, cq_hi0);

            const svint16_t x0_1 = (kb + 0 & 1) ? QO0_1 : QE0_1;
            const svint16_t x1_1 = (kb + 0 & 1) ? QO1_1 : QE1_1;
            svint64_t d_1 = svdot_s64(zacc, x0_1, cq_lo0);
            d_1 = svdot_s64(d_1, x1_1, cq_hi0);

            const svint16_t x0_2 = (kb + 0 & 1) ? QO0_2 : QE0_2;
            const svint16_t x1_2 = (kb + 0 & 1) ? QO1_2 : QE1_2;
            svint64_t d_2 = svdot_s64(zacc, x0_2, cq_lo0);
            d_2 = svdot_s64(d_2, x1_2, cq_hi0);

            const svint16_t x0_3 = (kb + 0 & 1) ? QO0_3 : QE0_3;
            const svint16_t x1_3 = (kb + 0 & 1) ? QO1_3 : QE1_3;
            svint64_t d_3 = svdot_s64(zacc, x0_3, cq_lo0);
            d_3 = svdot_s64(d_3, x1_3, cq_hi0);

            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_0),
                    svreinterpret_s32_s64(d_1));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb + 0) + 0, n);
            }
            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_2),
                    svreinterpret_s32_s64(d_3));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb + 0) + 8, n);
            }
        }
{
        const svint16_t cq_lo1 = svld1_s16(p16, CQ_LO[kb + 2]);
        const svint16_t cq_hi1 = svld1_s16(p16, CQ_HI[kb + 2]);

            const svint16_t x0_0 = (kb + 2 & 1) ? QO0_0 : QE0_0;
            const svint16_t x1_0 = (kb + 2 & 1) ? QO1_0 : QE1_0;
            svint64_t d_0 = svdot_s64(zacc, x0_0, cq_lo1);
            d_0 = svdot_s64(d_0, x1_0, cq_hi1);

            const svint16_t x0_1 = (kb + 2 & 1) ? QO0_1 : QE0_1;
            const svint16_t x1_1 = (kb + 2 & 1) ? QO1_1 : QE1_1;
            svint64_t d_1 = svdot_s64(zacc, x0_1, cq_lo1);
            d_1 = svdot_s64(d_1, x1_1, cq_hi1);

            const svint16_t x0_2 = (kb + 2 & 1) ? QO0_2 : QE0_2;
            const svint16_t x1_2 = (kb + 2 & 1) ? QO1_2 : QE1_2;
            svint64_t d_2 = svdot_s64(zacc, x0_2, cq_lo1);
            d_2 = svdot_s64(d_2, x1_2, cq_hi1);

            const svint16_t x0_3 = (kb + 2 & 1) ? QO0_3 : QE0_3;
            const svint16_t x1_3 = (kb + 2 & 1) ? QO1_3 : QE1_3;
            svint64_t d_3 = svdot_s64(zacc, x0_3, cq_lo1);
            d_3 = svdot_s64(d_3, x1_3, cq_hi1);

            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_0),
                    svreinterpret_s32_s64(d_1));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb + 2) + 0, n);
            }
            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_2),
                    svreinterpret_s32_s64(d_3));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb + 2) + 8, n);
            }
        }
{
        const svint16_t cq_lo2 = svld1_s16(p16, CQ_LO[kb + 4]);
        const svint16_t cq_hi2 = svld1_s16(p16, CQ_HI[kb + 4]);

            const svint16_t x0_0 = (kb + 4 & 1) ? QO0_0 : QE0_0;
            const svint16_t x1_0 = (kb + 4 & 1) ? QO1_0 : QE1_0;
            svint64_t d_0 = svdot_s64(zacc, x0_0, cq_lo2);
            d_0 = svdot_s64(d_0, x1_0, cq_hi2);

            const svint16_t x0_1 = (kb + 4 & 1) ? QO0_1 : QE0_1;
            const svint16_t x1_1 = (kb + 4 & 1) ? QO1_1 : QE1_1;
            svint64_t d_1 = svdot_s64(zacc, x0_1, cq_lo2);
            d_1 = svdot_s64(d_1, x1_1, cq_hi2);

            const svint16_t x0_2 = (kb + 4 & 1) ? QO0_2 : QE0_2;
            const svint16_t x1_2 = (kb + 4 & 1) ? QO1_2 : QE1_2;
            svint64_t d_2 = svdot_s64(zacc, x0_2, cq_lo2);
            d_2 = svdot_s64(d_2, x1_2, cq_hi2);

            const svint16_t x0_3 = (kb + 4 & 1) ? QO0_3 : QE0_3;
            const svint16_t x1_3 = (kb + 4 & 1) ? QO1_3 : QE1_3;
            svint64_t d_3 = svdot_s64(zacc, x0_3, cq_lo2);
            d_3 = svdot_s64(d_3, x1_3, cq_hi2);

            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_0),
                    svreinterpret_s32_s64(d_1));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb + 4) + 0, n);
            }
            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_2),
                    svreinterpret_s32_s64(d_3));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb + 4) + 8, n);
            }
        }
{
        const svint16_t cq_lo3 = svld1_s16(p16, CQ_LO[kb + 6]);
        const svint16_t cq_hi3 = svld1_s16(p16, CQ_HI[kb + 6]);

            const svint16_t x0_0 = (kb + 6 & 1) ? QO0_0 : QE0_0;
            const svint16_t x1_0 = (kb + 6 & 1) ? QO1_0 : QE1_0;
            svint64_t d_0 = svdot_s64(zacc, x0_0, cq_lo3);
            d_0 = svdot_s64(d_0, x1_0, cq_hi3);

            const svint16_t x0_1 = (kb + 6 & 1) ? QO0_1 : QE0_1;
            const svint16_t x1_1 = (kb + 6 & 1) ? QO1_1 : QE1_1;
            svint64_t d_1 = svdot_s64(zacc, x0_1, cq_lo3);
            d_1 = svdot_s64(d_1, x1_1, cq_hi3);

            const svint16_t x0_2 = (kb + 6 & 1) ? QO0_2 : QE0_2;
            const svint16_t x1_2 = (kb + 6 & 1) ? QO1_2 : QE1_2;
            svint64_t d_2 = svdot_s64(zacc, x0_2, cq_lo3);
            d_2 = svdot_s64(d_2, x1_2, cq_hi3);

            const svint16_t x0_3 = (kb + 6 & 1) ? QO0_3 : QE0_3;
            const svint16_t x1_3 = (kb + 6 & 1) ? QO1_3 : QE1_3;
            svint64_t d_3 = svdot_s64(zacc, x0_3, cq_lo3);
            d_3 = svdot_s64(d_3, x1_3, cq_hi3);

            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_0),
                    svreinterpret_s32_s64(d_1));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb + 6) + 0, n);
            }
            {
                const svint32_t w = svuzp1_s32(
                    svreinterpret_s32_s64(d_2),
                    svreinterpret_s32_s64(d_3));
                svint16_t n = svqrshrnb_n_s32(w, shift);
                n = svuzp1_s16(n, n);
                svst1_s16(p8h, dst + 16 * (kb + 6) + 8, n);
            }
        }
    }

}

static void pass2_upstream(const int16_t* src, int16_t* dst)
{
    const int shift = 10;
    const int line = 16;
    const svbool_t p16q = svptrue_b16();
    // odd k: quarter-interleaved O packs; even path interleaved per group.
    const svbool_t p64q = svptrue_b64();
    const svbool_t p4q = svwhilelt_b16(0, 4);
    const svbool_t p8q = svwhilelt_b16(0, 8);
    const svuint16_t iloq = svld1_u16(p16q, idx_lo);
    const svuint16_t q0q = svld1_u16(p16q, idx_q0);
    const svuint16_t q1q = svld1_u16(p16q, idx_q1);
    const svuint16_t qsel = svld1_u16(p16q, idx_q0);
    const svint64_t zaccq = svdup_n_s64(0);
    const svbool_t p32 = svptrue_b32();
    const svint32_t cT0 = svld1_s32(p32, T8E8[0]);
    const svint32_t cT1 = svld1_s32(p32, T8E8[1]);
    const svint32_t cT2 = svld1_s32(p32, T8E8[2]);
    const svint32_t cT3 = svld1_s32(p32, T8E8[3]);
    const svint64_t evoffs = svld1_s64(svptrue_b64(), EVEN_OFFS);


    svint16_t zO0, zO1, zO2, zO3, zO4, zO5, zO6, zO7;
    svint16_t zO8, zO9, zO10, zO11, zO12, zO13, zO14, zO15;
    svint16_t QO0_0, QO1_0, QO0_1, QO1_1, QO0_2, QO1_2, QO0_3, QO1_3;
    svint16_t QEOW0, QEOW1, QEOW2, QEOW3;
    int32x4_t EO_g0_0, EO_g0_1, EO_g0_2, EO_g0_3;
    int32x4_t EEE_g0, EEE_g0_1, EEO_g0, EEO_g0_1;
    int16x4_t EO16_g0_0, EO16_g0_1, EO16_g0_2, EO16_g0_3;
    int32x4_t EO_g1_0, EO_g1_1, EO_g1_2, EO_g1_3;
    int32x4_t EEE_g1, EEE_g1_1, EEO_g1, EEO_g1_1;
    int16x4_t EO16_g1_0, EO16_g1_1, EO16_g1_2, EO16_g1_3;
    int32x4_t EO_g2_0, EO_g2_1, EO_g2_2, EO_g2_3;
    int32x4_t EEE_g2, EEE_g2_1, EEO_g2, EEO_g2_1;
    int16x4_t EO16_g2_0, EO16_g2_1, EO16_g2_2, EO16_g2_3;
    int32x4_t EO_g3_0, EO_g3_1, EO_g3_2, EO_g3_3;
    int32x4_t EEE_g3, EEE_g3_1, EEO_g3, EEO_g3_1;
    int16x4_t EO16_g3_0, EO16_g3_1, EO16_g3_2, EO16_g3_3;



        {
            const svint16_t z0 = svld1_s16(p16q, src + 0 * line);
            const svint16_t z1 = svld1_s16(p16q, src + 1 * line);
            const svint16_t z2 = svld1_s16(p16q, src + 2 * line);
            const svint16_t z3 = svld1_s16(p16q, src + 3 * line);
            const svint64_t a0 = svreinterpret_s64_s16(z0);
            const svint64_t a1 = svreinterpret_s64_s16(z1);
            const svint64_t a2 = svreinterpret_s64_s16(z2);
            const svint64_t a3 = svreinterpret_s64_s16(z3);
            const svint64_t t0 = svzip1_s64(a0, a2);
            const svint64_t t1 = svzip2_s64(a0, a2);
            const svint64_t t2 = svzip1_s64(a1, a3);
            const svint64_t t3 = svzip2_s64(a1, a3);
            const svint64_t p0 = svzip1_s64(t0, t2);
            const svint64_t p1 = svzip2_s64(t0, t2);
            const svint64_t p2 = svzip1_s64(t1, t3);
            const svint64_t p3 = svzip2_s64(t1, t3);
            const svint16_t q0 = svreinterpret_s16_s64(p0);
            const svint16_t q1 = svreinterpret_s16_s64(p1);
            const svint16_t q2 = revh_d(svreinterpret_s16_s64(p2));
            const svint16_t q3 = revh_d(svreinterpret_s16_s64(p3));
            QO0_0 = svsub_s16_x(p16q, q0, q3);
            QO1_0 = svsub_s16_x(p16q, q1, q2);
            const svint32_t e0 = svaddlb_s32(q0, q3);
            const svint32_t e1 = svaddlt_s32(q0, q3);
            const svint32_t e2 = svaddlb_s32(q1, q2);
            const svint32_t e3 = svaddlt_s32(q1, q2);
            const svint32_t w0 = svzip1_s32(e0, e1);
            const svint32_t w1 = svzip2_s32(e0, e1);
            const svint32_t u2 = revw_d32(e2);
            const svint32_t u3 = revw_d32(e3);
            const svint32_t w2 = svzip1_s32(u3, u2);
            const svint32_t w3 = svzip2_s32(u3, u2);
            const svint32_t s0 = svsub_s32_x(p32, w0, w2);
            const svint32_t s1 = svsub_s32_x(p32, w1, w3);
            const svint32_t s2 = svadd_s32_x(p32, w0, w2);
            const svint32_t s3 = svadd_s32_x(p32, w1, w3);
            QEOW0 = svuzp1_s16(svreinterpret_s16_s32(s0), svreinterpret_s16_s32(s1));

            const svint64_t v0 = svuzp1_s64(svreinterpret_s64_s32(s2),
                                            svreinterpret_s64_s32(s3));
            const svint64_t v1 = svuzp2_s64(svreinterpret_s64_s32(s2),
                                            svreinterpret_s64_s32(s3));
            const svint64_t v1r = revw_d64(v1);
            const svint32_t EEp = svadd_s32_x(p32, svreinterpret_s32_s64(v0),
                                              svreinterpret_s32_s64(v1r));
            const svint32_t EOp = svsub_s32_x(p32, svreinterpret_s32_s64(v0),
                                              svreinterpret_s32_s64(v1r));
            const svint32_t m0 = svmul_s32_x(p32, EEp, cT0);
            const svint32_t m1 = svmul_s32_x(p32, EOp, cT1);
            const svint32_t m2 = svmul_s32_x(p32, EEp, cT2);
            const svint32_t m3 = svmul_s32_x(p32, EOp, cT3);
            const svint32_t pa = addp_s32(m0, m2);
            const svint32_t pb = addp_s32(m1, m3);
            const svint32_t xa = svuzp1_s32(pa, pb);
            const svint32_t xb = svuzp2_s32(pa, pb);
            const svint16_t na = svqrshrnb_n_s32(xa, shift);
            const svint16_t nb = svqrshrnb_n_s32(xb, shift);
            const svint16_t n16 = svuzp1_s16(na, nb);
            st1d_scatter_s16(dst + 0, evoffs, n16);
        }

        {
            const svint16_t z0 = svld1_s16(p16q, src + 4 * line);
            const svint16_t z1 = svld1_s16(p16q, src + 5 * line);
            const svint16_t z2 = svld1_s16(p16q, src + 6 * line);
            const svint16_t z3 = svld1_s16(p16q, src + 7 * line);
            const svint64_t a0 = svreinterpret_s64_s16(z0);
            const svint64_t a1 = svreinterpret_s64_s16(z1);
            const svint64_t a2 = svreinterpret_s64_s16(z2);
            const svint64_t a3 = svreinterpret_s64_s16(z3);
            const svint64_t t0 = svzip1_s64(a0, a2);
            const svint64_t t1 = svzip2_s64(a0, a2);
            const svint64_t t2 = svzip1_s64(a1, a3);
            const svint64_t t3 = svzip2_s64(a1, a3);
            const svint64_t p0 = svzip1_s64(t0, t2);
            const svint64_t p1 = svzip2_s64(t0, t2);
            const svint64_t p2 = svzip1_s64(t1, t3);
            const svint64_t p3 = svzip2_s64(t1, t3);
            const svint16_t q0 = svreinterpret_s16_s64(p0);
            const svint16_t q1 = svreinterpret_s16_s64(p1);
            const svint16_t q2 = revh_d(svreinterpret_s16_s64(p2));
            const svint16_t q3 = revh_d(svreinterpret_s16_s64(p3));
            QO0_1 = svsub_s16_x(p16q, q0, q3);
            QO1_1 = svsub_s16_x(p16q, q1, q2);
            const svint32_t e0 = svaddlb_s32(q0, q3);
            const svint32_t e1 = svaddlt_s32(q0, q3);
            const svint32_t e2 = svaddlb_s32(q1, q2);
            const svint32_t e3 = svaddlt_s32(q1, q2);
            const svint32_t w0 = svzip1_s32(e0, e1);
            const svint32_t w1 = svzip2_s32(e0, e1);
            const svint32_t u2 = revw_d32(e2);
            const svint32_t u3 = revw_d32(e3);
            const svint32_t w2 = svzip1_s32(u3, u2);
            const svint32_t w3 = svzip2_s32(u3, u2);
            const svint32_t s0 = svsub_s32_x(p32, w0, w2);
            const svint32_t s1 = svsub_s32_x(p32, w1, w3);
            const svint32_t s2 = svadd_s32_x(p32, w0, w2);
            const svint32_t s3 = svadd_s32_x(p32, w1, w3);
            QEOW1 = svuzp1_s16(svreinterpret_s16_s32(s0), svreinterpret_s16_s32(s1));

            const svint64_t v0 = svuzp1_s64(svreinterpret_s64_s32(s2),
                                            svreinterpret_s64_s32(s3));
            const svint64_t v1 = svuzp2_s64(svreinterpret_s64_s32(s2),
                                            svreinterpret_s64_s32(s3));
            const svint64_t v1r = revw_d64(v1);
            const svint32_t EEp = svadd_s32_x(p32, svreinterpret_s32_s64(v0),
                                              svreinterpret_s32_s64(v1r));
            const svint32_t EOp = svsub_s32_x(p32, svreinterpret_s32_s64(v0),
                                              svreinterpret_s32_s64(v1r));
            const svint32_t m0 = svmul_s32_x(p32, EEp, cT0);
            const svint32_t m1 = svmul_s32_x(p32, EOp, cT1);
            const svint32_t m2 = svmul_s32_x(p32, EEp, cT2);
            const svint32_t m3 = svmul_s32_x(p32, EOp, cT3);
            const svint32_t pa = addp_s32(m0, m2);
            const svint32_t pb = addp_s32(m1, m3);
            const svint32_t xa = svuzp1_s32(pa, pb);
            const svint32_t xb = svuzp2_s32(pa, pb);
            const svint16_t na = svqrshrnb_n_s32(xa, shift);
            const svint16_t nb = svqrshrnb_n_s32(xb, shift);
            const svint16_t n16 = svuzp1_s16(na, nb);
            st1d_scatter_s16(dst + 4, evoffs, n16);
        }

        {
            const svint16_t z0 = svld1_s16(p16q, src + 8 * line);
            const svint16_t z1 = svld1_s16(p16q, src + 9 * line);
            const svint16_t z2 = svld1_s16(p16q, src + 10 * line);
            const svint16_t z3 = svld1_s16(p16q, src + 11 * line);
            const svint64_t a0 = svreinterpret_s64_s16(z0);
            const svint64_t a1 = svreinterpret_s64_s16(z1);
            const svint64_t a2 = svreinterpret_s64_s16(z2);
            const svint64_t a3 = svreinterpret_s64_s16(z3);
            const svint64_t t0 = svzip1_s64(a0, a2);
            const svint64_t t1 = svzip2_s64(a0, a2);
            const svint64_t t2 = svzip1_s64(a1, a3);
            const svint64_t t3 = svzip2_s64(a1, a3);
            const svint64_t p0 = svzip1_s64(t0, t2);
            const svint64_t p1 = svzip2_s64(t0, t2);
            const svint64_t p2 = svzip1_s64(t1, t3);
            const svint64_t p3 = svzip2_s64(t1, t3);
            const svint16_t q0 = svreinterpret_s16_s64(p0);
            const svint16_t q1 = svreinterpret_s16_s64(p1);
            const svint16_t q2 = revh_d(svreinterpret_s16_s64(p2));
            const svint16_t q3 = revh_d(svreinterpret_s16_s64(p3));
            QO0_2 = svsub_s16_x(p16q, q0, q3);
            QO1_2 = svsub_s16_x(p16q, q1, q2);
            const svint32_t e0 = svaddlb_s32(q0, q3);
            const svint32_t e1 = svaddlt_s32(q0, q3);
            const svint32_t e2 = svaddlb_s32(q1, q2);
            const svint32_t e3 = svaddlt_s32(q1, q2);
            const svint32_t w0 = svzip1_s32(e0, e1);
            const svint32_t w1 = svzip2_s32(e0, e1);
            const svint32_t u2 = revw_d32(e2);
            const svint32_t u3 = revw_d32(e3);
            const svint32_t w2 = svzip1_s32(u3, u2);
            const svint32_t w3 = svzip2_s32(u3, u2);
            const svint32_t s0 = svsub_s32_x(p32, w0, w2);
            const svint32_t s1 = svsub_s32_x(p32, w1, w3);
            const svint32_t s2 = svadd_s32_x(p32, w0, w2);
            const svint32_t s3 = svadd_s32_x(p32, w1, w3);
            QEOW2 = svuzp1_s16(svreinterpret_s16_s32(s0), svreinterpret_s16_s32(s1));

            const svint64_t v0 = svuzp1_s64(svreinterpret_s64_s32(s2),
                                            svreinterpret_s64_s32(s3));
            const svint64_t v1 = svuzp2_s64(svreinterpret_s64_s32(s2),
                                            svreinterpret_s64_s32(s3));
            const svint64_t v1r = revw_d64(v1);
            const svint32_t EEp = svadd_s32_x(p32, svreinterpret_s32_s64(v0),
                                              svreinterpret_s32_s64(v1r));
            const svint32_t EOp = svsub_s32_x(p32, svreinterpret_s32_s64(v0),
                                              svreinterpret_s32_s64(v1r));
            const svint32_t m0 = svmul_s32_x(p32, EEp, cT0);
            const svint32_t m1 = svmul_s32_x(p32, EOp, cT1);
            const svint32_t m2 = svmul_s32_x(p32, EEp, cT2);
            const svint32_t m3 = svmul_s32_x(p32, EOp, cT3);
            const svint32_t pa = addp_s32(m0, m2);
            const svint32_t pb = addp_s32(m1, m3);
            const svint32_t xa = svuzp1_s32(pa, pb);
            const svint32_t xb = svuzp2_s32(pa, pb);
            const svint16_t na = svqrshrnb_n_s32(xa, shift);
            const svint16_t nb = svqrshrnb_n_s32(xb, shift);
            const svint16_t n16 = svuzp1_s16(na, nb);
            st1d_scatter_s16(dst + 8, evoffs, n16);
        }

        {
            const svint16_t z0 = svld1_s16(p16q, src + 12 * line);
            const svint16_t z1 = svld1_s16(p16q, src + 13 * line);
            const svint16_t z2 = svld1_s16(p16q, src + 14 * line);
            const svint16_t z3 = svld1_s16(p16q, src + 15 * line);
            const svint64_t a0 = svreinterpret_s64_s16(z0);
            const svint64_t a1 = svreinterpret_s64_s16(z1);
            const svint64_t a2 = svreinterpret_s64_s16(z2);
            const svint64_t a3 = svreinterpret_s64_s16(z3);
            const svint64_t t0 = svzip1_s64(a0, a2);
            const svint64_t t1 = svzip2_s64(a0, a2);
            const svint64_t t2 = svzip1_s64(a1, a3);
            const svint64_t t3 = svzip2_s64(a1, a3);
            const svint64_t p0 = svzip1_s64(t0, t2);
            const svint64_t p1 = svzip2_s64(t0, t2);
            const svint64_t p2 = svzip1_s64(t1, t3);
            const svint64_t p3 = svzip2_s64(t1, t3);
            const svint16_t q0 = svreinterpret_s16_s64(p0);
            const svint16_t q1 = svreinterpret_s16_s64(p1);
            const svint16_t q2 = revh_d(svreinterpret_s16_s64(p2));
            const svint16_t q3 = revh_d(svreinterpret_s16_s64(p3));
            QO0_3 = svsub_s16_x(p16q, q0, q3);
            QO1_3 = svsub_s16_x(p16q, q1, q2);
            const svint32_t e0 = svaddlb_s32(q0, q3);
            const svint32_t e1 = svaddlt_s32(q0, q3);
            const svint32_t e2 = svaddlb_s32(q1, q2);
            const svint32_t e3 = svaddlt_s32(q1, q2);
            const svint32_t w0 = svzip1_s32(e0, e1);
            const svint32_t w1 = svzip2_s32(e0, e1);
            const svint32_t u2 = revw_d32(e2);
            const svint32_t u3 = revw_d32(e3);
            const svint32_t w2 = svzip1_s32(u3, u2);
            const svint32_t w3 = svzip2_s32(u3, u2);
            const svint32_t s0 = svsub_s32_x(p32, w0, w2);
            const svint32_t s1 = svsub_s32_x(p32, w1, w3);
            const svint32_t s2 = svadd_s32_x(p32, w0, w2);
            const svint32_t s3 = svadd_s32_x(p32, w1, w3);
            QEOW3 = svuzp1_s16(svreinterpret_s16_s32(s0), svreinterpret_s16_s32(s1));

            const svint64_t v0 = svuzp1_s64(svreinterpret_s64_s32(s2),
                                            svreinterpret_s64_s32(s3));
            const svint64_t v1 = svuzp2_s64(svreinterpret_s64_s32(s2),
                                            svreinterpret_s64_s32(s3));
            const svint64_t v1r = revw_d64(v1);
            const svint32_t EEp = svadd_s32_x(p32, svreinterpret_s32_s64(v0),
                                              svreinterpret_s32_s64(v1r));
            const svint32_t EOp = svsub_s32_x(p32, svreinterpret_s32_s64(v0),
                                              svreinterpret_s32_s64(v1r));
            const svint32_t m0 = svmul_s32_x(p32, EEp, cT0);
            const svint32_t m1 = svmul_s32_x(p32, EOp, cT1);
            const svint32_t m2 = svmul_s32_x(p32, EEp, cT2);
            const svint32_t m3 = svmul_s32_x(p32, EOp, cT3);
            const svint32_t pa = addp_s32(m0, m2);
            const svint32_t pb = addp_s32(m1, m3);
            const svint32_t xa = svuzp1_s32(pa, pb);
            const svint32_t xb = svuzp2_s32(pa, pb);
            const svint16_t na = svqrshrnb_n_s32(xa, shift);
            const svint16_t nb = svqrshrnb_n_s32(xb, shift);
            const svint16_t n16 = svuzp1_s16(na, nb);
            st1d_scatter_s16(dst + 12, evoffs, n16);
        }

    for (int kb = 1; kb < 16; kb += 4)
    {
            const svint16_t cq_loq0 = svld1_s16(p16q, CQ_LO[kb + 0]);
            const svint16_t cq_hiq0 = svld1_s16(p16q, CQ_HI[kb + 0]);

            // k=kb + 0, groups 0..3
                svint64_t d_0_0 = svdot_s64(zaccq, QO0_0, cq_loq0);
                d_0_0 = svdot_s64(d_0_0, QO1_0, cq_hiq0);

                svint64_t d_1_0 = svdot_s64(zaccq, QO0_1, cq_loq0);
                d_1_0 = svdot_s64(d_1_0, QO1_1, cq_hiq0);

                svint64_t d_2_0 = svdot_s64(zaccq, QO0_2, cq_loq0);
                d_2_0 = svdot_s64(d_2_0, QO1_2, cq_hiq0);

                svint64_t d_3_0 = svdot_s64(zaccq, QO0_3, cq_loq0);
                d_3_0 = svdot_s64(d_3_0, QO1_3, cq_hiq0);


            {
                const svint32_t w01 = svuzp1_s32(
                    svreinterpret_s32_s64(d_0_0),
                    svreinterpret_s32_s64(d_1_0));
                const svint32_t w23 = svuzp1_s32(
                    svreinterpret_s32_s64(d_2_0),
                    svreinterpret_s32_s64(d_3_0));
                const svint16_t nb = svqrshrnb_n_s32(w01, shift);
                const svint16_t nt = svqrshrnb_n_s32(w23, shift);
                const svint16_t n16 = svuzp1_s16(nb, nt);
                svst1_s16(p16q, dst + (kb + 0) * line + 0, n16);
            }
            const svint16_t cq_loq1 = svld1_s16(p16q, CQ_LO[kb + 2]);
            const svint16_t cq_hiq1 = svld1_s16(p16q, CQ_HI[kb + 2]);

            // k=kb + 2, groups 0..3
                svint64_t d_0_1 = svdot_s64(zaccq, QO0_0, cq_loq1);
                d_0_1 = svdot_s64(d_0_1, QO1_0, cq_hiq1);

                svint64_t d_1_1 = svdot_s64(zaccq, QO0_1, cq_loq1);
                d_1_1 = svdot_s64(d_1_1, QO1_1, cq_hiq1);

                svint64_t d_2_1 = svdot_s64(zaccq, QO0_2, cq_loq1);
                d_2_1 = svdot_s64(d_2_1, QO1_2, cq_hiq1);

                svint64_t d_3_1 = svdot_s64(zaccq, QO0_3, cq_loq1);
                d_3_1 = svdot_s64(d_3_1, QO1_3, cq_hiq1);


            {
                const svint32_t w01 = svuzp1_s32(
                    svreinterpret_s32_s64(d_0_1),
                    svreinterpret_s32_s64(d_1_1));
                const svint32_t w23 = svuzp1_s32(
                    svreinterpret_s32_s64(d_2_1),
                    svreinterpret_s32_s64(d_3_1));
                const svint16_t nb = svqrshrnb_n_s32(w01, shift);
                const svint16_t nt = svqrshrnb_n_s32(w23, shift);
                const svint16_t n16 = svuzp1_s16(nb, nt);
                svst1_s16(p16q, dst + (kb + 2) * line + 0, n16);
            }
    }

    for (int kb = 2; kb < 16; kb += 8)
    {
            {
                const svint16_t cq_e0 = svld1_s16(p16q, CQ_LO[kb + 0]);
                svint64_t de0 = svdot_s64(zaccq, QEOW0, cq_e0);
                svint64_t de1 = svdot_s64(zaccq, QEOW1, cq_e0);
                svint64_t de2 = svdot_s64(zaccq, QEOW2, cq_e0);
                svint64_t de3 = svdot_s64(zaccq, QEOW3, cq_e0);
                const svint32_t w01 = svuzp1_s32(
                    svreinterpret_s32_s64(de0),
                    svreinterpret_s32_s64(de1));
                const svint32_t w23 = svuzp1_s32(
                    svreinterpret_s32_s64(de2),
                    svreinterpret_s32_s64(de3));
                const svint16_t nb = svqrshrnb_n_s32(w01, shift);
                const svint16_t nt = svqrshrnb_n_s32(w23, shift);
                const svint16_t n16 = svuzp1_s16(nb, nt);
                svst1_s16(p16q, dst + (kb + 0) * line + 0, n16);
            }

            {
                const svint16_t cq_e1 = svld1_s16(p16q, CQ_LO[kb + 4]);
                svint64_t de0 = svdot_s64(zaccq, QEOW0, cq_e1);
                svint64_t de1 = svdot_s64(zaccq, QEOW1, cq_e1);
                svint64_t de2 = svdot_s64(zaccq, QEOW2, cq_e1);
                svint64_t de3 = svdot_s64(zaccq, QEOW3, cq_e1);
                const svint32_t w01 = svuzp1_s32(
                    svreinterpret_s32_s64(de0),
                    svreinterpret_s32_s64(de1));
                const svint32_t w23 = svuzp1_s32(
                    svreinterpret_s32_s64(de2),
                    svreinterpret_s32_s64(de3));
                const svint16_t nb = svqrshrnb_n_s32(w01, shift);
                const svint16_t nt = svqrshrnb_n_s32(w23, shift);
                const svint16_t n16 = svuzp1_s16(nb, nt);
                svst1_s16(p16q, dst + (kb + 4) * line + 0, n16);
            }

    }
}

} // namespace

extern "C" void dynopt_dct16_sve2_shared(const int16_t* src, int16_t* dst, intptr_t srcStride)
{
    int16_t coef[256];
    pass_quarter<3>(src, coef, srcStride);
    pass2_upstream(coef, dst);
}
