#!/usr/bin/env python3
"""Contract corpus registry (effect/alias/rounding/tail/VL).

Seed for the round-0026 P2 corpus: one row per kernel/region with the
semantic facts AGO needs for sound bounded search (what may alias, what
rounding/tail obligations hold, which VLs are legal, what proof type is
claimed).

Usage:
  python3 tools/contract_corpus.py add 'family=dct kernel=dct16 ...'
  python3 tools/contract_corpus.py query --family filter
  python3 tools/contract_corpus.py export-md
"""

import argparse
import csv
import os
import sys
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = os.path.join(ROOT, "data", "contract-corpus.csv")
MD = os.path.join(ROOT, "data", "contract-corpus.md")

FIELDS = [
    "id", "date", "family", "kernel", "region",
    "input_isa", "output_isa", "vl_supported",
    "effects", "alias", "rounding", "tail",
    "dataflow_kind", "proof_type", "correctness_gate",
    "status", "notes",
]


def load_rows():
    if not os.path.exists(DB):
        return []
    with open(DB, newline="") as f:
        return list(csv.DictReader(f))


def save_rows(rows):
    os.makedirs(os.path.dirname(DB), exist_ok=True)
    with open(DB, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)


def parse_kv(s):
    d = OrderedDict()
    for part in s.split():
        k, _, v = part.partition("=")
        if k:
            d[k] = v
    return d


def do_add(args):
    rows = load_rows()
    row = parse_kv(" ".join(args.row))
    if not row.get("id"):
        row["id"] = "-".join(x for x in
                             (row.get("family"), row.get("kernel"),
                              row.get("region", ""), row.get("date")) if x)
    for f in FIELDS:
        row.setdefault(f, "")
    rows = [r for r in rows if r.get("id") != row["id"]]
    rows.append(row)
    rows.sort(key=lambda r: (r.get("family"), r.get("kernel"),
                             r.get("region")))
    save_rows(rows)
    print("added %s (%d rows)" % (row["id"], len(rows)))


def do_query(args):
    for r in load_rows():
        ok = all(not getattr(args, k) or getattr(args, k) in r.get(k, "")
                 for k in ("family", "kernel", "dataflow_kind", "status"))
        if ok:
            print("\t".join(r.get(f, "") for f in FIELDS))


def do_export_md(args):
    rows = load_rows()
    os.makedirs(os.path.dirname(MD), exist_ok=True)
    out = [
        "# Contract corpus (round-0026 P2, seed)",
        "",
        "Generated by `tools/contract_corpus.py export-md`; source: "
        "`data/contract-corpus.csv`. Fields: effects = memory/state "
        "footprint; alias = allowed aliasing; rounding = arithmetic "
        "semantics; tail = partial-vector/edge handling; vl_supported = "
        "legal vector lengths; proof_type = exhaustive/SMT/test "
        "obligation; correctness_gate = current gate evidence.",
        "",
        "Target (round-0026): >=4 families, >=50 regions, >=100 unique "
        "final objects.",
        "",
        "| family | kernel | region | effects | alias | rounding | tail | "
        "vl | dataflow | proof | gate | status |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | "
        "--- | --- |",
    ]
    for r in rows:
        out.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | "
                   "%s | %s |"
                   % (r.get("family"), r.get("kernel"), r.get("region"),
                      (r.get("effects") or "-").replace("|", "/"),
                      r.get("alias") or "-", r.get("rounding") or "-",
                      r.get("tail") or "-", r.get("vl_supported") or "-",
                      r.get("dataflow_kind") or "-",
                      r.get("proof_type") or "-",
                      r.get("correctness_gate") or "-",
                      r.get("status") or "-"))
    with open(MD, "w") as f:
        f.write("\n".join(out))
    print("wrote %s (%d rows)" % (MD, len(rows)))


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    a = sub.add_parser("add")
    a.add_argument("row", nargs="+")
    a.set_defaults(fn=do_add)
    q = sub.add_parser("query")
    for k in ("family", "kernel", "dataflow_kind", "status"):
        q.add_argument("--" + k, default="")
    q.set_defaults(fn=do_query)
    e = sub.add_parser("export-md")
    e.set_defaults(fn=do_export_md)
    args = ap.parse_args()
    sys.exit(args.fn(args) or 0)


if __name__ == "__main__":
    main()
