#!/usr/bin/env python3
"""Parameterized SVE2 (VL=256) emitter for DCT8, manifest-driven (docs/16).

DCT8 rows are 8 s16 (128 bits), so the leaf form is:
  out_k[i] = dot(g_t8[k][0..3], (E_i if k even else O_i))
  E_i[j] = s_i[j] + s_i[7-j],  O_i[j] = s_i[j] - s_i[7-j]
Four rows' 4-lane leaves are quarter-packed into one 16-lane register,
so one SVE2 `SDOT .d` computes all four outputs of a coefficient row.
"""

import argparse


GT8 = [
    [64, 64, 64, 64, 64, 64, 64, 64],
    [89, 75, 50, 18, -18, -50, -75, -89],
    [83, 36, -36, -83, -83, -36, 36, 83],
    [75, -18, -89, -50, 50, 89, 18, -75],
    [64, -64, -64, 64, 64, -64, -64, 64],
    [50, -89, 18, 75, -75, -18, 89, -50],
    [36, -83, 83, -36, -36, 83, -83, 36],
    [18, -50, 75, -89, 89, -75, 50, -18],
]


def cq_rows():
    rows = []
    for c in GT8:
        rows.append("    { %s }," % ", ".join(str(x) for x in c[:4] * 4))
    return "\n".join(rows)


def group_block(g):
    base = 4 * g
    return """\
        {
            const svint16_t z0 = svld1_s16(p8, src + %d * stride);
            const svint16_t z1 = svld1_s16(p8, src + %d * stride);
            const svint16_t z2 = svld1_s16(p8, src + %d * stride);
            const svint16_t z3 = svld1_s16(p8, src + %d * stride);
            const svint16_t r0 = svtbl_s16(z0, irv);
            const svint16_t r1 = svtbl_s16(z1, irv);
            const svint16_t r2 = svtbl_s16(z2, irv);
            const svint16_t r3 = svtbl_s16(z3, irv);
            const svint16_t E0 = svadd_s16_x(p16, z0, r0);
            const svint16_t E1 = svadd_s16_x(p16, z1, r1);
            const svint16_t E2 = svadd_s16_x(p16, z2, r2);
            const svint16_t E3 = svadd_s16_x(p16, z3, r3);
            const svint16_t O0 = svsub_s16_x(p16, z0, r0);
            const svint16_t O1 = svsub_s16_x(p16, z1, r1);
            const svint16_t O2 = svsub_s16_x(p16, z2, r2);
            const svint16_t O3 = svsub_s16_x(p16, z3, r3);
            const svint16_t tE01 = svtbl2_s16(svcreate2_s16(E0, E1), ilo);
            const svint16_t tE23 = svtbl2_s16(svcreate2_s16(E2, E3), ilo);
            const svint16_t tO01 = svtbl2_s16(svcreate2_s16(O0, O1), ilo);
            const svint16_t tO23 = svtbl2_s16(svcreate2_s16(O2, O3), ilo);
            QE0_%d = svtbl2_s16(svcreate2_s16(tE01, tE23), qsel);
            QO0_%d = svtbl2_s16(svcreate2_s16(tO01, tO23), qsel);
        }""" % (base, base + 1, base + 2, base + 3, g, g)


def dot_group(g, kexpr, lo):
    return """\
            const svint64_t d%d = svdot_s64(zacc, %s, %s);
            const svint32_t w%d = svuzp1_s32(
                svreinterpret_s32_s64(d%d), svreinterpret_s32_s64(d%d));
            svint16_t n%d = svrshrnb_n_s32(w%d, shift);
            n%d = svuzp1_s16(n%d, n%d);
            svst1_s16(p4h, dst + (%s) * 8 + %d, n%d);""" % (
        g, kexpr, lo, g, g, g, g, g, g, g, g, kexpr, 4 * g, g)


def emit(func_name="dynopt_dct8_sve2_shared", k_tile=1):
    cq = cq_rows()
    build = "\n".join(group_block(g) for g in range(2))
    tiles = []
    for t in range(k_tile):
        kexpr = "kb + %d" % t
        lo = "cq%d" % t
        tiles.append(
            "            {\n"
            "                const svint16_t %s = svld1_s16(p16, CQ[%s]);\n"
            "%s\n"
            "            }"
            % (lo, kexpr,
               "\n".join(dot_group(g, "(%s & 1) ? QO0_%d : QE0_%d"
                                   % (kexpr, g, g), lo)
                         for g in range(2))))
    dot = ("        for (int kb = 0; kb < 8; kb += %d)\n"
           "        {\n%s\n        }\n" % (k_tile, "\n".join(tiles)))
    return """\
// Generated by tools/emit_dct8_sve2_shared.py -- do not edit by hand.
#include <arm_sve.h>
#include <cstdint>

namespace {

static const int16_t CQ[8][16] = {
%s
};

static const uint16_t idx_rev[16] =
    { 7, 6, 5, 4, 3, 2, 1, 0, 15, 14, 13, 12, 11, 10, 9, 8 };
static const uint16_t idx_lo[16] =
    { 0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23 };
static const uint16_t idx_qsel[16] =
    { 0, 1, 2, 3, 8, 9, 10, 11, 16, 17, 18, 19, 24, 25, 26, 27 };

template <int shift>
static void pass(const int16_t* src, int16_t* dst, intptr_t stride)
{
    const svbool_t p16 = svptrue_b16();
    const svbool_t p8 = svwhilelt_b16(0, 8);
    const svbool_t p4h = svwhilelt_b16(0, 4);
    const svuint16_t irv = svld1_u16(p16, idx_rev);
    const svuint16_t ilo = svld1_u16(p16, idx_lo);
    const svuint16_t qsel = svld1_u16(p16, idx_qsel);
    const svint64_t zacc = svdup_n_s64(0);

    svint16_t QE0_0, QO0_0, QE0_1, QO0_1;
%s

%s
}

} // namespace

extern "C" void %s(const int16_t* src, int16_t* dst, intptr_t srcStride)
{
    int16_t coef[64];
    pass<2>(src, coef, srcStride);
    pass<9>(coef, dst, 8);
}
""" % (cq, build, dot, func_name)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out", default="kernels/dct8/candidates/sve2_shared.cpp",
                    nargs="?")
    ap.add_argument("--k-tile", type=int, default=1)
    args = ap.parse_args()
    with open(args.out, "w") as f:
        f.write(emit(k_tile=args.k_tile))
    print("wrote %s" % args.out)


if __name__ == "__main__":
    main()
