#!/usr/bin/env python3
"""Pure-NEON quant (256 elems) emitter for 920B (round-0023).

The SVE1 quant candidate measures ~0.75 vs x265_quant_neon on 920B
(CNTVCT).  This emitter ports the same element semantics to NEON and
searches:

  count  vaddv    -- accumulate nonzero via vaddvq_u32 per half
         vceqz    -- keep a u8 compare mask and use vaddlvq_u8 once

Semantics per element (x265 quant_c, 256 elems):
  a = abs(coef) * quantCoeff
  level = (a + add) >> qBits
  deltaU = (a - (level << qBits)) >> (qBits - 8)
  qCoef = level * sign(coef); return #nonzero(level)
"""


def emit_256(func_name="dynopt_quant_256_sve2", count="vaddv"):
    if count not in ("vaddv", "vceqz"):
        raise ValueError("unknown count %r" % count)

    if count == "vaddv":
        nz_src = ("    uint32_t nz = 0;\n"
                  "    uint32x4_t nzacc = vdupq_n_u32(0);")
        nz_step = ("    nzacc = vaddq_u32(nzacc, vandq_u32(\n"
                   "        vceqq_s32(%(p)sl0, vdupq_n_s32(0)),\n"
                   "        vdupq_n_u32(1)));\n"
                   "    nzacc = vaddq_u32(nzacc, vandq_u32(\n"
                   "        vceqq_s32(%(p)sl1, vdupq_n_s32(0)),\n"
                   "        vdupq_n_u32(1)));")
        nz_end = ("    nz = vaddvq_u32(nzacc);\n"
                  "    return 256 - nz;")
    else:
        nz_src = ("    uint32_t nz = 0;\n"
                  "    uint8x16_t nzm = vdupq_n_u8(0);")
        nz_step = ("    nzm = vaddq_u8(nzm, vcombine_u8(\n"
                   "        vmovn_u16(vcombine_u16(\n"
                   "            vmovn_u32(vceqq_s32(%(p)sl0,"
                   " vdupq_n_s32(0))),\n"
                   "            vmovn_u32(vceqq_s32(%(p)sl1,"
                   " vdupq_n_s32(0))))),\n"
                   "        vdup_n_u8(0)));")
        nz_end = ("    const uint16_t z16 = (uint16_t)vaddlvq_u8(nzm);\n"
                  "    return 256 - (int)z16;")

    step = """\
    int16x8_t %(p)sv = vld1q_s16(coef + %(i)d);
    int32x4_t %(p)sa0 = vabsq_s32(vmovl_s16(vget_low_s16(%(p)sv)));
    int32x4_t %(p)sa1 = vabsq_s32(vmovl_high_s16(%(p)sv));
    int32x4_t %(p)sqc0 = vld1q_s32(qc + %(i)d);
    int32x4_t %(p)sqc1 = vld1q_s32(qc + %(i)d + 4);
    int32x4_t %(p)sp0 = vmulq_s32(%(p)sa0, %(p)sqc0);
    int32x4_t %(p)sp1 = vmulq_s32(%(p)sa1, %(p)sqc1);
    int32x4_t %(p)sl0 = vshlq_s32(vaddq_s32(%(p)sp0, addv), qbits_neg);
    int32x4_t %(p)sl1 = vshlq_s32(vaddq_s32(%(p)sp1, addv), qbits_neg);
    int32x4_t %(p)sd0 = vshlq_s32(vsubq_s32(%(p)sp0,
                             vshlq_s32(%(p)sl0, qbits_pos)),
                             qbits8_neg);
    int32x4_t %(p)sd1 = vshlq_s32(vsubq_s32(%(p)sp1,
                             vshlq_s32(%(p)sl1, qbits_pos)),
                             qbits8_neg);
    vst1q_s32(du + %(i)d, %(p)sd0);
    vst1q_s32(du + %(i)d + 4, %(p)sd1);
    int32x4_t %(p)ssg = vshrq_n_s32(vmovl_s16(vget_low_s16(%(p)sv)), 31);
    int32x4_t %(p)ssg2 = vshrq_n_s32(vmovl_high_s16(%(p)sv), 31);
    int32x4_t %(p)sqq0 = vsubq_s32(veorq_s32(%(p)sl0, %(p)ssg), %(p)ssg);
    int32x4_t %(p)sqq1 = vsubq_s32(veorq_s32(%(p)sl1, %(p)ssg2), %(p)ssg2);
    vst1q_s16(qo + %(i)d,
              vcombine_s16(vqmovn_s32(%(p)sqq0), vqmovn_s32(%(p)sqq1)));
%(nz_step)s
"""
    steps = []
    for gi in range(32):
        steps.append(step % {
            "i": 8 * gi, "p": "u%d_" % gi,
            "nz_step": nz_step % {"p": "u%d_" % gi}})

    return """\
// Generated by tools/emit_quant_neon_shared.py -- do not edit by hand.
// quant 256 pure NEON, count=%(count)s.
#include <arm_neon.h>
#include <stdint.h>

extern "C" uint32_t %(func)s(
    const int16_t* coef, const int32_t* qc, int32_t* du,
    int16_t* qo, int qBits, int add)
{
    const int32x4_t addv = vdupq_n_s32(add);
    const int32x4_t qbits_neg = vdupq_n_s32(-qBits);
    const int32x4_t qbits_pos = vdupq_n_s32(qBits);
    const int32x4_t qbits8_neg = vdupq_n_s32(-(qBits - 8));
%(nz_src)s
%(steps)s
%(nz_end)s
}
""" % {"count": count, "func": func_name,
       "nz_src": nz_src, "steps": "\n".join(steps), "nz_end": nz_end}


def emit_combo(combo):
    return emit_256(
        count=combo.get("count", "vaddv"))
