#!/usr/bin/env python3
"""SVE2p3 (VL=256) emitter for the chroma 4-tap horizontal filter
(interp4 hpp), upstream-exact vs x265 interp4_horiz_pp_dotprod<W,H>.

Semantics: src -= 1; out[c] = sat_u8(round(SUM_{k=0..3} coeff[phase][k] *
src[c+k] / 2^6)); coefficients sum to 64 (g_chromaFilter, 8 phases).

Structure (2026-08-14): 16 pixels per row fit one z.h vector. A single
TBL builds the sliding byte pattern X = [s0,s1,s2,s3, s1,s2,s3,s4, ...];
two SDOT BtoH (SVE2p3) accumulate all four taps into one s16 lane
(4 products <= 4*58*127 fits s16); the (b-128) bias and +8192 DC offset
are folded into the accumulator (movprfx, fused). Per row: ld1b + sub +
tbl + movprfx(fused) + sdot + sdot + sqrshrunb + uzp1 + st1b = 8 counted.
"""

import argparse


CHROMA_COEFFS = {
    0: [0, 64, 0, 0],
    1: [-2, 58, 10, -2],
    2: [-4, 54, 16, -2],
    3: [-6, 46, 28, -4],
    4: [-4, 36, 36, -4],
    5: [-4, 28, 46, -6],
    6: [-2, 16, 54, -4],
    7: [-2, 10, 58, -2],
}


def emit(func_name=None, width=16, height=16):
    """Chroma 4-tap horizontal (SVE2p3, VL=256), W x H with W in
    {8,16,32,...}: each 16-pixel unit uses one 32-byte window; 8-wide
    blocks store only the low 8 bytes."""
    if func_name is None:
        func_name = "dynopt_interp4_%dx%d_sve2" % (width, height)
    units = max(1, (width + 15) // 16)
    coeff_lines = ["static const int8_t CHROMA_C[8][4] = {"]
    for ph in range(8):
        coeff_lines.append("    { %d, %d, %d, %d },"
                           % tuple(CHROMA_COEFFS[ph]))
    coeff_lines.append("};")
    body = """\
// Generated by tools/emit_interp4_sve2_shared.py -- do not edit.
// Chroma 4-tap horizontal %(width)dx%(height)d (SVE2p3, VL=256).
#include <arm_sve.h>

%(coeffs)s

static const uint8_t IX_A[32] =
    { 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8,
      8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16 };
static const uint8_t IX_B[32] =
    { 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10,
      10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18 };

static inline svint16_t sdot_h(svint16_t acc, svint8_t a, svint8_t b)
{
    asm volatile("sdot %%0.h, %%1.b, %%2.b"
                 : "+w"(acc) : "w"(a), "w"(b));
    return acc;
}

static inline svint16_t sdot_h_acc(svint16_t acc, svint8_t a, svint8_t b)
{
    svint16_t out;
    asm volatile("movprfx %%0, %%1\\n\\tsdot %%0.h, %%2.b, %%3.b"
                 : "=&w"(out) : "w"(acc), "w"(a), "w"(b));
    return out;
}

extern "C" void %(func_name)s(const uint8_t* src, intptr_t srcStride,
                   uint8_t* dst, intptr_t dstStride, int coeffIdx)
{
    const svbool_t p32 = svptrue_b8();
    const svbool_t p16b = svwhilelt_b8((uint32_t)0, (uint32_t)16);
    const svbool_t p8b = svwhilelt_b8((uint32_t)0, (uint32_t)8);
    const int ph = coeffIdx & 7;
    const int8_t* cf = (const int8_t*)CHROMA_C[ph];
    const svint8_t c01 = svdupq_n_s8(cf[0], cf[1], cf[0], cf[1],
        cf[0], cf[1], cf[0], cf[1], cf[0], cf[1], cf[0], cf[1],
        cf[0], cf[1], cf[0], cf[1]);
    const svint8_t c23 = svdupq_n_s8(cf[2], cf[3], cf[2], cf[3],
        cf[2], cf[3], cf[2], cf[3], cf[2], cf[3], cf[2], cf[3],
        cf[2], cf[3], cf[2], cf[3]);
    const svuint8_t ix_a = svld1_u8(p32, IX_A);
    const svuint8_t ix_b = svld1_u8(p32, IX_B);
    const svint16_t zero = svdup_n_s16(0);

    for (int r = 0; r < %(height)d; r++)
    {
        const uint8_t* row = src + r * srcStride - 1;
        uint8_t* drow = dst + r * dstStride;
        for (int u = 0; u < %(units)d; u++)
        {
            svuint8_t W32 = svld1_u8(p32, row + u * 16);
            svint8_t W = svreinterpret_s8_u8(
                svsub_n_u8_x(p32, W32, 128));
            svint8_t X = svtbl_s8(W, ix_a);
            svint8_t X2 = svtbl_s8(W, ix_b);
            svint16_t t = sdot_h_acc(zero, X, c01);
            t = sdot_h(t, X2, c23);
            t = svadd_n_s16_x(svptrue_b16(), t, 8192);
            svuint8_t u8 = svqrshrunb_n_s16(t, 6);
            svuint8_t uz = svuzp1_u8(u8, u8);
            svst1_u8(%(width)d < 16 ? p8b : p16b, drow + u * 16, uz);
        }
    }
}
""" % {"func_name": func_name, "width": width, "height": height,
       "units": units,
       "coeffs": "\n".join(coeff_lines)}
    return body


def emit_8x8(func_name="dynopt_interp4_8x8_sve2"):
    return emit(func_name, width=8, height=8)


def emit_16x16(func_name="dynopt_interp4_16x16_sve2"):
    return emit(func_name, width=16, height=16)


def emit_32x32(func_name="dynopt_interp4_32x32_sve2"):
    return emit(func_name, width=32, height=32)


def emit_vpp(func_name, width=16, height=16):
    """Chroma 4-tap vertical W x H (SVE2, VL=256), upstream-exact vs
    x265::interp_vert_pp_neon<4,W,H>.

    Contract: src is the block top-left; output row r = sat_u8(round(
    SUM f_k * src[(r-1+k)*stride + c] / 2^6)); coefficients sum to 64
    (g_chromaFilter, 8 phases).

    Sliding-row pipeline (2026-08-14): 19 row vectors (rows -1..+18) are
    loaded lazily; output row i consumes v_i..v_{i+3} with 4 MLA into one
    s16 accumulator (4 products <= 4*58*127 fits s16), then +8192 DC
    offset, sqrshrunb+uzp1+st1b. Per row: 1 load + 1 sub + 4 mla + 1 add
    + 3 tail = 9 counted.
    """
    units = max(1, (width + 15) // 16)
    rows = height
    n_rows = rows + 3
    coeff = {
        0: [0, 64, 0, 0],
        1: [-2, 58, 10, -2],
        2: [-4, 54, 16, -2],
        3: [-6, 46, 28, -4],
        4: [-4, 36, 36, -4],
        5: [-4, 28, 46, -6],
        6: [-2, 16, 54, -4],
        7: [-2, 10, 58, -2],
    }
    head = """\
// Generated by tools/emit_interp4_sve2_shared.py -- do not edit.
// Chroma 4-tap vertical %(width)dx%(height)d (SVE2, VL=256).
#include <arm_sve.h>

static inline svint16_t vrow(const uint8_t* p, intptr_t st, int k, int u,
                             svbool_t p16)
{
    svuint16_t w = svld1ub_u16(p16, p + k * st + u * 16);
    return svreinterpret_s16_u16(svsub_n_u16_x(p16, w, 128));
}

extern "C" void %(func_name)s(const uint8_t* src, intptr_t srcStride,
                   uint8_t* dst, intptr_t dstStride, int coeffIdx)
{
    const svbool_t p16 = svptrue_b16();
    const svbool_t p16b = svwhilelt_b8((uint32_t)0, (uint32_t)16);
    const svbool_t p8b = svwhilelt_b8((uint32_t)0, (uint32_t)8);
%(pout_lines)s
    const int ph = coeffIdx & 7;
    const int8_t* cf = (const int8_t*)CHROMA_C[ph];
    const svint16_t c0 = svdup_n_s16(cf[0]);
    const svint16_t c1 = svdup_n_s16(cf[1]);
    const svint16_t c2 = svdup_n_s16(cf[2]);
    const svint16_t c3 = svdup_n_s16(cf[3]);
    const svint16_t zero = svdup_n_s16(0);
    const uint8_t* rb = src - srcStride;

"""
    lines = []
    for k in range(5):
        for u in range(units):
            lines.append("    svint16_t v%d_%d = vrow(rb, srcStride, %d, %d,"
                         " p16);" % (k, u, k, u))
    for r in range(rows):
        if r + 5 < n_rows:
            for u in range(units):
                lines.append("    svint16_t v%d_%d = vrow(rb, srcStride, %d,"
                             " %d, p16);" % (r + 5, u, r + 5, u))
        for u in range(units):
            lines.append("    {")
            for k in range(4):
                lines.append("        svint16_t acc%d = svmla_s16_x(p16, %s,"
                             " v%d_%d, c%d);"
                             % (k, "zero" if k == 0 else "acc%d" % (k - 1),
                                r + k, u, k))
            lines.append("        svint16_t acc = svadd_n_s16_x(p16, acc3,"
                         " 8192);")
            lines.append("        svuint8_t u8 = svqrshrunb_n_s16(acc, 6);")
            lines.append("        svuint8_t uz = svuzp1_u8(u8, u8);")
            lines.append("        svst1_u8(pout%d, dst + %d * dstStride + %d,"
                         " uz);" % (u, r, u * 16))
            lines.append("    }")
    lines.append("}")
    pout_lines = []
    for u in range(units):
        n = min(16, width - u * 16)
        pout_lines.append(
            "    const svbool_t pout%d = svwhilelt_b8((uint32_t)0,"
            " (uint32_t)%d);" % (u, n))
    body = head % {"func_name": func_name, "width": width,
                   "height": height,
                   "pout_lines": "\n".join(pout_lines)} + "\n".join(lines)
    coeff_lines = ["static const int8_t CHROMA_C[8][4] = {"]
    for ph in range(8):
        coeff_lines.append("    { %d, %d, %d, %d },"
                           % tuple(coeff[ph]))
    coeff_lines.append("};")
    return body.replace(
        "#include <arm_sve.h>",
        "#include <arm_sve.h>\n\n" + "\n".join(coeff_lines))


def emit_vpp_16x16(func_name="dynopt_interp4_16x16_sve2_vpp"):
    return emit_vpp(func_name, width=16, height=16)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out", default="generated/interp4/sve2_16x16.cpp")
    args = ap.parse_args()
    with open(args.out, "w") as f:
        f.write(emit_16x16())
    print("wrote %s" % args.out)


if __name__ == "__main__":
    main()
