#!/usr/bin/env python3
"""SVE2 (VL=256) emitter for the 8-bit horizontal 8-tap luma filter
(interp8, 8x8), upstream-exact (path A: sdot .d slices + NEON-bridge
saturating narrow).

Semantics (x265 interp8_horiz_pp_neon): src -= 3; out[c] =
sat_u8(round(SUM_{k=0..7} coeff[phase][k] * src[c-3+k] / 2^6)).

Structure (mirrors the DCT32 v3 lane-per-output trick):
  - one 16-byte window W = src[row]-3 .. +12 (svld1ub_u16, widening);
  - three TBL slices (windows overlap, so X1 is reused):
      X0 = outs0-3 taps0-3, X1 = outs0-3 taps4-7 == outs4-7 taps0-3,
      X2 = outs4-7 taps4-7;
  - per half: 2 SDOT .d (4 outputs accumulate their full 8 taps in 4
    s64 lanes) + uzp1_s32 + rshrnb(6) + uzp1_s16 + vqmovun (NEON bridge,
    saturating) + 4-lane predicate store.
"""

import argparse


COEFFS = {
    1: [-1, 4, -10, 58, 17, -5, 1, 0],
    2: [-1, 4, -11, 40, 40, -11, 4, -1],
    3: [0, 1, -5, 17, 58, -10, 4, -1],
}


def cpp_constants():
    lines = ["static const int16_t CTBL[4][2][16] = {"]
    for ph in (1, 2, 3):
        c = COEFFS[ph]
        lines.append("    {")
        for m in range(2):
            g = c[4 * m:4 * m + 4]
            body = ", ".join(str(x) for x in g)
            lines.append("        { %s, %s, %s, %s },  // m=%d"
                         % (body, body, body, body, m))
        lines.append("    },  // phase %d" % ph)
    lines.append("};")
    lines.append("""\
static const uint16_t IDX_X0[16] =
    { 0, 1, 2, 3, 1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6 };
static const uint16_t IDX_X1[16] =
    { 4, 5, 6, 7, 5, 6, 7, 8, 6, 7, 8, 9, 7, 8, 9, 10 };
static const uint16_t IDX_X2[16] =
    { 8, 9, 10, 11, 9, 10, 11, 12, 10, 11, 12, 13, 11, 12, 13, 14 };
""")
    return "\n".join(lines)


def emit(func_name="dynopt_interp8_8x8_sve2"):
    return """\
// Generated by tools/emit_interp8_sve2_shared.py -- do not edit by hand.
// 8-bit horizontal 8-tap luma filter 8x8 (SVE2, VL=256), upstream-exact.
#include <arm_sve.h>
#include <arm_neon.h>
#include <arm_neon_sve_bridge.h>

%s

extern "C" void %s(const uint8_t* src, intptr_t srcStride,
                   uint8_t* dst, intptr_t dstStride, int coeffIdx)
{
    const svbool_t p16 = svptrue_b16();
    const svbool_t pg4b = svwhilelt_b8(0, 4);
    const svint64_t zero64 = svdup_n_s64(0);
    const int ph = (coeffIdx >= 1 && coeffIdx <= 3) ? coeffIdx : 2;
    const svint16_t c0 = svld1_s16(p16, CTBL[ph - 1][0]);
    const svint16_t c1 = svld1_s16(p16, CTBL[ph - 1][1]);
    const svuint16_t ix0 = svld1_u16(p16, IDX_X0);
    const svuint16_t ix1 = svld1_u16(p16, IDX_X1);
    const svuint16_t ix2 = svld1_u16(p16, IDX_X2);

    for (int r = 0; r < 8; r++)
    {
        const uint8_t* row = src + r * srcStride - 3;
        svuint16_t W = svld1ub_u16(p16, row);
        svint16_t X0 = svreinterpret_s16_u16(svtbl_u16(W, ix0));
        svint16_t X1 = svreinterpret_s16_u16(svtbl_u16(W, ix1));
        svint16_t X2 = svreinterpret_s16_u16(svtbl_u16(W, ix2));

        svint64_t t0 = svdot_s64(zero64, X0, c0);
        t0 = svdot_s64(t0, X1, c1);
        svint32_t lo0 = svuzp1_s32(svreinterpret_s32_s64(t0),
                                   svreinterpret_s32_s64(t0));
        svint16_t r0 = svrshrnb_n_s32(lo0, 6);
        svint16_t rz0 = svuzp1_s16(r0, r0);
        uint8x8_t u0 = vqmovun_s16(svget_neonq_s16(rz0));
        svst1_u8(pg4b, dst + r * dstStride,
                 svset_neonq_u8(svundef_u8(), vcombine_u8(u0, vdup_n_u8(0))));

        svint64_t t1 = svdot_s64(zero64, X1, c0);
        t1 = svdot_s64(t1, X2, c1);
        svint32_t lo1 = svuzp1_s32(svreinterpret_s32_s64(t1),
                                   svreinterpret_s32_s64(t1));
        svint16_t r1 = svrshrnb_n_s32(lo1, 6);
        svint16_t rz1 = svuzp1_s16(r1, r1);
        uint8x8_t u1 = vqmovun_s16(svget_neonq_s16(rz1));
        svst1_u8(pg4b, dst + r * dstStride + 4,
                 svset_neonq_u8(svundef_u8(), vcombine_u8(u1, vdup_n_u8(0))));
    }
}
""" % (cpp_constants(), func_name)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out", default="generated/interp8/sve2_8x8.cpp")
    args = ap.parse_args()
    with open(args.out, "w") as f:
        f.write(emit())
    print("wrote %s" % args.out)


if __name__ == "__main__":
    main()
