#!/usr/bin/env python3
"""Emit a fused luma_hvpp candidate by extracting x265's own fused
interp8_hv_pp_i8mm implementation.

x265 compiles the fused register-window hvpp only under Clang; GCC
builds dispatch luma_hvpp to an immed-buffer path (horiz_ps -> memory ->
vert_sp).  This emitter packages the upstream fused code as a standalone
candidate so GCC/SVE2 builds can use it for vertical phases 1..3, with
an upstream-exact buffer fallback for phases 4..7.

Usage:
  python3 tools/emit_hvpp_fused.py --width 32 --height 32 \
      --out kernels/interp8-hvpp-32x32/candidates/best_sve2.cpp
"""

import argparse
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
I8MM = os.path.join(
    ROOT, "third_party/x265/source/common/aarch64/filter-neon-i8mm.cpp")
PRIMH = os.path.join(
    ROOT, "third_party/x265/source/common/aarch64/filter-prim.h")
MEMH = os.path.join(
    ROOT, "third_party/x265/source/common/aarch64/mem-neon.h")


def _extract_block(text, start_marker, end_marker=None, braces=True):
    i = text.index(start_marker)
    j = text.index("{", i)
    if end_marker is not None and not braces:
        k = text.index(end_marker, i)
        return text[i:k].rstrip()
    depth = 0
    k = j
    while k < len(text):
        if text[k] == "{":
            depth += 1
        elif text[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    return text[i:k + 1].rstrip()


def _tables(i8mm):
    i = i8mm.index("static const uint8_t matmul_permute_tbl")
    j = i8mm.index("template<bool coeff2>\nuint8x8_t inline filter8_8_pp_matmul", i)
    return i8mm[i:j].rstrip()


def _filter8_8_ps_matmul(i8mm):
    return _extract_block(
        i8mm, "template<bool coeff2>\nint16x8_t inline filter8_8_ps_matmul")


def _filter8_4_ps_matmul(i8mm):
    return _extract_block(
        i8mm, "template<bool coeff2>\nint16x4_t inline filter8_4_ps_matmul")


def _fused_hvpp(i8mm):
    return _extract_block(
        i8mm,
        "template<bool coeff2, int coeffIdy, int width, int height>\n"
        "void interp8_hv_pp_i8mm")


def _filter8_s16x8(primh):
    return _extract_block(primh, "template<int coeffIdx>\nvoid inline filter8_s16x8")


def _filter8_s16x4(primh):
    return _extract_block(primh, "template<int coeffIdx>\nvoid inline filter8_s16x4")


def _vtbl2q(primh):
    return _extract_block(primh, "static inline int16x8_t vtbl2q_s32_s16")


def _store_helpers(memh):
    i = memh.index(
        "template<int N>\nstatic void inline store_u8x4_strided_xN")
    j = memh.index(
        "template<int N, int M>\nstatic void inline store_u8xnxm_strided", i)
    return memh[i:j].rstrip()


def emit(width, height, func_name):
    with open(I8MM) as f:
        i8mm = f.read()
    with open(PRIMH) as f:
        primh = f.read()
    with open(MEMH) as f:
        memh = f.read()

    fused = _fused_hvpp(i8mm)
    fallback = """\
    // Phases 4..7: upstream GCC path (immed buffer + separate filters).
    // Reference the lib's own instantiations to stay bit-exact.
    int16_t immed[%d * (%d + 7)] __attribute__((aligned(32)));
    x265::interp8_horiz_ps_i8mm<%d, %d>(src, srcStride, immed, %d, idxX, 1);
    x265::interp_vert_sp_neon<8, %d, %d>(
        immed + 3 * %d, %d, dst, dstStride, idxY);
}""" % (width, height, width, height, width, width, height, width, width)

    return """\
// Generated by tools/emit_hvpp_fused.py -- do not edit by hand.
// Fused luma_hvpp %dx%d: extracted from x265's Clang-only fused
// interp8_hv_pp_i8mm (GCC builds fall back to the immed-buffer path).
#include <arm_neon.h>
#include <assert.h>
#include <stdint.h>
#include <stddef.h>

typedef uint8_t pixel;
#define IF_INTERNAL_PREC 14
#define IF_FILTER_PREC 6
#define IF_INTERNAL_OFFS (1 << (IF_INTERNAL_PREC - 1))
#define X265_DEPTH 8
namespace x265 {
extern const int16_t g_lumaFilter[4][8];
template <int W, int H> void interp8_horiz_ps_i8mm(
    const uint8_t*, intptr_t, int16_t*, intptr_t, int, int);
template <int N, int W, int H> void interp_vert_sp_neon(
    const int16_t*, intptr_t, uint8_t*, intptr_t, int);
}

%s

%s

%s

%s

%s

%s

%s

%s

extern "C" void %s(const uint8_t* src, intptr_t srcStride,
                   uint8_t* dst, intptr_t dstStride, int idxX, int idxY)
{
    switch (idxX)
    {
    case 2:
        switch (idxY)
        {
        case 1:
            return interp8_hv_pp_i8mm<true, 1, %d, %d>(src, srcStride, dst,
                                                       dstStride, idxX);
        case 2:
            return interp8_hv_pp_i8mm<true, 2, %d, %d>(src, srcStride, dst,
                                                       dstStride, idxX);
        case 3:
            return interp8_hv_pp_i8mm<true, 3, %d, %d>(src, srcStride, dst,
                                                       dstStride, idxX);
        }
        break;

    default:
        switch (idxY)
        {
        case 1:
            return interp8_hv_pp_i8mm<false, 1, %d, %d>(src, srcStride, dst,
                                                        dstStride, idxX);
        case 2:
            return interp8_hv_pp_i8mm<false, 2, %d, %d>(src, srcStride, dst,
                                                        dstStride, idxX);
        case 3:
            return interp8_hv_pp_i8mm<false, 3, %d, %d>(src, srcStride, dst,
                                                        dstStride, idxX);
        }
        break;
    }

%s
""" % (width, height,
       _tables(i8mm),
       _vtbl2q(primh),
       _filter8_s16x4(primh),
       _filter8_s16x8(primh),
       _filter8_8_ps_matmul(i8mm),
       _filter8_4_ps_matmul(i8mm),
       _store_helpers(memh),
       fused,
       func_name,
       width, height, width, height, width, height,
       width, height, width, height, width, height,
       fallback)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--width", type=int, default=32)
    ap.add_argument("--height", type=int, default=32)
    ap.add_argument("--func", default="")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    func = args.func or "dynopt_interp_hvpp_%dx%d_sve2" % (
        args.width, args.height)
    src = emit(args.width, args.height, func)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(src)
    print("wrote %s (%d bytes)" % (args.out, len(src)))


if __name__ == "__main__":
    main()
