#!/usr/bin/env python3
"""Pure-NEON SA8D 16x16 emitter for the 920B NEON datapath (round-0022).

The SVE1 natural-row sa8d16 candidate measures 0.67-0.81 vs upstream NEON
on 920B (CNTVCT), i.e. the SVE1 CADD/TBL pipeline loses to the NEON 8-lane
Hadamard.  This emitter ports the x265 NEON 8x8 Hadamard structure and
searches the reduction/quadrant axes that the open-source version fixes:

  reduce  vpadal  upstream-style vpaddlq_u16 + vpadalq_u16 accumulate
          vaddlv  keep u16x8 lane sums and use one vaddlvq_u16 at the end
          vaddv   per-quadrant vaddvq_u16 + scalar u32 accumulate
  quad    seq     upstream quadrant order TL, TR, BL, BR (load per quad)
          pair    load both top-row quadrants before the top Hadamards
                  (more load ILP, same math)

Contract: bit-exact with the SVE2 reference (integer Hadamard sum), so the
existing sa8d16 upstream-exact verifier gates it.
"""


def emit_16x16(func_name="dynopt_sa8d_16x16_sve2", reduce="vpadal",
               quad="seq"):
    if reduce not in ("vpadal", "vaddlv", "vaddv"):
        raise ValueError("unknown reduce %r" % reduce)
    if quad not in ("seq", "pair"):
        raise ValueError("unknown quad %r" % quad)

    if reduce == "vpadal":
        red_init = ("    uint32x4_t sum0 = vpaddlq_u16(r0);\n"
                    "    uint32x4_t sum1 = vpaddlq_u16(r1);")
        red_acc = ("    sum0 = vpadalq_u16(sum0, r0);\n"
                   "    sum1 = vpadalq_u16(sum1, r1);")
        red_end = ("    sum0 = vaddq_u32(sum0, sum1);\n"
                   "    return (int)((vaddvq_u32(sum0) + 1) >> 1);")
    elif reduce == "vaddlv":
        red_init = "    uint16x8_t tot = vaddq_u16(r0, r1);"
        red_acc = "    tot = vaddq_u16(tot, r0);\n    tot = vaddq_u16(tot, r1);"
        red_end = ("    return (int)((vaddlvq_u16(tot) + 1) >> 1);")
    else:  # vaddv: per-quadrant horizontal sum into scalar u32 total
        red_init = ("    uint32_t total = (uint32_t)vaddvq_u16("
                    "vaddq_u16(r0, r1));")
        red_acc = ("    total += (uint32_t)vaddvq_u16(vaddq_u16(r0, r1));")
        red_end = "    return (int)((total + 1) >> 1);"

    if quad == "seq":
        qbody = """\
    loadq(pix1, pix2, 0, 0, diff);
    hadamard_8x8(diff, &r0, &r1);
    %(red_init)s
    loadq(pix1, pix2, 8, 0, diff);
    hadamard_8x8(diff, &r0, &r1);
    %(red_acc)s
    loadq(pix1, pix2, 0, 8, diff);
    hadamard_8x8(diff, &r0, &r1);
    %(red_acc)s
    loadq(pix1, pix2, 8, 8, diff);
    hadamard_8x8(diff, &r0, &r1);
    %(red_acc)s
    %(red_end)s
""" % {"red_init": red_init, "red_acc": red_acc, "red_end": red_end}
    else:  # pair: load top two quadrants' rows first, then bottom two.
        qbody = """\
    loadq(pix1, pix2, 0, 0, dl);
    loadq(pix1, pix2, 8, 0, dr);
    hadamard_8x8(dl, &r0, &r1);
    %(red_init)s
    hadamard_8x8(dr, &r0, &r1);
    %(red_acc)s
    loadq(pix1, pix2, 0, 8, dl);
    loadq(pix1, pix2, 8, 8, dr);
    hadamard_8x8(dl, &r0, &r1);
    %(red_acc)s
    hadamard_8x8(dr, &r0, &r1);
    %(red_acc)s
    %(red_end)s
""" % {"red_init": red_init, "red_acc": red_acc, "red_end": red_end}

    return """\
// Generated by tools/emit_sa8d_neon_shared.py -- do not edit by hand.
// SA8D 16x16 pure NEON, reduce=%(reduce)s, quad=%(quad)s.
#include <arm_neon.h>
#include <stdint.h>

static inline void sumsubq_s16(int16x8_t *sum, int16x8_t *sub,
                               const int16x8_t a, const int16x8_t b)
{
    *sum = vaddq_s16(a, b);
    *sub = vsubq_s16(a, b);
}

static inline void abssumsubq_s16(int16x8_t *sum, int16x8_t *sub,
                                  const int16x8_t a, const int16x8_t b)
{
    *sum = vabsq_s16(vaddq_s16(a, b));
    *sub = vabdq_s16(a, b);
}

static inline void transpose_s16_s16x2(int16x8_t *t1, int16x8_t *t2,
                                       const int16x8_t s1,
                                       const int16x8_t s2)
{
    *t1 = vtrn1q_s16(s1, s2);
    *t2 = vtrn2q_s16(s1, s2);
}

static inline void transpose_s16_s32x2(int16x8_t *t1, int16x8_t *t2,
                                       const int16x8_t s1,
                                       const int16x8_t s2)
{
    *t1 = vreinterpretq_s16_s32(
        vtrn1q_s32(vreinterpretq_s32_s16(s1), vreinterpretq_s32_s16(s2)));
    *t2 = vreinterpretq_s16_s32(
        vtrn2q_s32(vreinterpretq_s32_s16(s1), vreinterpretq_s32_s16(s2)));
}

static inline void transpose_s16_s64x2(int16x8_t *t1, int16x8_t *t2,
                                       const int16x8_t s1,
                                       const int16x8_t s2)
{
    *t1 = vreinterpretq_s16_s64(
        vtrn1q_s64(vreinterpretq_s64_s16(s1), vreinterpretq_s64_s16(s2)));
    *t2 = vreinterpretq_s16_s64(
        vtrn2q_s64(vreinterpretq_s64_s16(s1), vreinterpretq_s64_s16(s2)));
}

static inline void hadamard_4_v(const int16x8_t in[4], int16x8_t out[4])
{
    int16x8_t s0, s1, d0, d1;
    sumsubq_s16(&s0, &d0, in[0], in[1]);
    sumsubq_s16(&s1, &d1, in[2], in[3]);
    sumsubq_s16(&out[0], &out[2], s0, s1);
    sumsubq_s16(&out[1], &out[3], d0, d1);
}

static inline void hadamard_8_v(const int16x8_t in[8], int16x8_t out[8])
{
    int16x8_t temp[8];
    hadamard_4_v(in, temp);
    hadamard_4_v(in + 4, temp + 4);
    sumsubq_s16(&out[0], &out[4], temp[0], temp[4]);
    sumsubq_s16(&out[1], &out[5], temp[1], temp[5]);
    sumsubq_s16(&out[2], &out[6], temp[2], temp[6]);
    sumsubq_s16(&out[3], &out[7], temp[3], temp[7]);
}

static inline void hadamard_4_h(const int16x8_t in[4], int16x8_t out[4])
{
    int16x8_t s0, s1, d0, d1, t0, t1, t2, t3;
    transpose_s16_s16x2(&t0, &t1, in[0], in[1]);
    transpose_s16_s16x2(&t2, &t3, in[2], in[3]);
    sumsubq_s16(&s0, &d0, t0, t1);
    sumsubq_s16(&s1, &d1, t2, t3);
    transpose_s16_s32x2(&out[0], &out[1], s0, s1);
    transpose_s16_s32x2(&out[2], &out[3], d0, d1);
}

static inline void hadamard_8_h(const int16x8_t coefs[8],
                                uint16x8_t out[4])
{
    int16x8_t s0, s1, s2, s3, d0, d1, d2, d3;
    int16x8_t temp[8];
    hadamard_4_h(coefs, temp);
    hadamard_4_h(coefs + 4, temp + 4);
    abssumsubq_s16(&s0, &d0, temp[0], temp[1]);
    abssumsubq_s16(&s1, &d1, temp[2], temp[3]);
    abssumsubq_s16(&s2, &d2, temp[4], temp[5]);
    abssumsubq_s16(&s3, &d3, temp[6], temp[7]);
    transpose_s16_s64x2(&temp[0], &temp[1], s0, s2);
    transpose_s16_s64x2(&temp[2], &temp[3], s1, s3);
    transpose_s16_s64x2(&temp[4], &temp[5], d0, d2);
    transpose_s16_s64x2(&temp[6], &temp[7], d1, d3);
    out[0] = vmaxq_u16(vreinterpretq_u16_s16(temp[0]),
                       vreinterpretq_u16_s16(temp[1]));
    out[1] = vmaxq_u16(vreinterpretq_u16_s16(temp[2]),
                       vreinterpretq_u16_s16(temp[3]));
    out[2] = vmaxq_u16(vreinterpretq_u16_s16(temp[4]),
                       vreinterpretq_u16_s16(temp[5]));
    out[3] = vmaxq_u16(vreinterpretq_u16_s16(temp[6]),
                       vreinterpretq_u16_s16(temp[7]));
}

static inline void hadamard_8x8(const int16x8_t diff[8], uint16x8_t *r0,
                                uint16x8_t *r1)
{
    int16x8_t temp[8];
    uint16x8_t sum[4];
    hadamard_8_v(diff, temp);
    hadamard_8_h(temp, sum);
    *r0 = vaddq_u16(sum[0], sum[1]);
    *r1 = vaddq_u16(sum[2], sum[3]);
}

extern "C" int %(func)s(const uint8_t* pix1, intptr_t sp1,
                        const uint8_t* pix2, intptr_t sp2)
{
    int16x8_t diff[8];
    int16x8_t dl[8], dr[8];
    uint16x8_t r0, r1;

    #define loadq(a, b, xo, yo, d)                                         \\
        do {                                                               \\
            for (int yy = 0; yy < 8; yy++)                                 \\
                d[yy] = vreinterpretq_s16_u16(vsubl_u8(                    \\
                    vld1_u8(a + (yo + yy) * sp1 + xo),                     \\
                    vld1_u8(b + (yo + yy) * sp2 + xo)));                   \\
        } while (0)

    // (macro fixup below: the second load base is pix2)
%(qbody)s
}
""" % {"reduce": reduce, "quad": quad, "func": func_name,
       "qbody": qbody}
