"""SVE2 scale2D_64to32 (VL=256) candidate emitter (docs/37).

64x64 -> 32x32: each 2x2 block -> (a+b+c+d+2)>>2. Two searchable
lowerings:

  addp-rshr   (original): per 16 input bytes per row pair, widen to u16,
              even/odd uzp pair sums (2x1), add rows (2x2), rounding shift
              right 2, qxtnb+uzp1 narrow to u8.  13 vector ops / block.
  neon-paddl  (2026-08-15): NEON vpaddlq_u8 does the horizontal 2x1 sum in
              one instruction; add the two rows, vrshr, vqmovn, store.
              8 vector ops / block.
  neon-paddl-pair: process two 16-byte input chunks and combine their two
              8-byte outputs into one 16-byte store (uqxtn2), 6.5 vector
              ops / 16-byte block.
  neon-paddl-loop: same pair body in explicit y/c loops, to reduce the
              unrolled code footprint and stack pressure.
"""


def emit_64to32(func_name="dynopt_scale2d_64to32_sve2",
                impl="addp-rshr"):
    if impl == "neon-paddl-loop":
        return emit_64to32_neon_paddl_loop(func_name)
    if impl == "neon-paddl-pair":
        return emit_64to32_neon_paddl_pair(func_name)
    if impl == "neon-paddl":
        return emit_64to32_neon_paddl(func_name)
    return emit_64to32_uzp(func_name)


def emit_64to32_uzp(func_name="dynopt_scale2d_64to32_sve2"):
    lines = [
        "#include <arm_sve.h>",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "extern \"C\" void %s(uint8_t* dst, const uint8_t* src,"
        " intptr_t stride)" % func_name,
        "{",
        "    svbool_t pg16 = svptrue_b16();",
        "    svbool_t pg8_8 = svwhilelt_b8_u64(0, 8);",
    ]
    for y in range(0, 64, 2):
        for c in (0, 16, 32, 48):
            d = y // 2 * 32 + c // 2
            lines.extend([
                "    {",
                "        const uint8_t* r0 = src + %d * stride + %d;"
                % (y, c),
                "        svuint16_t a0 = svld1ub_u16(pg16, r0);",
                "        svuint16_t b0 = svld1ub_u16(pg16, r0 + stride);",
                "        svuint16_t ae = svuzp1_u16(a0, a0);",
                "        svuint16_t ao = svuzp2_u16(a0, a0);",
                "        svuint16_t be = svuzp1_u16(b0, b0);",
                "        svuint16_t bo = svuzp2_u16(b0, b0);",
                "        svuint16_t s = svadd_u16_x(pg16,"
                " svadd_u16_x(pg16, ae, ao), svadd_u16_x(pg16, be, bo));",
                "        s = svrshr_n_u16_x(pg16, s, 2);",
                "        svuint8_t out = svuzp1_u8(svqxtnb_u16(s),"
                " svqxtnb_u16(s));",
                "        svst1_u8(pg8_8, dst + %d, out);" % d,
                "    }",
            ])
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_64to32_neon_paddl(func_name="dynopt_scale2d_64to32_sve2"):
    """NEON-bridge lowering: vpaddlq_u8 pairs adjacent pixels, then
    add/vrshr/vqmovn/st1 in 128-bit vectors. Each 16-byte input chunk
    costs 8 vector ops instead of 13 in the uzp lowering."""
    lines = [
        "// Generated by tools/emit_scale2d_sve2_shared.py"
        " (neon-paddl lowering)",
        "#include <arm_neon.h>",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "extern \"C\" void %s(uint8_t* dst, const uint8_t* src,"
        " intptr_t stride)" % func_name,
        "{",
    ]
    for y in range(0, 64, 2):
        for c in (0, 16, 32, 48):
            d = y // 2 * 32 + c // 2
            lines.extend([
                "    {",
                "        const uint8_t* r0 = src + %d * stride + %d;"
                % (y, c),
                "        uint16x8_t a = vpaddlq_u8(vld1q_u8(r0));",
                "        uint16x8_t b = vpaddlq_u8(vld1q_u8(r0 + stride));",
                "        uint16x8_t s = vrshrq_n_u16(vaddq_u16(a, b), 2);",
                "        vst1_u8(dst + %d, vqmovn_u16(s));" % d,
                "    }",
            ])
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_64to32_neon_paddl_pair(func_name="dynopt_scale2d_64to32_sve2"):
    """Two chunks per iteration; vqmovn + vqmovn2 fill one q register, so
    two 8-byte outputs are stored as one 16-byte vector."""
    lines = [
        "// Generated by tools/emit_scale2d_sve2_shared.py"
        " (neon-paddl-pair lowering)",
        "#include <arm_neon.h>",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "extern \"C\" void %s(uint8_t* dst, const uint8_t* src,"
        " intptr_t stride)" % func_name,
        "{",
    ]
    for y in range(0, 64, 2):
        for c in (0, 32):
            d = y // 2 * 32 + c // 2
            lines.extend([
                "    {",
                "        const uint8_t* r0 = src + %d * stride + %d;"
                % (y, c),
                "        const uint8_t* r1 = r0 + stride;",
                "        uint16x8_t a0 = vpaddlq_u8(vld1q_u8(r0));",
                "        uint16x8_t a1 = vpaddlq_u8(vld1q_u8(r0 + 16));",
                "        uint16x8_t b0 = vpaddlq_u8(vld1q_u8(r1));",
                "        uint16x8_t b1 = vpaddlq_u8(vld1q_u8(r1 + 16));",
                "        uint8x8_t o0 = vqmovn_u16("
                "            vrshrq_n_u16(vaddq_u16(a0, b0), 2));",
                "        uint8x8_t o1 = vqmovn_u16("
                "            vrshrq_n_u16(vaddq_u16(a1, b1), 2));",
                "        vst1q_u8(dst + %d, vcombine_u8(o0, o1));" % d,
                "    }",
            ])
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_64to32_neon_paddl_loop(func_name="dynopt_scale2d_64to32_sve2"):
    """Same pair body, but with explicit loops so the compiler can schedule
    a smaller register window instead of one giant unrolled body."""
    lines = [
        "// Generated by tools/emit_scale2d_sve2_shared.py"
        " (neon-paddl-loop lowering)",
        "#include <arm_neon.h>",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "extern \"C\" void %s(uint8_t* dst, const uint8_t* src,"
        " intptr_t stride)" % func_name,
        "{",
        "    for (int y = 0; y < 64; y += 2)",
        "    {",
        "        const uint8_t* r0 = src + (intptr_t)y * stride;",
        "        const uint8_t* r1 = r0 + stride;",
        "        uint8_t* d = dst + (y / 2) * 32;",
        "        for (int c = 0; c < 64; c += 32, d += 16)",
        "        {",
        "            uint16x8_t a0 = vpaddlq_u8(vld1q_u8(r0 + c));",
        "            uint16x8_t a1 = vpaddlq_u8(vld1q_u8(r0 + c + 16));",
        "            uint16x8_t b0 = vpaddlq_u8(vld1q_u8(r1 + c));",
        "            uint16x8_t b1 = vpaddlq_u8(vld1q_u8(r1 + c + 16));",
        "            uint8x8_t o0 = vqmovn_u16("
        "                vrshrq_n_u16(vaddq_u16(a0, b0), 2));",
        "            uint8x8_t o1 = vqmovn_u16("
        "                vrshrq_n_u16(vaddq_u16(a1, b1), 2));",
        "            vst1q_u8(d, vcombine_u8(o0, o1));",
        "        }",
        "    }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def emit_combo(combo):
    return emit_64to32(impl=combo.get("impl", "addp-rshr"))
