#!/usr/bin/env python3
"""Parameterized SVE2 (VL=256) emitter for the DCT16 shared-leaf form.

The emitter is the tool-side generator for the structure discovered by
`tools/dct16_shared_discovery.py`:

    out_k[i] = dot(g_t16[k][0..7], (E_i if k even else O_i))
    E_i[j] = s_i[j] + s_i[15-j],   O_i[j] = s_i[j] - s_i[15-j]

with the 8-lane E/O leaves packed two-per-register so one SVE2
`SDOT .d` computes the two 4-element partials of two rows against the
pre-permuted (duplicated) constant [C | C].

Layout parameters (v2, fixed):
  - one row per z-register (16 s16, E/O occupy the low 8 lanes);
  - E/O built with a rev-segment TBL (reverse within each 8-lane half) +
    add/sub, avoiding the upstream rev64/ext chain;
  - dot: one SVE2 `SDOT .d` per row against the pre-duplicated constant
    [C | C] (2 useful s64 lanes = the row's two 4-element partials);
  - narrow: NEON bridge (svget_neonq + vmovn + vcombine + vpaddq +
    vrshrn) so the four row results stay contiguous; SVE2 RSHRNB/RSHRNT
    was rejected because it interleaves results into even/odd half-width
    lanes per 128-bit segment and cannot emit [f0,f1,f2,f3] contiguously.

Generated code must be rebuildable from this script alone; the g_t16 first
half rows are the same constants the discovery report folds into C.
"""

import argparse


GT16_FIRST8 = [
    [64, 64, 64, 64, 64, 64, 64, 64],
    [90, 87, 80, 70, 57, 43, 25, 9],
    [89, 75, 50, 18, -18, -50, -75, -89],
    [87, 57, 9, -43, -80, -90, -70, -25],
    [83, 36, -36, -83, -83, -36, 36, 83],
    [80, 9, -70, -87, -25, 57, 90, 43],
    [75, -18, -89, -50, 50, 89, 18, -75],
    [70, -43, -87, 9, 90, 25, -80, -57],
    [64, -64, -64, 64, 64, -64, -64, 64],
    [57, -80, -25, 90, -9, -87, 43, 70],
    [50, -89, 18, 75, -75, -18, 89, -50],
    [43, -90, 57, 25, -87, 70, 9, -80],
    [36, -83, 83, -36, -36, 83, -83, 36],
    [25, -70, 90, -80, 43, 9, -57, 87],
    [18, -50, 75, -89, 89, -75, 50, -18],
    [9, -25, 43, -57, 70, -80, 87, -90],
]


def const_rows_cpp():
    rows = []
    for c in GT16_FIRST8:
        body = ", ".join(str(x) for x in c)
        rows.append("    { %s }," % body)
    return "\n".join(rows)


def build_block(i):
    return """\
        {
            const svint16_t z = svld1_s16(p16, src + %d * stride);
            const svint16_t rr = svtbl_s16(z, irv);
            E%d = svadd_s16_x(p16, z, rr);
            O%d = svsub_s16_x(p16, z, rr);
        }""" % (i, i, i)


def group_block(g):
    """One 4-row group: per-row SDOT + NEON-bridge contiguous narrow."""
    base = 4 * g
    dots = []
    for r in range(base, base + 4):
        dots.append("""\
            const svint16_t x%d = (k & 1) ? O%d : E%d;
            const svint64_t d%d = svdot_s64(zacc, x%d, ck);""" % (r, r, r, r, r))
    narrow = """\
        {
            const int64x2_t t0 = svget_neonq_s64(d%d);
            const int64x2_t t1 = svget_neonq_s64(d%d);
            const int64x2_t t2 = svget_neonq_s64(d%d);
            const int64x2_t t3 = svget_neonq_s64(d%d);
            const int32x4_t t01 = vcombine_s32(vmovn_s64(t0), vmovn_s64(t1));
            const int32x4_t t23 = vcombine_s32(vmovn_s64(t2), vmovn_s64(t3));
            const int32x4_t w = vpaddq_s32(t01, t23);
            const int16x4_t n = vrshrn_n_s32(w, shift);
            vst1_s16(dst + 16 * k + %d, n);
        }""" % (base, base + 1, base + 2, base + 3, base)
    return "\n".join(dots) + "\n" + narrow


def emit(func_name="dynopt_dct16_sve2_shared", export_pass1=False):
    rows = const_rows_cpp()
    build_src = "\n".join(build_block(i) for i in range(16))
    dot_src = "\n".join(group_block(g) for g in range(4))
    pass1_export = ""
    if export_pass1:
        pass1_export = """

extern "C" void %s_pass1(const int16_t* src, int16_t* dst, intptr_t srcStride)
{
    pass<3>(src, dst, srcStride);
}
""" % func_name
    return """\
// Generated by tools/emit_dct16_sve2_shared.py -- do not edit by hand.
// SVE2 VL=256 shared-leaf DCT16: E/O leaves + SDOT + NEON-bridge narrow.
#include <arm_sve.h>
#include <arm_neon.h>
#include <arm_neon_sve_bridge.h>
#include <cstdint>

namespace {

static const int16_t C8[16][8] = {
%s
};

// tbl2 index: low 8 lanes of {z_a, z_b} -> [z_a[0..7], z_b[0..7]]
// hi: [z_a[8..15], z_b[8..15]]
static const uint16_t idx_rev[16] =
    { 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 };

template <int shift>
static void pass(const int16_t* src, int16_t* dst, intptr_t stride)
{
    const svbool_t p16 = svptrue_b16();
    const svuint16_t irv = svld1_u16(p16, idx_rev);
    const svint64_t zacc = svdup_n_s64(0);

    // E/O leaves: low 8 lanes per row; rows are unrolled (ACLE: no arrays
    // of SVE types).
    svint16_t E0, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13,
              E14, E15;
    svint16_t O0, O1, O2, O3, O4, O5, O6, O7, O8, O9, O10, O11, O12, O13,
              O14, O15;
%s

    for (int k = 0; k < 16; k++)
    {
        const svint16_t ck = svld1_s16(p16, C8[k]);   // [C | C]
%s
    }
}

} // namespace

extern "C" void %s(const int16_t* src, int16_t* dst, intptr_t srcStride)
{
    int16_t coef[256];
    pass<3>(src, coef, srcStride);
    pass<10>(coef, dst, 16);
}
%s""" % (rows, build_src, dot_src, func_name, pass1_export)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out", default="kernels/dct16/candidates/sve2_shared.cpp",
                    nargs="?")
    args = ap.parse_args()
    with open(args.out, "w") as f:
        f.write(emit())
    print("wrote %s" % args.out)


if __name__ == "__main__":
    main()
