"""pu.addAvg representative candidate emitter (docs/37).

16x16: dst = sat_u8((src0+src1+32)>>7) with rounding; SVE 16-lane rows.
"""


def emit(func_name="dynopt_pu_addavg_16x16_sve2"):
    return """\
// Generated by tools/emit_pu_addavg_sve2_shared.py -- do not edit.
#include <arm_sve.h>
#include <stdint.h>
#include <stddef.h>

extern "C" void %s(const int16_t* src0, intptr_t s0st,
                   const int16_t* src1, intptr_t s1st,
                   uint8_t* dst, intptr_t dstStride)
{
    const svbool_t p16 = svptrue_b16();
    const svbool_t pout = svwhilelt_b8((uint32_t)0, (uint32_t)16);
    for (int r = 0; r < 16; r++)
    {
        const svint16_t a = svld1_s16(p16, src0 + r * s0st);
        const svint16_t b = svld1_s16(p16, src1 + r * s1st);
        svint16_t sum = svadd_s16_x(p16, a, b);
        sum = svrshr_n_s16_x(p16, sum, 7);
        sum = svadd_n_s16_x(p16, sum, 128);
        svuint8_t u = svqxtunb_s16(sum);
        svst1_u8(pout, dst + r * dstStride, svuzp1_u8(u, u));
    }
}
""" % func_name


def emit_combo(combo):
    return emit()
