#!/usr/bin/env python3
"""SVE2 (VL=256) emitter for the 8-bit horizontal 8-tap luma filter
(interp8, 8x8), upstream-exact (path A: sdot .d slices + NEON-bridge
saturating narrow).

Semantics (x265 interp8_horiz_pp_neon): src -= 3; out[c] =
sat_u8(round(SUM_{k=0..7} coeff[phase][k] * src[c-3+k] / 2^6)).

Structure (mirrors the DCT32 v3 lane-per-output trick):
  - one 16-byte window W = src[row]-3 .. +12 (svld1ub_u16, widening);
  - three TBL slices (windows overlap, so X1 is reused):
      X0 = outs0-3 taps0-3, X1 = outs0-3 taps4-7 == outs4-7 taps0-3,
      X2 = outs4-7 taps4-7;
  - per half: 2 SDOT .d (4 outputs accumulate their full 8 taps in 4
    s64 lanes) + uzp1_s32 + rshrnb(6) + uzp1_s16 + vqmovun (NEON bridge,
    saturating) + 4-lane predicate store.
"""

import argparse


COEFFS = {
    1: [-1, 4, -10, 58, 17, -5, 1, 0],
    2: [-1, 4, -11, 40, 40, -11, 4, -1],
    3: [0, 1, -5, 17, 58, -10, 4, -1],
}


def cpp_constants():
    lines = ["static const int16_t CTBL[4][2][16] = {"]
    for ph in (1, 2, 3):
        c = COEFFS[ph]
        lines.append("    {")
        for m in range(2):
            g = c[4 * m:4 * m + 4]
            body = ", ".join(str(x) for x in g)
            lines.append("        { %s, %s, %s, %s },  // m=%d"
                         % (body, body, body, body, m))
        lines.append("    },  // phase %d" % ph)
    lines.append("};")
    lines.append("""\
static const uint16_t IDX_X0[16] =
    { 0, 1, 2, 3, 1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6 };
static const uint16_t IDX_X1[16] =
    { 4, 5, 6, 7, 5, 6, 7, 8, 6, 7, 8, 9, 7, 8, 9, 10 };
static const uint16_t IDX_X2[16] =
    { 8, 9, 10, 11, 9, 10, 11, 12, 10, 11, 12, 13, 11, 12, 13, 14 };
static const uint32_t IDX_08[16] =
    { 0, 1, 2, 3, 8, 9, 10, 11, 0, 1, 2, 3, 8, 9, 10, 11 };
""")
    return "\n".join(lines)


def emit(func_name="dynopt_interp8_8x8_sve2"):
    return """\
// Generated by tools/emit_interp8_sve2_shared.py -- do not edit by hand.
// 8-bit horizontal 8-tap luma filter 8x8 (SVE2, VL=256), upstream-exact.
#include <arm_sve.h>
#include <arm_neon.h>
#include <arm_neon_sve_bridge.h>

%s

extern "C" void %s(const uint8_t* src, intptr_t srcStride,
                   uint8_t* dst, intptr_t dstStride, int coeffIdx)
{
    const svbool_t p16 = svptrue_b16();
    const svint64_t zero64 = svdup_n_s64(0);
    const int ph = (coeffIdx >= 1 && coeffIdx <= 3) ? coeffIdx : 2;
    const svint16_t c0 = svld1_s16(p16, CTBL[ph - 1][0]);
    const svint16_t c1 = svld1_s16(p16, CTBL[ph - 1][1]);
    const svuint16_t ix0 = svld1_u16(p16, IDX_X0);
    const svuint16_t ix1 = svld1_u16(p16, IDX_X1);
    const svuint16_t ix2 = svld1_u16(p16, IDX_X2);
    const svuint32_t ix08 = svld1_u32(svptrue_b32(), IDX_08);

    for (int r = 0; r < 8; r++)
    {
        const uint8_t* row = src + r * srcStride - 3;
        svuint16_t W = svld1ub_u16(p16, row);
        svint16_t X0 = svreinterpret_s16_u16(svtbl_u16(W, ix0));
        svint16_t X1 = svreinterpret_s16_u16(svtbl_u16(W, ix1));
        svint16_t X2 = svreinterpret_s16_u16(svtbl_u16(W, ix2));

        svint64_t t0 = svdot_s64(zero64, X0, c0);
        t0 = svdot_s64(t0, X1, c1);
        svint32_t lo0 = svuzp1_s32(svreinterpret_s32_s64(t0),
                                   svreinterpret_s32_s64(t0));
        svint64_t t1 = svdot_s64(zero64, X1, c0);
        t1 = svdot_s64(t1, X2, c1);
        svint32_t lo1 = svuzp1_s32(svreinterpret_s32_s64(t1),
                                   svreinterpret_s32_s64(t1));
        svint32_t all = svtbl2_s32(svcreate2_s32(lo0, lo1), ix08);
        svint16_t rr = svrshrnb_n_s32(all, 6);
        svint16_t rz = svuzp1_s16(rr, rr);
        uint8x8_t u = vqmovun_s16(svget_neonq_s16(rz));
        // Exactly 8 bytes per row: a full-width SVE store (or the 16-byte
        // NEON bridge value) would scribble past the 8x8 tile and fail the
        // IPFilterHarness whole-buffer memcmp gate.
        vst1_u8(dst + r * dstStride, u);
    }
}
""" % (cpp_constants(), func_name)


def emit_sdot_h(func_name=None, n=8, unroll=False):
    """Path B (docs/22 §5, SVE2p3): sdot z.h,z.b,z.b direct 8-tap
    horizontal filter. 16 h-lanes = 8 pixels x 2 tap-pairs
    ((0,1)+(4,5) in lane 2p, (2,3)+(6,7) in lane 2p+1), addp sums
    pairs, svqrshrunb rounds/shifts/clamps to u8. Needs SVE2p3 QEMU
    (custom build, patches/qemu-sve2p3-sdot-btoh.patch).
    n: 8/16/32 square shape; each 8-pixel unit uses the same base index
    vectors, with window loads at row+8u and shifted index vectors for
    units 1/2 (16/32 only)."""
    if func_name is None:
        func_name = "dynopt_interp8_%dx%d_sve2_sdoth" % (n, n)
    return """\
// Generated by tools/emit_interp8_sve2_shared.py -- do not edit by hand.
// 8-bit horizontal 8-tap luma filter %(n)dx%(n)d (SVE2p3, VL=256), path B.
#include <arm_sve.h>

static const int8_t CB0[32] =
    { -1, 4, -10, 58, -1, 4, -10, 58, -1, 4, -10, 58, -1, 4, -10, 58,
      -1, 4, -10, 58, -1, 4, -10, 58, -1, 4, -10, 58, -1, 4, -10, 58 };
static const int8_t CB1[32] =
    { 17, -5, 1, 0, 17, -5, 1, 0, 17, -5, 1, 0, 17, -5, 1, 0,
      17, -5, 1, 0, 17, -5, 1, 0, 17, -5, 1, 0, 17, -5, 1, 0 };
static const int8_t CB2[32] =
    { -1, 4, -11, 40, -1, 4, -11, 40, -1, 4, -11, 40, -1, 4, -11, 40,
      -1, 4, -11, 40, -1, 4, -11, 40, -1, 4, -11, 40, -1, 4, -11, 40 };
static const int8_t CB3[32] =
    { 40, -11, 4, -1, 40, -11, 4, -1, 40, -11, 4, -1, 40, -11, 4, -1,
      40, -11, 4, -1, 40, -11, 4, -1, 40, -11, 4, -1, 40, -11, 4, -1 };
static const int8_t CB4[32] =
    { 0, 1, -5, 17, 0, 1, -5, 17, 0, 1, -5, 17, 0, 1, -5, 17,
      0, 1, -5, 17, 0, 1, -5, 17, 0, 1, -5, 17, 0, 1, -5, 17 };
static const int8_t CB5[32] =
    { 58, -10, 4, -1, 58, -10, 4, -1, 58, -10, 4, -1, 58, -10, 4, -1,
      58, -10, 4, -1, 58, -10, 4, -1, 58, -10, 4, -1, 58, -10, 4, -1 };
static const uint8_t IX0B[32] =
    { 0, 1, 2, 3, 1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6,
      4, 5, 6, 7, 5, 6, 7, 8, 6, 7, 8, 9, 7, 8, 9, 10 };
static const uint8_t IX1B[32] =
    { 4, 5, 6, 7, 5, 6, 7, 8, 6, 7, 8, 9, 7, 8, 9, 10,
      8, 9, 10, 11, 9, 10, 11, 12, 10, 11, 12, 13, 11, 12, 13, 14 };
static const uint8_t IX0B8[32] =
    { 8, 9, 10, 11, 9, 10, 11, 12, 10, 11, 12, 13, 11, 12, 13, 14,
      12, 13, 14, 15, 13, 14, 15, 16, 14, 15, 16, 17, 15, 16, 17, 18 };
static const uint8_t IX1B8[32] =
    { 12, 13, 14, 15, 13, 14, 15, 16, 14, 15, 16, 17, 15, 16, 17, 18,
      16, 17, 18, 19, 17, 18, 19, 20, 18, 19, 20, 21, 19, 20, 21, 22 };
static const uint8_t IX0B16[32] =
    { 16, 17, 18, 19, 17, 18, 19, 20, 18, 19, 20, 21, 19, 20, 21, 22,
      20, 21, 22, 23, 21, 22, 23, 24, 22, 23, 24, 25, 23, 24, 25, 26 };
static const uint8_t IX1B16[32] =
    { 20, 21, 22, 23, 21, 22, 23, 24, 22, 23, 24, 25, 23, 24, 25, 26,
      24, 25, 26, 27, 25, 26, 27, 28, 26, 27, 28, 29, 27, 28, 29, 30 };

static inline svint16_t sdot_h(svint16_t acc, svint8_t a, svint8_t b)
{
    asm volatile("sdot %%0.h, %%1.b, %%2.b"
                 : "+w"(acc) : "w"(a), "w"(b));
    return acc;
}

static inline svint16_t sdot_h_acc(svint16_t acc, svint8_t a, svint8_t b)
{
    // MOVPRFX (unpredicated) is fused with the following SVE instruction on
    // real pipes, so it costs no issue slot; it both resets the accumulator
    // and folds in the +8192 DC offset (docs/22 offset trick).
    // MOVPRFX requires Zd != Zn and the following sdot must not use Zd as a
    // non-destructive source: early-clobber on the output forces a fresh
    // register distinct from acc/a/b.
    svint16_t out;
    asm volatile("movprfx %%0, %%1\\n\\tsdot %%0.h, %%2.b, %%3.b"
                 : "=&w"(out) : "w"(acc), "w"(a), "w"(b));
    return out;
}

static inline void interp8_unit8(
    svint8_t W, svuint8_t ix0, svuint8_t ix1,
    svint8_t c0, svint8_t c1, svint16_t off4096,
    uint8_t* dstp, svbool_t p8h8)
{
    svint8_t X0 = svtbl_s8(W, ix0);
    svint8_t X1 = svtbl_s8(W, ix1);
    svint16_t t = sdot_h_acc(off4096, X0, c0);
    t = sdot_h(t, X1, c1);
    // lane 2p = pixel p taps (0,1)+(4,5); lane 2p+1 = taps (2,3)+(6,7).
    // Pair-sum via uzp1+uzp2+add (SVE2 ADDP is predicated with odd slots
    // from the second source, so it cannot pack the pairs; verified
    // 2026-08-14).
    svint16_t pixels = svadd_s16_x(
        svptrue_b16(), svuzp1_s16(t, t), svuzp2_s16(t, t));
    svuint8_t u = svqrshrunb_n_s16(pixels, 6);
    // SVE2 bottom-narrow writes each result to the low byte of its
    // 16-bit slot (bytes 0,2,4,...); uzp1 compacts to bytes 0..7.
    svuint8_t uz = svuzp1_u8(u, u);
    svst1_u8(p8h8, dstp, uz);
}

extern "C" void %(func_name)s(const uint8_t* src, intptr_t srcStride,
                   uint8_t* dst, intptr_t dstStride, int coeffIdx)
{
    const svbool_t p32 = svptrue_b8();
    const svbool_t p8h8 = svwhilelt_b8((uint32_t)0, (uint32_t)8);
    const int ph = (coeffIdx >= 1 && coeffIdx <= 3) ? coeffIdx : 2;
    const svint8_t c0 = svld1_s8(p32, (const int8_t*)
        (ph == 1 ? CB0 : (ph == 3 ? CB4 : CB2)));
    const svint8_t c1 = svld1_s8(p32, (const int8_t*)
        (ph == 1 ? CB1 : (ph == 3 ? CB5 : CB3)));
    const svuint8_t ix0 = svld1_u8(p32, IX0B);
    const svuint8_t ix1 = svld1_u8(p32, IX1B);
    const svuint8_t ix0_8 = svld1_u8(p32, IX0B8);
    const svuint8_t ix1_8 = svld1_u8(p32, IX1B8);
    const svuint8_t ix0_16 = svld1_u8(p32, IX0B16);
    const svuint8_t ix1_16 = svld1_u8(p32, IX1B16);
    // Each output pixel = t[2p] + t[2p+1]; the 8192 DC offset must be
    // split across both accumulator lanes (4096 each) so the pair-sum
    // restores the full +8192 once (verified 2026-08-14).
    const svint16_t off4096 = svdup_n_s16(4096);

    %(unroll_pragma)s
    for (int r = 0; r < %(n)d; r++)
    {
        const uint8_t* row = src + r * srcStride - 3;
        // Whole-vector TBL: load the 32-byte window directly.
        svuint8_t W32 = svld1_u8(p32, row);
        // (s - 128) fits int8; sum f*(s-128) = sum f*s - 8192, and the
        // 8192 is re-added before qrshrunb(6) (docs/22 §5 offset trick).
        // NOT removable by "s8 on raw bytes + constant result offset":
        // s8 is two's complement (0x64=+100, 0xFF=-1), not b-128; probe
        // sdot(100,255)=-200 (2026-08-14), so the correction is
        // data-dependent and no constant 8192 suffices.
        svint8_t W = svreinterpret_s8_u8(
            svsub_n_u8_x(svptrue_b8(), W32, 128));
        uint8_t* drow = dst + r * dstStride;
        interp8_unit8(W, ix0, ix1, c0, c1, off4096, drow, p8h8);
        if (%(n)d >= 16)
            interp8_unit8(W, ix0_8, ix1_8, c0, c1, off4096, drow + 8, p8h8);
        if (%(n)d >= 32)
        {
            interp8_unit8(W, ix0_16, ix1_16, c0, c1, off4096,
                          drow + 16, p8h8);
            // Unit 3 needs samples s21..s35: window at row+24 (base s21)
            // with the base index vectors (indices <= 14 -> s21..s35).
            svuint8_t W32b = svld1_u8(p32, row + 24);
            svint8_t Wb = svreinterpret_s8_u8(
                svsub_n_u8_x(svptrue_b8(), W32b, 128));
            interp8_unit8(Wb, ix0, ix1, c0, c1, off4096, drow + 24, p8h8);
        }
    }
}
""" % {"func_name": func_name, "n": n,
       "unroll_pragma": ("#pragma clang loop unroll(full)\n    "
                         if unroll else "")}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out", default="generated/interp8/sve2_8x8.cpp")
    ap.add_argument("--compute", default="sdot-d",
                    choices=("sdot-d", "sdot-h"))
    ap.add_argument("--n", type=int, default=8, choices=(8, 16, 32),
                    help="square shape (8/16/32; sdot-h only, docs/22 §5.5)")
    args = ap.parse_args()
    with open(args.out, "w") as f:
        if args.compute == "sdot-h":
            f.write(emit_sdot_h(n=args.n))
        else:
            f.write(emit())
    print("wrote %s" % args.out)


if __name__ == "__main__":
    main()
