"""Inlined interp8 vert_sp candidates (GCC12 filter8_s16x8 outline fix).

Upstream interp8_vert_sp_neon (s16 -> u8, 8-tap) calls
filter8_s16x8<coeffIdx> 4 times per 4-row group through a `bl`
(verified on 920B lib; vert_sp is ~1.8% of the 1080p encode). This
emitter reproduces the upstream dataflow with the filter helper forced
inline; semantics bit-exact (20k differential per shape).
"""

FILTERS = {}
FILTERS[1] = """\
    d0 = vsubl_s16(vget_low_s16(s[6]), vget_low_s16(s[0]));
    d0 = vaddq_s32(d0, c);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[1]), filter, 1);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[2]), filter, 2);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[3]), filter, 3);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[4]), filter, 4);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[5]), filter, 5);
    d1 = vsubl_s16(vget_high_s16(s[6]), vget_high_s16(s[0]));
    d1 = vaddq_s32(d1, c);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[1]), filter, 1);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[2]), filter, 2);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[3]), filter, 3);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[4]), filter, 4);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[5]), filter, 5);"""
FILTERS[2] = """\
    int16x8_t sum07 = vaddq_s16(s[0], s[7]);
    int16x8_t sum16 = vaddq_s16(s[1], s[6]);
    int16x8_t sum25 = vaddq_s16(s[2], s[5]);
    int16x8_t sum34 = vaddq_s16(s[3], s[4]);
    int32x4_t slo = vmlal_laneq_s16(c, vget_low_s16(sum16), filter, 1);
    slo = vmlal_laneq_s16(slo, vget_low_s16(sum25), filter, 2);
    slo = vmlal_laneq_s16(slo, vget_low_s16(sum34), filter, 3);
    int32x4_t shi = vmlal_laneq_s16(c, vget_high_s16(sum16), filter, 1);
    shi = vmlal_laneq_s16(shi, vget_high_s16(sum25), filter, 2);
    shi = vmlal_laneq_s16(shi, vget_high_s16(sum34), filter, 3);
    d0 = vsubw_s16(slo, vget_low_s16(sum07));
    d1 = vsubw_s16(shi, vget_high_s16(sum07));"""
FILTERS[3] = """\
    int16x8_t sum17 = vsubq_s16(s[1], s[7]);
    d0 = vaddw_s16(c, vget_low_s16(sum17));
    d1 = vaddw_s16(c, vget_high_s16(sum17));
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[2]), filter, 2);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[3]), filter, 3);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[4]), filter, 4);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[5]), filter, 5);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[6]), filter, 6);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[2]), filter, 2);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[3]), filter, 3);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[4]), filter, 4);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[5]), filter, 5);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[6]), filter, 6);"""


def _filter_fn(idx):
    return ('__attribute__((always_inline)) static inline void '
            'filter8_s16x8_%d(const int16x8_t* s, const int16x8_t filter,\n'
            '                   const int32x4_t c, int32x4_t& d0, '
            'int32x4_t& d1)\n{\n' % idx) + FILTERS[idx] + "\n}\n"


VTBL_HELPER = """\
__attribute__((always_inline)) static inline int16x8_t vtbl2q_s32_s16(
    int32x4_t a, int32x4_t b, uint8x16_t index)
{
    uint8x16x2_t ab;
    ab.val[0] = vreinterpretq_u8_s32(a);
    ab.val[1] = vreinterpretq_u8_s32(b);
    return vreinterpretq_s16_u8(vqtbl2q_u8(ab, index));
}
"""


_IMPL = """\
template<int CI, int W, int H>
static void vsp_impl_%(ci)d(const int16_t* src, intptr_t sstride,
                            uint8_t* dst, intptr_t dstride)
{
    const int shift = 6 + (14 - 8);          // IF_FILTER_PREC + headRoom
    const int shift_offset = shift - 8;      // 4
    const int offset = (1 << (shift - 1)) + (8192 << 6);
    src -= 3 * sstride;
    static const int16_t LUMA_F[4][8] = {
        {0,0,0,64,0,0,0,0}, {-1,4,-10,58,17,-5,1,0},
        {-1,4,-11,40,40,-11,4,-1}, {0,1,-5,17,58,-10,4,-1}};
    static const uint8_t SHR[16] =
        {1,2,5,6,9,10,13,14,17,18,21,22,25,26,29,30};
    const int16x8_t filter = vld1q_s16(LUMA_F[CI]);
    const int32x4_t c = vdupq_n_s32(offset);
    const uint8x16_t shr_tbl = vld1q_u8(SHR);
    const int SEG = W / 8;
    for (int row = 0; row < H; row += 4)
    {
        const int16_t* p = src + row * sstride;
        uint8_t* d = dst + row * dstride;
        for (int seg = 0; seg < SEG; seg++)
        {
            int16x8_t in[11];
            for (int i = 0; i < 11; i++)
                in[i] = vld1q_s16(p + i * sstride + seg * 8);
            for (int k = 0; k < 4; k++)
            {
                int32x4_t slo, shi;
                filter8_s16x8_%(ci)d(in + k, filter, c, slo, shi);
                int16x8_t sum = vtbl2q_s32_s16(slo, shi, shr_tbl);
                uint8x8_t o = vqshrun_n_s16(sum, shift_offset);
                vst1_u8(d + k * dstride + seg * 8, o);
            }
        }
    }
}
"""


def emit(shapes):
    out = ["// Generated by tools/emit_interp8_vsp_inline.py -- do not edit.",
           "#include <arm_neon.h>", "#include <stdint.h>", ""]
    out.append(VTBL_HELPER)
    for idx in (1, 2, 3):
        out.append(_filter_fn(idx))
    for idx in (1, 2, 3):
        out.append(_IMPL % {"ci": idx})
    for w, h in shapes:
        out.append(
            'extern "C" void dynopt_interp8_vsp_%dx%d_sve2(\n'
            '    const int16_t* src, intptr_t sstride,\n'
            '    uint8_t* dst, intptr_t dstride, int coeffIdx)\n{\n'
            '    switch (coeffIdx)\n    {\n'
            '    case 1: vsp_impl_1<1, %d, %d>(src, sstride, dst, dstride); break;\n'
            '    case 2: vsp_impl_2<2, %d, %d>(src, sstride, dst, dstride); break;\n'
            '    default: vsp_impl_3<3, %d, %d>(src, sstride, dst, dstride); break;\n'
            '    }\n}\n' % (w, h, w, h, w, h, w, h))
    return "\n".join(out) + "\n"
