"""Generic MachineIR -> SVE2 candidate emitter (docs/40 M3, /goal).

Recipe registry: each recipe declares (a) a MachineIR op-signature
detector and (b) an SVE2 ACLE lowering. The emitter consumes only the
imported MachineIR JSON of the seed -- no per-kernel hand-written emitter.
The search layer consumes the emitted source through the normal
verify/trace/MCA funnel (`search_sve2_layouts.py --backend gen`).

Recipes so far:
  diff-sum   (sad 16/16/32): uabd + uaddlv per row -> svld1/svabd/svaddv.

Adding a recipe = register a (name, detect, emit) triple; family members
covered by the same recipe need no emitter code at all.
"""

import json
import os
import re
import sys

try:
    import yaml
except ImportError:
    yaml = None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# kernel name -> seed recipe name (kernel dirs may cover several shapes).
_RECIPE_ALIAS = {
    "sad": "sad-16x16",
    "sad-32": "sad-32x32",
    "sa8d": "sa8d-8x8",
}


def _load_machine_ir(kernel):
    """Load the seed MachineIR JSON declared by seeds/<kernel>.yaml."""
    recipe_name = _RECIPE_ALIAS.get(kernel, kernel)
    recipe_path = os.path.join(ROOT, "seeds", recipe_name + ".yaml")
    if yaml is None or not os.path.exists(recipe_path):
        # fall back to the canonical m30 layout for known kernels
        alt = os.path.join(
            ROOT, "experiments", "m30-%s-search" % kernel,
            "imported", "machine-ir.json")
        if os.path.exists(alt):
            return json.load(open(alt))
        raise ValueError("no MachineIR for kernel %r" % kernel)
    recipe = yaml.safe_load(open(recipe_path))
    out = recipe["output"]["json"]
    path = out if os.path.isabs(out) else os.path.join(ROOT, out)
    if not os.path.exists(path):
        raise ValueError("MachineIR not found: %s" % path)
    return json.load(open(path))


def detect_diff_sum(machine_ir):
    """Diff-sum signature: uabd+uaddlv (sad 16/32)."""
    intr = {n.get("intrinsic") for n in machine_ir["nodes"]
            if n.get("op") == "intrinsic"}
    if "uabd" in intr and "uaddlv" in intr:
        return True
    return False


def detect_hadamard(machine_ir):
    """Hadamard butterfly signature: sabd+abs+umax+uaddlv (sa8d 8x8).
    Recognized but not yet lowered: the generic emitter reports the
    recipe gap instead of silently emitting a wrong kernel."""
    intr = {n.get("intrinsic") for n in machine_ir["nodes"]
            if n.get("op") == "intrinsic"}
    return {"sabd", "abs", "umax", "uaddlv"} <= intr


def detect_fir(machine_ir):
    """FIR signature: dot-product / tbl / narrowing (interp8/4).
    Recognized but not yet lowered (recipe gap)."""
    intr = {n.get("intrinsic") for n in machine_ir["nodes"]
            if n.get("op") == "intrinsic"}
    return "sdot" in intr or "sqrshrn" in intr


def detect_family(machine_ir):
    """Return the first matching recipe name, or None."""
    for name, rec in RECIPES.items():
        if rec["detect"](machine_ir):
            return name
    return None


def _row_offset(addr_rhs, row_vars):
    """Parse `getelementptr ... i8, ptr %base, i64 %expr` and return the
    expression as a C string over row variables (r), or None."""
    m = re.search(r"i64\s+%([A-Za-z0-9._]+)", addr_rhs)
    if not m:
        return None
    return m.group(1)


def emit_diff_sum(machine_ir, func_name):
    """Emit SVE2 ACLE for the diff-sum family (sad shape: 4 args)."""
    nodes = machine_ir["nodes"]
    uabd_rows = 0
    max_row = -1
    row_offs = set()
    for n in nodes:
        if n.get("op") == "intrinsic" and n.get("intrinsic") == "uabd":
            uabd_rows += 1
    # derive the row count from the row-offset expression magnitudes:
    # seeds unroll r*stride as shl/mul chains; take the max constant
    # multiplier seen in shl/mul nodes feeding addr nodes.
    for n in nodes:
        if n.get("op") in ("shl", "mul") and n.get("amt") is not None:
            max_row = max(max_row, n.get("amt"))
        if n.get("op") == "mul" and n.get("const") is not None:
            max_row = max(max_row, n.get("const"))
    # row count comes from the max row-offset multiplier (the seed may
    # process several uabd groups per row, e.g. 32x32 halves); fall back
    # to the uabd count only when no offset constants are visible.
    rows = max_row + 1 if max_row >= 0 else uabd_rows
    if rows <= 0:
        raise ValueError("diff-sum emitter: could not derive row count")
    groups = max(1, uabd_rows // rows)
    width = 16 * groups
    lines = [
        "// Generated by tools/gen_sve2_emit.py (generic diff-sum recipe)",
        "#include <arm_sve.h>",
        "#include <stdint.h>",
        "",
        "extern \"C\" int %s(const uint8_t* a, intptr_t sa,"
        " const uint8_t* b, intptr_t sb)" % func_name,
        "{",
        "    const svbool_t p = svwhilelt_b8((uint32_t)0,"
        " (uint32_t)%d);" % width,
        "    uint64_t total = 0;",
        "    for (int r = 0; r < %d; r++)" % rows,
        "    {",
        "        svuint8_t x = svld1_u8(p, a + r * sa);",
        "        svuint8_t y = svld1_u8(p, b + r * sb);",
        "        svuint8_t d = svabd_u8_x(p, x, y);",
        "        total += svaddv_u8(p, d);",
    ]
    lines.extend([
        "    }",
        "    return (int)total;",
        "}",
    ])
    return "\n".join(lines) + "\n"


RECIPES = {
    "diff-sum": {
        "detect": detect_diff_sum,
        "emit": emit_diff_sum,
    },
    # Recognized structure families without a lowering yet: they produce a
    # clear "recipe gap" error so the tool never silently mis-emits.
    "hadamard": {"detect": detect_hadamard, "emit": None},
    "fir": {"detect": detect_fir, "emit": None},
}


def make_generic_emitter(kernel):
    """Return emit(combo) that derives the candidate from the MachineIR.
    Family detection is per-kernel but recipe-driven: no kernel-specific
    emitter code is written for a new member of a known family."""
    mi = _load_machine_ir(kernel)
    family = detect_family(mi)
    recipe = RECIPES.get(family)
    if recipe is None or recipe["emit"] is None:
        raise ValueError(
            "generic emitter: family %r has no lowering yet (kernel %s);"
            " add a recipe in tools/gen_sve2_emit.py RECIPES"
            % (family, kernel))

    manifest_path = os.path.join(ROOT, "kernels", kernel, "manifest.yaml")
    symbol = None
    if os.path.exists(manifest_path):
        man = yaml.safe_load(open(manifest_path))
        symbol = man.get("candidate", {}).get("symbol")

    def emit(combo):
        return recipe["emit"](mi, symbol or "dynopt_%s_sve2" % kernel)
    return emit


def list_recipes():
    return sorted(RECIPES)
