#!/usr/bin/env python3
"""Generate the upstream-exact differential harness from a kernel manifest.

The manifest (docs/16) declares the reference symbol/declaration, corpus
(strides, value range, cases) and VL contract; this generator turns it into
a self-contained C++ verify source so the evaluation funnel is manifest-
driven and no per-kernel harness needs to be hand-maintained.

Usage:
  python3 tools/gen_verify.py --manifest kernels/dct16/manifest.yaml \
      --out build/dct16_generated_verify.cpp
"""

import argparse
import sys
import os
import string

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))

from kernel_manifest import load_manifest  # noqa: E402


def generate(manifest):
    ref = manifest["reference"]
    cand = manifest["candidate"]
    corpus = manifest.get("corpus", {})
    contract = manifest.get("contract", "upstream-exact")
    strides = corpus.get("strides", [16])
    lo, hi = corpus.get("value_range", [-255, 255])
    vl = manifest.get("vl_bytes", 32)
    cases = corpus.get("cases", 20000)
    n = manifest.get("shape", {}).get("n", 16)
    n_out = n * n
    strides_c = ", ".join(str(s) for s in strides)
    maxstride = max(strides)
    nstrides = len(strides)
    kind = manifest.get("shape", {}).get("kind", "dct")
    rows = manifest.get("shape", {}).get("rows", n)
    if kind == "interp8":
        ref = manifest["reference"]
        cand = manifest["candidate"]
        corpus = manifest.get("corpus", {})
        contract = manifest.get("contract", "upstream-exact")
        vl = manifest.get("vl_bytes", 32)
        strides_c = ", ".join(str(s) for s in corpus.get("strides", [16]))
        nstrides = len(corpus.get("strides", [16]))
        cases = corpus.get("cases", 20000)
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: interp8 (8x8).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(
    const uint8_t*, intptr_t, uint8_t*, intptr_t, int);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        const intptr_t ss = strides[rng() % ${nstrides}];
        const intptr_t ds = strides[rng() % ${nstrides}];
        uint8_t src[8 * 64 + 32], wa[8 * 64], wb[8 * 64];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() % 256);
        for (int ph = 1; ph <= 3; ph++)
        {
            ${ref_call}(src + 16, ss, wa, ds, ph);
            memset(wb, 0, sizeof(wb));
            ${cand_sym}(src + 16, ss, wb, ds, ph);
            for (int r = 0; r < 8; r++)
                for (int c = 0; c < 8; c++)
                    if (wa[r * ds + c] != wb[r * ds + c]) mism++;
        }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract, vl=vl,
            decl=ref["decl"], cand_sym=cand["symbol"], cases=cases,
            nstrides=nstrides, strides_c=strides_c, ref_call=ref["call"])
    oracle = ""
    ref_call = ref["call"]
    ref_decl = ref["decl"]
    if kind == "sa8d":
        # SA8D is a pixel-shaped kernel: two uint8_t planes in, one int out.
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sa8d.
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" int ${cand_sym}(
    const uint8_t*, intptr_t, const uint8_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0)
    {
        perror("prctl(PR_SVE_SET_VL)");
        return 77;
    }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0;
    int first_want = 0, first_got = 0;
    for (int i = 0; i < cases; i++)
    {
        const intptr_t sa = strides[rng() % ${nstrides}];
        const intptr_t sb = strides[rng() % ${nstrides}];
        uint8_t buf[2][${rows} * 64 + 64];
        for (int j = 0; j < (int)(sizeof(buf[0]) / sizeof(buf[0][0])); j++)
        {
            buf[0][j] = (uint8_t)(rng() % 256);
            buf[1][j] = (uint8_t)(rng() % 256);
        }

        const int want = ${ref_call}(buf[0], sa, buf[1], sb);
        const int got = ${cand_sym}(buf[0], sa, buf[1], sb);
        if (want != got)
        {
            mism++;
            if (mism == 1)
            {
                first_want = want;
                first_got = got;
            }
        }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    if (mism)
        printf(" first-diff want=%d got=%d\\n", first_want, first_got);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract, vl=vl,
            decl=ref_decl, cand_sym=cand["symbol"], cases=cases,
            nstrides=nstrides, strides_c=strides_c, ref_call=ref_call,
            rows=rows)
    if kind == "idct":
        # IDCT: src is a contiguous 16x16 coefficient block (no srcStride),
        # dst is written with dstStride; the reference is the x265 C
        # idctN_c (upstream has no SVE IDCT, docs/27).
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: idct (${n}x${n}).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(const int16_t*, int16_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0, total = 0;
    int first_k = -1;
    int16_t first_want = 0, first_got = 0;
    for (int i = 0; i < cases; i++)
    {
        const int ds = strides[rng() % ${nstrides}];
        int16_t src[${n} * ${n}];
        for (int j = 0; j < ${n} * ${n}; j++)
            src[j] = (int16_t)((int)(rng() % (${hi} - ${lo} + 1)) + ${lo});

        int16_t want[${n} * ${maxstride} + ${n}], got[${n} * ${maxstride} + ${n}];
        memset(want, 0, sizeof(want));
        memset(got, 0, sizeof(got));
        ${ref_call}(src, want, ds);
        ${cand_sym}(src, got, ds);
        total += ${n_out};
        for (int k = 0; k < ${n_out}; k++)
            if (want[k] != got[k])
            {
                mism++;
                if (first_k < 0)
                {
                    first_k = k;
                    first_want = want[k];
                    first_got = got[k];
                }
            }
    }
    printf("cases=%d lanes=%ld mismatches=%ld rate=%f%%\\n",
           cases, total, mism, 100.0 * mism / total);
    if (first_k >= 0)
        printf(" first-diff idx=%d want=%d got=%d\\n",
               first_k, first_want, first_got);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, decl=ref_decl, cand_sym=cand["symbol"],
            cases=cases, nstrides=nstrides, strides_c=strides_c,
            n=n, n_out=n_out, hi=hi, lo=lo, ref_call=ref_call,
            maxstride=maxstride)
    if contract == "legacy-internal-exact":
        # Spec-defined legacy oracle (no internal code): pass2 E/O wrap in
        # s16, narrowing rounds then saturates (sqrshrnb semantics).
        ref_decl = ""
        oracle = """\
static inline int16_t sat_rnd(int64_t v, int shift)
{
    // sqrshrnb semantics: round-to-nearest with ties toward +inf,
    // i.e. floor((v + half) / 2^shift), then saturate.
    const int64_t s = (v + (1LL << (shift - 1))) >> shift;
    if (s > 32767) return 32767;
    if (s < -32768) return -32768;
    return (int16_t)s;
}

static const int16_t LG[16][16] = {
    {64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64},
    {90,87,80,70,57,43,25,9,-9,-25,-43,-57,-70,-80,-87,-90},
    {89,75,50,18,-18,-50,-75,-89,-89,-75,-50,-18,18,50,75,89},
    {87,57,9,-43,-80,-90,-70,-25,25,70,90,80,43,-9,-57,-87},
    {83,36,-36,-83,-83,-36,36,83,83,36,-36,-83,-83,-36,36,83},
    {80,9,-70,-87,-25,57,90,43,-43,-90,-57,25,87,70,-9,-80},
    {75,-18,-89,-50,50,89,18,-75,-75,18,89,50,-50,-89,-18,75},
    {70,-43,-87,9,90,25,-80,-57,57,80,-25,-90,-9,87,43,-70},
    {64,-64,-64,64,64,-64,-64,64,64,-64,-64,64,64,-64,-64,64},
    {57,-80,-25,90,-9,-87,43,70,-70,-43,87,9,-90,25,80,-57},
    {50,-89,18,75,-75,-18,89,-50,-50,89,-18,-75,75,18,-89,50},
    {43,-90,57,25,-87,70,9,-80,80,-9,-70,87,-25,-57,90,-43},
    {36,-83,83,-36,-36,83,-83,36,36,-83,83,-36,-36,83,-83,36},
    {25,-70,90,-80,43,9,-57,87,-87,57,-9,-43,80,-90,70,-25},
    {18,-50,75,-89,89,-75,50,-18,-18,50,-75,89,-89,75,-50,18},
    {9,-25,43,-57,70,-80,87,-90,90,-87,80,-70,57,-43,25,-9},
};

static void legacy_dct16(const int16_t* src, int16_t* dst, intptr_t stride)
{
    int16_t coef[256];
    for (int k = 0; k < 16; k++)
        for (int i = 0; i < 16; i++)
        {
            int16_t E[8], O[8];
            for (int j = 0; j < 8; j++)
            {
                int16_t lo = src[i * stride + j];
                int16_t hi = src[i * stride + 15 - j];
                E[j] = (int16_t)(lo + hi);
                O[j] = (int16_t)(lo - hi);
            }
            int64_t s = 0;
            for (int j = 0; j < 8; j++)
                s += (int64_t)LG[k][j] * ((k & 1) ? O[j] : E[j]);
            coef[k * 16 + i] = sat_rnd(s, 3);
        }
    for (int k = 0; k < 16; k++)
        for (int i = 0; i < 16; i++)
        {
            int16_t E[8], O[8];
            for (int j = 0; j < 8; j++)
            {
                int16_t lo = coef[i * 16 + j];
                int16_t hi = coef[i * 16 + 15 - j];
                E[j] = (int16_t)(lo + hi);
                O[j] = (int16_t)(lo - hi);
            }
            int64_t s = 0;
            for (int j = 0; j < 8; j++)
                s += (int64_t)LG[k][j] * ((k & 1) ? O[j] : E[j]);
            dst[k * 16 + i] = sat_rnd(s, 10);
        }
}
"""
        ref_call = "legacy_dct16"
    t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes.
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

${oracle}

extern "C" void ${cand_sym}(const int16_t*, int16_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0)
    {
        perror("prctl(PR_SVE_SET_VL)");
        return 77;
    }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0, total = 0;
    int first_k = -1;
    int16_t first_want = 0, first_got = 0;
    for (int i = 0; i < cases; i++)
    {
        const int stride = strides[rng() % ${nstrides}];
        int16_t buf[${n} * 32 + ${n}];
        for (int j = 0; j < (int)(sizeof(buf) / sizeof(buf[0])); j++)
            buf[j] = (int16_t)((int)(rng() % (${hi} - ${lo} + 1)) + ${lo});

        int16_t want[${n_out}], got[${n_out}];
        ${ref_call}(buf, want, stride);
        memset(got, 0, sizeof(got));
        ${cand_sym}(buf, got, stride);
        total += ${n_out};
        for (int k = 0; k < ${n_out}; k++)
            if (want[k] != got[k])
            {
                mism++;
                if (first_k < 0)
                {
                    first_k = k;
                    first_want = want[k];
                    first_got = got[k];
                }
            }
    }
    printf("cases=%d lanes=%ld mismatches=%ld rate=%f%%\\n",
           cases, total, mism, 100.0 * mism / total);
    if (first_k >= 0)
        printf(" first-diff idx=%d want=%d got=%d\\n",
               first_k, first_want, first_got);
    return mism != 0;
}
"""
    )
    return t.substitute(
        path=manifest["_path"], contract=contract,
        vl=vl, decl=ref_decl, oracle=oracle, cand_sym=cand["symbol"],
        cases=cases, nstrides=nstrides, strides_c=strides_c,
        n=n, n_out=n_out, hi=hi, lo=lo, ref_call=ref_call)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default="kernels/dct16/manifest.yaml")
    ap.add_argument("--out", default="build/dct16_generated_verify.cpp")
    ap.add_argument("--contract", default=None)
    args = ap.parse_args()
    manifest = load_manifest(
        os.path.basename(os.path.dirname(args.manifest)))
    if args.contract:
        manifest["contract"] = args.contract
    src = generate(manifest)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(src)
    print("wrote %s" % args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
