"""Generic MachineIR -> SVE2 candidate emitter (docs/40 M3, /goal).

Recipe registry: each recipe declares (a) a MachineIR op-signature
detector and (b) an SVE2 ACLE lowering. The emitter consumes only the
imported MachineIR JSON of the seed -- no per-kernel hand-written emitter.
The search layer consumes the emitted source through the normal
verify/trace/MCA funnel (`search_sve2_layouts.py --backend gen`).

Recipes so far:
  diff-sum   (sad 16/16/32): uabd + uaddlv per row -> svld1/svabd/svaddv.

Adding a recipe = register a (name, detect, emit) triple; family members
covered by the same recipe need no emitter code at all.
"""

import json
import os
import re
import sys

try:
    import yaml
except ImportError:
    yaml = None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# kernel name -> seed recipe name (kernel dirs may cover several shapes).
_RECIPE_ALIAS = {
    "sad": "sad-16x16",
    "sad-32": "sad-32x32",
    "sa8d": "sa8d-8x8",
    "sa8d16": "sa8d-16x16",
}


def _load_machine_ir(kernel):
    """Load the seed MachineIR JSON declared by seeds/<kernel>.yaml."""
    recipe_name = _RECIPE_ALIAS.get(kernel, kernel)
    recipe_path = os.path.join(ROOT, "seeds", recipe_name + ".yaml")
    if yaml is None or not os.path.exists(recipe_path):
        # fall back to the canonical m30 layout for known kernels
        alt = os.path.join(
            ROOT, "experiments", "m30-%s-search" % kernel,
            "imported", "machine-ir.json")
        if os.path.exists(alt):
            return json.load(open(alt))
        raise ValueError("no MachineIR for kernel %r" % kernel)
    recipe = yaml.safe_load(open(recipe_path))
    out = recipe["output"]["json"]
    path = out if os.path.isabs(out) else os.path.join(ROOT, out)
    if not os.path.exists(path):
        raise ValueError("MachineIR not found: %s" % path)
    return json.load(open(path))


def detect_diff_sum(machine_ir):
    """Diff-sum signature: uabd+uaddlv (sad 16/32)."""
    intr = {n.get("intrinsic") for n in machine_ir["nodes"]
            if n.get("op") == "intrinsic"}
    if "uabd" in intr and "uaddlv" in intr:
        return True
    return False


def detect_hadamard(machine_ir):
    """Hadamard butterfly signature: sabd+abs+umax+uaddlv (sa8d 8x8).
    16x16 reduces with uaddlp + vecreduce_add instead of uaddlv."""
    intr = {n.get("intrinsic") for n in machine_ir["nodes"]
            if n.get("op") == "intrinsic"}
    if {"sabd", "abs", "umax"} <= intr:
        if "uaddlv" in intr or ("uaddlp" in intr and
                                "vecreduce_add" in intr):
            return True
    return False


def detect_fir(machine_ir):
    """FIR signature: dot-product / tbl / narrowing (interp8/4).
    Recognized but not yet lowered (recipe gap)."""
    intr = {n.get("intrinsic") for n in machine_ir["nodes"]
            if n.get("op") == "intrinsic"}
    return "sdot" in intr or "sqrshrn" in intr


def detect_family(machine_ir):
    """Return the first matching recipe name, or None."""
    for name, rec in RECIPES.items():
        if rec["detect"](machine_ir):
            return name
    return None


def _row_offset(addr_rhs, row_vars):
    """Parse `getelementptr ... i8, ptr %base, i64 %expr` and return the
    expression as a C string over row variables (r), or None."""
    m = re.search(r"i64\s+%([A-Za-z0-9._]+)", addr_rhs)
    if not m:
        return None
    return m.group(1)


def emit_diff_sum(machine_ir, func_name):
    """Emit SVE2 ACLE for the diff-sum family (sad shape: 4 args)."""
    nodes = machine_ir["nodes"]
    uabd_rows = 0
    max_row = -1
    row_offs = set()
    for n in nodes:
        if n.get("op") == "intrinsic" and n.get("intrinsic") == "uabd":
            uabd_rows += 1
    # derive the row count from the row-offset expression magnitudes:
    # seeds unroll r*stride as shl/mul chains; take the max constant
    # multiplier seen in shl/mul nodes feeding addr nodes.
    for n in nodes:
        if n.get("op") in ("shl", "mul") and n.get("amt") is not None:
            max_row = max(max_row, n.get("amt"))
        if n.get("op") == "mul" and n.get("const") is not None:
            max_row = max(max_row, n.get("const"))
    # row count comes from the max row-offset multiplier (the seed may
    # process several uabd groups per row, e.g. 32x32 halves); fall back
    # to the uabd count only when no offset constants are visible.
    rows = max_row + 1 if max_row >= 0 else uabd_rows
    if rows <= 0:
        raise ValueError("diff-sum emitter: could not derive row count")
    groups = max(1, uabd_rows // rows)
    width = 16 * groups
    lines = [
        "// Generated by tools/gen_sve2_emit.py (generic diff-sum recipe)",
        "#include <arm_sve.h>",
        "#include <stdint.h>",
        "",
        "extern \"C\" int %s(const uint8_t* a, intptr_t sa,"
        " const uint8_t* b, intptr_t sb)" % func_name,
        "{",
        "    const svbool_t p = svwhilelt_b8((uint32_t)0,"
        " (uint32_t)%d);" % width,
        "    uint64_t total = 0;",
        "    for (int r = 0; r < %d; r++)" % rows,
        "    {",
        "        svuint8_t x = svld1_u8(p, a + r * sa);",
        "        svuint8_t y = svld1_u8(p, b + r * sb);",
        "        svuint8_t d = svabd_u8_x(p, x, y);",
        "        total += svaddv_u8(p, d);",
    ]
    lines.extend([
        "    }",
        "    return (int)total;",
        "}",
    ])
    return "\n".join(lines) + "\n"


def emit_hadamard(machine_ir, func_name):
    """Straight-line transliteration of the sa8d 8x8 Hadamard DAG to SVE2
    ACLE (docs/40 §7 recipe protocol; naive pack=1, correctness first).

    Data is kept in the low 8 lanes of 16-lane s16 registers (inactive
    lanes are zeroed by predicated loads); only the final reduction is
    predicated to the 8 active lanes. NEON 8-lane trn1/trn2 maps to
    svzip1/svtrn2 of the 16-lane SVE vectors (low-8-lane equivalence).
    """
    nodes = machine_ir["nodes"]
    nd = {}
    for n in nodes:
        nd[n.get("dst")] = n

    lines = [
        "// Generated by tools/gen_sve2_emit.py (generic hadamard recipe)",
        "#include <arm_sve.h>",
        "#include <arm_neon.h>",
        "#include <arm_neon_sve_bridge.h>",
        "#include <stdint.h>",
        "",
        "extern \"C\" int %s(const uint8_t* pix1, intptr_t sa,"
        " const uint8_t* pix2, intptr_t sb)" % func_name,
        "{",
        "    const svbool_t pg8 = svwhilelt_b8((uint32_t)0, (uint32_t)8);",
        "    const svbool_t pg8h = svwhilelt_b16((uint32_t)0, (uint32_t)8);",
        "    const svbool_t pg4w = svwhilelt_b32((uint32_t)0, (uint32_t)4);",
        "    const svbool_t p16 = svptrue_b16();",
        "    const svbool_t pg4 = svwhilelt_b16((uint32_t)0, (uint32_t)4);",
        "    static const uint16_t ROT4[16] ="
        " { 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3 };",
        "    const svuint16_t rot4 = svld1_u16(p16, ROT4);",
    ]
    env = {}
    vtypes = {}
    counter = [0]

    def var(dst):
        if dst not in env:
            env[dst] = "v%d" % counter[0]
            counter[0] += 1
        return env[dst]

    def setvar(dst, ctype):
        vtypes[var(dst)] = ctype

    def as_s16(v):
        return v if vtypes.get(v) == "svint16_t" \
            else "svreinterpret_s16_u16(%s)" % v

    def as_s32(v):
        return v if vtypes.get(v) == "svint32_t" \
            else "svreinterpret_s32_u32(%s)" % v

    def as_u32(v):
        return v if vtypes.get(v) == "svuint32_t" \
            else "svreinterpret_u32_s32(%s)" % v

    def emit(node, line):
        lines.append("    %s" % line)

    # scalar address env: (var, coef) over the stride symbols.
    for name, sym in (("i_pix1", "sa"), ("i_pix2", "sb"),
                      ("%i_pix1", "sa"), ("%i_pix2", "sb"),
                      ("1", "sa"), ("3", "sb")):
        env[name] = (sym, 1)
    ptr_off = {}

    for n in nodes:
        op = n["op"]
        dst = n.get("dst")
        if op == "load":
            ptr = n["ptr"]
            base, coef, byte = ptr_off.get(ptr, (ptr, 0, 0))
            if base not in ("pix1", "pix2", "0", "2"):
                raise ValueError(
                    "hadamard: unknown load base %r" % base)
            abi = "pix1" if base in ("pix1", "0") else "pix2"
            stride = "sa" if abi == "pix1" else "sb"
            t = "svuint8_t"
            if byte:
                emit(n, "%s %s = svld1_u8(pg8, %s + %d * %s + %d);"
                     % (t, var(dst), abi, coef, stride, byte))
            else:
                emit(n, "%s %s = svld1_u8(pg8, %s + %d * %s);"
                     % (t, var(dst), abi, coef, stride))
            setvar(dst, t)
        elif op == "addr":
            mi = re.search(r"i64\s+%([A-Za-z0-9._]+)", n["rhs"])
            mb = re.search(r"ptr\s+%([A-Za-z0-9._]+),", n["rhs"])
            mc = re.search(r"i64\s+(-?\d+)\s*$", n["rhs"])
            if not mb:
                raise ValueError("hadamard: non-dynamic addr %r" % n["rhs"])
            base = mb.group(1)
            root, prev, prevb = ptr_off.get(base, (base, 0, 0))
            if mc:
                ptr_off[dst] = (root, prev, prevb + int(mc.group(1)))
            else:
                if not mi:
                    raise ValueError("hadamard: addr without offset %r"
                                     % n["rhs"])
                coef = env.get(mi.group(1))
                if not isinstance(coef, tuple):
                    raise ValueError("hadamard: unresolved addr index %r"
                                     % mi.group(1))
                ptr_off[dst] = (root, prev + coef[1], prevb)
        elif op in ("shl", "mul"):
            src = n["src"][0]
            if isinstance(env.get(src), tuple):
                sym, coef = env[src]
                amt = n.get("amt") if op == "shl" else n.get("const")
                if amt is None:
                    raise ValueError("hadamard: non-const %s" % op)
                env[dst] = (sym, coef * (1 << amt) if op == "shl"
                            else coef * amt)
            else:
                raise ValueError("hadamard: unexpected %s on %r" % (op, src))
        elif op == "zext" and n.get("type") == "<8 x i16>":
            emit(n, "svuint16_t %s = svunpklo_u16(%s);"
                 % (var(dst), var(n["src"])))
            setvar(dst, "svuint16_t")
        elif op in ("add", "sub") and str(n.get("type", "")).startswith("<"):
            vtype = n["type"]
            if vtype == "<8 x i16>":
                f = "svadd_s16_x(p16, %s, %s)" if op == "add" \
                    else "svsub_s16_x(p16, %s, %s)"
                t = "svint16_t"
            elif vtype == "<4 x i32>":
                f = "svadd_s32_x(p16, %s, %s)" if op == "add" \
                    else "svsub_s32_x(p16, %s, %s)"
                t = "svint32_t"
            else:
                raise ValueError("hadamard: unsupported vec %s %s"
                                 % (op, vtype))
            if vtype == "<4 x i32>":
                a, b = as_s32(var(n["src"][0])), as_s32(var(n["src"][1]))
            else:
                a, b = as_s16(var(n["src"][0])), as_s16(var(n["src"][1]))
            emit(n, "%s %s = %s;" % (t, var(dst), f % (a, b)))
            setvar(dst, t)
        elif op == "shuffle":
            vtype = n["type"]
            mask = n["mask"]
            a, b = var(n["src"][0]), var(n["src"][1])
            fn = {
                "<8 x i16>": {
                    (0, 8, 2, 10, 4, 12, 6, 14): ("svtrn1_s16", "svint16_t"),
                    (1, 9, 3, 11, 5, 13, 7, 15): ("svtrn2_s16", "svint16_t"),
                },
                "<4 x i32>": {
                    (0, 4, 2, 6): ("svtrn1_s32", "svint32_t"),
                    (1, 5, 3, 7): ("svtrn2_s32", "svint32_t"),
                },
                "<2 x i64>": {
                    (0, 2): None,
                    (1, 3): None,
                },
            }.get(vtype, {})
            key = tuple(mask)
            if vtype == "<8 x i16>" and key == (0, 1, 2, 3, 8, 9, 10, 11):
                # concat low halves: [a0..a3, b0..b3]
                emit(n, "svint16_t %s = svsplice_s16(pg4, %s, %s);"
                     % (var(dst), a, b))
                setvar(dst, "svint16_t")
                continue
            if vtype == "<2 x i64>" and key in fn:
                # NEON 2x i64 trn = 4-s16 chunk moves; in SVE 8-of-16 lane
                # layout this is splice of the low 4 lanes (trn1) or of
                # lanes rotated by 4 (trn2).
                a64, b64 = a, b
                a16 = "svreinterpret_s16_s64(%s)" % a64
                b16 = "svreinterpret_s16_s64(%s)" % b64
                if key == (1, 3):
                    a16 = "svtbl_s16(%s, rot4)" % a16
                    b16 = "svtbl_s16(%s, rot4)" % b16
                emit(n, "svint64_t %s = svreinterpret_s64_s16("
                     "svsplice_s16(pg4, %s, %s));"
                     % (var(dst), a16, b16))
                setvar(dst, "svint64_t")
                continue
            if key not in fn or fn[key] is None:
                raise ValueError("hadamard: unhandled shuffle %s %r"
                                 % (vtype, mask))
            name, t = fn[key]
            emit(n, "%s %s = %s(%s, %s);"
                 % (t, var(dst), name, a, b))
            setvar(dst, t)
        elif op == "bitcast":
            st, dt = n.get("src_type"), n["type"]
            src = var(n["src"])
            if (st, dt) == ("<8 x i16>", "<2 x i64>"):
                emit(n, "svint64_t %s = svreinterpret_s64_s16(%s);"
                     % (var(dst), src))
                setvar(dst, "svint64_t")
            elif (st, dt) == ("<2 x i64>", "<8 x i16>"):
                emit(n, "svint16_t %s = svreinterpret_s16_s64(%s);"
                     % (var(dst), src))
                setvar(dst, "svint16_t")
            elif (st, dt) == ("<8 x i16>", "<4 x i32>"):
                emit(n, "svint32_t %s = svreinterpret_s32_s16(%s);"
                     % (var(dst), src))
                setvar(dst, "svint32_t")
            elif (st, dt) == ("<4 x i32>", "<8 x i16>"):
                emit(n, "svint16_t %s = svreinterpret_s16_s32(%s);"
                     % (var(dst), src))
                setvar(dst, "svint16_t")
            else:
                raise ValueError("hadamard: unhandled bitcast %s -> %s"
                                 % (st, dt))
        elif op == "intrinsic":
            name = n["intrinsic"]
            src = [var(s) for s in n["src"]]
            if name == "sabd":
                emit(n, "svint16_t %s = svabd_s16_x(p16, %s, %s);"
                     % (var(dst), as_s16(src[0]), as_s16(src[1])))
                setvar(dst, "svint16_t")
            elif name == "abs":
                emit(n, "svint16_t %s = svabs_s16_x(p16, %s);"
                     % (var(dst), as_s16(src[0])))
                setvar(dst, "svint16_t")
            elif name == "umax":
                emit(n, "svuint16_t %s = svmax_u16_x(p16,"
                     " svreinterpret_u16_s16(%s), svreinterpret_u16_s16(%s));"
                     % (var(dst), src[0], src[1]))
                setvar(dst, "svuint16_t")
            elif name == "uaddlv":
                emit(n, "uint16_t %s = svaddv_u16(pg8h,"
                     " svreinterpret_u16_s16(%s));" % (var(dst), src[0]))
                setvar(dst, "uint16_t")
            elif name == "uaddlp":
                emit(n, "svuint32_t %s = svset_neonq_u32(svundef_u32(),"
                     " vpaddlq_u16(svget_neonq_u16("
                     "svreinterpret_u16_s16(%s))));" % (var(dst), src[0]))
                setvar(dst, "svuint32_t")
            elif name == "vecreduce_add":
                emit(n, "uint32_t %s = svaddv_u32(pg4w, %s);"
                     % (var(dst), as_u32(src[0])))
                setvar(dst, "uint32_t")
            else:
                raise ValueError("hadamard: unhandled intrinsic %r" % name)
        elif op == "add" and n.get("type") == "i32" and \
                n.get("const") is not None:
            emit(n, "uint32_t %s = %s + %d;"
                 % (var(dst), var(n["src"][0]), n["const"]))
        elif op == "lshr" and n.get("type") == "i32":
            emit(n, "uint32_t %s = %s >> %d;"
                 % (var(dst), var(n["src"][0]), n.get("amt", 0)))
        elif op == "ret":
            emit(n, "return (int)%s;" % var(n["operand"]))
        else:
            raise ValueError("hadamard: unhandled op %r" % n)
    lines.append("}")
    return "\n".join(lines) + "\n"


RECIPES = {
    "diff-sum": {
        "detect": detect_diff_sum,
        "emit": emit_diff_sum,
    },
    "hadamard": {"detect": detect_hadamard, "emit": emit_hadamard},
    # Recognized structure family without a lowering yet: clear error.
    "fir": {"detect": detect_fir, "emit": None},
}


def make_generic_emitter(kernel):
    """Return emit(combo) that derives the candidate from the MachineIR.
    Family detection is per-kernel but recipe-driven: no kernel-specific
    emitter code is written for a new member of a known family."""
    mi = _load_machine_ir(kernel)
    family = detect_family(mi)
    recipe = RECIPES.get(family)
    if recipe is None or recipe["emit"] is None:
        raise ValueError(
            "generic emitter: family %r has no lowering yet (kernel %s);"
            " add a recipe in tools/gen_sve2_emit.py RECIPES"
            % (family, kernel))

    manifest_path = os.path.join(ROOT, "kernels", kernel, "manifest.yaml")
    symbol = None
    if os.path.exists(manifest_path):
        man = yaml.safe_load(open(manifest_path))
        symbol = man.get("candidate", {}).get("symbol")

    def emit(combo):
        return recipe["emit"](mi, symbol or "dynopt_%s_sve2" % kernel)
    return emit


def list_recipes():
    return sorted(RECIPES)
