#!/usr/bin/env python3
"""Generate the upstream-exact differential harness from a kernel manifest.

The manifest (docs/16) declares the reference symbol/declaration, corpus
(strides, value range, cases) and VL contract; this generator turns it into
a self-contained C++ verify source so the evaluation funnel is manifest-
driven and no per-kernel harness needs to be hand-maintained.

Usage:
  python3 tools/gen_verify.py --manifest kernels/dct16/manifest.yaml \
      --out build/dct16_generated_verify.cpp
"""

import argparse
import sys
import os
import string

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))

from kernel_manifest import load_manifest  # noqa: E402


def generate(manifest):
    ref = manifest["reference"]
    cand = manifest["candidate"]
    corpus = manifest.get("corpus", {})
    contract = manifest.get("contract", "upstream-exact")
    strides = corpus.get("strides", [16])
    lo, hi = corpus.get("value_range", [-255, 255])
    vl = manifest.get("vl_bytes", 32)
    cases = corpus.get("cases", 20000)
    n = manifest.get("shape", {}).get("n", 16)
    n_out = n * n
    strides_c = ", ".join(str(s) for s in strides)
    maxstride = max(strides)
    nstrides = len(strides)
    kind = manifest.get("shape", {}).get("kind", "dct")
    rows = manifest.get("shape", {}).get("rows", n)
    if kind == "interp8":
        ref = manifest["reference"]
        cand = manifest["candidate"]
        corpus = manifest.get("corpus", {})
        contract = manifest.get("contract", "upstream-exact")
        vl = manifest.get("vl_bytes", 32)
        strides_c = ", ".join(str(s) for s in corpus.get("strides", [16]))
        nstrides = len(corpus.get("strides", [16]))
        cases = corpus.get("cases", 20000)
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: interp8 (${n}x${n}).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(
    const uint8_t*, intptr_t, uint8_t*, intptr_t, int);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        const intptr_t ss = strides[rng() % ${nstrides}];
        const intptr_t ds = strides[rng() % ${nstrides}];
        uint8_t src[${n} * 64 + 32], wa[${n} * 64], wb[${n} * 64];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() % 256);
        for (int ph = 1; ph <= 3; ph++)
        {
            ${ref_call}(src + 16, ss, wa, ds, ph);
            memset(wb, 0, sizeof(wb));
            ${cand_sym}(src + 16, ss, wb, ds, ph);
            for (int r = 0; r < ${n}; r++)
                for (int c = 0; c < ${n}; c++)
                    if (wa[r * ds + c] != wb[r * ds + c]) mism++;
        }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract, vl=vl,
            decl=ref["decl"], cand_sym=cand["symbol"], cases=cases,
            nstrides=nstrides, strides_c=strides_c, ref_call=ref["call"],
            n=manifest.get("shape", {}).get("n", 8))
    if kind == "interp8_hps":
        # luma_hps: pixel -> int16 horizontal 8-tap filter. First slice
        # contract is isRowExt == 0 (the extracted straight-line path);
        # coeffIdx sweeps phases 1..3 at runtime.
        t = string.Template("""// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: interp8_hps ${n}x${n}.
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(
    const uint8_t*, intptr_t, int16_t*, intptr_t, int, int);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        const intptr_t ss = strides[rng() % ${nstrides}];
        const intptr_t ds = strides[rng() % ${nstrides}];
        const int coeffIdx = 1 + (int)(rng() % 3);
        uint8_t srcbuf[${n} * 64 + 64];
        int16_t want[${n} * 64 + ${n}], got[${n} * 64 + ${n}];
        for (int j = 0; j < (int)sizeof(srcbuf); j++)
            srcbuf[j] = (uint8_t)(rng() % 256);
        uint8_t* src = srcbuf + 16;  // left margin for src - 3

        ${ref_call}(src, ss, want, ds, coeffIdx, 0);
        ${cand_sym}(src, ss, got, ds, coeffIdx, 0);
        for (int r = 0; r < ${n}; r++)
            for (int c = 0; c < ${n}; c++)
                if (want[r * ds + c] != got[r * ds + c])
                    mism++;
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract, vl=vl,
            decl=ref["decl"], cand_sym=cand["symbol"], cases=cases,
            nstrides=nstrides, strides_c=strides_c, ref_call=ref["call"],
            n=n)

    if kind == "interp8vpp":
        # Vertical 8-tap: caller passes the block top-left; both reference
        # and candidate subtract 3*stride internally, so the source buffer
        # needs a >= 3*max(stride) margin above the block (max 64 here).
        ref = manifest["reference"]
        cand = manifest["candidate"]
        corpus = manifest.get("corpus", {})
        contract = manifest.get("contract", "upstream-exact")
        vl = manifest.get("vl_bytes", 32)
        strides_c = ", ".join(str(s) for s in corpus.get("strides", [16]))
        nstrides = len(corpus.get("strides", [16]))
        cases = corpus.get("cases", 20000)
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: interp8vpp
// (${n}x${n} vertical).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(
    const uint8_t*, intptr_t, uint8_t*, intptr_t, int);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        const intptr_t ss = strides[rng() % ${nstrides}];
        const intptr_t ds = strides[rng() % ${nstrides}];
        uint8_t src[(${n} + 6) * 64 + 32], wa[${n} * 64], wb[${n} * 64];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() % 256);
        for (int ph = 1; ph <= 3; ph++)
        {
            ${ref_call}(src + 3 * 64 + 16, ss, wa, ds, ph);
            memset(wb, 0, sizeof(wb));
            ${cand_sym}(src + 3 * 64 + 16, ss, wb, ds, ph);
            for (int r = 0; r < ${n}; r++)
                for (int c = 0; c < ${n}; c++)
                    if (wa[r * ds + c] != wb[r * ds + c]) mism++;
        }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract, vl=vl,
            decl=ref["decl"], cand_sym=cand["symbol"], cases=cases,
            nstrides=nstrides, strides_c=strides_c, ref_call=ref["call"],
            n=manifest.get("shape", {}).get("n", 16))
    if kind == "interp4":
        # Chroma 4-tap horizontal: 8 phases (1..7 tested; phase 0 integer),
        # src -= 1 internally, 16-pixel rows.
        ref = manifest["reference"]
        cand = manifest["candidate"]
        corpus = manifest.get("corpus", {})
        contract = manifest.get("contract", "upstream-exact")
        vl = manifest.get("vl_bytes", 32)
        strides_c = ", ".join(str(s) for s in corpus.get("strides", [16]))
        nstrides = len(corpus.get("strides", [16]))
        cases = corpus.get("cases", 20000)
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: interp4 (${n}x${n}).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(
    const uint8_t*, intptr_t, uint8_t*, intptr_t, int);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        const intptr_t ss = strides[rng() % ${nstrides}];
        const intptr_t ds = strides[rng() % ${nstrides}];
        uint8_t src[${n} * 64 + 32], wa[${n} * 64], wb[${n} * 64];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() % 256);
        for (int ph = 1; ph <= 7; ph++)
        {
            ${ref_call}(src + 16, ss, wa, ds, ph);
            memset(wb, 0, sizeof(wb));
            ${cand_sym}(src + 16, ss, wb, ds, ph);
            for (int r = 0; r < ${n}; r++)
                for (int c = 0; c < ${n}; c++)
                    if (wa[r * ds + c] != wb[r * ds + c]) mism++;
        }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract, vl=vl,
            decl=ref["decl"], cand_sym=cand["symbol"], cases=cases,
            nstrides=nstrides, strides_c=strides_c, ref_call=ref["call"],
            n=manifest.get("shape", {}).get("n", 16))
    if kind == "interp4vpp":
        # Chroma 4-tap vertical: caller passes block top-left; both sides
        # subtract 1*stride internally; source buffer needs >= 1*max(stride)
        # margin above (plus safety), phases 1..7.
        ref = manifest["reference"]
        cand = manifest["candidate"]
        corpus = manifest.get("corpus", {})
        contract = manifest.get("contract", "upstream-exact")
        vl = manifest.get("vl_bytes", 32)
        strides_c = ", ".join(str(s) for s in corpus.get("strides", [16]))
        nstrides = len(corpus.get("strides", [16]))
        cases = corpus.get("cases", 20000)
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: interp4vpp
// (${n}x${n} vertical chroma).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(
    const uint8_t*, intptr_t, uint8_t*, intptr_t, int);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        const intptr_t ss = strides[rng() % ${nstrides}];
        const intptr_t ds = strides[rng() % ${nstrides}];
        uint8_t src[(${n} + 4) * 64 + 32], wa[${n} * 64], wb[${n} * 64];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() % 256);
        for (int ph = 1; ph <= 7; ph++)
        {
            ${ref_call}(src + 3 * 64 + 16, ss, wa, ds, ph);
            memset(wb, 0, sizeof(wb));
            ${cand_sym}(src + 3 * 64 + 16, ss, wb, ds, ph);
            for (int r = 0; r < ${n}; r++)
                for (int c = 0; c < ${n}; c++)
                    if (wa[r * ds + c] != wb[r * ds + c]) mism++;
        }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract, vl=vl,
            decl=ref["decl"], cand_sym=cand["symbol"], cases=cases,
            nstrides=nstrides, strides_c=strides_c, ref_call=ref["call"],
            n=manifest.get("shape", {}).get("n", 16))
    if kind == "sad":
        # SAD: two uint8 planes in, int out (same shape as sa8d).
        ref = manifest["reference"]
        cand = manifest["candidate"]
        corpus = manifest.get("corpus", {})
        contract = manifest.get("contract", "upstream-exact")
        vl = manifest.get("vl_bytes", 32)
        strides_c = ", ".join(str(s) for s in corpus.get("strides", [16]))
        nstrides = len(corpus.get("strides", [16]))
        cases = corpus.get("cases", 20000)
        n = manifest.get("shape", {}).get("n", 16)
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sad (${n}x${n}).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" int ${cand_sym}(
    const uint8_t*, intptr_t, const uint8_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        const intptr_t sa = strides[rng() % ${nstrides}];
        const intptr_t sb = strides[rng() % ${nstrides}];
        uint8_t a[${n} * 64], b[${n} * 64];
        for (int j = 0; j < (int)sizeof(a); j++)
        {
            a[j] = (uint8_t)(rng() % 256);
            b[j] = (uint8_t)(rng() % 256);
        }
        const int want = ${ref_call}(a, sa, b, sb);
        const int got = ${cand_sym}(a, sa, b, sb);
        if (want != got) mism++;
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract, vl=vl,
            decl=ref["decl"], cand_sym=cand["symbol"], cases=cases,
            nstrides=nstrides, strides_c=strides_c, ref_call=ref["call"],
            n=n)
    oracle = ""
    ref_call = ref["call"]
    ref_decl = ref["decl"]
    if kind == "sa8d":
        # SA8D is a pixel-shaped kernel: two uint8_t planes in, one int out.
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sa8d.
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" int ${cand_sym}(
    const uint8_t*, intptr_t, const uint8_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0)
    {
        perror("prctl(PR_SVE_SET_VL)");
        return 77;
    }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0;
    int first_want = 0, first_got = 0;
    for (int i = 0; i < cases; i++)
    {
        const intptr_t sa = strides[rng() % ${nstrides}];
        const intptr_t sb = strides[rng() % ${nstrides}];
        uint8_t buf[2][${rows} * 64 + 64];
        for (int j = 0; j < (int)(sizeof(buf[0]) / sizeof(buf[0][0])); j++)
        {
            buf[0][j] = (uint8_t)(rng() % 256);
            buf[1][j] = (uint8_t)(rng() % 256);
        }

        const int want = ${ref_call}(buf[0], sa, buf[1], sb);
        const int got = ${cand_sym}(buf[0], sa, buf[1], sb);
        if (want != got)
        {
            mism++;
            if (mism == 1)
            {
                first_want = want;
                first_got = got;
            }
        }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    if (mism)
        printf(" first-diff want=%d got=%d\\n", first_want, first_got);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract, vl=vl,
            decl=ref_decl, cand_sym=cand["symbol"], cases=cases,
            nstrides=nstrides, strides_c=strides_c, ref_call=ref_call,
            rows=rows)
    if kind == "idct":
        # IDCT: src is a contiguous 16x16 coefficient block (no srcStride),
        # dst is written with dstStride; the reference is the x265 C
        # idctN_c (upstream has no SVE IDCT, docs/27).
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: idct (${n}x${n}).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(const int16_t*, int16_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0, total = 0;
    int first_k = -1;
    int16_t first_want = 0, first_got = 0;
    for (int i = 0; i < cases; i++)
    {
        const int ds = strides[rng() % ${nstrides}];
        int16_t src[${n} * ${n}];
        for (int j = 0; j < ${n} * ${n}; j++)
            src[j] = (int16_t)((int)(rng() % (${hi} - ${lo} + 1)) + ${lo});

        int16_t want[${n} * ${maxstride} + ${n}], got[${n} * ${maxstride} + ${n}];
        memset(want, 0, sizeof(want));
        memset(got, 0, sizeof(got));
        ${ref_call}(src, want, ds);
        ${cand_sym}(src, got, ds);
        total += ${n_out};
        for (int k = 0; k < ${n_out}; k++)
            if (want[k] != got[k])
            {
                mism++;
                if (first_k < 0)
                {
                    first_k = k;
                    first_want = want[k];
                    first_got = got[k];
                }
            }
    }
    printf("cases=%d lanes=%ld mismatches=%ld rate=%f%%\\n",
           cases, total, mism, 100.0 * mism / total);
    if (first_k >= 0)
        printf(" first-diff idx=%d want=%d got=%d\\n",
               first_k, first_want, first_got);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, decl=ref_decl, cand_sym=cand["symbol"],
            cases=cases, nstrides=nstrides, strides_c=strides_c,
            n=n, n_out=n_out, hi=hi, lo=lo, ref_call=ref_call,
            maxstride=maxstride)
    if kind == "dequant":
        # dequant_normal: contiguous s16 coeff array, runtime scale/shift;
        # reference is the NEON asm with an extra num argument.
        n = manifest.get("shape", {}).get("n", 256)
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: dequant (${n} elems).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(const int16_t*, int16_t*, int, int);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xDE0A2026u);
    const int scales[8] = { 1, 3, 16, 64, 72, 255, 1024, 18432 };
    const int shifts[6] = { 1, 2, 4, 6, 8, 10 };

    long mism = 0, total = 0;
    int first_k = -1;
    int16_t first_want = 0, first_got = 0;
    for (int i = 0; i < cases; i++)
    {
        int16_t src[${n}], want[${n}], got[${n}];
        for (int j = 0; j < ${n}; j++)
            src[j] = (int16_t)(rng() & 0xFFFF);
        const int scale = scales[rng() % 8];
        const int shift = shifts[rng() % 6];
        memset(want, 0, sizeof(want));
        memset(got, 0, sizeof(got));
        ${ref_call}(src, want, ${n}, scale, shift);
        ${cand_sym}(src, got, scale, shift);
        total += ${n};
        for (int k = 0; k < ${n}; k++)
            if (want[k] != got[k])
            {
                mism++;
                if (first_k < 0)
                {
                    first_k = k;
                    first_want = want[k];
                    first_got = got[k];
                }
            }
    }
    printf("cases=%d lanes=%ld mismatches=%ld rate=%f%%\\n",
           cases, total, mism, 100.0 * mism / total);
    if (first_k >= 0)
        printf(" first-diff idx=%d want=%d got=%d\\n",
               first_k, first_want, first_got);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, decl=ref_decl, cand_sym=cand["symbol"],
            cases=cases, n=n, ref_call=ref_call)
    if kind == "dequant_scaling":
        # dequant_scaling: q (s16) * dq (s32) -> coef (s16), runtime
        # per/shift; branch gt (shift+4 > per) or le (shift+4 <= per)
        # selects the value ranges (docs/44).
        n = manifest.get("shape", {}).get("n", 256)
        branch = manifest.get("shape", {}).get("branch", "gt")
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: dequant_scaling
// (${n} elems, branch ${branch}).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(
    const int16_t*, const int32_t*, int16_t*, int, int);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    const int branch = ${branch};
    std::mt19937 rng(0x5CA1E2026u);

    long mism = 0, total = 0;
    int first_k = -1;
    int16_t first_want = 0, first_got = 0;
    for (int i = 0; i < cases; i++)
    {
        int16_t q[${n}], want[${n}], got[${n}];
        int32_t dq[${n}];
        for (int j = 0; j < ${n}; j++)
        {
            q[j] = (int16_t)(rng() & 0xFFFF);
            dq[j] = (int32_t)(rng() % 2097153) - 1048576;
        }
        int per, shift;
        if (branch == 1)
        {
            per = 8 + (int)(rng() % 5);
            const int lo = per - 3;
            shift = lo + (int)(rng() % (10 - lo + 1));
        }
        else
        {
            per = (rng() % 2) ? 8 : 16;
            shift = 1 + (int)(rng() % (per - 4));
        }
        memset(want, 0, sizeof(want));
        memset(got, 0, sizeof(got));
        ${ref_call}(q, dq, want, ${n}, per, shift);
        ${cand_sym}(q, dq, got, shift, per);
        total += ${n};
        for (int k = 0; k < ${n}; k++)
            if (want[k] != got[k])
            {
                mism++;
                if (first_k < 0)
                {
                    first_k = k;
                    first_want = want[k];
                    first_got = got[k];
                }
            }
    }
    printf("cases=%d lanes=%ld mismatches=%ld rate=%f%%\\n",
           cases, total, mism, 100.0 * mism / total);
    if (first_k >= 0)
        printf(" first-diff idx=%d want=%d got=%d\\n",
               first_k, first_want, first_got);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, decl=ref_decl, cand_sym=cand["symbol"],
            cases=cases, n=n, branch=(1 if branch == "gt" else 0),
            ref_call=ref_call)
    if kind == "quant":
        # quant: coef(s16) * quantCoeff(s32) -> level/deltaU/qCoef/numSig;
        # constrained ranges keep level in s16 (docs/44).
        n = manifest.get("shape", {}).get("n", 256)
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: quant (${n} elems).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" uint32_t ${cand_sym}(
    const int16_t*, const int32_t*, int32_t*, int16_t*, int, int);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x0A7E2026u);

    long mism = 0, total = 0;
    int first_k = -1;
    int16_t first_qw = 0, first_qg = 0;
    int32_t first_dw = 0, first_dg = 0;
    uint32_t first_sw = 0, first_sg = 0;
    for (int i = 0; i < cases; i++)
    {
        int16_t coef[${n}], qw[${n}], qg[${n}];
        int32_t qc[${n}], dw[${n}], dg[${n}];
        for (int j = 0; j < ${n}; j++)
        {
            coef[j] = (int16_t)(rng() & 0xFFFF);
            qc[j] = 1 + (int32_t)(rng() % 16384);
        }
        const int qBits = 14 + (int)(rng() % 9);
        const int add = (int)(rng() % (1 << qBits));
        memset(qw, 0, sizeof(qw)); memset(qg, 0, sizeof(qg));
        memset(dw, 0, sizeof(dw)); memset(dg, 0, sizeof(dg));
        const uint32_t sw = ${ref_call}(
            coef, qc, dw, qw, qBits, add, ${n});
        const uint32_t sg = ${cand_sym}(coef, qc, dg, qg, qBits, add);
        total += ${n};
        int bad = (sw != sg);
        for (int k = 0; k < ${n} && !bad; k++)
            if (qw[k] != qg[k] || dw[k] != dg[k])
                bad = 1;
        if (bad)
        {
            mism++;
            if (first_k < 0)
            {
                first_k = i;
                first_qw = qw[0]; first_qg = qg[0];
                first_dw = dw[0]; first_dg = dg[0];
                first_sw = sw; first_sg = sg;
            }
        }
    }
    printf("cases=%d lanes=%ld mismatches=%ld rate=%f%%\\n",
           cases, total, mism, 100.0 * mism / total);
    if (first_k >= 0)
        printf(" first-diff case=%d numsig=%u/%u q=%d/%d d=%d/%d\\n",
               first_k, first_sw, first_sg,
               first_qw, first_qg, first_dw, first_dg);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, decl=ref_decl, cand_sym=cand["symbol"],
            cases=cases, n=n, ref_call=ref_call)
    if kind == "nquant":
        # nquant: same as quant but no deltaU; qCoef stores |level|.
        n = manifest.get("shape", {}).get("n", 256)
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: nquant (${n} elems).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" uint32_t ${cand_sym}(
    const int16_t*, const int32_t*, int16_t*, int, int);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x9A7E2026u);

    long mism = 0, total = 0;
    int first_k = -1;
    int16_t first_qw = 0, first_qg = 0;
    uint32_t first_sw = 0, first_sg = 0;
    for (int i = 0; i < cases; i++)
    {
        int16_t coef[${n}], qw[${n}], qg[${n}];
        int32_t qc[${n}];
        for (int j = 0; j < ${n}; j++)
        {
            coef[j] = (int16_t)(rng() & 0xFFFF);
            qc[j] = 1 + (int32_t)(rng() % 16384);
        }
        const int qBits = 14 + (int)(rng() % 9);
        const int add = (int)(rng() % (1 << qBits));
        memset(qw, 0, sizeof(qw)); memset(qg, 0, sizeof(qg));
        const uint32_t sw = ${ref_call}(
            coef, qc, qw, qBits, add, ${n});
        const uint32_t sg = ${cand_sym}(coef, qc, qg, qBits, add);
        total += ${n};
        int bad = (sw != sg);
        for (int k = 0; k < ${n} && !bad; k++)
            if (qw[k] != qg[k])
                bad = 1;
        if (bad)
        {
            mism++;
            if (first_k < 0)
            {
                first_k = i;
                first_qw = qw[0]; first_qg = qg[0];
                first_sw = sw; first_sg = sg;
            }
        }
    }
    printf("cases=%d lanes=%ld mismatches=%ld rate=%f%%\\n",
           cases, total, mism, 100.0 * mism / total);
    if (first_k >= 0)
        printf(" first-diff case=%d numsig=%u/%u q=%d/%d\\n",
               first_k, first_sw, first_sg, first_qw, first_qg);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, decl=ref_decl, cand_sym=cand["symbol"],
            cases=cases, n=n, ref_call=ref_call)
    if kind == "ssim":
        # ssim_4x4x2_core: two adjacent 4x4 blocks, sums[8].
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: ssim 4x4x2.
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(
    const uint8_t*, intptr_t, const uint8_t*, intptr_t, int32_t*);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x51D2026u);
    const int strides[5] = { 8, 16, 17, 32, 64 };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        uint8_t b1[4 * 64 + 16], b2[4 * 64 + 16];
        for (int j = 0; j < (int)sizeof(b1); j++)
        {
            b1[j] = (uint8_t)(rng() & 0xFF);
            b2[j] = (uint8_t)(rng() & 0xFF);
        }
        const intptr_t s1 = strides[rng() % 5];
        const intptr_t s2 = strides[rng() % 5];
        int32_t w[8], g[8];
        memset(w, 0, sizeof(w)); memset(g, 0, sizeof(g));
        ${ref_call}(b1, s1, b2, s2, w);
        ${cand_sym}(b1, s1, b2, s2, g);
        for (int k = 0; k < 8; k++)
            if (w[k] != g[k])
            {
                if (mism < 5)
                    fprintf(stderr, "mismatch %d[%d]: ref=%d gen=%d\\n",
                            i, k, w[k], g[k]);
                mism++;
                break;
            }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, decl=ref_decl, cand_sym=cand["symbol"],
            cases=cases, ref_call=ref_call)
    if kind == "scale1d":
        # scale1D_128to64: two 128-px rows -> two 64-px rows.
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: scale1d 128to64.
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(uint8_t*, const uint8_t*);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5C1E2026u);

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        uint8_t src[256], w[128], g[128];
        for (int j = 0; j < 256; j++)
            src[j] = (uint8_t)(rng() & 0xFF);
        memset(w, 0, sizeof(w)); memset(g, 0, sizeof(g));
        ${ref_call}(w, src);
        ${cand_sym}(g, src);
        for (int k = 0; k < 128; k++)
            if (w[k] != g[k])
            {
                if (mism < 5)
                    fprintf(stderr, "mismatch %d[%d]: ref=%d gen=%d\\n",
                            i, k, w[k], g[k]);
                mism++;
                break;
            }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, decl=ref_decl, cand_sym=cand["symbol"],
            cases=cases, ref_call=ref_call)
    if kind == "scale2d":
        # scale2D_64to32: 64x64 -> 32x32 (2x2 average).
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: scale2d 64to32.
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

extern "C" void ${cand_sym}(uint8_t*, const uint8_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5C2D2026u);
    const int strides[4] = { 64, 65, 96, 128 };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        uint8_t src[64 * 128 + 16], w[1024], g[1024];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() & 0xFF);
        const intptr_t stride = strides[rng() % 4];
        memset(w, 0, sizeof(w)); memset(g, 0, sizeof(g));
        ${ref_call}(w, src, stride);
        ${cand_sym}(g, src, stride);
        for (int k = 0; k < 1024; k++)
            if (w[k] != g[k])
            {
                if (mism < 5)
                    fprintf(stderr, "mismatch %d[%d]: ref=%d gen=%d\\n",
                            i, k, w[k], g[k]);
                mism++;
                break;
            }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, decl=ref_decl, cand_sym=cand["symbol"],
            cases=cases, ref_call=ref_call)
    if kind == "sao_e0":
        # SAO edge class 0, width 64, 2 rows. The open-source NEON
        # reference is a static ACLE function: compile it in directly.
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sao_e0 (64x2).
#define HAVE_NEON 1
#define X265_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X265_NS x265
#include "../../third_party/x265/source/common/aarch64/loopfilter-prim.cpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

extern "C" void ${cand_sym}(uint8_t*, int8_t*, int8_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5A0E2026u);
    const int strides[4] = { 64, 65, 96, 128 };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        uint8_t src[4 * 128 + 16], w[4 * 128 + 16], g[4 * 128 + 16];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() & 0xFF);
        int8_t off[5];
        for (int j = 0; j < 5; j++)
            off[j] = (int8_t)(rng() % 33) - 16;
        int8_t sl[2] = { (int8_t)((int)(rng() % 3) - 1),
                         (int8_t)((int)(rng() % 3) - 1) };
        const intptr_t stride = strides[rng() % 4];
        memset(w, 0, sizeof(w)); memset(g, 0, sizeof(g));
        memcpy(w, src, sizeof(src));
        processSaoCUE0_neon(w, off, 64, sl, stride);
        memcpy(g, src, sizeof(src));
        ${cand_sym}(g, off, sl, stride);
        for (int r = 0; r < 2 && !mism; r++)
            for (int k = 0; k < 64; k++)
                if (w[r * stride + k] != g[r * stride + k])
                {
                    if (mism < 5)
                        fprintf(stderr,
                                "mismatch %d[%d]: ref=%d gen=%d\\n",
                                i, r * 64 + k, w[r * stride + k],
                                g[r * stride + k]);
                    mism++;
                    break;
                }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, cand_sym=cand["symbol"], cases=cases)
    if kind == "sao_b0":
        # SAO band offset, 64x4. Reference is the static ACLE NEON
        # processSaoCUB0_neon compiled in directly.
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sao_b0 (64x4).
#define HAVE_NEON 1
#define X265_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X265_NS x265
#include "../../third_party/x265/source/common/aarch64/loopfilter-prim.cpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

extern "C" void ${cand_sym}(uint8_t*, const int8_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5A0B2026u);
    const int strides[4] = { 64, 65, 96, 128 };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        uint8_t src[4 * 128 + 16], w[4 * 128 + 16], g[4 * 128 + 16];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() & 0xFF);
        int8_t off[32];
        for (int j = 0; j < 32; j++)
            off[j] = (int8_t)(rng() % 33) - 16;
        const intptr_t stride = strides[rng() % 4];
        memset(w, 0, sizeof(w)); memset(g, 0, sizeof(g));
        memcpy(w, src, sizeof(src));
        processSaoCUB0_neon(w, off, 64, 4, stride);
        memcpy(g, src, sizeof(src));
        ${cand_sym}(g, off, stride);
        for (int r = 0; r < 4; r++)
            for (int k = 0; k < 64; k++)
                if (w[r * stride + k] != g[r * stride + k])
                {
                    if (mism < 5)
                        fprintf(stderr,
                                "mismatch %d[%d]: ref=%d gen=%d\\n",
                                i, r * 64 + k, w[r * stride + k],
                                g[r * stride + k]);
                    mism++;
                    break;
                }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, cand_sym=cand["symbol"], cases=cases)
    if kind == "sao_e1":
        # SAO edge class 1 (vertical), 64x4. Reference is the static ACLE
        # processSaoCUE1_neon called per row (x265 usage).
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sao_e1 (64x4).
#define HAVE_NEON 1
#define X265_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X265_NS x265
#include "../../third_party/x265/source/common/aarch64/loopfilter-prim.cpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

extern "C" void ${cand_sym}(uint8_t*, int8_t*, int8_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5A1E2026u);
    const int strides[4] = { 64, 65, 96, 128 };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        uint8_t src[5 * 128 + 16], w[5 * 128 + 16], g[5 * 128 + 16];
        int8_t upw[128], upg[128];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() & 0xFF);
        int8_t off[5];
        for (int j = 0; j < 5; j++)
            off[j] = (int8_t)(rng() % 33) - 16;
        for (int j = 0; j < 128; j++)
        {
            upw[j] = (int8_t)(rng() % 3) - 1;
            upg[j] = upw[j];
        }
        const intptr_t stride = strides[rng() % 4];
        memset(w, 0, sizeof(w)); memset(g, 0, sizeof(g));
        memcpy(w, src, sizeof(src));
        for (int y = 0; y < 4; y++)
            processSaoCUE1_neon(w + y * stride, upw, off, stride, 64);
        memcpy(g, src, sizeof(src));
        ${cand_sym}(g, upg, off, stride);
        for (int r = 0; r < 4; r++)
            for (int k = 0; k < 64; k++)
                if (w[r * stride + k] != g[r * stride + k] ||
                    upw[k] != upg[k])
                {
                    if (mism < 5)
                        fprintf(stderr,
                                "mismatch %d[%d]: ref=%d gen=%d up=%d/%d\\n",
                                i, r * 64 + k, w[r * stride + k],
                                g[r * stride + k], upw[k], upg[k]);
                    mism++;
                    break;
                }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, cand_sym=cand["symbol"], cases=cases)
    if kind == "sao_e2":
        # SAO edge class 2 (diagonal), 64x1.
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sao_e2 (64x1).
#define HAVE_NEON 1
#define X265_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X265_NS x265
#include "../../third_party/x265/source/common/aarch64/loopfilter-prim.cpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

extern "C" void ${cand_sym}(
    uint8_t*, int8_t*, int8_t*, int8_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5A2E2026u);
    const int strides[4] = { 64, 65, 96, 128 };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        uint8_t src[2 * 128 + 16], w[2 * 128 + 16], g[2 * 128 + 16];
        int8_t btw[130], btg[130], b1w[130], b1g[130];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() & 0xFF);
        int8_t off[5];
        for (int j = 0; j < 5; j++)
            off[j] = (int8_t)(rng() % 33) - 16;
        for (int j = 0; j < 130; j++)
        {
            btw[j] = (int8_t)(rng() % 3) - 1; btg[j] = btw[j];
            b1w[j] = (int8_t)(rng() % 3) - 1; b1g[j] = b1w[j];
        }
        const intptr_t stride = strides[rng() % 4];
        memset(w, 0, sizeof(w)); memset(g, 0, sizeof(g));
        memcpy(w, src, sizeof(src));
        processSaoCUE2_neon(w, btw, b1w, off, 64, stride);
        memcpy(g, src, sizeof(src));
        ${cand_sym}(g, btg, b1g, off, stride);
        for (int k = 0; k < 64; k++)
            if (w[k] != g[k] || btw[k + 1] != btg[k + 1])
            {
                if (mism < 5)
                    fprintf(stderr,
                            "mismatch %d[%d]: ref=%d gen=%d bt=%d/%d\\n",
                            i, k, w[k], g[k], btw[k + 1], btg[k + 1]);
                mism++;
                break;
            }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, cand_sym=cand["symbol"], cases=cases)
    if kind == "sao_e3":
        # SAO edge class 3 (diagonal), 64x1, startX=0/endX=64.
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sao_e3 (64x1).
#define HAVE_NEON 1
#define X265_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X265_NS x265
#include "../../third_party/x265/source/common/aarch64/loopfilter-prim.cpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

extern "C" void ${cand_sym}(uint8_t*, int8_t*, int8_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5A3E2026u);
    const int strides[4] = { 64, 65, 96, 128 };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        uint8_t src[2 * 128 + 16], w[2 * 128 + 16], g[2 * 128 + 16];
        int8_t upw[130], upg[130];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() & 0xFF);
        int8_t off[5];
        for (int j = 0; j < 5; j++)
            off[j] = (int8_t)(rng() % 33) - 16;
        for (int j = 0; j < 130; j++)
        {
            upw[j] = (int8_t)(rng() % 3) - 1;
            upg[j] = upw[j];
        }
        const intptr_t stride = strides[rng() % 4];
        memset(w, 0, sizeof(w)); memset(g, 0, sizeof(g));
        memcpy(w, src, sizeof(src));
        processSaoCUE3_neon(w, upw, off, stride, 0, 64);
        memcpy(g, src, sizeof(src));
        ${cand_sym}(g, upg, off, stride);
        for (int k = 1; k < 64; k++)
            if (w[k] != g[k] || upw[k - 1] != upg[k - 1])
            {
                if (mism < 5)
                    fprintf(stderr,
                            "mismatch %d[%d]: ref=%d gen=%d up=%d/%d\\n",
                            i, k, w[k], g[k], upw[k - 1], upg[k - 1]);
                mism++;
                break;
            }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, cand_sym=cand["symbol"], cases=cases)
    if kind == "sao_e1_2rows":
        # SAO edge class 1, 2 rows (64x2).
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sao_e1_2rows.
#define HAVE_NEON 1
#define X265_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X265_NS x265
#include "../../third_party/x265/source/common/aarch64/loopfilter-prim.cpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

extern "C" void ${cand_sym}(uint8_t*, int8_t*, int8_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5A1E2026u);
    const int strides[4] = { 64, 65, 96, 128 };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        uint8_t src[3 * 128 + 16], w[3 * 128 + 16], g[3 * 128 + 16];
        int8_t upw[128], upg[128];
        for (int j = 0; j < (int)sizeof(src); j++)
            src[j] = (uint8_t)(rng() & 0xFF);
        int8_t off[5];
        for (int j = 0; j < 5; j++)
            off[j] = (int8_t)(rng() % 33) - 16;
        for (int j = 0; j < 128; j++)
        {
            upw[j] = (int8_t)(rng() % 3) - 1;
            upg[j] = upw[j];
        }
        const intptr_t stride = strides[rng() % 4];
        memset(w, 0, sizeof(w)); memset(g, 0, sizeof(g));
        memcpy(w, src, sizeof(src));
        processSaoCUE1_2Rows_neon(w, upw, off, stride, 64);
        memcpy(g, src, sizeof(src));
        ${cand_sym}(g, upg, off, stride);
        for (int r = 0; r < 2; r++)
            for (int k = 0; k < 64; k++)
                if (w[r * stride + k] != g[r * stride + k] ||
                    upw[k] != upg[k])
                {
                    if (mism < 5)
                        fprintf(stderr,
                                "mismatch %d[%d]: ref=%d gen=%d up=%d/%d\\n",
                                i, r * 64 + k, w[r * stride + k],
                                g[r * stride + k], upw[k], upg[k]);
                    mism++;
                    break;
                }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, cand_sym=cand["symbol"], cases=cases)
    if kind == "sao_stats_e0":
        # SAO stats edge class 0 (horizontal), 64x1.
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sao_stats_e0 (64x1).
#define HAVE_NEON 1
#define X265_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X265_NS x265
#include "../../third_party/x265/source/common/aarch64/sao-prim.cpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

extern "C" void ${cand_sym}(
    const int16_t*, const uint8_t*, intptr_t, int32_t*, int32_t*);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5A3E2026u);
    const int strides[4] = { ${strides_c} };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        int16_t diff[80];
        uint8_t buf[2 * 128 + 32];
        int32_t ws[5] = { 0 }, wc[5] = { 0 };
        int32_t gs[5] = { 0 }, gc[5] = { 0 };
        for (int j = 0; j < 80; j++)
            // Match PixelHarness sbuf2 range (SMAX = 1<<12): [-4097, 4094].
            diff[j] = (int16_t)(rng() % (2 * 4096 + 1)) - 4096 - 1;
        for (int j = 0; j < (int)sizeof(buf); j++)
            buf[j] = (uint8_t)(rng() & 0xFF);
        const intptr_t stride = strides[rng() % ${nstrides}];
        buf[16 - 1] = buf[16];  // rec[-1] = left neighbor of rec[0]
        X265_NS::saoCuStatsE0_neon(
            diff, buf + 16, stride, 64, 1, ws, wc);
        ${cand_sym}(diff, buf + 16, stride, gs, gc);
        for (int k = 0; k < 5; k++)
            if (ws[k] != gs[k] || wc[k] != gc[k])
            {
                if (mism < 5)
                    fprintf(stderr,
                            "mismatch %d[%d]: s=%d/%d c=%d/%d\\n",
                            i, k, ws[k], gs[k], wc[k], gc[k]);
                mism++;
                break;
            }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, cand_sym=cand["symbol"], cases=cases,
            strides_c=strides_c, nstrides=nstrides)
    if kind == "sao_stats_e1":
        # SAO stats edge class 1 (vertical), 64x1, with upBuff1 carry.
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sao_stats_e1 (64x1).
#define HAVE_NEON 1
#define X265_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X265_NS x265
#include "../../third_party/x265/source/common/aarch64/sao-prim.cpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

extern "C" void ${cand_sym}(
    const int16_t*, const uint8_t*, intptr_t, int8_t*, int32_t*, int32_t*);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5A6F2026u);
    const int strides[4] = { ${strides_c} };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        int16_t diff[80];
        uint8_t rec[3 * 128 + 16];
        int8_t upw[70], upg[70];
        int32_t ws[5] = { 0 }, wc[5] = { 0 };
        int32_t gs[5] = { 0 }, gc[5] = { 0 };
        for (int j = 0; j < 80; j++)
            // Match PixelHarness sbuf2 range (SMAX = 1<<12): [-4097, 4094].
            diff[j] = (int16_t)(rng() % (2 * 4096 + 1)) - 4096 - 1;
        for (int j = 0; j < (int)sizeof(rec); j++)
            rec[j] = (uint8_t)(rng() & 0xFF);
        for (int j = 0; j < 70; j++)
            upw[j] = upg[j] = (int8_t)(rng() % 3) - 1;
        const intptr_t stride = strides[rng() % ${nstrides}];
        X265_NS::saoCuStatsE1_neon(
            diff, rec, stride, upw, 64, 1, ws, wc);
        ${cand_sym}(diff, rec, stride, upg, gs, gc);
        for (int k = 0; k < 5; k++)
            if (ws[k] != gs[k] || wc[k] != gc[k])
            {
                if (mism < 5)
                    fprintf(stderr,
                            "mismatch %d[%d]: s=%d/%d c=%d/%d\\n",
                            i, k, ws[k], gs[k], wc[k], gc[k]);
                mism++;
                break;
            }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, cand_sym=cand["symbol"], cases=cases,
            strides_c=strides_c, nstrides=nstrides)
    if kind == "sao_stats_e2":
        # SAO stats edge class 2 (diagonal 135deg), 64x1.
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sao_stats_e2 (64x1).
#define HAVE_NEON 1
#define X265_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X265_NS x265
#include "../../third_party/x265/source/common/aarch64/sao-prim.cpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

extern "C" void ${cand_sym}(
    const int16_t*, const uint8_t*, intptr_t, int8_t*, int8_t*,
    int32_t*, int32_t*);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5A812026u);
    const int strides[4] = { ${strides_c} };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        int16_t diff[80];
        uint8_t rec[3 * 128 + 32];
        int8_t u1w[70], u1g[70], utw[70], utg[70];
        int32_t ws[5] = { 0 }, wc[5] = { 0 };
        int32_t gs[5] = { 0 }, gc[5] = { 0 };
        for (int j = 0; j < 80; j++)
            // Match PixelHarness sbuf2 range (SMAX = 1<<12): [-4097, 4094].
            diff[j] = (int16_t)(rng() % (2 * 4096 + 1)) - 4096 - 1;
        for (int j = 0; j < (int)sizeof(rec); j++)
            rec[j] = (uint8_t)(rng() & 0xFF);
        for (int j = 0; j < 70; j++)
            u1w[j] = u1g[j] = utw[j] = utg[j] = (int8_t)(rng() % 3) - 1;
        const intptr_t stride = strides[rng() % ${nstrides}];
        X265_NS::saoCuStatsE2_neon(
            diff, rec, stride, u1w, utw, 64, 1, ws, wc);
        ${cand_sym}(diff, rec, stride, u1g, utg, gs, gc);
        for (int k = 0; k < 5; k++)
            if (ws[k] != gs[k] || wc[k] != gc[k])
            {
                if (mism < 5)
                    fprintf(stderr,
                            "mismatch %d[%d]: s=%d/%d c=%d/%d\\n",
                            i, k, ws[k], gs[k], wc[k], gc[k]);
                mism++;
                break;
            }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, cand_sym=cand["symbol"], cases=cases,
            strides_c=strides_c, nstrides=nstrides)
    if kind == "sao_stats_e3":
        # SAO stats edge class 3 (diagonal 45deg), 64x1.
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sao_stats_e3 (64x1).
#define HAVE_NEON 1
#define X265_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X265_NS x265
#include "../../third_party/x265/source/common/aarch64/sao-prim.cpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

extern "C" void ${cand_sym}(
    const int16_t*, const uint8_t*, intptr_t, int8_t*, int32_t*, int32_t*);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5A9F2026u);
    const int strides[4] = { ${strides_c} };

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        int16_t diff[80];
        uint8_t rec[3 * 128 + 32];
        int8_t upw[70], upg[70];
        int32_t ws[5] = { 0 }, wc[5] = { 0 };
        int32_t gs[5] = { 0 }, gc[5] = { 0 };
        for (int j = 0; j < 80; j++)
            // Match PixelHarness sbuf2 range (SMAX = 1<<12): [-4097, 4094].
            diff[j] = (int16_t)(rng() % (2 * 4096 + 1)) - 4096 - 1;
        for (int j = 0; j < (int)sizeof(rec); j++)
            rec[j] = (uint8_t)(rng() & 0xFF);
        for (int j = 0; j < 70; j++)
            upw[j] = upg[j] = (int8_t)(rng() % 3) - 1;
        const intptr_t stride = strides[rng() % ${nstrides}];
        X265_NS::saoCuStatsE3_neon(
            diff, rec, stride, upw + 1, 64, 1, ws, wc);
        ${cand_sym}(diff, rec, stride, upg + 1, gs, gc);
        for (int k = 0; k < 5; k++)
            if (ws[k] != gs[k] || wc[k] != gc[k])
            {
                if (mism < 5)
                    fprintf(stderr,
                            "mismatch %d[%d]: s=%d/%d c=%d/%d\\n",
                            i, k, ws[k], gs[k], wc[k], gc[k]);
                mism++;
                break;
            }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, cand_sym=cand["symbol"], cases=cases,
            strides_c=strides_c, nstrides=nstrides)
    if kind == "sao_stats_bo":
        # SAO stats band offset, 64x1 (32 classes).
        t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes, shape: sao_stats_bo (64x1).
#define HAVE_NEON 1
#define X265_DEPTH 8
#define HIGH_BIT_DEPTH 0
#define X265_NS x265
#include "../../third_party/x265/source/common/aarch64/sao-prim.cpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

extern "C" void ${cand_sym}(
    const int16_t*, const uint8_t*, intptr_t, int32_t*, int32_t*);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0) { perror("prctl(PR_SVE_SET_VL)"); return 77; }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0x5ABD2026u);

    long mism = 0;
    for (int i = 0; i < cases; i++)
    {
        int16_t diff[80];
        uint8_t rec[2 * 128 + 16];
        int32_t ws[32] = { 0 }, wc[32] = { 0 };
        int32_t gs[32] = { 0 }, gc[32] = { 0 };
        for (int j = 0; j < 80; j++)
            // Match PixelHarness sbuf2 range (SMAX = 1<<12): [-4097, 4094].
            diff[j] = (int16_t)(rng() % (2 * 4096 + 1)) - 4096 - 1;
        for (int j = 0; j < (int)sizeof(rec); j++)
            rec[j] = (uint8_t)(rng() & 0xFF);
        X265_NS::saoCuStatsBO_neon(
            diff, rec, 64, 64, 1, ws, wc);
        ${cand_sym}(diff, rec, 64, gs, gc);
        for (int k = 0; k < 32; k++)
            if (ws[k] != gs[k] || wc[k] != gc[k])
            {
                if (mism < 5)
                    fprintf(stderr,
                            "mismatch %d[%d]: s=%d/%d c=%d/%d\\n",
                            i, k, ws[k], gs[k], wc[k], gc[k]);
                mism++;
                break;
            }
    }
    printf("cases=%d mismatches=%ld\\n", cases, mism);
    return mism != 0;
}
""")
        return t.substitute(
            path=manifest["_path"], contract=contract,
            vl=vl, cand_sym=cand["symbol"], cases=cases)
    if contract == "legacy-internal-exact":
        # Spec-defined legacy oracle (no internal code): pass2 E/O wrap in
        # s16, narrowing rounds then saturates (sqrshrnb semantics).
        ref_decl = ""
        oracle = """\
static inline int16_t sat_rnd(int64_t v, int shift)
{
    // sqrshrnb semantics: round-to-nearest with ties toward +inf,
    // i.e. floor((v + half) / 2^shift), then saturate.
    const int64_t s = (v + (1LL << (shift - 1))) >> shift;
    if (s > 32767) return 32767;
    if (s < -32768) return -32768;
    return (int16_t)s;
}

static const int16_t LG[16][16] = {
    {64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64},
    {90,87,80,70,57,43,25,9,-9,-25,-43,-57,-70,-80,-87,-90},
    {89,75,50,18,-18,-50,-75,-89,-89,-75,-50,-18,18,50,75,89},
    {87,57,9,-43,-80,-90,-70,-25,25,70,90,80,43,-9,-57,-87},
    {83,36,-36,-83,-83,-36,36,83,83,36,-36,-83,-83,-36,36,83},
    {80,9,-70,-87,-25,57,90,43,-43,-90,-57,25,87,70,-9,-80},
    {75,-18,-89,-50,50,89,18,-75,-75,18,89,50,-50,-89,-18,75},
    {70,-43,-87,9,90,25,-80,-57,57,80,-25,-90,-9,87,43,-70},
    {64,-64,-64,64,64,-64,-64,64,64,-64,-64,64,64,-64,-64,64},
    {57,-80,-25,90,-9,-87,43,70,-70,-43,87,9,-90,25,80,-57},
    {50,-89,18,75,-75,-18,89,-50,-50,89,-18,-75,75,18,-89,50},
    {43,-90,57,25,-87,70,9,-80,80,-9,-70,87,-25,-57,90,-43},
    {36,-83,83,-36,-36,83,-83,36,36,-83,83,-36,-36,83,-83,36},
    {25,-70,90,-80,43,9,-57,87,-87,57,-9,-43,80,-90,70,-25},
    {18,-50,75,-89,89,-75,50,-18,-18,50,-75,89,-89,75,-50,18},
    {9,-25,43,-57,70,-80,87,-90,90,-87,80,-70,57,-43,25,-9},
};

static void legacy_dct16(const int16_t* src, int16_t* dst, intptr_t stride)
{
    int16_t coef[256];
    for (int k = 0; k < 16; k++)
        for (int i = 0; i < 16; i++)
        {
            int16_t E[8], O[8];
            for (int j = 0; j < 8; j++)
            {
                int16_t lo = src[i * stride + j];
                int16_t hi = src[i * stride + 15 - j];
                E[j] = (int16_t)(lo + hi);
                O[j] = (int16_t)(lo - hi);
            }
            int64_t s = 0;
            for (int j = 0; j < 8; j++)
                s += (int64_t)LG[k][j] * ((k & 1) ? O[j] : E[j]);
            coef[k * 16 + i] = sat_rnd(s, 3);
        }
    for (int k = 0; k < 16; k++)
        for (int i = 0; i < 16; i++)
        {
            int16_t E[8], O[8];
            for (int j = 0; j < 8; j++)
            {
                int16_t lo = coef[i * 16 + j];
                int16_t hi = coef[i * 16 + 15 - j];
                E[j] = (int16_t)(lo + hi);
                O[j] = (int16_t)(lo - hi);
            }
            int64_t s = 0;
            for (int j = 0; j < 8; j++)
                s += (int64_t)LG[k][j] * ((k & 1) ? O[j] : E[j]);
            dst[k * 16 + i] = sat_rnd(s, 10);
        }
}
"""
        ref_call = "legacy_dct16"
    t = string.Template("""\
// Generated by tools/gen_verify.py from ${path} -- do not edit by hand.
// Contract: ${contract}, fixed VL=${vl} bytes.
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <sys/prctl.h>

${decl}

${oracle}

extern "C" void ${cand_sym}(const int16_t*, int16_t*, intptr_t);

int main(int argc, char** argv)
{
#ifndef PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
#endif
    const int vl = prctl(PR_SVE_SET_VL, ${vl}, 0, 0, 0, 0);
    if (vl < 0)
    {
        perror("prctl(PR_SVE_SET_VL)");
        return 77;
    }
    if (vl != ${vl})
    {
        fprintf(stderr, "prctl returned VL=%d bytes, contract requires ${vl}\\n",
                vl);
        return 78;
    }

    const int cases = argc > 1 ? atoi(argv[1]) : ${cases};
    std::mt19937 rng(0xD16C2026u);
    const int strides[${nstrides}] = { ${strides_c} };

    long mism = 0, total = 0;
    int first_k = -1;
    int16_t first_want = 0, first_got = 0;
    for (int i = 0; i < cases; i++)
    {
        const int stride = strides[rng() % ${nstrides}];
        int16_t buf[${n} * 32 + ${n}];
        for (int j = 0; j < (int)(sizeof(buf) / sizeof(buf[0])); j++)
            buf[j] = (int16_t)((int)(rng() % (${hi} - ${lo} + 1)) + ${lo});

        int16_t want[${n_out}], got[${n_out}];
        ${ref_call}(buf, want, stride);
        memset(got, 0, sizeof(got));
        ${cand_sym}(buf, got, stride);
        total += ${n_out};
        for (int k = 0; k < ${n_out}; k++)
            if (want[k] != got[k])
            {
                mism++;
                if (first_k < 0)
                {
                    first_k = k;
                    first_want = want[k];
                    first_got = got[k];
                }
            }
    }
    printf("cases=%d lanes=%ld mismatches=%ld rate=%f%%\\n",
           cases, total, mism, 100.0 * mism / total);
    if (first_k >= 0)
        printf(" first-diff idx=%d want=%d got=%d\\n",
               first_k, first_want, first_got);
    return mism != 0;
}
"""
    )
    return t.substitute(
        path=manifest["_path"], contract=contract,
        vl=vl, decl=ref_decl, oracle=oracle, cand_sym=cand["symbol"],
        cases=cases, nstrides=nstrides, strides_c=strides_c,
        n=n, n_out=n_out, hi=hi, lo=lo, ref_call=ref_call)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default="kernels/dct16/manifest.yaml")
    ap.add_argument("--out", default="build/dct16_generated_verify.cpp")
    ap.add_argument("--contract", default=None)
    args = ap.parse_args()
    manifest = load_manifest(
        os.path.basename(os.path.dirname(args.manifest)))
    if args.contract:
        manifest["contract"] = args.contract
    src = generate(manifest)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(src)
    print("wrote %s" % args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
