"""Generic MachineIR -> SVE2 candidate emitter (docs/40 M3, /goal).

Recipe registry: each recipe declares (a) a MachineIR op-signature
detector and (b) an SVE2 ACLE lowering. The emitter consumes only the
imported MachineIR JSON of the seed -- no per-kernel hand-written emitter.
The search layer consumes the emitted source through the normal
verify/trace/MCA funnel (`search_sve2_layouts.py --backend gen`).

Recipes so far:
  diff-sum   (sad 16/16/32): uabd + uaddlv per row -> svld1/svabd/svaddv.

Adding a recipe = register a (name, detect, emit) triple; family members
covered by the same recipe need no emitter code at all.
"""

import json
import os
import re
import sys

try:
    import yaml
except ImportError:
    yaml = None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# kernel name -> seed recipe name (kernel dirs may cover several shapes).
_RECIPE_ALIAS = {
    "sad": "sad-16x16",
    "sad-32": "sad-32x32",
    "sa8d": "sa8d-8x8",
    "sa8d16": "sa8d-16x16",
    "interp8": "interp8-8x8",
    "interp8-16": "interp8-16x16",
    "interp8-32": "interp8-32x32",
    "interp4": "interp4-16x16",
    "interp4-8": "interp4-8x8",
    "interp4-32": "interp4-32x32",
    "satd-8": "satd-8x8",
    "satd-4": "satd-4x4",
    "satd-16": "satd-16x16",
}


def _load_machine_ir(kernel):
    """Load the seed MachineIR JSON declared by seeds/<kernel>.yaml."""
    recipe_name = _RECIPE_ALIAS.get(kernel, kernel)
    recipe_path = os.path.join(ROOT, "seeds", recipe_name + ".yaml")
    if yaml is None or not os.path.exists(recipe_path):
        # fall back to the canonical m30 layout for known kernels
        alt = os.path.join(
            ROOT, "experiments", "m30-%s-search" % kernel,
            "imported", "machine-ir.json")
        if os.path.exists(alt):
            return json.load(open(alt))
        raise ValueError("no MachineIR for kernel %r" % kernel)
    recipe = yaml.safe_load(open(recipe_path))
    out = recipe["output"]["json"]
    path = out if os.path.isabs(out) else os.path.join(ROOT, out)
    if not os.path.exists(path):
        raise ValueError("MachineIR not found: %s" % path)
    return json.load(open(path))


def detect_diff_sum(machine_ir):
    """Diff-sum signature: uabd+uaddlv (sad 16/32)."""
    intr = {n.get("intrinsic") for n in machine_ir["nodes"]
            if n.get("op") == "intrinsic"}
    if "uabd" in intr and "uaddlv" in intr:
        return True
    return False


def detect_hadamard(machine_ir):
    """Hadamard butterfly signature: sabd+abs+umax+uaddlv (sa8d 8x8).
    16x16 reduces with uaddlp + vecreduce_add instead of uaddlv."""
    intr = {n.get("intrinsic") for n in machine_ir["nodes"]
            if n.get("op") == "intrinsic"}
    if {"sabd", "abs", "umax"} <= intr:
        if "uaddlv" in intr or ("uaddlp" in intr and
                                "vecreduce_add" in intr):
            return True
    return False


def detect_fir(machine_ir):
    """FIR signature: dot-product / tbl / narrowing (interp8/4).
    Recognized but not yet lowered (recipe gap)."""
    intr = {n.get("intrinsic") for n in machine_ir["nodes"]
            if n.get("op") == "intrinsic"}
    return "sdot" in intr or "sqrshrn" in intr


def detect_family(machine_ir):
    """Return the first matching recipe name, or None."""
    for name, rec in RECIPES.items():
        if rec["detect"](machine_ir):
            return name
    return None


def _row_offset(addr_rhs, row_vars):
    """Parse `getelementptr ... i8, ptr %base, i64 %expr` and return the
    expression as a C string over row variables (r), or None."""
    m = re.search(r"i64\s+%([A-Za-z0-9._]+)", addr_rhs)
    if not m:
        return None
    return m.group(1)


def emit_diff_sum(machine_ir, func_name):
    """Emit SVE2 ACLE for the diff-sum family (sad shape: 4 args)."""
    nodes = machine_ir["nodes"]
    uabd_rows = 0
    max_row = -1
    row_offs = set()
    for n in nodes:
        if n.get("op") == "intrinsic" and n.get("intrinsic") == "uabd":
            uabd_rows += 1
    # derive the row count from the row-offset expression magnitudes:
    # seeds unroll r*stride as shl/mul chains; take the max constant
    # multiplier seen in shl/mul nodes feeding addr nodes.
    for n in nodes:
        if n.get("op") in ("shl", "mul") and n.get("amt") is not None:
            max_row = max(max_row, n.get("amt"))
        if n.get("op") == "mul" and n.get("const") is not None:
            max_row = max(max_row, n.get("const"))
    # row count comes from the max row-offset multiplier (the seed may
    # process several uabd groups per row, e.g. 32x32 halves); fall back
    # to the uabd count only when no offset constants are visible.
    rows = max_row + 1 if max_row >= 0 else uabd_rows
    if rows <= 0:
        raise ValueError("diff-sum emitter: could not derive row count")
    groups = max(1, uabd_rows // rows)
    width = 16 * groups
    lines = [
        "// Generated by tools/gen_sve2_emit.py (generic diff-sum recipe)",
        "#include <arm_sve.h>",
        "#include <stdint.h>",
        "",
        "extern \"C\" int %s(const uint8_t* a, intptr_t sa,"
        " const uint8_t* b, intptr_t sb)" % func_name,
        "{",
        "    const svbool_t p = svwhilelt_b8((uint32_t)0,"
        " (uint32_t)%d);" % width,
        "    uint64_t total = 0;",
        "    for (int r = 0; r < %d; r++)" % rows,
        "    {",
        "        svuint8_t x = svld1_u8(p, a + r * sa);",
        "        svuint8_t y = svld1_u8(p, b + r * sb);",
        "        svuint8_t d = svabd_u8_x(p, x, y);",
        "        total += svaddv_u8(p, d);",
    ]
    lines.extend([
        "    }",
        "    return (int)total;",
        "}",
    ])
    return "\n".join(lines) + "\n"


def _fir_derived(machine_ir):
    """Derive (rows, groups, prec, taps, load_off, filter_name) from the
    FIR MachineIR.

    rows = max dst row-stride multiplier + 1 (from store addr chains);
    groups = stores / rows (each store is one 8-output group); prec from
    the sqrshrun immediate; taps from the coefficient load type;
    load_off from the first src addr constant; filter from the global."""
    nodes = machine_ir["nodes"]
    stores = [n for n in nodes if n.get("op") == "store"]
    addrs = {n["dst"]: n for n in nodes if n.get("op") == "addr"}
    env = {"1": ("sa", 1), "3": ("sb", 1),
           "i_pix1": ("sa", 1), "i_pix2": ("sb", 1)}
    ptr_off = {}
    for n in nodes:
        if n.get("op") in ("shl", "mul"):
            src = n["src"][0]
            if src in env:
                sym, coef = env[src]
                amt = n.get("amt") if n.get("op") == "shl" \
                    else n.get("const")
                if amt is not None:
                    env[n["dst"]] = (sym, coef * (1 << amt)
                                     if n.get("op") == "shl"
                                     else coef * amt)
        elif n.get("op") == "addr":
            mb = re.search(r"ptr\s+%([A-Za-z0-9._]+),", n["rhs"])
            mi = re.search(r"i64\s+%([A-Za-z0-9._]+)", n["rhs"])
            mc = re.search(r"i64\s+(-?\d+)\s*$", n["rhs"])
            if not mb:
                continue
            base = mb.group(1)
            root, prev, prevb = ptr_off.get(base, (base, 0, 0))
            if mc:
                ptr_off[n["dst"]] = (root, prev, prevb + int(mc.group(1)))
            elif mi and mi.group(1) in env:
                ptr_off[n["dst"]] = (root, prev + env[mi.group(1)][1],
                                     prevb)
    maxrow = -1
    for s in stores:
        base, coef, byte = ptr_off.get(s["ptr"], (s["ptr"], 0, 0))
        if base in ("2", "dst"):
            maxrow = max(maxrow, coef)
    rows = maxrow + 1 if maxrow >= 0 else len(stores)
    store_lanes = 8
    for s in stores:
        m = re.match(r"<(\d+) x i\d+>", s.get("type", ""))
        if m:
            store_lanes = max(store_lanes, int(m.group(1)))
    groups = (store_lanes // 8) * (len(stores) // rows if rows else 1)
    prec = 6
    taps = 8
    load_off = -3
    filter_name = "g_lumaFilter"
    for n in nodes:
        if n.get("op") == "intrinsic" and n.get("intrinsic") == "sqrshrun":
            imm = next((a.get("imm") for a in n.get("args", [])
                        if isinstance(a, dict) and "imm" in a), prec)
            prec = int(imm)
        if n.get("op") == "load" and n.get("type") == "<4 x i16>":
            taps = 4
        if n.get("op") == "addr" and "g_chromaFilter" in n.get("rhs", ""):
            filter_name = "g_chromaFilter"
        if n.get("op") == "addr":
            moff = re.search(r"i8,\s*ptr\s+%[0-9A-Za-z._]+,\s*i64\s+(-?\d+)",
                             n["rhs"])
            if moff and n.get("id", 0) < 8:
                load_off = int(moff.group(1))
    return rows, groups, prec, taps, load_off, filter_name


def emit_fir(machine_ir, func_name):
    """Generic 8-tap FIR (interp8 hpp) transliteration to SVE2 ACLE.

    Mirrors x265 interp8_horiz_pp_dotprod semantics:
      out[c] = sat_u8(round(SUM_k coeff[phase][k] * (src[c-3+k]-128) / 2^prec
                            + 64*128))
    via the shared sliding-window permute + 4-way svdot_s32 structure.
    Coefficients come from the x265 source constant tables (generic).
    """
    rows, groups, prec, taps, load_off, filter_name = _fir_derived(
        machine_ir)
    sys.path.insert(0, os.path.join(ROOT, "tools"))
    from extract_x265_constants import parse_int16_tables  # noqa: E402
    cpp = os.path.join(ROOT, "third_party/x265/source/common/constants.cpp")
    tables = parse_int16_tables(open(cpp).read())
    gf = tables[filter_name]["rows"]
    if filter_name == "g_chromaFilter":
        phases = gf
    else:
        phases = gf[1:4]
    ctable = ",\n".join(
        "        { %s }" % ", ".join(str(v) for v in row) for row in phases)

    # sliding-window index patterns for 4-output groups:
    # taps=8 -> 3 perm vectors (X0/X1/X2); taps=4 -> 2 (X0/X1).
    if taps == 8:
        idx = [
            [0, 1, 2, 3, 1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6],
            [4, 5, 6, 7, 5, 6, 7, 8, 6, 7, 8, 9, 7, 8, 9, 10],
            [8, 9, 10, 11, 9, 10, 11, 12, 10, 11, 12, 13, 11, 12, 13, 14],
        ]
        bs = [[0, 1, 2, 3] * 4, [4, 5, 6, 7] * 4]
    else:
        idx = [
            [0, 1, 2, 3, 1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6],
            [4, 5, 6, 7, 5, 6, 7, 8, 6, 7, 8, 9, 7, 8, 9, 10],
        ]
        bs = [[0, 1, 2, 3] * 4]

    def c16(name, vals):
        return ("static const uint8_t %s[16] = { %s };" %
                (name, ", ".join(str(v) for v in vals)))

    lines = [
        "// Generated by tools/gen_sve2_emit.py (generic fir recipe)",
        "#include <arm_sve.h>",
        "#include <arm_neon.h>",
        "#include <arm_neon_sve_bridge.h>",
        "#include <stdint.h>",
        "",
        "static const int16_t CTBL[%d][%d] = {" % (len(phases), taps),
        ctable,
        "};",
        c16("IDX0", idx[0]),
        c16("IDX1", idx[1]),
    ]
    if taps == 8:
        lines.append(c16("IDX2", idx[2]))
    lines.extend([
        c16("IDX_B0", bs[0]),
    ])
    if taps == 8:
        lines.append(c16("IDX_B1", bs[1]))
    lines.extend([
        "",
        "extern \"C\" void %s(const uint8_t* src, intptr_t srcStride,"
        " uint8_t* dst, intptr_t dstStride, int coeffIdx)" % func_name,
        "{",
        "    const svbool_t p16 = svptrue_b16();",
        "    const svbool_t pg16b = svwhilelt_b8((uint32_t)0, (uint32_t)16);",
        "    const svbool_t pg8 = svwhilelt_b8((uint32_t)0, (uint32_t)8);",
        "    const svbool_t pg8h = svwhilelt_b16((uint32_t)0, (uint32_t)8);",
        "    const svbool_t pg4 = svwhilelt_b16((uint32_t)0, (uint32_t)4);",
    ])
    if filter_name == "g_chromaFilter":
        lines.append(
            "    const int ph = (coeffIdx >= 0 && coeffIdx <= 7) ?"
            " coeffIdx : 0;")
    else:
        lines.append(
            "    const int ph = (coeffIdx >= 1 && coeffIdx <= 3) ?"
            " coeffIdx : 2;")
    if filter_name == "g_chromaFilter":
        lines.append("    const svint16_t f16 = svld1_s16(pg8h, CTBL[ph]);")
    else:
        lines.append(
            "    const svint16_t f16 = svld1_s16(pg8h, CTBL[ph - 1]);")
    lines.extend([
        "    const svint8_t f8 = svset_neonq_s8(svundef_s8(),",
        "        vcombine_s8(vmovn_s16(svget_neonq_s16(f16)),"
        " vdup_n_s8(0)));",
        "    const svint8_t b0 = svtbl_s8(f8,"
        " svld1_u8(svptrue_b8(), IDX_B0));",
        "    const svuint8_t ix0 = svld1_u8(svptrue_b8(), IDX0);",
        "    const svuint8_t ix1 = svld1_u8(svptrue_b8(), IDX1);",
        "    const svint32_t c8192 = svdup_n_s32(64 * 128);",
    ])
    if taps == 8:
        lines.extend([
            "    const svint8_t b1 = svtbl_s8(f8,"
            " svld1_u8(svptrue_b8(), IDX_B1));",
            "    const svuint8_t ix2 = svld1_u8(svptrue_b8(), IDX2);",
        ])
    lines.extend([
        "    for (int r = 0; r < %d; r++)" % rows,
        "    {",
        "        for (int g = 0; g < %d; g++)" % groups,
        "        {",
        "            svuint8_t s = svld1_u8(pg16b,"
        " src + r * srcStride %s + g * 8);" % load_off,
        "            svint8_t s8 = svreinterpret_s8_u8(",
        "                svsub_u8_x(pg16b, s, svdup_n_u8(128)));",
        "            svint8_t p0 = svtbl_s8(s8, ix0);",
        "            svint8_t p1 = svtbl_s8(s8, ix1);",
        "            svint32_t lo = svdot_s32(c8192, p0, b0);",
        "            svint32_t hi = svdot_s32(c8192, p1, b0);",
    ])
    if taps == 8:
        lines.extend([
            "            svint8_t p2 = svtbl_s8(s8, ix2);",
            "            lo = svdot_s32(lo, p1, b1);",
            "            hi = svdot_s32(hi, p2, b1);",
        ])
    lines.extend([
        "            int16x8_t dot = vcombine_s16(",
        "                vmovn_s32(svget_neonq_s32(lo)),",
        "                vmovn_s32(svget_neonq_s32(hi)));",
        "            uint8x8_t out = vqrshrun_n_s16(dot, %d);" % prec,
        "            svuint8_t outv = svset_neonq_u8(svundef_u8(),"
        " vcombine_u8(out, vdup_n_u8(0)));",
        "            svst1_u8(pg8, dst + r * dstStride + g * 8, outv);",
        "        }",
        "    }",
        "}",
    ])
    return "\n".join(lines) + "\n"


def emit_hadamard(machine_ir, func_name):
    """Straight-line transliteration of the sa8d 8x8 Hadamard DAG to SVE2
    ACLE (docs/40 §7 recipe protocol; naive pack=1, correctness first).

    Data is kept in the low 8 lanes of 16-lane s16 registers (inactive
    lanes are zeroed by predicated loads); only the final reduction is
    predicated to the 8 active lanes. NEON 8-lane trn1/trn2 maps to
    svzip1/svtrn2 of the 16-lane SVE vectors (low-8-lane equivalence).
    """
    nodes = machine_ir["nodes"]
    nd = {}
    for n in nodes:
        nd[n.get("dst")] = n

    lines = [
        "// Generated by tools/gen_sve2_emit.py (generic hadamard recipe)",
        "#include <arm_sve.h>",
        "#include <arm_neon.h>",
        "#include <arm_neon_sve_bridge.h>",
        "#include <stdint.h>",
        "",
        "extern \"C\" int %s(const uint8_t* pix1, intptr_t sa,"
        " const uint8_t* pix2, intptr_t sb)" % func_name,
        "{",
        "    const svbool_t pg8 = svwhilelt_b8((uint32_t)0, (uint32_t)8);",
        "    const svbool_t pg16b = svwhilelt_b8((uint32_t)0, (uint32_t)16);",
        "    const svbool_t pg8h = svwhilelt_b16((uint32_t)0, (uint32_t)8);",
        "    const svbool_t pg4w = svwhilelt_b32((uint32_t)0, (uint32_t)4);",
        "    const svbool_t p16 = svptrue_b16();",
        "    const svbool_t pg4 = svwhilelt_b16((uint32_t)0, (uint32_t)4);",
        "    static const uint16_t ROT4[16] ="
        " { 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3 };",
        "    const svuint16_t rot4 = svld1_u16(p16, ROT4);",
    ]
    env = {}
    vtypes = {}
    counter = [0]

    def var(dst):
        if dst not in env:
            env[dst] = "v%d" % counter[0]
            counter[0] += 1
        return env[dst]

    def setvar(dst, ctype):
        vtypes[var(dst)] = ctype

    def as_s16(v):
        return v if vtypes.get(v) == "svint16_t" \
            else "svreinterpret_s16_u16(%s)" % v

    def as_u16(v):
        return v if vtypes.get(v) == "svuint16_t" \
            else "svreinterpret_u16_s16(%s)" % v

    def as_s32(v):
        return v if vtypes.get(v) == "svint32_t" \
            else "svreinterpret_s32_u32(%s)" % v

    def as_u32(v):
        return v if vtypes.get(v) == "svuint32_t" \
            else "svreinterpret_u32_s32(%s)" % v

    def emit(node, line):
        lines.append("    %s" % line)

    # scalar address env: (var, coef) over the stride symbols.
    for name, sym in (("i_pix1", "sa"), ("i_pix2", "sb"),
                      ("%i_pix1", "sa"), ("%i_pix2", "sb")):
        env[name] = (sym, 1)

    def stride_env(src):
        if src in ("i_pix1", "%i_pix1", "1"):
            return ("sa", 1)
        if src in ("i_pix2", "%i_pix2", "3"):
            return ("sb", 1)
        return None

    ptr_off = {}

    for n in nodes:
        op = n["op"]
        dst = n.get("dst")
        if op == "load":
            ptr = n["ptr"]
            base, coef, byte = ptr_off.get(ptr, (ptr, 0, 0))
            if base not in ("pix1", "pix2", "0", "2"):
                raise ValueError(
                    "hadamard: unknown load base %r" % base)
            abi = "pix1" if base in ("pix1", "0") else "pix2"
            stride = "sa" if abi == "pix1" else "sb"
            if n.get("type") in ("i8", "i16", "i32", "i64"):
                ctyp = {"i8": "uint8_t", "i16": "uint16_t",
                        "i32": "uint32_t",
                        "i64": "uint64_t"}[n["type"]]
                emit(n, "%s %s = *(const %s*)((const uint8_t*)%s +"
                     " %d * %s + %d);"
                     % (ctyp, var(dst), ctyp, abi, coef, stride, byte))
                setvar(dst, ctyp)
                continue
            t = "svuint8_t"
            pg = "pg8" if n.get("type") == "<8 x i8>" else "pg16b"
            if byte:
                emit(n, "%s %s = svld1_u8(%s, %s + %d * %s + %d);"
                     % (t, var(dst), pg, abi, coef, stride, byte))
            else:
                emit(n, "%s %s = svld1_u8(%s, %s + %d * %s);"
                     % (t, var(dst), pg, abi, coef, stride))
            setvar(dst, t)
        elif op == "addr":
            mi = re.search(r"i64\s+%([A-Za-z0-9._]+)", n["rhs"])
            mb = re.search(r"ptr\s+%([A-Za-z0-9._]+),", n["rhs"])
            mc = re.search(r"i64\s+(-?\d+)\s*$", n["rhs"])
            if not mb:
                raise ValueError("hadamard: non-dynamic addr %r" % n["rhs"])
            base = mb.group(1)
            root, prev, prevb = ptr_off.get(base, (base, 0, 0))
            if mc:
                ptr_off[dst] = (root, prev, prevb + int(mc.group(1)))
            else:
                if not mi:
                    raise ValueError("hadamard: addr without offset %r"
                                     % n["rhs"])
                coef = env.get(mi.group(1)) or stride_env(mi.group(1))
                if not isinstance(coef, tuple):
                    raise ValueError("hadamard: unresolved addr index %r"
                                     % mi.group(1))
                ptr_off[dst] = (root, prev + coef[1], prevb)
        elif op in ("shl", "mul"):
            src = n["src"][0]
            sv = env.get(src) or stride_env(src)
            if isinstance(sv, tuple):
                sym, coef = sv
                amt = n.get("amt") if op == "shl" else n.get("const")
                if amt is None:
                    raise ValueError("hadamard: non-const %s" % op)
                env[dst] = (sym, coef * (1 << amt) if op == "shl"
                            else coef * amt)
            else:
                raise ValueError("hadamard: unexpected %s on %r" % (op, src))
        elif op == "zext" and n.get("type") == "<8 x i16>":
            emit(n, "svuint16_t %s = svunpklo_u16(%s);"
                 % (var(dst), var(n["src"])))
            setvar(dst, "svuint16_t")
        elif op == "insertelement":
            srcs = n.get("src") or []
            idx = n.get("index", 0)
            if not srcs:
                raise ValueError("hadamard: empty insertelement")
            val = var(srcs[-1])
            if len(srcs) == 1:
                prev = "vdupq_n_u32(0)"
            else:
                prev = "svget_neonq_u32(%s)" % var(srcs[0])
            emit(n, "svuint32_t %s = svset_neonq_u32(svundef_u32(),"
                 " vsetq_lane_u32((uint32_t)%s, %s, %d));"
                 % (var(dst), val, prev, idx))
            setvar(dst, "svuint32_t")
        elif op in ("add", "sub") and str(n.get("type", "")).startswith("<"):
            vtype = n["type"]
            if vtype == "<8 x i16>":
                f = "svadd_s16_x(p16, %s, %s)" if op == "add" \
                    else "svsub_s16_x(p16, %s, %s)"
                t = "svint16_t"
            elif vtype == "<4 x i32>":
                f = "svadd_s32_x(p16, %s, %s)" if op == "add" \
                    else "svsub_s32_x(p16, %s, %s)"
                t = "svint32_t"
            else:
                raise ValueError("hadamard: unsupported vec %s %s"
                                 % (op, vtype))
            if vtype == "<4 x i32>":
                a, b = as_s32(var(n["src"][0])), as_s32(var(n["src"][1]))
            else:
                a, b = as_s16(var(n["src"][0])), as_s16(var(n["src"][1]))
            emit(n, "%s %s = %s;" % (t, var(dst), f % (a, b)))
            setvar(dst, t)
        elif op == "shuffle":
            vtype = n["type"]
            mask = n["mask"]
            if vtype == "<8 x i8>" and len(n.get("src") or []) == 1:
                src = var(n["src"][0])
                if tuple(mask) == (0, 1, 2, 3, 4, 5, 6, 7):
                    emit(n, "svuint8_t %s = svset_neonq_u8(svundef_u8(),"
                         " vcombine_u8(vget_low_u8(svget_neonq_u8(%s)),"
                         " vdup_n_u8(0)));" % (var(dst), src))
                    setvar(dst, "svuint8_t")
                    continue
                if tuple(mask) == (8, 9, 10, 11, 12, 13, 14, 15):
                    emit(n, "svuint8_t %s = svset_neonq_u8(svundef_u8(),"
                         " vcombine_u8(vget_high_u8(svget_neonq_u8(%s)),"
                         " vdup_n_u8(0)));" % (var(dst), src))
                    setvar(dst, "svuint8_t")
                    continue
            a, b = var(n["src"][0]), var(n["src"][1])
            fn = {
                "<8 x i16>": {
                    (0, 8, 2, 10, 4, 12, 6, 14): ("svtrn1_s16", "svint16_t"),
                    (1, 9, 3, 11, 5, 13, 7, 15): ("svtrn2_s16", "svint16_t"),
                },
                "<4 x i32>": {
                    (0, 4, 2, 6): ("svtrn1_s32", "svint32_t"),
                    (1, 5, 3, 7): ("svtrn2_s32", "svint32_t"),
                },
                "<2 x i64>": {
                    (0, 2): None,
                    (1, 3): None,
                },
            }.get(vtype, {})
            key = tuple(mask)
            if vtype == "<8 x i16>" and key == (0, 1, 2, 3, 8, 9, 10, 11):
                # concat low halves: [a0..a3, b0..b3]
                emit(n, "svint16_t %s = svsplice_s16(pg4, %s, %s);"
                     % (var(dst), a, b))
                setvar(dst, "svint16_t")
                continue
            if vtype == "<2 x i64>" and key in fn:
                # NEON 2x i64 trn = 4-s16 chunk moves; in SVE 8-of-16 lane
                # layout this is splice of the low 4 lanes (trn1) or of
                # lanes rotated by 4 (trn2).
                a64, b64 = a, b
                a16 = "svreinterpret_s16_s64(%s)" % a64
                b16 = "svreinterpret_s16_s64(%s)" % b64
                if key == (1, 3):
                    a16 = "svtbl_s16(%s, rot4)" % a16
                    b16 = "svtbl_s16(%s, rot4)" % b16
                emit(n, "svint64_t %s = svreinterpret_s64_s16("
                     "svsplice_s16(pg4, %s, %s));"
                     % (var(dst), a16, b16))
                setvar(dst, "svint64_t")
                continue
            if key not in fn or fn[key] is None:
                raise ValueError("hadamard: unhandled shuffle %s %r"
                                 % (vtype, mask))
            name, t = fn[key]
            emit(n, "%s %s = %s(%s, %s);"
                 % (t, var(dst), name, a, b))
            setvar(dst, t)
        elif op == "bitcast":
            st, dt = n.get("src_type"), n["type"]
            src = var(n["src"])
            if (st, dt) == ("<8 x i16>", "<2 x i64>"):
                emit(n, "svint64_t %s = svreinterpret_s64_s16(%s);"
                     % (var(dst), src))
                setvar(dst, "svint64_t")
            elif (st, dt) == ("<2 x i64>", "<8 x i16>"):
                emit(n, "svint16_t %s = svreinterpret_s16_s64(%s);"
                     % (var(dst), src))
                setvar(dst, "svint16_t")
            elif (st, dt) == ("<8 x i16>", "<4 x i32>"):
                emit(n, "svint32_t %s = svreinterpret_s32_s16(%s);"
                     % (var(dst), src))
                setvar(dst, "svint32_t")
            elif (st, dt) == ("<4 x i32>", "<8 x i16>"):
                emit(n, "svint16_t %s = svreinterpret_s16_s32(%s);"
                     % (var(dst), src))
                setvar(dst, "svint16_t")
            elif (st, dt) == ("<2 x i32>", "<8 x i8>"):
                emit(n, "svuint8_t %s = svreinterpret_u8_u32(%s);"
                     % (var(dst), src))
                setvar(dst, "svuint8_t")
            else:
                raise ValueError("hadamard: unhandled bitcast %s -> %s"
                                 % (st, dt))
        elif op == "intrinsic":
            name = n["intrinsic"]
            src = [var(s) for s in n["src"]]
            if name == "sabd":
                emit(n, "svint16_t %s = svabd_s16_x(p16, %s, %s);"
                     % (var(dst), as_s16(src[0]), as_s16(src[1])))
                setvar(dst, "svint16_t")
            elif name == "abs":
                emit(n, "svint16_t %s = svabs_s16_x(p16, %s);"
                     % (var(dst), as_s16(src[0])))
                setvar(dst, "svint16_t")
            elif name == "umax":
                emit(n, "svuint16_t %s = svmax_u16_x(p16,"
                     " svreinterpret_u16_s16(%s), svreinterpret_u16_s16(%s));"
                     % (var(dst), src[0], src[1]))
                setvar(dst, "svuint16_t")
            elif name == "uaddlv":
                emit(n, "uint16_t %s = svaddv_u16(pg8h,"
                     " %s);" % (var(dst), as_u16(src[0])))
                setvar(dst, "uint16_t")
            elif name == "uaddlp":
                emit(n, "svuint32_t %s = svset_neonq_u32(svundef_u32(),"
                     " vpaddlq_u16(svget_neonq_u16("
                     "svreinterpret_u16_s16(%s))));" % (var(dst), src[0]))
                setvar(dst, "svuint32_t")
            elif name == "vecreduce_add":
                emit(n, "uint32_t %s = svaddv_u32(pg4w, %s);"
                     % (var(dst), as_u32(src[0])))
                setvar(dst, "uint32_t")
            else:
                raise ValueError("hadamard: unhandled intrinsic %r" % name)
        elif op == "add" and n.get("type") == "i32" and \
                n.get("const") is not None:
            emit(n, "uint32_t %s = %s + %d;"
                 % (var(dst), var(n["src"][0]), n["const"]))
        elif op == "lshr" and n.get("type") == "i32":
            emit(n, "uint32_t %s = %s >> %d;"
                 % (var(dst), var(n["src"][0]), n.get("amt", 0)))
        elif op == "ret":
            emit(n, "return (int)%s;" % var(n["operand"]))
        else:
            raise ValueError("hadamard: unhandled op %r" % n)
    lines.append("}")
    return "\n".join(lines) + "\n"


RECIPES = {
    "diff-sum": {
        "detect": detect_diff_sum,
        "emit": emit_diff_sum,
    },
    "hadamard": {"detect": detect_hadamard, "emit": emit_hadamard},
    "fir": {"detect": detect_fir, "emit": emit_fir},
}


def make_generic_emitter(kernel):
    """Return emit(combo) that derives the candidate from the MachineIR.
    Family detection is per-kernel but recipe-driven: no kernel-specific
    emitter code is written for a new member of a known family."""
    mi = _load_machine_ir(kernel)
    family = detect_family(mi)
    recipe = RECIPES.get(family)
    if recipe is None or recipe["emit"] is None:
        raise ValueError(
            "generic emitter: family %r has no lowering yet (kernel %s);"
            " add a recipe in tools/gen_sve2_emit.py RECIPES"
            % (family, kernel))

    manifest_path = os.path.join(ROOT, "kernels", kernel, "manifest.yaml")
    symbol = None
    if os.path.exists(manifest_path):
        man = yaml.safe_load(open(manifest_path))
        symbol = man.get("candidate", {}).get("symbol")

    def emit(combo):
        return recipe["emit"](mi, symbol or "dynopt_%s_sve2" % kernel)
    return emit


def list_recipes():
    return sorted(RECIPES)
