#!/usr/bin/env python3
"""Simple kernel test database (CSV-backed) for AGO results.

One row = one measurement of a candidate variant on one machine (or a
gate-only row when machine is empty). Columns cover the input kernel
source ISA, output/target ISA, MCA counts, differential gates, real
machine kernel metrics and E2E numbers.

Usage:
  python3 tools/kernel_db.py add 'kernel=dct16 variant=op895 ...'
  python3 tools/kernel_db.py query --kernel dct16 --machine 950
  python3 tools/kernel_db.py export-md

Rows are upserted on (kernel, variant, machine, date, commit) when an
`id` is not given; pass `id=...` to replace an exact row.
"""

import argparse
import csv
import os
import sys
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = os.path.join(ROOT, "data", "kernel-test-db.csv")
MD = os.path.join(ROOT, "data", "kernel-test-db.md")

FIELDS = [
    "id", "date", "commit", "kernel", "family", "variant",
    "input_isa", "output_isa", "candidate_file",
    "mca_fused_uop", "mca_total", "gate_vq", "gate_cases",
    "gate_mismatch", "testbench", "machine", "kernel_metric",
    "kernel_value", "e2e_30f_pct", "e2e_100f_pct", "e2e_ci_ms",
    "bit_exact", "report",
]


def load_rows():
    if not os.path.exists(DB):
        return []
    with open(DB, newline="") as f:
        return list(csv.DictReader(f))


def save_rows(rows):
    os.makedirs(os.path.dirname(DB), exist_ok=True)
    with open(DB, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)


def parse_kv(s):
    d = OrderedDict()
    for part in s.split():
        k, _, v = part.partition("=")
        if not k:
            continue
        d[k] = v
    return d


def do_add(args):
    rows = load_rows()
    row = parse_kv(" ".join(args.row))
    if not row.get("id"):
        base = "-".join(x for x in
                        (row.get("kernel"), row.get("variant"),
                         row.get("machine", ""), row.get("date"),
                         row.get("commit", "")) if x)
        row["id"] = base
    for f in FIELDS:
        row.setdefault(f, "")
    rows = [r for r in rows if r.get("id") != row["id"]]
    rows.append(row)
    rows.sort(key=lambda r: (r.get("kernel"), r.get("variant"),
                             r.get("machine"), r.get("date")))
    save_rows(rows)
    print("added %s (%d rows)" % (row["id"], len(rows)))


def do_query(args):
    rows = load_rows()
    for r in rows:
        ok = True
        for k in ("kernel", "family", "variant", "machine",
                  "output_isa", "input_isa"):
            v = getattr(args, k)
            if v and v not in r.get(k, ""):
                ok = False
                break
        if ok:
            print("\t".join(r.get(f, "") for f in FIELDS))


def do_export_md(args):
    rows = load_rows()
    os.makedirs(os.path.dirname(MD), exist_ok=True)
    out = [
        "# Kernel test database (latest, auto-generated)",
        "",
        "Generated by `tools/kernel_db.py export-md`; source: "
        "`data/kernel-test-db.csv`. Columns: input_isa = kernel source "
        "family the DAG/candidate came from; output_isa = target of the "
        "lowered candidate; MCA = LLVM-MCA fused uop (or total op count "
        "when marked); kernel_value = real-machine paired metric "
        "(ratio >1 means candidate faster unless noted); E2E % = "
        "negative is faster; CI = bootstrap95 ms (empty/0 = not "
        "computed); bit_exact = same-machine md5 gate.",
        "",
        "## Machines",
        "",
        "| machine | ISA | notes |",
        "| --- | --- | --- |",
        "| N1 | NEON-only | 2-core shared; worktree dirty; scp .so |",
        "| 920B | SVE1 VL256 | shared Kunpeng; no PMU; CNTVCT |",
        "| 710 | SVE2 VL128 | Yitian N2; git push direct sync |",
        "| 950 | SVE2 2x256 | internal; E2E pending host+yuv |",
        "",
    ]
    by_family = OrderedDict()
    for r in rows:
        by_family.setdefault(r.get("family") or "other", []).append(r)
    for fam, fam_rows in by_family.items():
        out.append("## %s" % fam)
        out.append("")
        out.append("| kernel | variant | in | out | MCA fused | gate "
                   "(vq/cases/mm) | TB | machine | kernel metric | "
                   "30f% | 100f% | CI ms | exact | date | report |")
        out.append("| --- | --- | --- | --- | ---: | --- | --- | --- | "
                   "--- | ---: | ---: | --- | --- | --- | --- |")
        for r in fam_rows:
            gate = "%s/%s/%s" % (r.get("gate_vq") or "-",
                                 r.get("gate_cases") or "-",
                                 r.get("gate_mismatch") or "-")
            km = r.get("kernel_value") or "-"
            if r.get("kernel_metric"):
                km = "%s=%s" % (r.get("kernel_metric"), km)
            ci = r.get("e2e_ci_ms") or "-"
            out.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s | "
                       "%s | %s | %s | %s | %s | %s |"
                       % (r.get("kernel"), r.get("variant"),
                          r.get("input_isa"), r.get("output_isa"),
                          r.get("mca_fused_uop") or "-", gate,
                          r.get("testbench") or "-", r.get("machine") or "-",
                          km, r.get("e2e_30f_pct") or "-",
                          r.get("e2e_100f_pct") or "-", ci,
                          r.get("bit_exact") or "-", r.get("date"),
                          (r.get("report") or "-").replace("|", "/")))
        out.append("")
    with open(MD, "w") as f:
        f.write("\n".join(out))
    print("wrote %s (%d rows)" % (MD, len(rows)))


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    a = sub.add_parser("add")
    a.add_argument("row", nargs="+")
    a.set_defaults(fn=do_add)
    q = sub.add_parser("query")
    for k in ("kernel", "family", "variant", "machine",
              "output_isa", "input_isa"):
        q.add_argument("--" + k, default="")
    q.set_defaults(fn=do_query)
    e = sub.add_parser("export-md")
    e.set_defaults(fn=do_export_md)
    args = ap.parse_args()
    sys.exit(args.fn(args) or 0)


if __name__ == "__main__":
    main()
