#!/usr/bin/env python3
"""asm-family DAG tests (sad/mc/ssd)."""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "optimizer", "ir"))

from lane_defuse import defuse_report  # noqa: E402
from mc_avg_emit import emit_avg_pp  # noqa: E402
from mc_avg_op_ir import avg_pp_16x16_dag  # noqa: E402
from sad_emit import emit_sad16  # noqa: E402
from sad_op_ir import sad16x16_dag  # noqa: E402
from ssd_emit import emit_sse_pp  # noqa: E402
from ssd_op_ir import sse_pp_16x16_dag  # noqa: E402
from pixel_var_emit import emit_pixel_var  # noqa: E402
from pixel_var_op_ir import pixel_var_16x16_dag  # noqa: E402


def main():
    for tag, dag, emit in (
            ("sad", sad16x16_dag, emit_sad16),
            ("mc", avg_pp_16x16_dag, emit_avg_pp),
            ("ssd", sse_pp_16x16_dag, emit_sse_pp),
            ("pixel_var", pixel_var_16x16_dag, emit_pixel_var)):
        ops = dag()
        assert all("n_out" in o.attrs and "lane_in" in o.attrs
                   for o in ops)
        r = defuse_report(ops)
        assert r["ok"], (tag, r["issues"][:5])
        src = emit(ops)
        assert "Generated by optimizer/ir" in src
        print("asm-family %s DAG OK: ops=%d" % (tag, len(ops)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
