// Generated by tools/emit_interp8_vps_inline.py -- do not edit.
#include <arm_neon.h>
#include <stdint.h>

__attribute__((always_inline)) static inline void filter16_1(const uint8x16_t* s, const uint16x8_t c,
             int16x8_t& d0, int16x8_t& d1)
{
    const uint8x16_t f0 = vdupq_n_u8(4);
    const uint8x16_t f1 = vdupq_n_u8(10);
    const uint8x16_t f2 = vdupq_n_u8(58);
    const uint8x16_t f3 = vdupq_n_u8(17);
    const uint8x16_t f4 = vdupq_n_u8(5);
    uint16x8_t t0 = vsubl_u8(vget_low_u8(s[6]), vget_low_u8(s[0]));
    t0 = vaddq_u16(c, t0);
    t0 = vmlal_u8(t0, vget_low_u8(s[1]), vget_low_u8(f0));
    t0 = vmlsl_u8(t0, vget_low_u8(s[2]), vget_low_u8(f1));
    t0 = vmlal_u8(t0, vget_low_u8(s[3]), vget_low_u8(f2));
    t0 = vmlal_u8(t0, vget_low_u8(s[4]), vget_low_u8(f3));
    t0 = vmlsl_u8(t0, vget_low_u8(s[5]), vget_low_u8(f4));
    d0 = vreinterpretq_s16_u16(t0);
    uint16x8_t t1 = vsubl_u8(vget_high_u8(s[6]), vget_high_u8(s[0]));
    t1 = vaddq_u16(c, t1);
    t1 = vmlal_u8(t1, vget_high_u8(s[1]), vget_high_u8(f0));
    t1 = vmlsl_u8(t1, vget_high_u8(s[2]), vget_high_u8(f1));
    t1 = vmlal_u8(t1, vget_high_u8(s[3]), vget_high_u8(f2));
    t1 = vmlal_u8(t1, vget_high_u8(s[4]), vget_high_u8(f3));
    t1 = vmlsl_u8(t1, vget_high_u8(s[5]), vget_high_u8(f4));
    d1 = vreinterpretq_s16_u16(t1);
}

__attribute__((always_inline)) static inline void filter8_1(const uint8x8_t* s, const uint16x8_t c,
            int16x8_t& d)
{
    uint16x8_t t = vaddq_u16(c, vsubl_u8(s[6], s[0]));
    t = vmlal_u8(t, s[1], vdup_n_u8(4));
    t = vmlsl_u8(t, s[2], vdup_n_u8(10));
    t = vmlal_u8(t, s[3], vdup_n_u8(58));
    t = vmlal_u8(t, s[4], vdup_n_u8(17));
    t = vmlsl_u8(t, s[5], vdup_n_u8(5));
    d = vreinterpretq_s16_u16(t);
}

__attribute__((always_inline)) static inline void filter16_2(const uint8x16_t* s, const uint16x8_t c,
             int16x8_t& d0, int16x8_t& d1)
{
    int16x8_t t0 = vreinterpretq_s16_u16(vaddl_u8(vget_low_u8(s[3]),
                                                  vget_low_u8(s[4])));
    int16x8_t t1 = vreinterpretq_s16_u16(vaddl_u8(vget_low_u8(s[2]),
                                                  vget_low_u8(s[5])));
    int16x8_t t2 = vreinterpretq_s16_u16(vaddl_u8(vget_low_u8(s[1]),
                                                  vget_low_u8(s[6])));
    int16x8_t t3 = vreinterpretq_s16_u16(vaddl_u8(vget_low_u8(s[0]),
                                                  vget_low_u8(s[7])));
    d0 = vreinterpretq_s16_u16(c);
    d0 = vmlaq_n_s16(d0, t0, 40);
    d0 = vmlaq_n_s16(d0, t1, -11);
    d0 = vmlaq_n_s16(d0, t2, 4);
    d0 = vmlaq_n_s16(d0, t3, -1);
    int16x8_t t4 = vreinterpretq_s16_u16(vaddl_u8(vget_high_u8(s[3]),
                                                  vget_high_u8(s[4])));
    int16x8_t t5 = vreinterpretq_s16_u16(vaddl_u8(vget_high_u8(s[2]),
                                                  vget_high_u8(s[5])));
    int16x8_t t6 = vreinterpretq_s16_u16(vaddl_u8(vget_high_u8(s[1]),
                                                  vget_high_u8(s[6])));
    int16x8_t t7 = vreinterpretq_s16_u16(vaddl_u8(vget_high_u8(s[0]),
                                                  vget_high_u8(s[7])));
    d1 = vreinterpretq_s16_u16(c);
    d1 = vmlaq_n_s16(d1, t4, 40);
    d1 = vmlaq_n_s16(d1, t5, -11);
    d1 = vmlaq_n_s16(d1, t6, 4);
    d1 = vmlaq_n_s16(d1, t7, -1);
}

__attribute__((always_inline)) static inline void filter8_2(const uint8x8_t* s, const uint16x8_t c,
            int16x8_t& d)
{
    int16x8_t t0 = vreinterpretq_s16_u16(vaddl_u8(s[3], s[4]));
    int16x8_t t1 = vreinterpretq_s16_u16(vaddl_u8(s[2], s[5]));
    int16x8_t t2 = vreinterpretq_s16_u16(vaddl_u8(s[1], s[6]));
    int16x8_t t3 = vreinterpretq_s16_u16(vaddl_u8(s[0], s[7]));
    d = vreinterpretq_s16_u16(c);
    d = vmlaq_n_s16(d, t0, 40);
    d = vmlaq_n_s16(d, t1, -11);
    d = vmlaq_n_s16(d, t2, 4);
    d = vmlaq_n_s16(d, t3, -1);
}

__attribute__((always_inline)) static inline void filter16_3(const uint8x16_t* s, const uint16x8_t c,
             int16x8_t& d0, int16x8_t& d1)
{
    const uint8x16_t f0 = vdupq_n_u8(4);
    const uint8x16_t f1 = vdupq_n_u8(10);
    const uint8x16_t f2 = vdupq_n_u8(58);
    const uint8x16_t f3 = vdupq_n_u8(17);
    const uint8x16_t f4 = vdupq_n_u8(5);
    uint16x8_t t0 = vsubl_u8(vget_low_u8(s[1]), vget_low_u8(s[7]));
    t0 = vaddq_u16(c, t0);
    t0 = vmlal_u8(t0, vget_low_u8(s[6]), vget_low_u8(f0));
    t0 = vmlsl_u8(t0, vget_low_u8(s[5]), vget_low_u8(f1));
    t0 = vmlal_u8(t0, vget_low_u8(s[4]), vget_low_u8(f2));
    t0 = vmlal_u8(t0, vget_low_u8(s[3]), vget_low_u8(f3));
    t0 = vmlsl_u8(t0, vget_low_u8(s[2]), vget_low_u8(f4));
    d0 = vreinterpretq_s16_u16(t0);
    uint16x8_t t1 = vsubl_u8(vget_high_u8(s[1]), vget_high_u8(s[7]));
    t1 = vaddq_u16(c, t1);
    t1 = vmlal_u8(t1, vget_high_u8(s[6]), vget_high_u8(f0));
    t1 = vmlsl_u8(t1, vget_high_u8(s[5]), vget_high_u8(f1));
    t1 = vmlal_u8(t1, vget_high_u8(s[4]), vget_high_u8(f2));
    t1 = vmlal_u8(t1, vget_high_u8(s[3]), vget_high_u8(f3));
    t1 = vmlsl_u8(t1, vget_high_u8(s[2]), vget_high_u8(f4));
    d1 = vreinterpretq_s16_u16(t1);
}

__attribute__((always_inline)) static inline void filter8_3(const uint8x8_t* s, const uint16x8_t c,
            int16x8_t& d)
{
    uint16x8_t t = vaddq_u16(c, vsubl_u8(s[1], s[7]));
    t = vmlal_u8(t, s[6], vdup_n_u8(4));
    t = vmlsl_u8(t, s[5], vdup_n_u8(10));
    t = vmlal_u8(t, s[4], vdup_n_u8(58));
    t = vmlal_u8(t, s[3], vdup_n_u8(17));
    t = vmlsl_u8(t, s[2], vdup_n_u8(5));
    d = vreinterpretq_s16_u16(t);
}

template<int CI, int W, int H>
static void vps_impl_1(const uint8_t* src, intptr_t sstride,
                   int16_t* dst, intptr_t dstride)
{
    const int offset = (unsigned)-8192;  // IF_INTERNAL_OFFS
    src -= 3 * sstride;
    const uint16x8_t c = vdupq_n_u16((uint16_t)offset);
    const int SEG = W / 16;
    for (int row = 0; row < H; row += 4)
    {
        const uint8_t* p = src + row * sstride;
        int16_t* d = dst + row * dstride;
        if (W == 8)
        {
            uint8x8_t in[11];
            for (int i = 0; i < 11; i++)
                in[i] = vld1_u8(p + i * sstride);
            for (int k = 0; k < 4; k++)
            {
                int16x8_t sum;
                filter8_1(in + k, c, sum);
                vst1q_s16(d + k * dstride, sum);
            }
        }
        else
        {
            uint8x16_t in[SEG][11];
            for (int i = 0; i < 11; i++)
                for (int seg = 0; seg < SEG; seg++)
                    in[seg][i] = vld1q_u8(p + i * sstride + seg * 16);
            for (int k = 0; k < 4; k++)
                for (int seg = 0; seg < SEG; seg++)
                {
                    int16x8_t d0, d1;
                    filter16_1(in[seg] + k, c, d0, d1);
                    vst1q_s16(d + k * dstride + seg * 16, d0);
                    vst1q_s16(d + k * dstride + seg * 16 + 8, d1);
                }
        }
    }
}

template<int CI, int W, int H>
static void vps_impl_2(const uint8_t* src, intptr_t sstride,
                   int16_t* dst, intptr_t dstride)
{
    const int offset = (unsigned)-8192;  // IF_INTERNAL_OFFS
    src -= 3 * sstride;
    const uint16x8_t c = vdupq_n_u16((uint16_t)offset);
    const int SEG = W / 16;
    for (int row = 0; row < H; row += 4)
    {
        const uint8_t* p = src + row * sstride;
        int16_t* d = dst + row * dstride;
        if (W == 8)
        {
            uint8x8_t in[11];
            for (int i = 0; i < 11; i++)
                in[i] = vld1_u8(p + i * sstride);
            for (int k = 0; k < 4; k++)
            {
                int16x8_t sum;
                filter8_2(in + k, c, sum);
                vst1q_s16(d + k * dstride, sum);
            }
        }
        else
        {
            uint8x16_t in[SEG][11];
            for (int i = 0; i < 11; i++)
                for (int seg = 0; seg < SEG; seg++)
                    in[seg][i] = vld1q_u8(p + i * sstride + seg * 16);
            for (int k = 0; k < 4; k++)
                for (int seg = 0; seg < SEG; seg++)
                {
                    int16x8_t d0, d1;
                    filter16_2(in[seg] + k, c, d0, d1);
                    vst1q_s16(d + k * dstride + seg * 16, d0);
                    vst1q_s16(d + k * dstride + seg * 16 + 8, d1);
                }
        }
    }
}

template<int CI, int W, int H>
static void vps_impl_3(const uint8_t* src, intptr_t sstride,
                   int16_t* dst, intptr_t dstride)
{
    const int offset = (unsigned)-8192;  // IF_INTERNAL_OFFS
    src -= 3 * sstride;
    const uint16x8_t c = vdupq_n_u16((uint16_t)offset);
    const int SEG = W / 16;
    for (int row = 0; row < H; row += 4)
    {
        const uint8_t* p = src + row * sstride;
        int16_t* d = dst + row * dstride;
        if (W == 8)
        {
            uint8x8_t in[11];
            for (int i = 0; i < 11; i++)
                in[i] = vld1_u8(p + i * sstride);
            for (int k = 0; k < 4; k++)
            {
                int16x8_t sum;
                filter8_3(in + k, c, sum);
                vst1q_s16(d + k * dstride, sum);
            }
        }
        else
        {
            uint8x16_t in[SEG][11];
            for (int i = 0; i < 11; i++)
                for (int seg = 0; seg < SEG; seg++)
                    in[seg][i] = vld1q_u8(p + i * sstride + seg * 16);
            for (int k = 0; k < 4; k++)
                for (int seg = 0; seg < SEG; seg++)
                {
                    int16x8_t d0, d1;
                    filter16_3(in[seg] + k, c, d0, d1);
                    vst1q_s16(d + k * dstride + seg * 16, d0);
                    vst1q_s16(d + k * dstride + seg * 16 + 8, d1);
                }
        }
    }
}

extern "C" void dynopt_interp8_vps_8x8_sve2(
    const uint8_t* src, intptr_t sstride,
    int16_t* dst, intptr_t dstride, int coeffIdx)
{
    switch (coeffIdx)
    {
    case 1: vps_impl_1<1, 8, 8>(src, sstride, dst, dstride); break;
    case 2: vps_impl_2<2, 8, 8>(src, sstride, dst, dstride); break;
    default: vps_impl_3<3, 8, 8>(src, sstride, dst, dstride); break;
    }
}

