// Generated by tools/emit_interp8_vsp_inline.py -- do not edit.
#include <arm_neon.h>
#include <stdint.h>

__attribute__((always_inline)) static inline int16x8_t vtbl2q_s32_s16(
    int32x4_t a, int32x4_t b, uint8x16_t index)
{
    uint8x16x2_t ab;
    ab.val[0] = vreinterpretq_u8_s32(a);
    ab.val[1] = vreinterpretq_u8_s32(b);
    return vreinterpretq_s16_u8(vqtbl2q_u8(ab, index));
}

__attribute__((always_inline)) static inline void filter8_s16x8_1(const int16x8_t* s, const int16x8_t filter,
                   const int32x4_t c, int32x4_t& d0, int32x4_t& d1)
{
    d0 = vsubl_s16(vget_low_s16(s[6]), vget_low_s16(s[0]));
    d0 = vaddq_s32(d0, c);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[1]), filter, 1);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[2]), filter, 2);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[3]), filter, 3);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[4]), filter, 4);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[5]), filter, 5);
    d1 = vsubl_s16(vget_high_s16(s[6]), vget_high_s16(s[0]));
    d1 = vaddq_s32(d1, c);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[1]), filter, 1);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[2]), filter, 2);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[3]), filter, 3);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[4]), filter, 4);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[5]), filter, 5);
}

__attribute__((always_inline)) static inline void filter8_s16x8_2(const int16x8_t* s, const int16x8_t filter,
                   const int32x4_t c, int32x4_t& d0, int32x4_t& d1)
{
    int16x8_t sum07 = vaddq_s16(s[0], s[7]);
    int16x8_t sum16 = vaddq_s16(s[1], s[6]);
    int16x8_t sum25 = vaddq_s16(s[2], s[5]);
    int16x8_t sum34 = vaddq_s16(s[3], s[4]);
    int32x4_t slo = vmlal_laneq_s16(c, vget_low_s16(sum16), filter, 1);
    slo = vmlal_laneq_s16(slo, vget_low_s16(sum25), filter, 2);
    slo = vmlal_laneq_s16(slo, vget_low_s16(sum34), filter, 3);
    int32x4_t shi = vmlal_laneq_s16(c, vget_high_s16(sum16), filter, 1);
    shi = vmlal_laneq_s16(shi, vget_high_s16(sum25), filter, 2);
    shi = vmlal_laneq_s16(shi, vget_high_s16(sum34), filter, 3);
    d0 = vsubw_s16(slo, vget_low_s16(sum07));
    d1 = vsubw_s16(shi, vget_high_s16(sum07));
}

__attribute__((always_inline)) static inline void filter8_s16x8_3(const int16x8_t* s, const int16x8_t filter,
                   const int32x4_t c, int32x4_t& d0, int32x4_t& d1)
{
    int16x8_t sum17 = vsubq_s16(s[1], s[7]);
    d0 = vaddw_s16(c, vget_low_s16(sum17));
    d1 = vaddw_s16(c, vget_high_s16(sum17));
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[2]), filter, 2);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[3]), filter, 3);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[4]), filter, 4);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[5]), filter, 5);
    d0 = vmlal_laneq_s16(d0, vget_low_s16(s[6]), filter, 6);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[2]), filter, 2);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[3]), filter, 3);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[4]), filter, 4);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[5]), filter, 5);
    d1 = vmlal_laneq_s16(d1, vget_high_s16(s[6]), filter, 6);
}

template<int CI, int W, int H>
static void vsp_impl_1(const int16_t* src, intptr_t sstride,
                            uint8_t* dst, intptr_t dstride)
{
    const int shift = 6 + (14 - 8);          // IF_FILTER_PREC + headRoom
    const int shift_offset = shift - 8;      // 4
    const int offset = (1 << (shift - 1)) + (8192 << 6);
    src -= 3 * sstride;
    static const int16_t LUMA_F[4][8] = {
        {0,0,0,64,0,0,0,0}, {-1,4,-10,58,17,-5,1,0},
        {-1,4,-11,40,40,-11,4,-1}, {0,1,-5,17,58,-10,4,-1}};
    static const uint8_t SHR[16] =
        {1,2,5,6,9,10,13,14,17,18,21,22,25,26,29,30};
    const int16x8_t filter = vld1q_s16(LUMA_F[CI]);
    const int32x4_t c = vdupq_n_s32(offset);
    const uint8x16_t shr_tbl = vld1q_u8(SHR);
    const int SEG = W / 8;
    for (int row = 0; row < H; row += 4)
    {
        const int16_t* p = src + row * sstride;
        uint8_t* d = dst + row * dstride;
        for (int seg = 0; seg < SEG; seg++)
        {
            int16x8_t in[11];
            for (int i = 0; i < 11; i++)
                in[i] = vld1q_s16(p + i * sstride + seg * 8);
            for (int k = 0; k < 4; k++)
            {
                int32x4_t slo, shi;
                filter8_s16x8_1(in + k, filter, c, slo, shi);
                int16x8_t sum = vtbl2q_s32_s16(slo, shi, shr_tbl);
                uint8x8_t o = vqshrun_n_s16(sum, shift_offset);
                vst1_u8(d + k * dstride + seg * 8, o);
            }
        }
    }
}

template<int CI, int W, int H>
static void vsp_impl_2(const int16_t* src, intptr_t sstride,
                            uint8_t* dst, intptr_t dstride)
{
    const int shift = 6 + (14 - 8);          // IF_FILTER_PREC + headRoom
    const int shift_offset = shift - 8;      // 4
    const int offset = (1 << (shift - 1)) + (8192 << 6);
    src -= 3 * sstride;
    static const int16_t LUMA_F[4][8] = {
        {0,0,0,64,0,0,0,0}, {-1,4,-10,58,17,-5,1,0},
        {-1,4,-11,40,40,-11,4,-1}, {0,1,-5,17,58,-10,4,-1}};
    static const uint8_t SHR[16] =
        {1,2,5,6,9,10,13,14,17,18,21,22,25,26,29,30};
    const int16x8_t filter = vld1q_s16(LUMA_F[CI]);
    const int32x4_t c = vdupq_n_s32(offset);
    const uint8x16_t shr_tbl = vld1q_u8(SHR);
    const int SEG = W / 8;
    for (int row = 0; row < H; row += 4)
    {
        const int16_t* p = src + row * sstride;
        uint8_t* d = dst + row * dstride;
        for (int seg = 0; seg < SEG; seg++)
        {
            int16x8_t in[11];
            for (int i = 0; i < 11; i++)
                in[i] = vld1q_s16(p + i * sstride + seg * 8);
            for (int k = 0; k < 4; k++)
            {
                int32x4_t slo, shi;
                filter8_s16x8_2(in + k, filter, c, slo, shi);
                int16x8_t sum = vtbl2q_s32_s16(slo, shi, shr_tbl);
                uint8x8_t o = vqshrun_n_s16(sum, shift_offset);
                vst1_u8(d + k * dstride + seg * 8, o);
            }
        }
    }
}

template<int CI, int W, int H>
static void vsp_impl_3(const int16_t* src, intptr_t sstride,
                            uint8_t* dst, intptr_t dstride)
{
    const int shift = 6 + (14 - 8);          // IF_FILTER_PREC + headRoom
    const int shift_offset = shift - 8;      // 4
    const int offset = (1 << (shift - 1)) + (8192 << 6);
    src -= 3 * sstride;
    static const int16_t LUMA_F[4][8] = {
        {0,0,0,64,0,0,0,0}, {-1,4,-10,58,17,-5,1,0},
        {-1,4,-11,40,40,-11,4,-1}, {0,1,-5,17,58,-10,4,-1}};
    static const uint8_t SHR[16] =
        {1,2,5,6,9,10,13,14,17,18,21,22,25,26,29,30};
    const int16x8_t filter = vld1q_s16(LUMA_F[CI]);
    const int32x4_t c = vdupq_n_s32(offset);
    const uint8x16_t shr_tbl = vld1q_u8(SHR);
    const int SEG = W / 8;
    for (int row = 0; row < H; row += 4)
    {
        const int16_t* p = src + row * sstride;
        uint8_t* d = dst + row * dstride;
        for (int seg = 0; seg < SEG; seg++)
        {
            int16x8_t in[11];
            for (int i = 0; i < 11; i++)
                in[i] = vld1q_s16(p + i * sstride + seg * 8);
            for (int k = 0; k < 4; k++)
            {
                int32x4_t slo, shi;
                filter8_s16x8_3(in + k, filter, c, slo, shi);
                int16x8_t sum = vtbl2q_s32_s16(slo, shi, shr_tbl);
                uint8x8_t o = vqshrun_n_s16(sum, shift_offset);
                vst1_u8(d + k * dstride + seg * 8, o);
            }
        }
    }
}

extern "C" void dynopt_interp8_vsp_32x32_sve2(
    const int16_t* src, intptr_t sstride,
    uint8_t* dst, intptr_t dstride, int coeffIdx)
{
    switch (coeffIdx)
    {
    case 1: vsp_impl_1<1, 32, 32>(src, sstride, dst, dstride); break;
    case 2: vsp_impl_2<2, 32, 32>(src, sstride, dst, dstride); break;
    default: vsp_impl_3<3, 32, 32>(src, sstride, dst, dstride); break;
    }
}

