"""Bounded NEON cover search for SATD 8x8 (AGO M2).

All covers share the upstream prefix (load_diff_u8x8x8 ->
hadamard_4_v x2 -> hadamard_abs_4_h x2 -> vmaxq_u16 x4) and differ only
in the sum/reduce tail:

  A upstream : o0=sum0+sum1; o1=sum2+sum3; accv=o0+o1; uaddlv
  B balanced : acc0=sum0+sum2; acc1=sum1+sum3; accv=acc0+acc1; uaddlv
  C dual-red : o0=sum0+sum1; o1=sum2+sum3; uaddlv(o0)+uaddlv(o1)

All are semantically equal (per-lane u16 adds, lane sums far below
overflow) and each must pass the 20k oracle gate. The tail is the
region where instruction selection can vary without changing the
dataflow graph; this is the M2 bounded cover space.

Prediction uses per-op cost tables (N1 timing-n1.json; 920B table where
available) with throughput-cycle sums as the primary rank, latency sums
as tie-break. Proxies: vaddq_u16 -> add_u16; vmaxq_u16 -> maxv_u8;
uaddlvq_u16 -> paddl_u16.
"""

from __future__ import annotations

from typing import Dict, List

from ago.cover_neon import NEON_HELPERS


_PREFIX = """\
extern "C" int %s(const uint8_t* pix1, intptr_t stride1,
                  const uint8_t* pix2, intptr_t stride2)
{
    int16x8_t d[8];
    d[0] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 0 * stride1),
                                          vld1_u8(pix2 + 0 * stride2)));
    d[1] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 1 * stride1),
                                          vld1_u8(pix2 + 1 * stride2)));
    d[2] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 2 * stride1),
                                          vld1_u8(pix2 + 2 * stride2)));
    d[3] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 3 * stride1),
                                          vld1_u8(pix2 + 3 * stride2)));
    d[4] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 4 * stride1),
                                          vld1_u8(pix2 + 4 * stride2)));
    d[5] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 5 * stride1),
                                          vld1_u8(pix2 + 5 * stride2)));
    d[6] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 6 * stride1),
                                          vld1_u8(pix2 + 6 * stride2)));
    d[7] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 7 * stride1),
                                          vld1_u8(pix2 + 7 * stride2)));
    int16x8_t t[8];
    hadamard_4_v(d, t);
    hadamard_4_v(d + 4, t + 4);
    hadamard_abs_4_h(t, d);
    hadamard_abs_4_h(t + 4, d + 4);
    uint16x8_t sum0 = vmaxq_u16(vreinterpretq_u16_s16(d[0]),
                                vreinterpretq_u16_s16(d[1]));
    uint16x8_t sum1 = vmaxq_u16(vreinterpretq_u16_s16(d[2]),
                                vreinterpretq_u16_s16(d[3]));
    uint16x8_t sum2 = vmaxq_u16(vreinterpretq_u16_s16(d[4]),
                                vreinterpretq_u16_s16(d[5]));
    uint16x8_t sum3 = vmaxq_u16(vreinterpretq_u16_s16(d[6]),
                                vreinterpretq_u16_s16(d[7]));
"""

_TAILS = {
    "A": """\
    uint16x8_t o0 = vaddq_u16(sum0, sum1);
    uint16x8_t o1 = vaddq_u16(sum2, sum3);
    uint16x8_t accv = vaddq_u16(o0, o1);
    return (int)vaddlvq_u16(accv);
}""",
    "B": """\
    uint16x8_t acc0 = vaddq_u16(sum0, sum2);
    uint16x8_t acc1 = vaddq_u16(sum1, sum3);
    uint16x8_t accv = vaddq_u16(acc0, acc1);
    return (int)vaddlvq_u16(accv);
}""",
    "C": """\
    uint16x8_t o0 = vaddq_u16(sum0, sum1);
    uint16x8_t o1 = vaddq_u16(sum2, sum3);
    return (int)(vaddlvq_u16(o0) + vaddlvq_u16(o1));
}""",
}

# tail op multiset per cover (u16x8 adds, uaddlv reductions, scalar add)
_TAIL_OPS = {
    "A": ["add_u16", "add_u16", "add_u16", "paddl_u16"],
    "B": ["add_u16", "add_u16", "add_u16", "paddl_u16"],
    "C": ["add_u16", "add_u16", "paddl_u16", "paddl_u16", "add_u8"],
}


def emit_cover(name: str, func: str) -> str:
    if name not in _TAILS:
        raise ValueError("unknown cover %r" % name)
    return ("// Generated by optimizer/ago/covers_satd8.py -- do not edit.\n"
            "#include <arm_neon.h>\n#include <stdint.h>\n" +
            NEON_HELPERS + "\n" + _PREFIX % func + "\n" + _TAILS[name] + "\n")


def predict_cost(name: str, table: Dict) -> Dict:
    """Static cost prediction from a per-instruction cost table.

    Primary rank: sum of throughput cycles per op; tie-break: sum of
    latency cycles. Missing keys get the table's "empty" cost so a
    missing entry cannot silently zero a whole op class.
    """
    empty = table.get("empty", {"latency_cyc": 1.0,
                                "throughput_cyc_per_op": 1.0})
    tput_sum = lat_sum = 0.0
    for op in _TAIL_OPS[name]:
        c = table.get(op, empty)
        tput_sum += float(c.get("throughput_cyc_per_op") or 0.0)
        lat_sum += float(c.get("latency_cyc") or 0.0)
    return {"cover": name, "tput_sum": round(tput_sum, 3),
            "lat_sum": round(lat_sum, 3)}


def all_covers() -> List[str]:
    return sorted(_TAILS)
