"""Shape-aware SATD NEON covers for the M2-expanded corpus.

Shapes: 8x4 (one 4-row band of two 4x4 blocks), 8x16 (four stacked
bands), 16x8 (left/right 8-col blocks, each two bands). Covers:

  A upstream-ish : sum quadrant vectors -> uaddlv
  B dual-reduce  : uaddlv per quadrant vector, scalar sum
  C pair-reduce  : vpaddlq + vaddvq (different reduction instruction)

All must pass the shape-specific 20k oracle (C satd_8x4 band sum).
"""

from __future__ import annotations

from typing import Dict, List

from ago.cover_neon import NEON_HELPERS


_SHAPE_DEFS = {
    "8x4": (4, 8, "dynopt_ago_satd8x4"),
    "8x16": (16, 8, "dynopt_ago_satd8x16"),
    "16x8": (8, 16, "dynopt_ago_satd16x8"),
}


def _loads(rows: int, cols: int, func: str) -> str:
    n = rows if cols == 8 else 2 * rows
    L = ["extern \"C\" int %s(const uint8_t* pix1, intptr_t stride1,"
         % func,
         "                  const uint8_t* pix2, intptr_t stride2)",
         "{",
         "    int16x8_t d[%d];" % n]
    for i in range(rows):
        L.append(
            "    d[%d] = vreinterpretq_s16_u16(vsubl_u8("
            "vld1_u8(pix1 + %d * stride1), vld1_u8(pix2 + %d * stride2)));"
            % (i, i, i))
    if cols == 16:
        for i in range(rows):
            L.append(
                "    d[%d] = vreinterpretq_s16_u16(vsubl_u8("
                "vld1_u8(pix1 + 8 + %d * stride1), "
                "vld1_u8(pix2 + 8 + %d * stride2)));" % (rows + i, i, i))
    return "\n".join(L)


def _quad_body(var: str, d_off: int) -> str:
    return """\
    int16x8_t t%s[4];
    hadamard_4_v(d + %d, t%s);
    hadamard_abs_4_h(t%s, d + %d);
    uint16x8_t m%sa = vmaxq_u16(vreinterpretq_u16_s16(d[%d]),
                                vreinterpretq_u16_s16(d[%d]));
    uint16x8_t m%sb = vmaxq_u16(vreinterpretq_u16_s16(d[%d]),
                                vreinterpretq_u16_s16(d[%d]));
    uint16x8_t o%s = vaddq_u16(m%sa, m%sb);
""" % (var, d_off, var, var, d_off,
        var, d_off, d_off + 1, var, d_off + 2, d_off + 3,
        var, var, var)


def _acc_expr(shape: str, cover: str) -> str:
    q = ["oa"] if shape == "8x4" else ["oa", "ob", "oc", "od"]
    if cover == "B":
        return " + ".join("vaddlvq_u16(%s)" % v for v in q)
    return "(" + " + ".join(q) + ")"


def emit_cover(shape: str, cover: str, func: str = "") -> str:
    if shape not in _SHAPE_DEFS or cover not in ("A", "B", "C"):
        raise ValueError("unknown shape/cover %s/%s" % (shape, cover))
    rows, cols, sym = _SHAPE_DEFS[shape]
    if not func:
        func = sym
    body = _loads(rows, cols, func)
    quads = []
    if shape == "8x4":
        quads.append(_quad_body("a", 0))
    elif shape == "8x16":
        for q, off in (("a", 0), ("b", 4), ("c", 8), ("d", 12)):
            quads.append(_quad_body(q, off))
    else:  # 16x8: d[0..7] left block, d[8..15] right block
        for q, off in (("a", 0), ("b", 4), ("c", 8), ("d", 12)):
            quads.append(_quad_body(q, off))
    acc = _acc_expr(shape, cover)
    if cover == "A":
        tail = ("    uint16x8_t accv = %s;\n"
                "    return (int)vaddlvq_u16(accv);\n}" % acc)
    elif cover == "B":
        tail = "    return (int)(%s);\n}" % acc
    else:
        tail = ("    uint16x8_t accv = %s;\n"
                "    uint32x4_t p = vpaddlq_u16(accv);\n"
                "    return (int)vaddvq_u32(p);\n}" % acc)
    return ("// Generated by optimizer/ago/covers_satd_shapes.py "
            "-- do not edit.\n"
            "#include <arm_neon.h>\n#include <stdint.h>\n" +
            NEON_HELPERS + "\n" + body + "\n" + "\n".join(quads) + "\n" +
            tail + "\n")


def all_shapes() -> List[str]:
    return sorted(_SHAPE_DEFS)


def all_covers() -> List[str]:
    return ["A", "B", "C"]


_QUAD_OPS = (["add_u16"] * 6 + ["sub_u8"] * 2 + ["trn"] * 8 +
             ["abs_s16"] * 2 + ["abd_u8"] * 2 + ["maxv_u8"] * 2 +
             ["add_u16"])
_TAIL_OPS = {
    "A": ["add_u16", "paddl_u16"],
    "B": ["paddl_u16", "paddl_u16", "add_u8"],
    "C": ["add_u16", "paddl_u16", "add_u8"],
}
_CP_QUAD = ["ld1_u8", "addl_u8", "add_u16", "add_u16",
            "sub_u8", "trn", "abs_s16", "trn", "maxv_u8", "add_u16"]
_CP_TAIL = {
    "A": ["add_u16", "paddl_u16"],
    "B": ["paddl_u16", "add_u8"],
    "C": ["add_u16", "paddl_u16", "add_u8"],
}

_SHAPE_COUNTS = {
    "8x4": {"rows": 4, "quads": 1, "cross_adds": 0},
    "8x16": {"rows": 16, "quads": 4, "cross_adds": 2},
    "16x8": {"rows": 16, "quads": 4, "cross_adds": 2},
}


def cover_meta() -> Dict:
    meta = {"kernel": "satd-shapes", "tail_ops": {}, "cp_chains": {},
            "regions": {}}
    for shape, info in _SHAPE_COUNTS.items():
        for cover in ("A", "B", "C"):
            key = "%s/%s" % (shape, cover)
            rows = info["rows"]
            ops = (["ld1_u8"] * (2 * rows) + ["addl_u8"] * rows +
                   _QUAD_OPS * info["quads"] +
                   ["add_u16"] * info["cross_adds"] +
                   _TAIL_OPS[cover])
            cp = (_CP_QUAD + ["add_u16"] * info["cross_adds"] +
                  _CP_TAIL[cover])
            meta["tail_ops"][key] = ops
            meta["cp_chains"][key] = cp
            meta["regions"][key] = "satd-%s/reduce" % shape
    return meta


def shape_meta(shape: str) -> Dict:
    """Per-shape cover_meta for the AGO auto-search: keys are cover
    letters (A/B/C), so predict_from_features works with the standard
    `cover = tag.split('-')[-1]` lookup (docs/82)."""
    m = cover_meta()
    # Measured permute_depth_ratio per shape/cover (ago_auto_search
    # static_counts, 2026-08-18): NEON trn-based covers land 17-23%,
    # well below the sve16 candidates (50.7%/46.7%).
    _measured = {
        "8x16": {"A": 0.214, "B": 0.222, "C": 0.214},
        "16x8": {"A": 0.231, "B": 0.174, "C": 0.231},
        "8x4": {"A": 0.0, "B": 0.0, "C": 0.0},
    }
    return {
        "covers": ["A", "B", "C"],
        "names": {c: "satd-%s NEON cover %s" % (shape, c)
                  for c in "ABC"},
        "cp_chains": {c: m["cp_chains"]["%s/%s" % (shape, c)]
                      for c in "ABC"},
        "tail_ops": {c: m["tail_ops"]["%s/%s" % (shape, c)]
                     for c in "ABC"},
        "expected_permute_ratio": _measured.get(
            shape, {c: 0.0 for c in "ABC"}),
    }
