"""Bounded NEON cover variants for SA8D 8x8 (AGO M2-expanded corpus).

All covers share the upstream prefix (load_diff_u8x8x8 ->
hadamard_8_v -> hadamard_8_h) and differ in the sum/reduce tail:

  A upstream : o0=s0+s1; o1=s2+s3; accv=o0+o1; (uaddlv+1)>>1
  B dual-red : uaddlv(o0)+uaddlv(o1); (acc+1)>>1
  C balanced : acc0=s0+s2; acc1=s1+s3; accv=acc0+acc1; (uaddlv+1)>>1

Semantics identical to x265 sa8d_8x8 (C reference; 20k oracle in
scripts/verify-ago-sa8d8.sh pattern).
"""

from __future__ import annotations

from typing import Dict, List

from ago.cover_neon import NEON_HELPERS


_PREFIX = """\
extern "C" int %s(const uint8_t* pix1, intptr_t stride1,
                  const uint8_t* pix2, intptr_t stride2)
{
    int16x8_t d[8];
    d[0] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 0 * stride1),
                                          vld1_u8(pix2 + 0 * stride2)));
    d[1] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 1 * stride1),
                                          vld1_u8(pix2 + 1 * stride2)));
    d[2] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 2 * stride1),
                                          vld1_u8(pix2 + 2 * stride2)));
    d[3] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 3 * stride1),
                                          vld1_u8(pix2 + 3 * stride2)));
    d[4] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 4 * stride1),
                                          vld1_u8(pix2 + 4 * stride2)));
    d[5] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 5 * stride1),
                                          vld1_u8(pix2 + 5 * stride2)));
    d[6] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 6 * stride1),
                                          vld1_u8(pix2 + 6 * stride2)));
    d[7] = vreinterpretq_s16_u16(vsubl_u8(vld1_u8(pix1 + 7 * stride1),
                                          vld1_u8(pix2 + 7 * stride2)));
    int16x8_t t[8];
    hadamard_8_v(d, t);
    uint16x8_t s[4];
    hadamard_8_h(t, s);
"""

_TAILS = {
    "A": """\
    uint16x8_t o0 = vaddq_u16(s[0], s[1]);
    uint16x8_t o1 = vaddq_u16(s[2], s[3]);
    uint16x8_t accv = vaddq_u16(o0, o1);
    return (int)((vaddlvq_u16(accv) + 1) >> 1);
}""",
    "B": """\
    uint16x8_t o0 = vaddq_u16(s[0], s[1]);
    uint16x8_t o1 = vaddq_u16(s[2], s[3]);
    uint32_t acc = vaddlvq_u16(o0) + vaddlvq_u16(o1);
    return (int)((acc + 1) >> 1);
}""",
    "C": """\
    uint16x8_t acc0 = vaddq_u16(s[0], s[2]);
    uint16x8_t acc1 = vaddq_u16(s[1], s[3]);
    uint16x8_t accv = vaddq_u16(acc0, acc1);
    return (int)((vaddlvq_u16(accv) + 1) >> 1);
}""",
}

_TAIL_OPS = {
    "A": ["add_u16", "add_u16", "add_u16", "paddl_u16", "add_u8"],
    "B": ["add_u16", "add_u16", "paddl_u16", "paddl_u16",
          "add_u8", "add_u8"],
    "C": ["add_u16", "add_u16", "add_u16", "paddl_u16", "add_u8"],
}

_CP_CHAINS = {
    "A": ["ld1_u8", "addl_u8", "add_u16", "add_u16",
          "sub_u8", "trn", "abs_s16", "trn", "maxv_u8",
          "add_u16", "add_u16", "add_u16", "paddl_u16", "add_u8"],
    "B": ["ld1_u8", "addl_u8", "add_u16", "add_u16",
          "sub_u8", "trn", "abs_s16", "trn", "maxv_u8",
          "add_u16", "add_u16", "paddl_u16", "add_u8", "add_u8"],
    "C": ["ld1_u8", "addl_u8", "add_u16", "add_u16",
          "sub_u8", "trn", "abs_s16", "trn", "maxv_u8",
          "add_u16", "add_u16", "add_u16", "paddl_u16", "add_u8"],
}

_REGION = {
    "A": "sa8d8/reduce",
    "B": "sa8d8/reduce",
    "C": "sa8d8/reduce",
}


def emit_cover(name: str, func: str) -> str:
    if name not in _TAILS:
        raise ValueError("unknown sa8d8 cover %r" % name)
    return ("// Generated by optimizer/ago/covers_sa8d8.py -- do not edit.\n"
            "#include <arm_neon.h>\n#include <stdint.h>\n" +
            NEON_HELPERS + "\n" + _PREFIX % func + "\n" + _TAILS[name] + "\n")


def all_covers() -> List[str]:
    return sorted(_TAILS)


def cover_meta() -> Dict[str, Dict]:
    return {"kernel": "sa8d8", "tails": _TAILS, "tail_ops": _TAIL_OPS,
            "cp_chains": _CP_CHAINS, "regions": _REGION}
