#!/usr/bin/env python3
"""Generate C++ NEON or SVE2 intrinsics from imported MachineIR.

Usage: python3 kernels/sa8d/gen_roundtrip.py <machine-ir.json> <out.cpp>
       [--backend neon|sve2]
"""

import json
import os
import sys

from optimizer.ir.codegen import emit_c_intrinsics, emit_sve_intrinsics


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    backend = "sve2" if "--backend" in sys.argv and \
        sys.argv[sys.argv.index("--backend") + 1] == "sve2" else "neon"
    with open(sys.argv[1]) as f:
        doc = json.load(f)
    from optimizer.ir.machine_ir import MachineIR
    ir = MachineIR(function=doc["function"], nodes=doc["nodes"])
    if backend == "sve2":
        src = emit_sve_intrinsics(ir, "dynopt_sa8d_8x8_neon_sve2")
    else:
        src = emit_c_intrinsics(ir)
    with open(sys.argv[2], "w") as f:
        f.write("// generated by kernels/sa8d/gen_roundtrip.py; do not edit\n")
        f.write(src)
    print("wrote %s (%d lines)" % (sys.argv[2], src.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
